//>>built
require({cache:{"dojomat/_AppAware":function(){define("dojomat/_AppAware",["dojo/_base/declare","dojo/topic"],function(g,d){return g([],{setStylesheets:function(a){d.publish("dojomat/_AppAware/stylesheets",a)},setCss:function(a,b){d.publish("dojomat/_AppAware/css",{css:a,media:b})},setTitle:function(a){d.publish("dojomat/_AppAware/title",{title:a})},setNotification:function(a,b){d.publish("dojomat/_AppAware/notification",{message:a,type:b})},handleNotFound:function(){d.publish("dojomat/_AppAware/not-found",
{})},handleError:function(a){d.publish("dojomat/_AppAware/error",a)}})})},"dojomat/_StateAware":function(){define("dojomat/_StateAware",["dojo/_base/declare","dojo/topic"],function(g,d){return g([],{push:function(a){d.publish("dojomat/_StateAware/push-state",{url:a});if(document.body.scrollTop)document.body.scrollTop=0;if(document.documentElement.scrollTop)document.documentElement.scrollTop=0}})})},"dojomat/Application":function(){define("dojomat/Application","routed/Request,routed/Router,mijit/registry,dojo/_base/declare,dojo/_base/array,dojo/_base/lang,dojo/has,dojo/on,dojo/query,dojo/topic,dojo/dom-construct,./Notification,./Session,dojo/domReady!".split(","),
function(g,d,a,b,e,c,f,h,i,j,k,l,m){var n=function(){f.add("native-history-state",function(a){return void 0!==a.history&&void 0!==a.history.pushState})},o=function(){f.add("native-localstorage",function(a){var b=!1;try{b=void 0!==a.localStorage&&void 0!==a.localStorage.setItem}catch(e){}return b})};return b([],{router:new d,session:new m,notification:new l,stylesheetNodes:[],cssNode:null,pageNodeId:"page",run:function(){n();o();this.setSubscriptions();this.registerPopState();this.handleState()},setStylesheets:function(a){var b=
function(a,b){var e=null,c=null,d=null,e=i("head link[rel=stylesheet]");b&&b.href&&(e.length?(c=e[e.length-1],d="after"):(c=i("head script")[0],d="before"),e={rel:"stylesheet",media:b.media||"all",href:b.href},a[a.length]=k.create("link",e,c,d))};e.forEach(this.stylesheetNodes,function(a){k.destroy(a)});this.stylesheetNodes=[];a&&a.length?e.forEach(a,c.hitch(this,function(a){b(this.stylesheetNodes,a)})):b(this.stylesheetNodes,a)},setCss:function(a,b){var a=a||"",e={media:b||"all"},c=i("head script")[0];
this.cssNode&&k.destroy(this.cssNode);this.cssNode=k.create("style",e,c,"before");this.cssNode.styleSheet?this.cssNode.styleSheet.cssText=a:this.cssNode.innerHTML=a},setPageNode:function(){var b={id:this.pageNodeId},e=i("body")[0];a.byId(this.pageNodeId)&&a.byId(this.pageNodeId).destroyRecursive();k.create("div",b,e,"last")},handleState:function(a,b,e){var c;return function(){var d=this,f=arguments,i=e&&!c;clearTimeout(c);c=setTimeout(function(){c=null;e||a.apply(d,f)},b);i&&a.apply(d,f)}}(function(){var a=
null,b=new g(window.location.href);this.router.route(b);(a=this.router.getCurrentRoute())?a.run(b):this.makeNotFoundPage()},500,!0),registerPopState:function(){h(window,"popstate",c.hitch(this,function(){this.handleState()}))},makePage:function(a,b,e,d){var f=function(b){this.setStylesheets(d);this.setCss();this.setPageNode();b=new b({request:a,router:this.router,session:this.session,notification:this.notification.get()},this.pageNodeId);this.notification.clear();b.startup()};e.length?require(e,c.hitch(this,
function(){require([b],c.hitch(this,f))})):require([b],c.hitch(this,f))},makeNotFoundPage:function(){alert("Page not found")},makeErrorPage:function(){alert("An error has occured")},setSubscriptions:function(){j.subscribe("dojomat/_AppAware/css",c.hitch(this,function(a){this.setCss(a.css,a.media)}));j.subscribe("dojomat/_AppAware/stylesheets",c.hitch(this,function(a){this.setStylesheets(a)}));j.subscribe("dojomat/_AppAware/title",c.hitch(this,function(a){window.document.title=a.title}));j.subscribe("dojomat/_AppAware/notification",
c.hitch(this,function(a){this.notification.set(a)}));j.subscribe("dojomat/_AppAware/error",c.hitch(this,function(a){this.makeErrorPage(a)}));j.subscribe("dojomat/_AppAware/not-found",c.hitch(this,function(){this.makeNotFoundPage()}));j.subscribe("dojomat/_StateAware/push-state",c.hitch(this,function(a){this.pushState(a)}))},pushState:function(a){f("native-history-state")?(history.pushState({},"",a.url),this.handleState()):window.location=a.url}})})},"routed/Request":function(){define("routed/Request",
[],function(){var g=function(a){return a.replace(/^\s+|\s+$/g,"")},d=function(a){a=a.split("?")[0].split("#")[0].replace(/\w+:\/\/[\w\d\._\-]*/,"");return a.match(/^\//)?a:""},a=function(a){var e={},a=a.split("?")[1]||"",c=null,d=null,h=null;if(a){c=a.split("&");for(d=0;d<c.length;d+=1)h=c[d].split("="),e[g(decodeURIComponent(h[0]))]=g(decodeURIComponent(h[1]))}return e};return function(b){var e=d(g(decodeURIComponent(b))),c=b.split("?")[1]||"",f=a(b),h={};return{getPathname:function(){return e},
getQueryString:function(){return c},getQueryParams:function(){return f},getPathParams:function(){return h},setPathParam:function(a,b){h[a]=b},getPathParam:function(a){return h[a]||null},getQueryParam:function(a){return f[a]||null},isSame:function(b){var c;if(e!==d(b))return!1;b=a(b);for(c in f)if(f.hasOwnProperty(c)&&(void 0===b[c]||b[c]!==f[c]))return!1;for(c in b)if(b.hasOwnProperty(c)&&(void 0===f[c]||b[c]!==f[c]))return!1;return!0},debug:function(){console.log("getPathname(): ",this.getPathname());
console.log("getQueryParams(): ",this.getQueryParams());console.log("getPathParams(): ",this.getPathParams())}}}})},"routed/Router":function(){define("routed/Router",["./Route"],function(){return function(g){var d=null,a=[],b=null;for(b in g)g.hasOwnProperty(b)&&(a[b]=g[b]);return{addRoute:function(b,c){a[b]=c},route:function(b){var c,f,g=[];for(c in a)if(a.hasOwnProperty(c)&&(g=a[c].match(b.getPathname()))){d=c;for(f in g)g.hasOwnProperty(f)&&b.setPathParam(f,g[f]);return b}return null},getCurrentRoute:function(){return a[d]||
null},getCurrentRouteName:function(){return d},getRoute:function(b){if(!a[b])throw Error("Route does not exist: "+b);return a[b]}}}})},"routed/Route":function(){define("routed/Route",[],function(){return function(g,d){return{run:d,match:function(a){var a=a.replace(/^\/|\/$/g,"").split("/"),b=g.replace(/^\/|\/$/g,"").split("/"),d={},c=0,f=null;if(a.length!==b.length)return!1;for(c=0;c<a.length;c+=1)if(b[c].match(/^\:(\w*)$/))f=b[c].replace(/^\:(\w*)$/,"$1"),d[f]=decodeURIComponent(a[c]);else if(b[c]!==
decodeURIComponent(a[c]))return!1;return d},assemble:function(a,b){for(var d="",c=null,c=null,f=0,h=g.replace(/^\/|\/$/g,"").split("/"),i=null,j=[],f=0;f<h.length;f+=1){if(h[f].match(/^\:(\w*)$/)){c=h[f].replace(/^\:(\w*)$/,"$1");if(void 0===a[c])throw Error('Missing param "'+c+'" for schema: "'+g+'"');c=a[c]}else c=h[f];d+="/"+c}g.match(/\/$/)&&(d+="/");if(b){for(i in b)b.hasOwnProperty(i)&&j.push(i+"="+encodeURIComponent(b[i]));j.length&&(d+="?"+j.join("&"))}return d}}}})},"dojomat/Notification":function(){define("dojomat/Notification",
["dojo/_base/declare","dojo/_base/json","dojo/has","dojo/cookie"],function(g,d,a,b){return g([],{id:"dojomat-notification",get:function(){return a("native-localstorage")&&a("native-history-state")?d.fromJson(localStorage.getItem(this.id)):d.fromJson(b(this.id))},clear:function(){a("native-localstorage")&&a("native-history-state")?localStorage.removeItem(this.id):b(this.id,null,{expires:-1,path:"/"})},set:function(e){a("native-localstorage")&&a("native-history-state")?localStorage.setItem(this.id,
d.toJson(e)):b(this.id,d.toJson(e),{expires:1,path:"/"})}})})},"dojomat/Session":function(){define("dojomat/Session",["dojo/_base/declare"],function(g){return g([],{props:{},get:function(d){return this.props[d]},set:function(d,a){this.props[d]=a},destroy:function(d){this.props[d]&&this.props[d].remove&&(this.props[d].remove(),delete this.props[d]);this.props[d]&&this.props[d].destroy&&(this.props[d].destroy(),delete this.props[d])}})})},"dojomat/populateRouter":function(){define("dojomat/populateRouter",
["routed/Route","dojo/_base/lang"],function(g,d){return function(a,b){var e=null,c=function(b,d,c){return function(e){a.makePage(e,b,d,c)}};for(e in b)b.hasOwnProperty(e)&&a.router.addRoute(e,new g(b[e].schema,d.hitch(a,c(b[e].widget,b[e].layers||[],b[e].stylesheets))))}})},"dojorama/routing-map":function(){define("dojorama/routing-map",["dojo/_base/config","require"],function(g,d){var a=g["routing-map"].pathPrefix,b=g["routing-map"].layers||{},e=d.toAbsMid;return{home:{schema:a+"",widget:e("./ui/home/HomePage"),
layers:b.home||[]},storage:{schema:a+"/storage",widget:e("./ui/storage/StoragePage"),layers:b.storage||[]},releaseIndex:{schema:a+"/releases",widget:e("./ui/release/ReleaseIndexPage"),layers:b.release||[]},releaseUpdate:{schema:a+"/release/:id",widget:e("./ui/release/ReleaseUpdatePage"),layers:b.release||[]},releaseCreate:{schema:a+"/new-release/",widget:e("./ui/release/ReleaseCreatePage"),layers:b.release||[]}}})},"dojorama/App":function(){define("dojorama/App","dojo/_base/declare,dojo/_base/lang,routed/Request,dojomat/Application,dojomat/populateRouter,./routing-map,require,dojo/domReady!".split(","),
function(g,d,a,b,e,c,f){var h=function(a){var b=a.getQueryString(),a=a.getPathname()+(""!==b?"?":"")+b;window._gaq&&window._gaq.push(["_trackPageview",a])};return g([b],{constructor:function(){e(this,c);this.run()},makeNotFoundPage:function(){var b=new a(window.location.href);f(["./ui/error/NotFoundPage"],d.hitch(this,function(a){this.setStylesheets();this.setCss();this.setPageNode();(new a({request:b,router:this.router},this.pageNodeId)).startup();this.notification.clear()}));h(b)},makeErrorPage:function(b){var c=
new a(window.location.href);f(["./ui/error/ErrorPage"],d.hitch(this,function(a){this.setStylesheets();this.setCss();this.setPageNode();(new a({request:c,router:this.router,error:b},this.pageNodeId)).startup();this.notification.clear()}));h(c)},makePage:function(a,b,c,d){this.inherited(arguments);h(a)}})})}}});define("dojorama/layers/app",[],1);