//>>built
require({cache:{"dojomat/_AppAware":function(){define("dojomat/_AppAware",["dojo/_base/declare","dojo/topic"],function(e,d){return e([],{setStylesheets:function(a){d.publish("dojomat/_AppAware/stylesheets",a)},setCss:function(a,b){d.publish("dojomat/_AppAware/css",{css:a,media:b})},setTitle:function(a){d.publish("dojomat/_AppAware/title",{title:a})},setNotification:function(a,b){d.publish("dojomat/_AppAware/notification",{message:a,type:b})},handleNotFound:function(){d.publish("dojomat/_AppAware/not-found",
{})},handleError:function(a){d.publish("dojomat/_AppAware/error",a)}})})},"dojomat/_StateAware":function(){define("dojomat/_StateAware",["dojo/_base/declare","dojo/topic"],function(e,d){return e([],{push:function(a){d.publish("dojomat/_StateAware/push-state",{url:a});if(document.body.scrollTop)document.body.scrollTop=0;if(document.documentElement.scrollTop)document.documentElement.scrollTop=0}})})},"dojomat/Application":function(){define("dojomat/Application","routed/Request,routed/Router,mijit/registry,dojo/_base/declare,dojo/_base/array,dojo/_base/lang,dojo/has,dojo/on,dojo/query,dojo/topic,dojo/dom-construct,./Notification,./Session,dojo/domReady!".split(","),
function(e,d,a,b,f,c,h,g,j,i,k,l,m){var n=function(){h.add("native-history-state",function(a){return void 0!==a.history&&void 0!==a.history.pushState})},o=function(){h.add("native-localstorage",function(a){var c=!1;try{c=void 0!==a.localStorage&&void 0!==a.localStorage.setItem}catch(b){}return c})};return b([],{router:new d,session:new m,notification:new l,stylesheetNodes:[],cssNode:null,pageNodeId:"page",run:function(){n();o();this.setSubscriptions();this.registerPopState();this.handleState()},setStylesheets:function(a){var b=
function(a,b){var c=null,f=null,d=null,c=j("head link[rel=stylesheet]");b&&b.href&&(c.length?(f=c[c.length-1],d="after"):(f=j("head script")[0],d="before"),c={rel:"stylesheet",media:b.media||"all",href:b.href},a[a.length]=k.create("link",c,f,d))};f.forEach(this.stylesheetNodes,function(a){k.destroy(a)});this.stylesheetNodes=[];a&&a.length?f.forEach(a,c.hitch(this,function(a){b(this.stylesheetNodes,a)})):b(this.stylesheetNodes,a)},setCss:function(a,c){var a=a||"",b={media:c||"all"},f=j("head script")[0];
this.cssNode&&k.destroy(this.cssNode);this.cssNode=k.create("style",b,f,"before");this.cssNode.styleSheet?this.cssNode.styleSheet.cssText=a:this.cssNode.innerHTML=a},setPageNode:function(){var c={id:this.pageNodeId},b=j("body")[0];a.byId(this.pageNodeId)&&a.byId(this.pageNodeId).destroyRecursive();k.create("div",c,b,"last")},handleState:function(a,c,b){var f;return function(){var d=this,g=arguments,h=b&&!f;clearTimeout(f);f=setTimeout(function(){f=null;b||a.apply(d,g)},c);h&&a.apply(d,g)}}(function(){var a=
null,c=new e(window.location.href);this.router.route(c);(a=this.router.getCurrentRoute())?a.run(c):this.makeNotFoundPage()},500,!0),registerPopState:function(){g(window,"popstate",c.hitch(this,function(){this.handleState()}))},makePage:function(a,b,f,d){var g=function(c){this.setStylesheets(d);this.setCss();this.setPageNode();c=new c({request:a,router:this.router,session:this.session,notification:this.notification.get()},this.pageNodeId);this.notification.clear();c.startup()};f.length?require(f,c.hitch(this,
function(){require([b],c.hitch(this,g))})):require([b],c.hitch(this,g))},makeNotFoundPage:function(){alert("Page not found")},makeErrorPage:function(){alert("An error has occured")},setSubscriptions:function(){i.subscribe("dojomat/_AppAware/css",c.hitch(this,function(a){this.setCss(a.css,a.media)}));i.subscribe("dojomat/_AppAware/stylesheets",c.hitch(this,function(a){this.setStylesheets(a)}));i.subscribe("dojomat/_AppAware/title",c.hitch(this,function(a){window.document.title=a.title}));i.subscribe("dojomat/_AppAware/notification",
c.hitch(this,function(a){this.notification.set(a)}));i.subscribe("dojomat/_AppAware/error",c.hitch(this,function(a){this.makeErrorPage(a)}));i.subscribe("dojomat/_AppAware/not-found",c.hitch(this,function(){this.makeNotFoundPage()}));i.subscribe("dojomat/_StateAware/push-state",c.hitch(this,function(a){this.pushState(a)}))},pushState:function(a){h("native-history-state")?(history.pushState({},"",a.url),this.handleState()):window.location=a.url}})})},"routed/Request":function(){define("routed/Request",
[],function(){var e=function(a){return a.replace(/^\s+|\s+$/g,"")},d=function(a){a=a.split("?")[0].split("#")[0].replace(/\w+:\/\/[\w\d\._\-]*/,"");return a.match(/^\//)?a:""},a=function(a){var f={},a=a.split("?")[1]||"",c=null,d=null,g=null;if(a){c=a.split("&");for(d=0;d<c.length;d+=1)g=c[d].split("="),f[e(decodeURIComponent(g[0]))]=e(decodeURIComponent(g[1]))}return f};return function(b){var f=d(e(decodeURIComponent(b))),c=a(b),h={};return{getPathname:function(){return f},getQueryParams:function(){return c},
getPathParams:function(){return h},setPathParam:function(a,c){h[a]=c},getPathParam:function(a){return h[a]||null},getQueryParam:function(a){return c[a]||null},isSame:function(b){var e;if(f!==d(b))return!1;b=a(b);for(e in c)if(c.hasOwnProperty(e)&&(void 0===b[e]||b[e]!==c[e]))return!1;for(e in b)if(b.hasOwnProperty(e)&&(void 0===c[e]||b[e]!==c[e]))return!1;return!0},debug:function(){console.log("getPathname(): ",this.getPathname());console.log("getQueryParams(): ",this.getQueryParams());console.log("getPathParams(): ",
this.getPathParams())}}}})},"routed/Router":function(){define("routed/Router",["./Route"],function(){return function(e){var d=null,a=[],b=null;for(b in e)e.hasOwnProperty(b)&&(a[b]=e[b]);return{addRoute:function(b,c){a[b]=c},route:function(b){var c,e,g=[];for(c in a)if(a.hasOwnProperty(c)&&(g=a[c].match(b.getPathname()))){d=c;for(e in g)g.hasOwnProperty(e)&&b.setPathParam(e,g[e]);return b}return null},getCurrentRoute:function(){return a[d]||null},getCurrentRouteName:function(){return d},getRoute:function(b){if(!a[b])throw Error("Route does not exist: "+
b);return a[b]}}}})},"routed/Route":function(){define("routed/Route",[],function(){return function(e,d){return{run:d,match:function(a){var a=a.replace(/^\/|\/$/g,"").split("/"),b=e.replace(/^\/|\/$/g,"").split("/"),d={},c=0,h=null;if(a.length!==b.length)return!1;for(c=0;c<a.length;c+=1)if(b[c].match(/^\:(\w*)$/))h=b[c].replace(/^\:(\w*)$/,"$1"),d[h]=decodeURIComponent(a[c]);else if(b[c]!==decodeURIComponent(a[c]))return!1;return d},assemble:function(a,b){for(var d="",c=null,c=null,h=0,g=e.replace(/^\/|\/$/g,
"").split("/"),j=null,i=[],h=0;h<g.length;h+=1){if(g[h].match(/^\:(\w*)$/)){c=g[h].replace(/^\:(\w*)$/,"$1");if(void 0===a[c])throw Error('Missing param "'+c+'" for schema: "'+e+'"');c=a[c]}else c=g[h];d+="/"+c}e.match(/\/$/)&&(d+="/");if(b){for(j in b)b.hasOwnProperty(j)&&i.push(j+"="+encodeURIComponent(b[j]));i.length&&(d+="?"+i.join("&"))}return d}}}})},"dojomat/Notification":function(){define("dojomat/Notification",["dojo/_base/declare","dojo/_base/json","dojo/has","dojo/cookie"],function(e,d,
a,b){return e([],{id:"dojomat-notification",get:function(){return a("native-localstorage")&&a("native-history-state")?d.fromJson(localStorage.getItem(this.id)):d.fromJson(b(this.id))},clear:function(){a("native-localstorage")&&a("native-history-state")?localStorage.removeItem(this.id):b(this.id,null,{expires:-1,path:"/"})},set:function(e){a("native-localstorage")&&a("native-history-state")?localStorage.setItem(this.id,d.toJson(e)):b(this.id,d.toJson(e),{expires:1,path:"/"})}})})},"dojomat/Session":function(){define("dojomat/Session",
["dojo/_base/declare"],function(e){return e([],{props:{},get:function(d){return this.props[d]},set:function(d,a){this.props[d]=a},destroy:function(d){this.props[d]&&this.props[d].remove&&(this.props[d].remove(),delete this.props[d]);this.props[d]&&this.props[d].destroy&&(this.props[d].destroy(),delete this.props[d])}})})},"dojomat/populateRouter":function(){define("dojomat/populateRouter",["routed/Route","dojo/_base/lang"],function(e,d){return function(a,b){var f=null,c=function(b,c,d){return function(e){a.makePage(e,
b,c,d)}};for(f in b)b.hasOwnProperty(f)&&a.router.addRoute(f,new e(b[f].schema,d.hitch(a,c(b[f].widget,b[f].layers||[],b[f].stylesheets))))}})},"dojorama/routing-map":function(){define("dojorama/routing-map",["dojo/_base/config","require"],function(e,d){var a=e["routing-map"].pathPrefix,b=e["routing-map"].layers,f=d.toAbsMid;return{home:{schema:a+"",widget:f("./ui/home/HomePage"),layers:b.home||[]},storage:{schema:a+"/storage",widget:f("./ui/storage/StoragePage"),layers:b.storage||[]},releaseIndex:{schema:a+
"/releases",widget:f("./ui/release/ReleaseIndexPage"),layers:b.release||[]},releaseUpdate:{schema:a+"/release/:id",widget:f("./ui/release/ReleaseUpdatePage"),layers:b.release||[]},releaseCreate:{schema:a+"/new-release/",widget:f("./ui/release/ReleaseCreatePage"),layers:b.release||[]}}})},"dojorama/App":function(){define("dojorama/App","dojo/_base/declare,dojo/_base/lang,dojo/_base/array,dojo/query,dojomat/Application,dojomat/populateRouter,./routing-map,require,dojo/domReady!".split(","),function(e,
d,a,b,f,c,h,g){return e([f],{constructor:function(){c(this,h);this.run()},makeNotFoundPage:function(){g(["./ui/error/NotFoundPage"],d.hitch(this,function(a){this.setStylesheets();this.setCss();this.setPageNode();(new a({router:this.router},this.pageNodeId)).startup();this.notification.clear()}))},makeErrorPage:function(a){g(["./ui/error/ErrorPage"],d.hitch(this,function(b){this.setStylesheets();this.setCss();this.setPageNode();(new b({router:this.router,error:a},this.pageNodeId)).startup();this.notification.clear()}))}})})}}});
define("dojorama/layers/app",[],1);