//>>built
require({cache:{"dgrid/OnDemandGrid":function(){define("dgrid/OnDemandGrid",["dojo/_base/declare","./Grid","./OnDemandList"],function(u,o,r){return u([o,r],{})})},"dgrid/Grid":function(){define("dgrid/Grid","dojo/_base/kernel,dojo/_base/declare,dojo/on,dojo/has,put-selector/put,./List,dojo/_base/sniff".split(","),function(u,o,r,k,i,p){function s(b,a){a&&a.nodeType&&b.appendChild(a)}var v=8>k("ie")&&!k("quirks"),w=/[^\._a-zA-Z0-9-]/g,o=o(p,{columns:null,cellNavigation:!0,tabableHeader:!0,showHeader:!0,
column:function(b){return"string"==typeof b?this.columns[b]:this.cell(b).column},listType:"grid",cell:function(b,a){if(b.row&&b.row instanceof this._Row)return b;if(b.target&&b.target.nodeType)b=b.target;var c;if(b.nodeType){do{if(this._rowIdToObject[b.id])break;var f=b.columnId;if(f){a=f;c=b;break}b=b.parentNode}while(b&&b!=this.domNode)}if(!c&&"undefined"!=typeof a){var e=this.row(b);if(f=e.element)for(var f=f.getElementsByTagName("td"),d=0;d<f.length;d++)if(f[d].columnId==a){c=f[d];break}}if(null!=
b)return{row:e||this.row(b),column:a&&this.column(a),element:c}},_columnsCss:function(b){b.fullSelector=function(){return this.parent.fullSelector()+" .dgrid-cell"};for(var a=0;a<b.children.length;a++){var c=b.children[a];c.field=c.className=c.selector.substring(1)}return b.children},createRowCells:function(b,a,c){var f=i("table.dgrid-row-table[role=presentation]"),e=9>k("ie")||k("quirks")?i(f,"tbody"):f,d,h,y,g,n,x,j,z,t,l,c=c||this.subRows;for(h=0,y=c.length;h<y;h++){x=c[h];d=1==y&&!k("ie")?e:i(e,
"tr");x.className&&i(d,"."+x.className);for(g=0,n=x.length;g<n;g++){j=x[g];z=j.id;t=j.className||j.field&&"field-"+j.field;t=i(b+(".dgrid-cell.dgrid-cell-padding"+(z?".dgrid-column-"+z:"")+(t?"."+t:"")).replace(w,"-")+"[role="+("th"===b?"columnheader":"gridcell")+"]");t.columnId=z;v?(z=i(t,"!dgrid-cell-padding div.dgrid-cell-padding"),t.contents=z):z=t;if(l=j.colSpan)t.colSpan=l;if(l=j.rowSpan)t.rowSpan=l;a(z,j);d.appendChild(t)}}return f},left:function(b,a){b.element||(b=this.cell(b));return this.cell(this._move(b,
-(a||1),"dgrid-cell"))},right:function(b,a){b.element||(b=this.cell(b));return this.cell(this._move(b,a||1,"dgrid-cell"))},renderRow:function(b,a){var c=this.createRowCells("td",function(f,e){var d=b;e.get?d=e.get(b):"field"in e&&"_item"!=e.field&&(d=d[e.field]);e.formatter?f.innerHTML=e.formatter(d):e.renderCell?s(f,e.renderCell(b,d,f,a)):null!=d&&f.appendChild(document.createTextNode(d))},a&&a.subRows);return i("div[role=row]>",c)},renderHeader:function(){var b=this,a=this.headerNode,c=a.childNodes.length;
for(a.setAttribute("role","row");c--;)i(a.childNodes[c],"!");c=this.createRowCells("th",function(a,e){var b=e.headerNode=a;if(v)a=a.parentNode;var c=e.field;if(c)a.field=c;if(e.renderHeaderCell)s(b,e.renderHeaderCell(b));else if(e.label||e.field)b.appendChild(document.createTextNode(e.label||e.field));if(!1!==e.sortable&&c&&"_item"!=c)a.sortable=!0,a.className+=" dgrid-sortable"},this.subRows&&this.subRows.headerRows);this._rowIdToObject[c.id=this.id+"-header"]=this.columns;a.appendChild(c);r(c,"click,keydown",
function(c){if("click"==c.type||32==c.keyCode||!k("opera")&&13==c.keyCode){var c=c.target,e,d;do if(c.sortable)return b._sortNode=c,c=c.field||c.columnId,e=(d=b._sort[0])&&d.attribute==c&&!d.descending,b.set("sort",c,e);while((c=c.parentNode)&&c!=a)}})},resize:function(){var b=this.headerNode.firstChild,a=this.contentNode,c;this.inherited(arguments);if(!k("ie")||7<k("ie")&&!k("quirks"))if(a.style.width="",a&&b&&(c=b.offsetWidth)!=a.offsetWidth)a.style.width=c+"px"},destroy:function(){this._destroyColumns();
this.inherited(arguments)},_setSort:function(b,a){this.inherited(arguments);this._lastSortedArrow&&(i(this._lastSortedArrow,"<!dgrid-sort-up!dgrid-sort-down"),i(this._lastSortedArrow,"!"),delete this._lastSortedArrow);if(this._sort[0]){var c=this._sort[0].attribute,f=this._sort[0].descending,e=this._sortNode,d,h,y;delete this._sortNode;if(!e)for(y in d=this.columns,d)if(h=d[y],h.field==c){e=h.headerNode;break}if(e)e=e.contents||e,this._lastSortedArrow=i(e.firstChild,"-div.dgrid-sort-arrow.ui-icon[role=presentation]"),
this._lastSortedArrow.innerHTML="&nbsp;",i(e,f?".dgrid-sort-down":".dgrid-sort-up"),this.resize()}},styleColumn:function(b,a){return this.addCssRule("#"+this.domNode.id+" .dgrid-column-"+b,a)},_configColumns:function(b,a){var c=[],f=a instanceof Array,e,d;for(e in a){d=a[e];"string"==typeof d&&(a[e]=d={label:d});if(!f&&!d.field)d.field=e;e=d.id=d.id||(isNaN(e)?e:b+e);b&&(this.columns[e]=d);this._configColumn&&this._configColumn(d,e,a,b);d.grid=this;"function"===typeof d.init&&d.init();c.push(d)}return f?
a:c},_destroyColumns:function(){var b=this.subRows.length,a,c,f,e;this.cleanup();for(a=0;a<b;a++)for(c=0,e=this.subRows[a].length;c<e;c++)f=this.subRows[a][c],"function"===typeof f.destroy&&f.destroy()},configStructure:function(){var b=this.subRows;if(b){this.columns={};for(var a=0;a<b.length;a++)b[a]=this._configColumns(a+"-",b[a])}else this.subRows=[this._configColumns("",this.columns)]},_setColumns:function(b){this._destroyColumns();this.subRows=null;this.columns=b;this._updateColumns()},_setSubRows:function(b){this._destroyColumns();
this.subRows=b;this._updateColumns()},setColumns:function(b){u.deprecated("setColumns(...)",'use set("columns", ...) instead',"dgrid 1.0");this.set("columns",b)},setSubRows:function(b){u.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 1.0");this.set("subRows",b)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);this.resize()}});o.appendIfNode=s;o.defaultRenderCell=function(b,a,c){null!=
a&&c.appendChild(document.createTextNode(a))};return o})},"dgrid/Selection":function(){define("dgrid/Selection","dojo/_base/kernel,dojo/_base/declare,dojo/_base/Deferred,dojo/on,dojo/has,dojo/aspect,./List,dojo/has!touch?./util/touch,put-selector/put,dojo/query".split(","),function(u,o,r,k,i,p,s,v,w){var b=i("mac")?"metaKey":"ctrlKey";return o(null,{selectionDelegate:".dgrid-row",selectionEvents:"mousedown,mouseup,dgrid-cellfocusin",deselectOnRefresh:!0,allowSelectAll:!1,create:function(){this.selection=
{};return this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this._initSelectionEvents()},selection:{},selectionMode:"extended",_setSelectionMode:function(a){if(a!=this.selectionMode)this.clearSelection(),this.selectionMode=a},setSelectionMode:function(a){u.deprecated("setSelectionMode(...)",'use set("selectionMode", ...) instead',"dgrid 1.0");this.set("selectionMode",a)},_handleSelect:function(a,c){if(!("none"==this.selectionMode||"dgrid-cellfocusin"==a.type&&"mousedown"==
a.parentType||"mouseup"==a.type&&c!=this._waitForMouseUp)){this._waitForMouseUp=null;this._selectionTriggerEvent=a;var f=!a.keyCode?a[b]:a.ctrlKey;if(!a.keyCode||!a.ctrlKey||32==a.keyCode){var e=this.selectionMode,d=this.row(c),h=this._lastSelected;if("single"==e)h===c?this.select(c,null,!f||!this.isSelected(c)):(this.clearSelection(),this.select(c),this._lastSelected=c);else if(this.selection[d.id]&&!a.shiftKey&&"mousedown"==a.type)this._waitForMouseUp=c;else{var i;(2!=a.button&&"extended"==e&&!f||
2==a.button&&!this.selection[d.id])&&this.clearSelection(d.id,!0);a.shiftKey||(h=i=f?null:void 0);this.select(c,h,i);if(!h)this._lastSelected=c}!a.keyCode&&(a.shiftKey||f)&&a.preventDefault()}this._selectionTriggerEvent=null}},_initSelectionEvents:function(){function a(a){c._handleSelect(a,this)}var c=this,f=this.selectionDelegate;k(this.domNode,"selectstart",function(a){var c=a.target&&a.target.tagName;"INPUT"!=c&&"TEXTAREA"!=c&&a.preventDefault()});i("touch")?k(this.contentNode,v.selector(f,v.tap),
function(a){c._handleSelect(a,this)}):k(this.contentNode,k.selector(f,this.selectionEvents),a);if(this.allowSelectAll)this.on("keydown",function(a){a[b]&&65==a.keyCode&&(a.preventDefault(),c[c.allSelected?"clearSelection":"selectAll"]())});p.before(this,"removeRow",function(a,c){var b;c||(b=this.row(a))&&b.id in this.selection&&this.deselect(a)})},allowSelect:function(){return!0},_selectionEventQueue:function(a,c){var b=this,e="dgrid-"+(a?"select":"deselect"),d=this[e],h=this._selectionTriggerEvent;
if(h)h=h.type;if(d)return d;setTimeout(this._fireSelectionEvent=function(){if(d){var a={bubbles:!0,grid:b};if(h)a.parentType=h;a[c]=d;k.emit(b.contentNode,e,a);d=null;delete b[e]}},0);return d=this[e]=[]},select:function(a,c,b){void 0===b&&(b=!0);a.element||(a=this.row(a));if(this.allowSelect(a)){var e=this.selection,d=e[a.id];null===b&&(b=!d);var h=a.element;!b&&!this.allSelected?delete this.selection[a.id]:e[a.id]=b;h&&(b?w(h,".dgrid-selected.ui-state-active"):w(h,"!dgrid-selected!ui-state-active"));
b!=d&&h&&this._selectionEventQueue(b,"rows").push(a);if(c){c.element||(c=this.row(c));c=c.element;b=a.element;for(b=c&&(c.compareDocumentPosition?2==c.compareDocumentPosition(b):c.sourceIndex>b.sourceIndex)?"down":"up";a.element!=c&&(a=this[b](a));)this.select(a)}}},deselect:function(a,b){this.select(a,b,!1)},clearSelection:function(a,b){this.allSelected=!1;for(var f in this.selection)a!==f&&this.deselect(f);if(!b)this._lastSelected=null},selectAll:function(){this.allSelected=!0;this.selection={};
for(var a in this._rowIdToObject)this.select(this.row(this._rowIdToObject[a]).id)},isSelected:function(a){if(!a)return!1;a.element||(a=this.row(a));return!!this.selection[a.id]},refresh:function(){this.deselectOnRefresh&&(this.clearSelection(),this._fireSelectionEvent&&this._fireSelectionEvent());this._lastSelected=null;this.inherited(arguments)},renderArray:function(){var a=this,b=this.inherited(arguments);r.when(b,function(b){var c=a.selection,d,h,i;for(d=0;d<b.length;d++)h=a.row(b[d]),(i=h.id in
c?c[h.id]:a.allSelected)&&a.select(h,null,i)});return b}})})},"dgrid/Keyboard":function(){define("dgrid/Keyboard","dojo/_base/declare,dojo/aspect,dojo/on,./List,dojo/_base/lang,dojo/has,put-selector/put,dojo/_base/Deferred,dojo/_base/sniff".split(","),function(u,o,r,k,i,p,s,v){var w={checkbox:1,radio:1,button:1},b=/\bdgrid-cell\b/,a=/\bdgrid-row\b/;p.add("dom-contains",function(){return!!document.createElement("a").contains});return u(null,{pageSkip:10,tabIndex:0,postCreate:function(){function c(a){var b=
a.target;return b.type&&(!w[b.type]||32==a.keyCode)}function f(d){function f(a,j,b){var c=e.cellNavigation?"cell":"row",d=e[c](a);if(a=d&&d.element){j=i.mixin({grid:e},j);if(j.type)j.parentType=j.type;if(!j.bubbles)j.bubbles=!0;s(g,"!dgrid-focus[!tabIndex]");if(g){if(8>p("ie"))g.style.position="";j[c]=e[c](g);r.emit(a,"dgrid-cellfocusout",j)}g=a;j[c]=d;if(!b){if(8>p("ie"))a.style.position="relative";a.tabIndex=e.tabIndex;a.focus()}s(a,".dgrid-focus");r.emit(g,"dgrid-cellfocusin",j)}}for(var k=e.cellNavigation?
b:a,g=d,n;(n=g.firstChild)&&!k.test(n.className);)g=n;n&&(g=n);if(d===e.contentNode)o.after(e,"renderArray",function(a){return v.when(a,function(a){if(k.test(g.className)&&(p("dom-contains")?d.contains(g):d.compareDocumentPosition(g)&8))return a;for(var b=0,c=d.getElementsByTagName("*"),l;l=c[b];++b)if(k.test(l.className)){g=l;break}g.tabIndex=e.tabIndex;return a})});else if(k.test(g.className))g.tabIndex=e.tabIndex;r(d,"mousedown",function(a){c(a)||f(a.target,a)});r(d,"keydown",function(a){if(!a.metaKey&&
!a.altKey){var j=a.keyCode;if(!c(a)){var b={32:0,33:-e.pageSkip,34:e.pageSkip,37:-1,38:-1,39:1,40:1,35:1E4,36:-1E4}[j];if(!isNaN(b)){var d,l=e.cell(g);if(37==j||39==j){if(!e.cellNavigation)return;j="right"}else j="down",d=l&&l.column&&l.column.id,l=e.row(g);b&&(l=l&&e[j](l,b,!0));if(b=l&&l.element){if(d)b=e.cell(b,d).element;if(e.cellNavigation){d=b.getElementsByTagName("input");for(var i,l=0;l<d.length;l++)if(j=d[l],(-1!=j.tabIndex||"lastValue"in j)&&!j.disabled){if(8>p("ie"))j.style.position="relative";
j.focus();if(8>p("ie"))j.style.position="";i=!0;break}}f(b,a,i)}a.preventDefault()}}}});return function(a){a=a||g;f(a,{target:a})}}this.inherited(arguments);var e=this;if(this.tabableHeader)this.focusHeader=f(this.headerNode);this.focus=f(this.contentNode)}})})},"dgrid/editor":function(){define("dgrid/editor","dojo/_base/kernel,dojo/_base/lang,dojo/_base/array,dojo/_base/Deferred,dojo/on,dojo/aspect,dojo/has,./Grid,put-selector/put,dojo/_base/sniff".split(","),function(u,o,r,k,i,p,s,v,w){function b(a,
b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=!!b}function a(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date)var c=new Date(a),a=isNaN(c.getTime())?a:c;return a}function c(a,c,e,d,f){var q,m,h;if(!(e>=d&&e<=d)&&(q=a.cell(c),m=q.row,h=q.column,h.field&&m)){q={grid:a,cell:q,rowId:m.id,oldValue:e,value:d,bubbles:!0,cancelable:!0};if(f&&f.type)q.parentType=f.type;if(i.emit(c,"dgrid-datachange",q))a.updateDirty&&
(a.updateDirty(m.id,h.field,d),h.autoSave&&setTimeout(function(){a._trackError("save")},0));else{var g;(g=c.widget)?(g._dgridIgnoreChange=!0,g.set("value",e),setTimeout(function(){g._dgridIgnoreChange=!1},0)):(g=c.input)&&b(g,e);return e}}return d}function f(b,e,d,f){if(!d.isValid||d.isValid())b=c(b,(d.domNode||d).parentNode,g?n:d._dgridLastValue,"function"==typeof d.get?a(d.get("value")):a(d["checkbox"==d.type||"radio"==d.type?"checked":"value"]),f),g?n=b:d._dgridLastValue=b}function e(a){var b=
a.editor,c=a.editOn,d=a.grid,e="string"!=typeof b,q,m,g;q=a.editorArgs||{};"function"==typeof q&&(q=q.call(d,a));if(e)m=new b(q),e=m.focusNode||m.domNode,e.className+=" dgrid-input",m.connect(m,c?"onBlur":"onChange",function(){m._dgridIgnoreChange||f(d,a,this,{type:"widget"})});else{g=function(b){var c=b.target;"_dgridLastValue"in c&&-1<c.className.indexOf("dgrid-input")&&f(d,a,c,b)};if(!a.grid._hasInputListener)d._hasInputListener=!0,d.on("change",function(a){g(a)});m=e=w(("textarea"==b?"textarea":
"input[type="+b+"]")+".dgrid-input",o.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},q));if(9>s("ie")||s("ie")&&s("quirks"))"radio"==b||"checkbox"==b?i(m,"click",function(a){g(a)}):i(m,"change",function(a){g(a)})}i(e,"mousedown",function(a){a.stopPropagation()});return m}function d(a){var c=e(a),d=c.domNode||c,l=c.focusNode||d,h=c.domNode?function(){c.set("value",c._dgridLastValue)}:function(){b(c,c._dgridLastValue);f(a.grid,a,c)};i(l,"keydown",function(b){b=b.keyCode||b.which;27==
b?(h(),n=c._dgridLastValue,l.blur()):13==b&&!1!==a.dismissOnEnter&&l.blur()});(a._editorBlurHandle=i.pausable(c,"blur",function(){var b=d.parentNode;a.grid.cell(d);var c=b.children.length-1,e={alreadyHooked:!0};for(b.removeChild(d);c--;)w(b.firstChild,"!");v.appendIfNode(b,a.renderCell(a.grid.row(b).data,n,b,x?o.delegate(e,x):e));g=n=x=null;a._editorBlurHandle.pause()})).pause();return c}function h(a,c,d,e){(c=a.domNode)||b(a,e);d.innerHTML="";w(d,a.domNode||a);if(c)a._started||a.startup(),a._dgridIgnoreChange=
!0,a.set("value",e),setTimeout(function(){a._dgridIgnoreChange=!1},0);a._dgridLastValue=e;g&&(n=e)}function y(a){var b,c,d,e,f,m;a.column||(a=this.cell(a));b=a.column;e=b.field;c=a.element.contents||a.element;if(f=b.editorInstance){if(g!=c&&(!b.canEdit||b.canEdit(a.row.data,d)))return g=c,a=a.row,d=(d=this.dirty&&this.dirty[a.id])&&e in d?d[e]:b.get?b.get(a.data):a.data[e],h(b.editorInstance,b,c,d),m=new k,setTimeout(function(){f.focus&&f.focus();b._editorBlurHandle&&b._editorBlurHandle.resume();
m.resolve(f)},0),m.promise}else if(b.editor&&(f=c.widget||c.input))return m=new k,f.focus&&f.focus(),m.resolve(f),m.promise;return null}var g,n,x;return function(a,b,c){var f=a.renderCell||v.defaultRenderCell,g=[],k;a||(a={});a.editor=b=b||a.editor||"text";a.editOn=c=c||a.editOn;k="string"!=typeof b;if(a.widgetArgs)u.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 1.0"),a.editorArgs=a.widgetArgs;p.after(a,"init",c?function(){var b=a.grid;if(!b.edit)b.edit=y;a.editorInstance=
d(a,f)}:function(){var b=a.grid;if(!b.edit)b.edit=y;k&&g.push(p.before(b,"removeRow",function(c){c=b.cell(c,a.id).element;(c=(c.contents||c).widget)&&c.destroyRecursive()}))});p.after(a,"destroy",function(){r.forEach(g,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();c&&k&&a.editorInstance.destroyRecursive()});a.renderCell=c?function(b,d,e,g){if(!g||!g.alreadyHooked)i("TD"==e.tagName?e:e.parentNode,c,function(){x=g;a.grid.edit(this)});return f.call(a,b,d,e,g)}:function(b,
c,d,g){if(!a.canEdit||a.canEdit(b,c))b=e(a),h(b,a,d,c),d[k?"widget":"input"]=b;else return f.call(a,b,c,d,g)};return a}})}}});define("dojorama/layers/dgrid-extra",[],1);