//>>built
require({cache:{"dgrid/OnDemandGrid":function(){define("dgrid/OnDemandGrid",["dojo/_base/declare","./Grid","./OnDemandList"],function(v,r,t){return v([r,t],{})})},"dgrid/Grid":function(){define("dgrid/Grid","dojo/_base/kernel dojo/_base/declare dojo/on dojo/has put-selector/put ./List ./util/misc dojo/_base/sniff".split(" "),function(v,r,t,l,f,y,B){function w(a,c){c&&c.nodeType&&a.appendChild(c)}function u(a,c,b,g){if(this.formatter){g=this.formatter;var d=this.grid.formatterScope;b.innerHTML="string"===
typeof g&&d?d[g](c,a):g(c,a)}else null!=c&&b.appendChild(document.createTextNode(c))}var z=8>l("ie")&&!l("quirks"),C=/[^\._a-zA-Z0-9-]/g;r=r(y,{columns:null,cellNavigation:!0,tabableHeader:!0,showHeader:!0,column:function(a){return"string"==typeof a?this.columns[a]:this.cell(a).column},listType:"grid",cell:function(a,c){if(a.column&&a.element)return a;a.target&&a.target.nodeType&&(a=a.target);var b;if(a.nodeType){do{if(this._rowIdToObject[a.id])break;var g=a.columnId;if(g){c=g;b=a;break}a=a.parentNode}while(a&&
a!=this.domNode)}if(!b&&"undefined"!=typeof c){var d=this.row(a);if(g=d.element)for(var g=g.getElementsByTagName("td"),e=0;e<g.length;e++)if(g[e].columnId==c){b=g[e];break}}if(null!=a)return{row:d||this.row(a),column:c&&this.column(c),element:b}},createRowCells:function(a,c,b){var g=f("table.dgrid-row-table[role\x3dpresentation]"),d=9>l("ie")||l("quirks")?f(g,"tbody"):g,e,h,n,x,m,k,q,A,s,E;b=b||this.subRows;h=0;for(n=b.length;h<n;h++){k=b[h];e=f(d,"tr");k.className&&f(e,"."+k.className);x=0;for(m=
k.length;x<m;x++){q=k[x];A=q.id;s=q.className||q.field&&"field-"+q.field;s=f(a+(".dgrid-cell.dgrid-cell-padding"+(A?".dgrid-column-"+A:"")+(s?"."+s:"")).replace(C,"-")+"[role\x3d"+("th"===a?"columnheader":"gridcell")+"]");s.columnId=A;z?(A=f(s,"!dgrid-cell-padding div.dgrid-cell-padding"),s.contents=A):A=s;if(E=q.colSpan)s.colSpan=E;if(E=q.rowSpan)s.rowSpan=E;c(A,q);e.appendChild(s)}}return g},left:function(a,c){a.element||(a=this.cell(a));return this.cell(this._move(a,-(c||1),"dgrid-cell"))},right:function(a,
c){a.element||(a=this.cell(a));return this.cell(this._move(a,c||1,"dgrid-cell"))},renderRow:function(a,c){var b=this.createRowCells("td",function(b,d){var e=a;d.get?e=d.get(a):"field"in d&&"_item"!=d.field&&(e=e[d.field]);d.renderCell?w(b,d.renderCell(a,e,b,c)):u.call(d,a,e,b,c)},c&&c.subRows);return f("div[role\x3drow]\x3e",b)},renderHeader:function(){var a=this,c=this.headerNode,b=c.childNodes.length;for(c.setAttribute("role","row");b--;)f(c.childNodes[b],"!");b=this.createRowCells("th",function(b,
d){var a=d.headerNode=b;z&&(b=b.parentNode);var c=d.field;c&&(b.field=c);if(d.renderHeaderCell)w(a,d.renderHeaderCell(a));else if(d.label||d.field)a.appendChild(document.createTextNode(d.label||d.field));!1!==d.sortable&&(c&&"_item"!=c)&&(b.sortable=!0,b.className+=" dgrid-sortable")},this.subRows&&this.subRows.headerRows);this._rowIdToObject[b.id=this.id+"-header"]=this.columns;c.appendChild(b);this._sortListener&&this._sortListener.remove();this._sortListener=t(b,"click,keydown",function(b){if("click"==
b.type||32==b.keyCode||!l("opera")&&13==b.keyCode){var d=b.target,e,h,f;do if(d.sortable){f=[{attribute:e=d.field||d.columnId,descending:(h=a._sort[0])&&h.attribute==e&&!h.descending}];b={bubbles:!0,cancelable:!0,grid:a,parentType:b.type,sort:f};t.emit(d,"dgrid-sort",b)&&(a._sortNode=d,a.set("sort",f));break}while((d=d.parentNode)&&d!=c)}})},resize:function(){var a=this.headerNode.firstChild,c=this.contentNode,b;this.inherited(arguments);if(!l("ie")||7<l("ie")&&!l("quirks"))if(c.style.width="",c&&
a&&(b=a.offsetWidth)!=c.offsetWidth)c.style.width=b+"px"},destroy:function(){this._destroyColumns();this._sortListener&&this._sortListener.remove();this.inherited(arguments)},_setSort:function(a,c){this.inherited(arguments);this.updateSortArrow(this._sort)},updateSortArrow:function(a,c){this._lastSortedArrow&&(f(this._lastSortedArrow,"\x3c!dgrid-sort-up!dgrid-sort-down"),f(this._lastSortedArrow,"!"),delete this._lastSortedArrow);c&&(this._sort=a);if(a[0]){var b=a[0].attribute,g=a[0].descending,d=
this._sortNode,e,h,n;delete this._sortNode;if(!d)for(n in e=this.columns,e)if(h=e[n],h.field==b){d=h.headerNode;break}d&&(d=d.contents||d,this._lastSortedArrow=f(d.firstChild,"-div.dgrid-sort-arrow.ui-icon[role\x3dpresentation]"),this._lastSortedArrow.innerHTML="\x26nbsp;",f(d,g?".dgrid-sort-down":".dgrid-sort-up"),this.resize())}},styleColumn:function(a,c){return this.addCssRule("#"+B.escapeCssIdentifier(this.domNode.id)+" .dgrid-column-"+a,c)},_configColumns:function(a,c){var b=[],g=c instanceof
Array,d,e;for(d in c)e=c[d],"string"==typeof e&&(c[d]=e={label:e}),!g&&!e.field&&(e.field=d),d=e.id=e.id||(isNaN(d)?d:a+d),g&&(this.columns[d]=e),this._configColumn&&this._configColumn(e,d,c,a),e.grid=this,"function"===typeof e.init&&e.init(),b.push(e);return g?c:b},_destroyColumns:function(){var a=this.subRows,c=a&&a.length,b,g,d,e;this.cleanup();for(b=0;b<c;b++){g=0;for(e=a[b].length;g<e;g++)d=a[b][g],"function"===typeof d.destroy&&d.destroy()}},configStructure:function(){var a=this.subRows,c=this._columns=
this.columns;this.columns=!c||c instanceof Array?{}:c;if(a)for(c=0;c<a.length;c++)a[c]=this._configColumns(c+"-",a[c]);else this.subRows=[this._configColumns("",c)]},_getColumns:function(){return this._columns||this.columns},_setColumns:function(a){this._destroyColumns();this.subRows=null;this.columns=a;this._updateColumns()},_setSubRows:function(a){this._destroyColumns();this.subRows=a;this._updateColumns()},setColumns:function(a){v.deprecated("setColumns(...)",'use set("columns", ...) instead',
"dgrid 1.0");this.set("columns",a)},setSubRows:function(a){v.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 1.0");this.set("subRows",a)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);this._started&&(this._sort&&this._sort.length?this.updateSortArrow(this._sort):this.resize())}});r.appendIfNode=w;r.defaultRenderCell=u;return r})},"dgrid/Selection":function(){define("dgrid/Selection",
"dojo/_base/kernel dojo/_base/declare dojo/_base/Deferred dojo/on dojo/has dojo/aspect ./List dojo/has!touch?./util/touch put-selector/put dojo/query dojo/_base/sniff".split(" "),function(v,r,t,l,f,y,B,w,u){function z(b,a){for(var d=b.unselectable=a?"on":"",c=b.getElementsByTagName("*"),h=c.length;--h;)"INPUT"===c[h].tagName||"TEXTAREA"===c[h].tagName||(c[h].unselectable=d)}function C(b,a){var d=b.bodyNode,e=a?"text":21>f("ff")?"-moz-none":"none";c?d.style[c]=e:f("dom-selectstart")?!a&&!b._selectstartHandle?
b._selectstartHandle=l(d,"selectstart",function(b){var a=b.target&&b.target.tagName;"INPUT"!==a&&"TEXTAREA"!==a&&b.preventDefault()}):a&&b._selectstartHandle&&(b._selectstartHandle.remove(),delete b._selectstartHandle):(z(d,!a),!a&&!b._unselectableHandle?b._unselectableHandle=y.after(b,"renderRow",function(b){z(b,!0);return b}):a&&b._unselectableHandle&&(b._unselectableHandle.remove(),delete b._unselectableHandle))}f.add("css-user-select",function(b,a,d){b=d.style;a=["Khtml","O","ms","Moz","Webkit"];
d=a.length;var c="userSelect";do if("undefined"!==typeof b[c])return c;while(d--&&(c=a[d]+"UserSelect"));return!1});f.add("dom-selectstart","undefined"!==typeof document.onselectstart);var a=f("mac")?"metaKey":"ctrlKey",c=f("css-user-select");return r(null,{selectionDelegate:".dgrid-row",selectionEvents:"mousedown,mouseup,dgrid-cellfocusin",deselectOnRefresh:!0,allowSelectAll:!1,selection:{},selectionMode:"extended",allowTextSelection:void 0,create:function(){this.selection={};return this.inherited(arguments)},
postCreate:function(){this.inherited(arguments);var b=this.selectionMode;this.selectionMode="";this._setSelectionMode(b);this._initSelectionEvents()},destroy:function(){this.inherited(arguments);this._selectstartHandle&&this._selectstartHandle.remove();this._unselectableHandle&&this._unselectableHandle.remove()},_setSelectionMode:function(b){b!=this.selectionMode&&(this.clearSelection(),this.selectionMode=b,this._selectionHandlerName="_"+b+"SelectionHandler",this._setAllowTextSelection(this.allowTextSelection))},
setSelectionMode:function(b){v.deprecated("setSelectionMode(...)",'use set("selectionMode", ...) instead',"dgrid 1.0");this.set("selectionMode",b)},_setAllowTextSelection:function(b){"undefined"!==typeof b?C(this,b):C(this,"none"===this.selectionMode);this.allowTextSelection=b},_handleSelect:function(b,a){if(this[this._selectionHandlerName]&&!("dgrid-cellfocusin"==b.type&&"mousedown"==b.parentType||"mouseup"==b.type&&a!=this._waitForMouseUp)){this._waitForMouseUp=null;this._selectionTriggerEvent=
b;if(!b.keyCode||!b.ctrlKey||32==b.keyCode)if(!b.shiftKey&&"mousedown"==b.type&&this.isSelected(a))this._waitForMouseUp=a;else this[this._selectionHandlerName](b,a);this._selectionTriggerEvent=null}},_singleSelectionHandler:function(b,c){var d=b.keyCode?b.ctrlKey:b[a];this._lastSelected===c?this.select(c,null,!d||!this.isSelected(c)):(this.clearSelection(),this.select(c),this._lastSelected=c)},_multipleSelectionHandler:function(b,c){var d=this._lastSelected,e=b.keyCode?b.ctrlKey:b[a],h;b.shiftKey||
(h=e?null:!0,d=null);this.select(c,d,h);d||(this._lastSelected=c)},_extendedSelectionHandler:function(b,c){(2===b.button?!this.isSelected(c):!(b.keyCode?b.ctrlKey:b[a]))&&this.clearSelection(null,!0);this._multipleSelectionHandler(b,c)},_toggleSelectionHandler:function(b,a){this.select(a,null,null)},_initSelectionEvents:function(){var b=this,c=this.selectionDelegate;f("touch")?l(this.contentNode,w.selector(c,w.tap),function(a){b._handleSelect(a,this)}):l(this.contentNode,l.selector(c,this.selectionEvents),
function(a){b._handleSelect(a,this)});this.addKeyHandler&&this.addKeyHandler(32,function(a){b._handleSelect(a,a.target)});if(this.allowSelectAll)this.on("keydown",function(d){d[a]&&65==d.keyCode&&(d.preventDefault(),b[b.allSelected?"clearSelection":"selectAll"]())});y.before(this,"removeRow",function(b,a){var c;a||(c=this.row(b))&&c.id in this.selection&&this.deselect(b)})},allowSelect:function(b){return!0},_selectionEventQueue:function(b,a){var d=this,c="dgrid-"+(b?"select":"deselect"),h=this[c],
f=this._selectionTriggerEvent;f&&(f=f.type);if(h)return h;setTimeout(this._fireSelectionEvent=function(){if(h){var b={bubbles:!0,grid:d};f&&(b.parentType=f);b[a]=h;l.emit(d.contentNode,c,b);h=null;delete d[c]}},0);return h=this[c]=[]},select:function(b,a,c){void 0===c&&(c=!0);b.element||(b=this.row(b));if(!c||this.allowSelect(b)){var e=this.selection,f=e[b.id];null===c&&(c=!f);var n=b.element;!c&&!this.allSelected?delete this.selection[b.id]:e[b.id]=c;n&&(c?u(n,".dgrid-selected.ui-state-active"):
u(n,"!dgrid-selected!ui-state-active"));c!=f&&n&&this._selectionEventQueue(c,"rows").push(b);if(a){a.element||(a=this.row(a));a=a.element;e=b.element;for(e=a&&(a.compareDocumentPosition?2==a.compareDocumentPosition(e):a.sourceIndex>e.sourceIndex)?"down":"up";b.element!=a&&(b=this[e](b));)this.select(b,null,c)}}},deselect:function(b,a){this.select(b,a,!1)},clearSelection:function(b,a){this.allSelected=!1;for(var c in this.selection)b!==c&&this.deselect(c);a||(this._lastSelected=null)},selectAll:function(){this.allSelected=
!0;this.selection={};for(var b in this._rowIdToObject){var a=this.row(this._rowIdToObject[b]);this.select(a.id)}},isSelected:function(b){if("undefined"===typeof b||null===b)return!1;b.element||(b=this.row(b));return b.id in this.selection?!!this.selection[b.id]:this.allSelected&&(!b.data||this.allowSelect(b))},refresh:function(){this.deselectOnRefresh&&(this.clearSelection(),this._fireSelectionEvent&&this._fireSelectionEvent());this._lastSelected=null;return this.inherited(arguments)},renderArray:function(){var b=
this,a=this.inherited(arguments);t.when(a,function(a){var c=b.selection,f,g,l;for(f=0;f<a.length;f++)g=b.row(a[f]),(l=g.id in c?c[g.id]:b.allSelected)&&b.select(g,null,l)});return a}})})},"dgrid/Keyboard":function(){define("dgrid/Keyboard","dojo/_base/declare dojo/aspect dojo/on dojo/_base/lang dojo/has put-selector/put dojo/_base/Deferred dojo/_base/sniff".split(" "),function(v,r,t,l,f,y,B){function w(b){b.preventDefault()}var u={checkbox:1,radio:1,button:1},z=/\bdgrid-cell\b/,C=/\bdgrid-row\b/;
f.add("dom-contains",function(b,a,c){return!!c.contains});var a=v(null,{pageSkip:10,tabIndex:0,keyMap:null,headerKeyMap:null,postMixInProperties:function(){this.inherited(arguments);this.keyMap||(this.keyMap=l.mixin({},a.defaultKeyMap));this.headerKeyMap||(this.headerKeyMap=l.mixin({},a.defaultHeaderKeyMap))},postCreate:function(){function b(a){var c=a.target;return c.type&&(!u[c.type]||32==a.keyCode)}function a(m){function d(){if(c._focusedHeaderNode=k=q?c.headerNode.getElementsByTagName("th")[0]:
c.headerNode)k.tabIndex=c.tabIndex}var q=c.cellNavigation,s=q?z:C,e=m===c.headerNode,k=m;e?(d(),r.after(c,"renderHeader",d,!0)):r.after(c,"renderArray",function(b){return B.when(b,function(b){var a=c._focusedNode||k,d;if(d=s.test(a.className))d=a,d=f("dom-contains")?m.contains(d):m.compareDocumentPosition(d)&8;if(d)return b;d=0;for(var A=m.getElementsByTagName("*"),q;q=A[d];++d)if(s.test(q.className)){a=c._focusedNode=q;break}a.tabIndex=c.tabIndex;return b})});c._listeners.push(t(m,"mousedown",function(a){b(a)||
c._focusOnNode(a.target,e,a)}));c._listeners.push(t(m,"keydown",function(a){if(!a.metaKey&&!a.altKey){var m=c[e?"headerKeyMap":"keyMap"][a.keyCode];m&&!b(a)&&m.call(c,a)}}))}this.inherited(arguments);var c=this;this.tabableHeader&&(a(this.headerNode),t(this.headerNode,"dgrid-cellfocusin",function(){c.scrollTo({x:this.scrollLeft})}));a(this.contentNode)},addKeyHandler:function(a,b,c){return r.after(this[c?"headerKeyMap":"keyMap"],a,b,!0)},_focusOnNode:function(a,b,c){b="_focused"+(b?"Header":"")+"Node";
var m=this[b],d=this.cellNavigation?"cell":"row",q=this[d](a),e,k,g,h,n;if(a=q&&q.element){if(this.cellNavigation){e=a.getElementsByTagName("input");n=0;for(g=e.length;n<g;n++)if(k=e[n],(-1!=k.tabIndex||"lastValue"in k)&&!k.disabled){8>f("ie")&&(k.style.position="relative");k.focus();8>f("ie")&&(k.style.position="");h=!0;break}}c=l.mixin({grid:this},c);c.type&&(c.parentType=c.type);c.bubbles||(c.bubbles=!0);m&&(y(m,"!dgrid-focus[!tabIndex]"),8>f("ie")&&(m.style.position=""),c[d]=this[d](m),t.emit(a,
"dgrid-cellfocusout",c));m=this[b]=a;c[d]=q;h||(8>f("ie")&&(a.style.position="relative"),a.tabIndex=this.tabIndex,a.focus());y(a,".dgrid-focus");t.emit(m,"dgrid-cellfocusin",c)}},focusHeader:function(a){this._focusOnNode(a||this._focusedHeaderNode,!0)},focus:function(a){this._focusOnNode(a||this._focusedNode,!1)}}),c=a.moveFocusVertical=function(a,b){var c=this.cellNavigation,m=this[c?"cell":"row"](a),m=c&&m.column.id,d=this.down(this._focusedNode,b,!0);c&&(d=this.cell(d,m));this._focusOnNode(d,!1,
a);a.preventDefault()};v=a.moveFocusUp=function(a){c.call(this,a,-1)};var b=a.moveFocusDown=function(a){c.call(this,a,1)},g=a.moveFocusPageUp=function(a){c.call(this,a,-this.pageSkip)},d=a.moveFocusPageDown=function(a){c.call(this,a,this.pageSkip)},e=a.moveFocusHorizontal=function(a,b){if(this.cellNavigation){var c=!this.row(a);this._focusOnNode(this.right(this["_focused"+(c?"Header":"")+"Node"],b),c,a);a.preventDefault()}},h=a.moveFocusLeft=function(a){e.call(this,a,-1)},n=a.moveFocusRight=function(a){e.call(this,
a,1)},x=a.moveHeaderFocusEnd=function(a,b){var c;this.cellNavigation&&(c=this.headerNode.getElementsByTagName("th"),this._focusOnNode(c[b?0:c.length-1],!0,a));a.preventDefault()},m=a.moveHeaderFocusHome=function(a){x.call(this,a,!0)},k=a.moveFocusEnd=function(a,b){var c=this,m=this.cellNavigation,d=this.contentNode,q=d.scrollTop+(b?0:d.scrollHeight),d=d[b?"firstChild":"lastChild"],e=-1<d.className.indexOf("dgrid-preload"),k=e?d[(b?"next":"previous")+"Sibling"]:d,g=k.offsetTop+(b?0:k.offsetHeight),
h;if(e){for(;k&&0>k.className.indexOf("dgrid-row");)k=k[(b?"next":"previous")+"Sibling"];if(!k)return}!e||1>d.offsetHeight?(m&&(k=this.cell(k,this.cell(a).column.id)),this._focusOnNode(k,!1,a)):(f("dom-addeventlistener")||(a=l.mixin({},a)),h=r.after(this,"renderArray",function(d){h.remove();return B.when(d,function(d){d=d[b?0:d.length-1];m&&(d=c.cell(d,c.cell(a).column.id));c._focusOnNode(d,!1,a)})}));q===g&&a.preventDefault()},q=a.moveFocusHome=function(a){k.call(this,a,!0)};a.defaultKeyMap={32:w,
33:g,34:d,35:k,36:q,37:h,38:v,39:n,40:b};a.defaultHeaderKeyMap={32:w,35:x,36:m,37:h,39:n};return a})},"dgrid/editor":function(){define("dgrid/editor","dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has ./Grid put-selector/put dojo/_base/sniff".split(" "),function(v,r,t,l,f,y,B,w,u){function z(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=a.defaultChecked=!!b}function C(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==
typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date){var c=new Date(a);a=isNaN(c.getTime())?a:c}return a}function a(a,b,c,d,e){var h,p,g;if((c&&c.valueOf())!=(d&&d.valueOf())&&(h=a.cell(b),p=h.row,g=h.column,g.field&&p))if(h={grid:a,cell:h,rowId:p.id,oldValue:c,value:d,bubbles:!0,cancelable:!0},e&&e.type&&(h.parentType=e.type),f.emit(b,"dgrid-datachange",h))a.updateDirty&&(a.updateDirty(p.id,g.field,d),g.autoSave&&setTimeout(function(){a._trackError("save")},0));else{var D;(D=b.widget)?
(D._dgridIgnoreChange=!0,D.set("value",c),setTimeout(function(){D._dgridIgnoreChange=!1},0)):(D=b.input)&&z(D,c);return c}return d}function c(b,c,d,e){if(!d.isValid||d.isValid()){c=a;var f=(d.domNode||d).parentNode,g=h?n:d._dgridLastValue,p;p="function"==typeof d.get?C(d.get("value")):C(d["checkbox"==d.type||"radio"==d.type?"checked":"value"]);b=c(b,f,g,p,e);h?n=b:d._dgridLastValue=b}}function b(a){var b=a.editor,d=a.editOn,e=a.grid,h="string"!=typeof b,g,p,F;g=a.editorArgs||{};"function"==typeof g&&
(g=g.call(e,a));if(h)p=new b(g),h=p.focusNode||p.domNode,h.className+=" dgrid-input",p.connect(p,d?"onBlur":"onChange",function(){p._dgridIgnoreChange||c(e,a,this,{type:"widget"})});else if(F=function(b){var d=b.target;"_dgridLastValue"in d&&-1<d.className.indexOf("dgrid-input")&&c(e,a,d,b)},a.grid._hasInputListener||(e._hasInputListener=!0,e.on("change",function(a){F(a)})),p=h=u(("textarea"==b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",r.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},
g)),9>B("ie")||B("ie")&&B("quirks"))"radio"==b||"checkbox"==b?f(p,"click",function(a){F(a)}):f(p,"change",function(a){F(a)});f(h,"mousedown",function(a){a.stopPropagation()});return p}function g(a,d){var e=b(a),g=a.grid,s=e.domNode||e,l=e.focusNode||s,p=e.domNode?function(){e.set("value",e._dgridLastValue)}:function(){z(e,e._dgridLastValue);c(a.grid,a,e)};f(l,"keydown",function(b){b=b.keyCode||b.which;27==b?(p(),n=e._dgridLastValue,l.blur()):13==b&&!1!==a.dismissOnEnter&&l.blur()});(a._editorBlurHandle=
f.pausable(e,"blur",function(){var b=s.parentNode,c=b.children.length-1,d={alreadyHooked:!0},k=g.cell(s);f.emit(k.element,"dgrid-editor-hide",{grid:g,cell:k,column:a,editor:e,bubbles:!0,cancelable:!1});b.removeChild(s);for(u(k.element,"!dgrid-cell-editing");c--;)u(b.firstChild,"!");w.appendIfNode(b,a.renderCell(a.grid.row(b).data,n,b,x?r.delegate(d,x):d));h=n=x=null;a._editorBlurHandle.pause()})).pause();return e}function d(a,b,c,d){var e=a.domNode,g=b.grid;e||z(a,d);c.innerHTML="";u(c,".dgrid-cell-editing");
u(c,a.domNode||a);e&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",d),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=d;h&&(n=d,f.emit(c,"dgrid-editor-show",{grid:g,cell:g.cell(c),column:b,editor:a,bubbles:!0,cancelable:!1}))}function e(a){var b,c,e,g,f,p;a.column||(a=this.cell(a));if(!a||!a.element)return null;b=a.column;g=b.field;c=a.element.contents||a.element;if(f=b.editorInstance){if(h!=c&&(!b.canEdit||b.canEdit(a.row.data,e)))return h=c,a=a.row,e=(e=this.dirty&&
this.dirty[a.id])&&g in e?e[g]:b.get?b.get(a.data):a.data[g],d(b.editorInstance,b,c,e),p=new l,setTimeout(function(){f.focus&&f.focus();b._editorBlurHandle&&b._editorBlurHandle.resume();p.resolve(f)},0),p.promise}else if(b.editor&&(f=c.widget||c.input))return p=new l,f.focus&&f.focus(),p.resolve(f),p.promise;return null}var h,n,x;return function(a,c,h){var l=a.renderCell||w.defaultRenderCell,n=[],r;a||(a={});a.editor=c=c||a.editor||"text";a.editOn=h=h||a.editOn;r="string"!=typeof c;a.widgetArgs&&
(v.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 1.0"),a.editorArgs=a.widgetArgs);y.after(a,"init",h?function(){var b=a.grid;b.edit||(b.edit=e);a.editorInstance=g(a,l)}:function(){var b=a.grid;b.edit||(b.edit=e);r&&n.push(y.before(b,"removeRow",function(c){c=b.cell(c,a.id).element;(c=(c.contents||c).widget)&&c.destroyRecursive()}))});y.after(a,"destroy",function(){t.forEach(n,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();h&&r&&a.editorInstance.destroyRecursive()});
a.renderCell=h?function(b,c,d,e){if(!e||!e.alreadyHooked)f("TD"==d.tagName?d:d.parentNode,h,function(){x=e;a.grid.edit(this)});return l.call(a,b,c,d,e)}:function(c,e,f,g){if(!a.canEdit||a.canEdit(c,e))c=b(a),d(c,a,f,e),f[r?"widget":"input"]=c;else return l.call(a,c,e,f,g)};return a}})}}});define("dojorama/layers/dgrid-extra",[],1);
//@ sourceMappingURL=dgrid-extra.js.map