//>>built
require({cache:{"put-selector/put":function(){(function(w){var h,d=/[-+,> ]/;w("put-selector/put",[],h=function(l,m){function v(k){function f(){a&&(g&&a!=g)&&(g==k&&(r||(r=d.test(t)&&l.createDocumentFragment()))||g).insertBefore(a,m||null)}for(var r,p,m,g,a,q=arguments,s=q[0],A=0;A<q.length;A++){var t=q[A];if("object"==typeof t){p=!1;if(t instanceof Array){a=l.createDocumentFragment();for(var y=0;y<t.length;y++)a.appendChild(v(t[y]));t=a}if(t.nodeType)a=t,f(),g=t,m=0;else for(y in t)a[y]=t[y]}else if(p)p=
!1,a.appendChild(l.createTextNode(t));else{1>A&&(k=null);p=!0;if(s=t.replace(u,function(s,n,y,d,r,p){n&&(f(),"-"==n||"+"==n?(g=(m=a||g).parentNode,a=null,"+"==n&&(m=m.nextSibling)):("\x3c"==n?g=a=(a||g).parentNode:(","==n?g=k:a&&(g=a),a=null),m=0),a&&(g=a));if((s=!y&&d)||!a&&(y||r))"$"==s?(s=q[++A],g.appendChild(l.createTextNode(s))):(s=s||v.defaultTag,(n=c&&q[A+1]&&q[A+1].name)&&(s="\x3c"+s+' name\x3d"'+n+'"\x3e'),a=b&&~(e=s.indexOf("|"))?l.createElementNS(b[s.slice(0,e)],s.slice(e+1)):l.createElement(s));
if(y)if("$"==d&&(d=q[++A]),"#"==y)a.id=d;else if(n=(s=a.className)&&(" "+s+" ").replace(" "+d+" "," "),"."==y)a.className=s?(n+d).substring(1):d;else if("!"==t){var h;c?v("div",a,"\x3c").innerHTML="":(h=a.parentNode)&&h.removeChild(a)}else n=n.substring(1,n.length-1),n!=s&&(a.className=n);r&&("$"==p&&(p=q[++A]),"style"==r?a.style.cssText=p:(y="!"==r.charAt(0)?(r=r.substring(1))&&"removeAttribute":"setAttribute",p=""===p?r:p,b&&~(e=r.indexOf("|"))?a[y+"NS"](b[r.slice(0,e)],r.slice(e+1),p):a[y](r,p)));
return""}))throw new SyntaxError("Unexpected char "+s+" in "+t);f();g=s=a||g}}k&&r&&k.appendChild(r);return s}d=m||d;var u=/(?:\s*([-+ ,<>]))?\s*(\.|!\.?|#)?([-\w%$|]+)?(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,e,b=!1;l=l||document;var c="object"==typeof l.createElement;v.addNamespace=function(c,f){l.createElementNS?(b||(b={}))[c]=f:l.namespaces.add(c,f)};v.defaultTag="div";v.forDocument=h;return v})})(function(w,h,d){d=d||h;"function"===typeof define?define([],function(){return d()}):"undefined"==
typeof window?require("./node-html")(module,d):put=d()})},"xstyle/has-class":function(){define("xstyle/has-class",["dojo/has"],function(w){var h={};return function(){for(var d,l=arguments,m=0;m<l.length;m++)if(d=l[m],!h[d]){h[d]=!0;var v=d.match(/^(no-)?(.+?)((-[\d\.]+)(-[\d\.]+)?)?$/),u=w(v[2]),e=-v[4];if((0<e?e<=u&&(-v[5]||e)>=u:!!u)==!v[1])document.documentElement.className+=" has-"+d}}})},"xstyle/css":function(){define("xstyle/css",["require"],function(w){function h(d,l,m){var h=document.documentElement;
d=h.insertBefore(document.createElement(d),h.firstChild);d.id=l;l=(d.currentStyle||getComputedStyle(d,null))[m];h.removeChild(d);return l}return{load:function(d,l,m,v){function u(){var b=h("x-parse",null,"content");b&&"none"!=b?l([eval(b)],m):m()}var e=l.toUrl(d),b=l.cache["url:"+e];if(b)return b.xCss&&(b=b.cssText),w(["./util/createStyleSheet"],function(c){c(b)}),u();if("none"==h("div",d.replace(/\//g,"-").replace(/\..*/,"")+"-loaded","display"))return u();w(["./load-css"],function(b){b(e,u)})}}})},
"dgrid/List":function(){define("dgrid/List","dojo/_base/kernel dojo/_base/declare dojo/on dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(w,h,d,l,m,v,u,e){function b(a,q){var b=document.body,c;e(b,a,".dgrid-scrollbar-measure");c=a["offset"+q]-a["client"+q];e(a,"!dgrid-scrollbar-measure");b.removeChild(a);return c}function c(a){var q=a?"."+a.replace(G,"."):"";this._class&&(q="!"+this._class.replace(G,
"!")+q);e(this.domNode,q);this._class=a}function k(){return this._class}u("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var f,r;l.add("dom-scrollbar-width",function(a,q,s){return b(s,"Width")});l.add("dom-scrollbar-height",function(a,q,s){return b(s,"Height")});var p=0,G=/ +/g,g=7>l("ie")&&!l("quirks")?function(){var a,q,b;if(this._started&&(a=document.documentElement,q=a.clientWidth,a=a.clientHeight,b=this._prevWinDims||[],b[0]!==q||b[1]!==a))this.resize(),this._prevWinDims=
[q,a]}:function(){this._started&&this.resize()};return h(v?v:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,postscript:function(a,q){var b=this;(this._Row=function(a,q,b){this.id=a;this.data=q;this.element=b}).prototype.remove=function(){b.removeRow(this.element)};q&&(this.srcNodeRef=q=q.nodeType?q:document.getElementById(q));this.create(a,q)},listType:"list",create:function(a,q){var b=this.domNode=q||e("div"),f;a?(this.params=a,h.safeMixin(this,a),f=a["class"]||
a.className||b.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=b.id=b.id||this.id||"dgrid_"+p++;this.buildRendering();f&&c.call(this,f);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,s,c,f,k;k=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||
document.body.style.direction).toLowerCase();a.className="";e(a,"[role\x3dgrid].ui-widget.dgrid.dgrid-"+this.listType);s=this.headerNode=e(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+(this.showHeader?"":".dgrid-header-hidden"));(l("quirks")||8>l("ie"))&&e(a,"div.dgrid-spacer");c=this.bodyNode=e(a,"div.dgrid-scroller");c.tabIndex=-1;this.headerScrollNode=e(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");f=this.footerNode=e("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));
e(a,f);k&&(a.className+=" dgrid-rtl"+(l("webkit")?"":" dgrid-rtl-nonwebkit"));d(c,"scroll",function(f){b.showHeader&&(s.scrollLeft=f.scrollLeft||c.scrollLeft);f.stopPropagation();d.emit(a,"scroll",{scrollTarget:c})});this.configStructure();this.renderHeader();this.contentNode=this.touchNode=e(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=d(window,"resize",m.throttleDelayed(g,this)))},startup:function(){this._started||(this.inherited(arguments),this._started=
!0,this.resize(),this.set("sort",this._sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,k=b.offsetHeight,e=this.showFooter?c.offsetHeight:0,d=l("quirks")||7>l("ie");this.headerScrollNode.style.height=a.style.marginTop=k+"px";a.style.marginBottom=e+"px";d&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-k-e,0)+"px",e&&(c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0)));f||(f=l("dom-scrollbar-width"),
r=l("dom-scrollbar-height"),l("ie")&&(f++,r++),m.addCssRule(".dgrid-scrollbar-width","width: "+f+"px"),m.addCssRule(".dgrid-scrollbar-height","height: "+r+"px"),17!=f&&!d&&(m.addCssRule(".dgrid-header","right: "+f+"px"),m.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header","left: "+f+"px")));d&&(b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0))},addCssRule:function(a,b){var c=m.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(c);return c},on:function(a,b){var c=
d(this.domNode,a,b);l("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();e(this.domNode,"!")},refresh:function(){this.cleanup();
this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},newRow:function(a,b,c,f,k){if(b){var d=this.insertRow(a,b,c,f,k);e(d,".ui-state-highlight");setTimeout(function(){e(d,"!ui-state-highlight")},250);return d}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(-1<(a.className+" ").indexOf("dgrid-row ")&&e(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=
b++);while((a=a.nextSibling)&&a.rowIndex!=b&&!a.blockRowIndex)}}},renderArray:function(a,b,c){function f(a){u=d.insertRow(a,m,null,e++,c);u.observerIndex=p;return u}function k(a){if(l=b?b.parentNode:d.contentNode)l.insertBefore(m,b||null),(u=a[a.length-1])&&d.adjustRowIndices(u);return g=a}c=c||{};var d=this,e=c.start||0,r,g,l;b||(this._lastCollection=a);if(a.observe)var p=this.observers.push(a.observe(function(a,f,k){var e,t,h;-1<f&&g[f]&&(r=g.splice(f,1)[0],r.parentNode==l&&((e=r.nextSibling)&&
f!=k&&e.rowIndex--,d.removeRow(r)),d._processScroll&&d._processScroll());if(-1<k){t=g[k];if(!t&&(t=g[k-1]))t=(t.connected||t).nextSibling;h=b&&b.parentNode||t&&t.parentNode||d.contentNode;if(r=d.newRow(a,h,t,c.start+k,c))if(r.observerIndex=p,g.splice(k,0,r),!e||k<f)e=r.previousSibling,e=!e||e.rowIndex+1==r.rowIndex||0==r.rowIndex?r:e;c.count++}f!=k&&e&&d.adjustRowIndices(e);d._onNotification(g,a,f,k)},!0))-1;var m=document.createDocumentFragment();if(a.map){if(g=a.map(f,console.error),g.then)return g.then(k)}else{g=
[];for(var h=0,v=a.length;h<v;h++)g[h]=f(a[h])}var u;return k(g)},_onNotification:function(a,b,c,f){},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,f,k){var d=k.parentId,d=this.id+"-row-"+(d?d+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),e=document.getElementById(d),r=e&&e.previousSibling;e&&this.removeRow(e);e=this.renderRow(a,k);e.className=(e.className||"")+" ui-state-default dgrid-row "+(1==f%2?"dgrid-row-odd":"dgrid-row-even");this._rowIdToObject[e.id=
d]=a;b.insertBefore(e,c||null);r&&this.adjustRowIndices(r);e.rowIndex=f;return e},renderRow:function(a,b){return e("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||e(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):
(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,f){var k,e;e=k=a.element;b=b||1;do if(a=k[0>b?"previousSibling":"nextSibling"]){do if((k=a)&&-1<(k.className+" ").indexOf(c+" ")){e=k;b+=0>b?1:-1;break}while(a=(!f||!k.hidden)&&k[0>b?"lastChild":"firstChild"])}else if(k=k.parentNode,k===this.bodyNode||k===this.headerNode)break;while(b);return e},up:function(a,b,c){a.element||(a=
this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:l("touch")?function(){return this.inherited(arguments)}:function(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:l("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},
get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:k,_setClass:c,_getClassName:k,_setClassName:c,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,
descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(c,k){var f=c[a],e=k[a];void 0===f&&(f="");void 0===e&&(e="");return f==e?0:f>e==!b?1:-1})),this.renderArray(this._lastCollection))},sort:function(a,b){w.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=
a;e(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},setShowHeader:function(a){w.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;e(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})})},"dgrid/util/misc":function(){define("dgrid/util/misc",["put-selector/put"],function(w){var h=[],d,l,m,v=/([^A-Za-z0-9_\u00A0-\uFFFF-])/g,
u={defaultDelay:15,throttle:function(e,b,c){var k=!1;c=c||u.defaultDelay;return function(){k||(k=!0,e.apply(b,arguments),setTimeout(function(){k=!1},c))}},throttleDelayed:function(e,b,c){var k=!1;c=c||u.defaultDelay;return function(){if(!k){k=!0;var f=arguments;setTimeout(function(){k=!1;e.apply(b,f)},c)}}},debounce:function(e,b,c){var k;c=c||u.defaultDelay;return function(){k&&(clearTimeout(k),k=null);var f=arguments;k=setTimeout(function(){e.apply(b,f)},c)}},addCssRule:function(e,b){d||(d=w(document.getElementsByTagName("head")[0],
"style"),d=d.sheet||d.styleSheet,l=d.deleteRule?"deleteRule":"removeRule",m=d.cssRules?"cssRules":"rules");var c=h.length;h[c]=(d.cssRules||d.rules).length;d.addRule?d.addRule(e,b):d.insertRule(e+"{"+b+"}",h[c]);return{get:function(b){return d[m][h[c]].style[b]},set:function(b,f){"undefined"!==typeof h[c]&&(d[m][h[c]].style[b]=f)},remove:function(){var b=h[c],f,e;if(void 0!==b){d[l](b);h[c]=void 0;f=c+1;for(e=h.length;f<e;f++)h[f]>b&&h[f]--}}}},escapeCssIdentifier:function(e){return e.replace(v,"\\$1")}};
return u})},"dgrid/OnDemandList":function(){define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(w,h,d,l,m,v,u,e){return d([w,h],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var b=this;v(this.bodyNode,
"scroll",u[this.pagingMethod](function(c){b._processScroll(c)},null,this.pagingDelay))},renderQuery:function(b,c,k){function f(a){e(q,"!");if(a)throw d._refreshDeferred&&(d._refreshDeferred.reject(a),delete d._refreshDeferred),a;}var d=this,p={query:b,count:0,node:c,options:k},h=this.preload,g;if(!c){var a={node:e(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:b,next:p,options:k};a.node.style.height="0";p.node=c=e(this.contentNode,"div.dgrid-preload");p.previous=a}c.rowIndex=this.minRowsPerPage;
h?((p.next=h.next)&&this.bodyNode.scrollTop>=h.node.offsetTop?p.previous=h:(p.next=h,p.previous=h.previous),p.previous.next=p,p.next.previous=p):this.preload=p;var q=e(c,"-div.dgrid-loading");e(q,"div.dgrid-below").innerHTML=this.loadingMessage;k=l.mixin(this.get("queryOptions"),k,{start:0,count:this.minRowsPerPage,query:b});this._trackError(function(){return g=b(k)});if("undefined"===typeof g)f();else return m.when(d.renderArray(g,c,k),function(a){return m.when(g.total||g.length,function(b){e(q,
"!");var f=a.length;0===b&&(d.noDataNode=e(d.contentNode,"div.dgrid-no-data"),d.noDataNode.innerHTML=d.noDataMessage);for(var k=0,l=0;l<f;l++)k+=d._calcRowHeight(a[l]);f&&k&&(d.rowHeight=k/f);b-=f;p.count=b;c.rowIndex=f;b?c.style.height=Math.min(b*d.rowHeight,d.maxEmptySpace)+"px":c.style.display="none";d._previousScrollPosition&&(d.scrollTo(d._previousScrollPosition),delete d._previousScrollPosition);d._processScroll();d._refreshDeferred&&(d._refreshDeferred.resolve(g),delete d._refreshDeferred);
return a},f)},f),g},refresh:function(b){var c=this,d=b&&b.keepScrollPosition,f;"undefined"===typeof d&&(d=this.keepScrollPosition);d&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return d=this._refreshDeferred=new m,f=c.renderQuery(function(b){return c.store.query(c.query,b)}),"undefined"===typeof f&&d.reject(),d.then(function(b){setTimeout(function(){v.emit(c.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:c,results:b})},0);delete c._refreshDeferred;
return b},function(b){delete c._refreshDeferred;throw b;})},resize:function(){this.inherited(arguments);this._processScroll()},_calcRowHeight:function(b){var c=b.previousSibling;return c&&c.offsetTop!=b.offsetTop?b.offsetHeight:0},lastScrollTop:0,_processScroll:function(b){function c(a,b,c,g){var l=f.farOffRemoval,h=a.node;if(b>2*l){for(var p,q=h[c],n=0,r=0,m=[];p=q;){var s=f._calcRowHeight(p);if(n+s+l>b||0>q.className.indexOf("dgrid-row")&&0>q.className.indexOf("dgrid-loading"))break;var q=p[c],
t,u=p.observerIndex;if(u!=t&&-1<t){var v=f.observers,w=v[t];w&&w.cancel();v[t]=0}n+=s;r+=p.count||1;t=u;f.removeRow(p,!0);m.push(p)}a.count+=r;g?(h.rowIndex-=r,d(a)):h.style.height=h.offsetHeight+n+"px";var y=e("div",m);setTimeout(function(){e(y,"!")},1)}}function d(a,b){a.node.style.height=Math.min(a.count*f.rowHeight,b?Infinity:f.maxEmptySpace)+"px"}var f=this,h=f.bodyNode;b=b&&b.scrollTop||this.getScrollPosition().y;var p=h.offsetHeight+b,u,g,a=f.preload,q=f.lastScrollTop,s=f.bufferRows*f.rowHeight,
v=s-f.rowHeight,t,y,w;for(f.lastScrollTop=b;a&&!a.node.offsetWidth;)a=a.previous;for(;a&&a!=u;){u=f.preload;f.preload=a;g=a.node;var n=g.offsetTop;if(p+1+v<n){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(b-1-v>n+g.offsetHeight){do a=a.next;while(a&&!a.node.offsetWidth)}else{var x=((g.rowIndex?b-s:p)-n)/f.rowHeight,n=(p-b+2*s)/f.rowHeight,D=Math.max(Math.min((b-q)*f.rowHeight,f.maxRowsPerPage/2),f.maxRowsPerPage/-2),n=n+Math.min(Math.abs(D),10);0==g.rowIndex&&(x-=n);x=Math.max(x,0);10>x&&
(0<x&&n+x<f.maxRowsPerPage)&&(n+=Math.max(0,x),x=0);n=Math.min(Math.max(n,f.minRowsPerPage),f.maxRowsPerPage,a.count);if(0==n)return;var n=Math.ceil(n),x=Math.min(Math.floor(x),a.count-n),B=l.mixin(f.get("queryOptions"),a.options);a.count-=n;var z=g,E,F=f.queryRowsOverlap;if(D=0<g.rowIndex&&a){var C=a.previous;C&&(c(C,b-(C.node.offsetTop+C.node.offsetHeight),"nextSibling"),0<x&&C.node==g.previousSibling?(x=Math.min(a.count,x),a.previous.count+=x,d(a.previous,!0),g.rowIndex+=x,F=0):n+=x,a.count-=x);
B.start=g.rowIndex-F;g.rowIndex+=n}else a.next&&(c(a.next,a.next.node.offsetTop-p,"previousSibling",!0),z=g.nextSibling,z==a.next.node?(a.next.count+=a.count-x,a.next.node.rowIndex=x+n,d(a.next),a.count=x,F=0):E=!0),B.start=a.count;B.count=Math.min(n+F,f.maxRowsPerPage);E&&(z&&z.offsetWidth)&&(E=z.offsetTop);d(a);g=e(z,"-div.dgrid-loading[style\x3dheight:"+n*f.rowHeight+"px]");e(g,"div.dgrid-"+(D?"below":"above")).innerHTML=f.loadingMessage;g.count=n;g.blockRowIndex=!0;B.query=a.query;var H=a.query(B);
if(void 0===f._trackError(function(){return H})){e(g,"!");return}(function(a,b,c,g,h){w=m.when(f.renderArray(h,a,B),function(b){y=h;z=a.nextSibling;e(a,"!");if(g&&z&&z.offsetWidth){var l=f.getScrollPosition();f.scrollTo({x:l.x,y:l.y+z.offsetTop-g,preserveMomentum:!0})}c&&m.when(h.total||h.length,function(a){c.count=a-c.node.rowIndex;d(c)});f._processScroll();return b},function(b){e(a,"!");throw b;})}).call(this,g,h,D,E,H);a=a.previous}}if(w&&(t=this._refreshDeferred))delete this._refreshDeferred,
m.when(w,function(){t.resolve(y)})}})})},"dgrid/_StoreMixin":function(){define("dgrid/_StoreMixin","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on put-selector/put".split(" "),function(w,h,d,l,m,v){function u(b){return b}function e(b){"object"!==typeof b&&(b=Error(b));b.grid=this;m.emit(this.domNode,"dgrid-error",{grid:this,error:b,cancelable:!0,bubbles:!0})&&console.error(b)}return h(null,{store:null,query:null,queryOptions:null,getBeforePut:!0,noDataMessage:"",
loadingMessage:"",constructor:function(){this.query={};this.queryOptions={};this.dirty={};this._updating={}},_configColumn:function(b){b.set&&(this._columnsWithSet||(this._columnsWithSet={}),this._columnsWithSet[b.field]=b)},_configColumns:function(){this._columnsWithSet=null;return this.inherited(arguments)},_setStore:function(b,c,d){this.store=b;this.dirty={};this.set("query",c,d)},_setQuery:function(b,c){var d=c&&c.sort;this.query=void 0!==b?b:this.query;this.queryOptions=c||this.queryOptions;
d?this.set("sort",d):this.refresh()},setStore:function(b,c,d){w.deprecated("setStore(...)",'use set("store", ...) instead',"dgrid 1.0");this.set("store",b,c,d)},setQuery:function(b,c){w.deprecated("setQuery(...)",'use set("query", ...) instead',"dgrid 1.0");this.set("query",b,c)},_getQueryOptions:function(){var b=d.delegate(this.queryOptions,{});this._sort.length&&(b.sort=this._sort);return b},_getQuery:function(){var b=this.query;return"object"==typeof b&&null!=b?d.delegate(b,{}):b},_setSort:function(b,
c){this.store&&(this._lastCollection=null);this.inherited(arguments)},insertRow:function(b,c,e,f,h){var l=this.store,m=this.dirty,l=l&&l.getIdentity(b),g;l in m&&!(l in this._updating)&&(g=m[l]);g&&(b=d.delegate(b,g));return this.inherited(arguments)},updateDirty:function(b,c,d){var f=this.dirty,e=f[b];e||(e=f[b]={});e[c]=d},setDirty:function(b,c,d){w.deprecated("setDirty(...)","use updateDirty() instead","dgrid 1.0");this.updateDirty(b,c,d)},save:function(){function b(a,b){return function(e){var g=
c._columnsWithSet,h=c._updating,m,n;for(m in b)e[m]=b[m];if(g)for(m in g)n=g[m].set(e),void 0!==n&&(e[m]=n);h[a]=!0;return l.when(d.put(e),function(){delete f[a];delete h[a]})}}var c=this,d=this.store,f=this.dirty,e=new l,h=e.promise,m=function(a){var b;return c.getBeforePut||!(b=c.row(a).data)?function(){return d.get(a)}:function(){return b}},g;for(g in f)var a=b(g,f[g]),h=h.then(m(g)).then(a);e.resolve();return h},revert:function(){this.dirty={};this.refresh()},_trackError:function(b){var c;"string"==
typeof b&&(b=d.hitch(this,b));try{c=b()}catch(k){e.call(this,k)}return l.when(c,u,d.hitch(this,e))},newRow:function(){this.noDataNode&&(v(this.noDataNode,"!"),delete this.noDataNode);return this.inherited(arguments)},removeRow:function(b,c){var d={element:b};!c&&(this.noDataMessage&&this.up(d).element===b&&this.down(d).element===b)&&(this.noDataNode=v(this.contentNode,"div.dgrid-no-data"),this.noDataNode.innerHTML=this.noDataMessage);return this.inherited(arguments)}})})}}});
define("dojorama/layers/dgrid-common",[],1);