//>>built
require({cache:{"put-selector/put":function(){(function(x){var m,c=/[-+,> ]/;x([],m=function(l,n){function r(f){function d(){a&&(g&&a!=g)&&(g==f&&(k||(k=c.test(s)&&l.createDocumentFragment()))||g).insertBefore(a,n||null)}for(var k,q,n,g,a,y=arguments,h=y[0],A=0;A<y.length;A++){var s=y[A];if("object"==typeof s){q=!1;if(s instanceof Array){a=l.createDocumentFragment();for(var t=0;t<s.length;t++)a.appendChild(r(s[t]));s=a}if(s.nodeType)a=s,d(),g=s,n=0;else for(t in s)a[t]=s[t]}else if(q)q=!1,a.appendChild(l.createTextNode(s));
else{1>A&&(f=null);q=!0;if(h=s.replace(u,function(h,p,t,c,k,q){p&&(d(),"-"==p||"+"==p?(g=(n=a||g).parentNode,a=null,"+"==p&&(n=n.nextSibling)):("\x3c"==p?g=a=(a||g).parentNode:(","==p?g=f:a&&(g=a),a=null),n=0),a&&(g=a));if((h=!t&&c)||!a&&(t||k))"$"==h?(h=y[++A],g.appendChild(l.createTextNode(h))):(h=h||r.defaultTag,(p=b&&y[A+1]&&y[A+1].name)&&(h="\x3c"+h+' name\x3d"'+p+'"\x3e'),a=v&&~(e=h.indexOf("|"))?l.createElementNS(v[h.slice(0,e)],h.slice(e+1)):l.createElement(h));if(t)if("$"==c&&(c=y[++A]),
"#"==t)a.id=c;else if(p=(h=a.className)&&(" "+h+" ").replace(" "+c+" "," "),"."==t)a.className=h?(p+c).substring(1):c;else if("!"==s){var m;b?r("div",a,"\x3c").innerHTML="":(m=a.parentNode)&&m.removeChild(a)}else p=p.substring(1,p.length-1),p!=h&&(a.className=p);k&&("$"==q&&(q=y[++A]),"style"==k?a.style.cssText=q:(t="!"==k.charAt(0)?(k=k.substring(1))&&"removeAttribute":"setAttribute",q=""===q?k:q,v&&~(e=k.indexOf("|"))?a[t+"NS"](v[k.slice(0,e)],k.slice(e+1),q):a[t](k,q)));return""}))throw new SyntaxError("Unexpected char "+
h+" in "+s);d();g=h=a||g}}f&&k&&f.appendChild(k);return h}c=n||c;var u=/(?:\s*([-+ ,<>]))?\s*(\.|!\.?|#)?([-\w%$|]+)?(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,e,v=!1;l=l||document;var b="object"==typeof l.createElement;r.addNamespace=function(b,d){l.createElementNS?(v||(v={}))[b]=d:l.namespaces.add(b,d)};r.defaultTag="div";r.forDocument=m;return r})})(function(x,m,c){c=c||m;"function"===typeof define?define([],function(){return c()}):"undefined"==typeof window?require("./node-html")(module,c):put=
c()})},"xstyle/has-class":function(){define(["dojo/has"],function(x){var m={};return function(){for(var c,l=arguments,n=0;n<l.length;n++)if(c=l[n],!m[c]){m[c]=!0;var r=c.match(/^(no-)?(.+?)((-[\d\.]+)(-[\d\.]+)?)?$/),u=x(r[2]),e=-r[4];if((0<e?e<=u&&(-r[5]||e)>=u:!!u)==!r[1])document.documentElement.className+=" has-"+c}}})},"xstyle/css":function(){define(["require"],function(x){function m(c,l,n){var m=document.documentElement;c=m.insertBefore(document.createElement(c),m.firstChild);c.id=l;l=(c.currentStyle||
getComputedStyle(c,null))[n];m.removeChild(c);return l}return{load:function(c,l,n,r){function u(){var b=m("x-parse",null,"content");b&&"none"!=b?l([eval(b)],n):n()}var e=l.toUrl(c),v=l.cache["url:"+e];if(v)return v.xCss&&(v=v.cssText),x(["./util/createStyleSheet"],function(b){b(v)}),u();if("none"==m("div",c.replace(/\//g,"-").replace(/\..*/,"")+"-loaded","display"))return u();x(["./core/load-css"],function(b){b(e,u)})}}})},"dgrid/List":function(){define("dojo/_base/kernel dojo/_base/declare dojo/on dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),
function(x,m,c,l,n,r,u,e){function v(a,b){var h=document.body,d;e(h,a,".dgrid-scrollbar-measure");d=a["offset"+b]-a["client"+b];e(a,"!dgrid-scrollbar-measure");h.removeChild(a);return d}function b(a){var b=a?"."+a.replace(G,"."):"";this._class&&(b="!"+this._class.replace(G,"!")+b);e(this.domNode,b);this._class=a}function f(){return this._class}u("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var d,k;l.add("dom-scrollbar-width",function(a,b,h){return v(h,"Width")});l.add("dom-scrollbar-height",
function(a,b,h){return v(h,"Height")});var q=0,G=/ +/g,g=7>l("ie")&&!l("quirks")?function(){var a,b,h;if(this._started&&(a=document.documentElement,b=a.clientWidth,a=a.clientHeight,h=this._prevWinDims||[],h[0]!==b||h[1]!==a))this.resize(),this._prevWinDims=[b,a]}:function(){this._started&&this.resize()};return m(r?r:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,postscript:function(a,b){var h=this;(this._Row=function(a,b,h){this.id=a;this.data=b;this.element=
h}).prototype.remove=function(){h.removeRow(this.element)};b&&(this.srcNodeRef=b=b.nodeType?b:document.getElementById(b));this.create(a,b)},listType:"list",create:function(a,y){var h=this.domNode=y||e("div"),d;a?(this.params=a,m.safeMixin(this,a),d=a["class"]||a.className||h.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=h.id=h.id||this.id||"dgrid_"+q++;this.buildRendering();
d&&b.call(this,d);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,h,d,f,t;t=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";e(a,"[role\x3dgrid].ui-widget.dgrid.dgrid-"+this.listType);h=this.headerNode=e(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+(this.showHeader?"":".dgrid-header-hidden"));(l("quirks")||
8>l("ie"))&&e(a,"div.dgrid-spacer");d=this.bodyNode=e(a,"div.dgrid-scroller");d.tabIndex=-1;this.headerScrollNode=e(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");f=this.footerNode=e("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));e(a,f);t&&(a.className+=" dgrid-rtl"+(l("webkit")?"":" dgrid-rtl-nonwebkit"));c(d,"scroll",function(f){b.showHeader&&(h.scrollLeft=f.scrollLeft||d.scrollLeft);f.stopPropagation();c.emit(a,"scroll",{scrollTarget:d})});this.configStructure();
this.renderHeader();this.contentNode=this.touchNode=e(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=c(window,"resize",n.throttleDelayed(g,this)))},startup:function(){this._started||(this.inherited(arguments),this._started=!0,this.resize(),this.set("sort",this._sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,h=this.footerNode,f=b.offsetHeight,c=this.showFooter?h.offsetHeight:0,t=l("quirks")||7>l("ie");this.headerScrollNode.style.height=
a.style.marginTop=f+"px";a.style.marginBottom=c+"px";t&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-f-c,0)+"px",c&&(h.style.bottom="1px",setTimeout(function(){h.style.bottom=""},0)));d||(d=l("dom-scrollbar-width"),k=l("dom-scrollbar-height"),l("ie")&&(d++,k++),n.addCssRule(".dgrid-scrollbar-width","width: "+d+"px"),n.addCssRule(".dgrid-scrollbar-height","height: "+k+"px"),17!=d&&!t&&(n.addCssRule(".dgrid-header","right: "+d+"px"),n.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header",
"left: "+d+"px")));t&&(b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0))},addCssRule:function(a,b){var h=n.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(h);return h},on:function(a,b){var h=c(this.domNode,a,b);l("dom-addeventlistener")||this._listeners.push(h);return h},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var h=document.getElementById(b);h&&this.removeRow(h,!0)}for(b=0;b<a.length;b++)(h=
a[b])&&h.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();e(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},newRow:function(a,b,h,d,f){if(b){var c=this.insertRow(a,b,h,d,f);e(c,".ui-state-highlight");setTimeout(function(){e(c,"!ui-state-highlight")},250);return c}},
adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(-1<(a.className+" ").indexOf("dgrid-row ")&&e(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++);while((a=a.nextSibling)&&a.rowIndex!=b&&!a.blockRowIndex)}}},renderArray:function(a,b,h){function d(a){r=c.insertRow(a,q,null,k++,h);r.observerIndex=l;return r}function f(a){if(v=b?b.parentNode:c.contentNode)v.insertBefore(q,b||null),(r=a[a.length-
1])&&c.adjustRowIndices(r);return g=a}h=h||{};var c=this,k=h.start||0,e,g,v;b||(this._lastCollection=a);if(a.observe)var l=this.observers.push(a.observe(function(a,d,f){var k,s,q;-1<d&&g[d]&&(e=g.splice(d,1)[0],e.parentNode==v&&((k=e.nextSibling)&&d!=f&&k.rowIndex--,c.removeRow(e)),c._processScroll&&c._processScroll());if(-1<f){s=g[f];if(!s&&(s=g[f-1]))s=(s.connected||s).nextSibling;q=b&&b.parentNode||s&&s.parentNode||c.contentNode;if(e=c.newRow(a,q,s,h.start+f,h))if(e.observerIndex=l,g.splice(f,
0,e),!k||f<d)k=e.previousSibling,k=!k||k.rowIndex+1==e.rowIndex||0==e.rowIndex?e:k;h.count++}d!=f&&k&&c.adjustRowIndices(k);c._onNotification(g,a,d,f)},!0))-1;var q=document.createDocumentFragment();if(a.map){if(g=a.map(d,console.error),g.then)return g.then(f)}else{g=[];for(var n=0,m=a.length;n<m;n++)g[n]=d(a[n])}var r;return f(g)},_onNotification:function(a,b,d,f){},renderHeader:function(){},_autoId:0,insertRow:function(a,b,d,f,c){var k=c.parentId,k=this.id+"-row-"+(k?k+"-":"")+(this.store&&this.store.getIdentity?
this.store.getIdentity(a):this._autoId++),e=document.getElementById(k),g=e&&e.previousSibling;e&&this.removeRow(e);e=this.renderRow(a,c);e.className=(e.className||"")+" ui-state-default dgrid-row "+(1==f%2?"dgrid-row-odd":"dgrid-row-even");this._rowIdToObject[e.id=k]=a;b.insertBefore(e,d||null);g&&this.adjustRowIndices(g);e.rowIndex=f;return e},renderRow:function(a,b){return e("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||e(a,"!")},row:function(a){var b;if(a instanceof
this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var d=a.id;if(b=this._rowIdToObject[d])return new this._Row(d.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,d,f){var e,c;c=e=a.element;b=b||1;do if(a=e[0>b?"previousSibling":
"nextSibling"]){do if((e=a)&&-1<(e.className+" ").indexOf(d+" ")){c=e;b+=0>b?1:-1;break}while(a=(!f||!e.hidden)&&e[0>b?"lastChild":"firstChild"])}else if(e=e.parentNode,e===this.bodyNode||e===this.headerNode)break;while(b);return c},up:function(a,b,d){a.element||(a=this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",d))},down:function(a,b,d){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",d))},scrollTo:l("touch")?function(){return this.inherited(arguments)}:function(a){"undefined"!==
typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:l("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var d in a)this.set(d,a[d]);else d="_set"+a.charAt(0).toUpperCase()+
a.slice(1),"function"===typeof this[d]?this[d].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:f,_setClass:b,_getClassName:f,_setClassName:b,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(d,f){var e=d[a],c=f[a];void 0===e&&(e="");void 0===c&&(c="");return e==c?0:e>c==!b?1:-1})),this.renderArray(this._lastCollection))},
sort:function(a,b){x.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;e(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},setShowHeader:function(a){x.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=
a;e(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})})},"dgrid/util/misc":function(){define(["put-selector/put"],function(x){var m=[],c,l,n,r=/([^A-Za-z0-9_\u00A0-\uFFFF-])/g,u={defaultDelay:15,throttle:function(e,c,b){var f=!1;b=b||u.defaultDelay;return function(){f||(f=!0,e.apply(c,arguments),setTimeout(function(){f=!1},b))}},throttleDelayed:function(e,c,b){var f=!1;b=b||u.defaultDelay;return function(){if(!f){f=!0;var d=arguments;setTimeout(function(){f=!1;e.apply(c,d)},b)}}},
debounce:function(e,c,b){var f;b=b||u.defaultDelay;return function(){f&&(clearTimeout(f),f=null);var d=arguments;f=setTimeout(function(){e.apply(c,d)},b)}},addCssRule:function(e,v){c||(c=x(document.getElementsByTagName("head")[0],"style"),c=c.sheet||c.styleSheet,l=c.deleteRule?"deleteRule":"removeRule",n=c.cssRules?"cssRules":"rules");var b=m.length;m[b]=(c.cssRules||c.rules).length;c.addRule?c.addRule(e,v):c.insertRule(e+"{"+v+"}",m[b]);return{get:function(f){return c[n][m[b]].style[f]},set:function(f,
d){"undefined"!==typeof m[b]&&(c[n][m[b]].style[f]=d)},remove:function(){var f=m[b],d,e;if(void 0!==f){c[l](f);m[b]=void 0;d=b+1;for(e=m.length;d<e;d++)m[d]>f&&m[d]--}}}},escapeCssIdentifier:function(e){return e.replace(r,"\\$1")}};return u})},"dgrid/OnDemandList":function(){define("./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(x,m,c,l,n,r,u,e){return c([x,m],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,
bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var e=this;r(this.bodyNode,"scroll",u[this.pagingMethod](function(b){e._processScroll(b)},null,this.pagingDelay))},renderQuery:function(c,b,f){function d(a){e(r,"!");if(a)throw k._refreshDeferred&&(k._refreshDeferred.reject(a),delete k._refreshDeferred),a;}var k=this,q={query:c,count:0,node:b,options:f},m=this.preload,
g;if(!b){var a={node:e(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:q,options:f};a.node.style.height="0";q.node=b=e(this.contentNode,"div.dgrid-preload");q.previous=a}b.rowIndex=this.minRowsPerPage;m?((q.next=m.next)&&this.bodyNode.scrollTop>=m.node.offsetTop?q.previous=m:(q.next=m,q.previous=m.previous),q.previous.next=q,q.next.previous=q):this.preload=q;var r=e(b,"-div.dgrid-loading");e(r,"div.dgrid-below").innerHTML=this.loadingMessage;f=l.mixin(this.get("queryOptions"),
f,{start:0,count:this.minRowsPerPage,query:c});this._trackError(function(){return g=c(f)});if("undefined"===typeof g)d();else return n.when(k.renderArray(g,b,f),function(a){return n.when("undefined"===typeof g.total?g.length:g.total,function(d){e(r,"!");var f=a.length;0===d&&(k.noDataNode=e(k.contentNode,"div.dgrid-no-data"),k.noDataNode.innerHTML=k.noDataMessage);for(var c=0,l=0;l<f;l++)c+=k._calcRowHeight(a[l]);f&&c&&(k.rowHeight=c/f);d-=f;q.count=d;b.rowIndex=f;d?b.style.height=Math.min(d*k.rowHeight,
k.maxEmptySpace)+"px":b.style.display="none";k._previousScrollPosition&&(k.scrollTo(k._previousScrollPosition),delete k._previousScrollPosition);k._processScroll();k._refreshDeferred&&(k._refreshDeferred.resolve(g),delete k._refreshDeferred);return a},d)},d),g},refresh:function(c){var b=this,f=c&&c.keepScrollPosition,d;"undefined"===typeof f&&(f=this.keepScrollPosition);f&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return f=this._refreshDeferred=
new n,d=b.renderQuery(function(d){return b.store.query(b.query,d)}),"undefined"===typeof d&&f.reject(),f.then(function(d){setTimeout(function(){r.emit(b.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:b,results:d})},0);delete b._refreshDeferred;return d},function(d){delete b._refreshDeferred;throw d;})},resize:function(){this.inherited(arguments);this._processScroll()},_calcRowHeight:function(c){var b=c.previousSibling;return b&&b.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,
_processScroll:function(c){function b(a,b,c,h){var k=d.farOffRemoval,g=a.node;if(b>2*k){for(var l,m=g[c],q=0,p=0,n=[];l=m;){var r=d._calcRowHeight(l);if(q+r+k>b||0>m.className.indexOf("dgrid-row")&&0>m.className.indexOf("dgrid-loading"))break;var m=l[c],s,t=l.observerIndex;if(t!=s&&-1<s){var u=d.observers,w=u[s];w&&w.cancel();u[s]=0}q+=r;p+=l.count||1;s=t;d.removeRow(l,!0);n.push(l)}a.count+=p;h?(g.rowIndex-=p,f(a)):g.style.height=g.offsetHeight+q+"px";var v=e("div",n);setTimeout(function(){e(v,"!")},
1)}}function f(a,b){a.node.style.height=Math.min(a.count*d.rowHeight,b?Infinity:d.maxEmptySpace)+"px"}var d=this,k=d.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;var q=k.offsetHeight+c,m,g,a=d.preload,r=d.lastScrollTop,h=d.bufferRows*d.rowHeight,u=h-d.rowHeight,s,t,x;for(d.lastScrollTop=c;a&&!a.node.offsetWidth;)a=a.previous;for(;a&&a!=m;){m=d.preload;d.preload=a;g=a.node;var p=g.offsetTop;if(q+1+u<p){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(c-1-u>p+g.offsetHeight){do a=a.next;
while(a&&!a.node.offsetWidth)}else{var w=((g.rowIndex?c-h:q)-p)/d.rowHeight,p=(q-c+2*h)/d.rowHeight,D=Math.max(Math.min((c-r)*d.rowHeight,d.maxRowsPerPage/2),d.maxRowsPerPage/-2),p=p+Math.min(Math.abs(D),10);0==g.rowIndex&&(w-=p);w=Math.max(w,0);10>w&&(0<w&&p+w<d.maxRowsPerPage)&&(p+=Math.max(0,w),w=0);p=Math.min(Math.max(p,d.minRowsPerPage),d.maxRowsPerPage,a.count);if(0==p)return;var p=Math.ceil(p),w=Math.min(Math.floor(w),a.count-p),B=l.mixin(d.get("queryOptions"),a.options);a.count-=p;var z=g,
E,F=d.queryRowsOverlap;if(D=0<g.rowIndex&&a){var C=a.previous;C&&(b(C,c-(C.node.offsetTop+C.node.offsetHeight),"nextSibling"),0<w&&C.node==g.previousSibling?(w=Math.min(a.count,w),a.previous.count+=w,f(a.previous,!0),g.rowIndex+=w,F=0):p+=w,a.count-=w);B.start=g.rowIndex-F;g.rowIndex+=p}else a.next&&(b(a.next,a.next.node.offsetTop-q,"previousSibling",!0),z=g.nextSibling,z==a.next.node?(a.next.count+=a.count-w,a.next.node.rowIndex=w+p,f(a.next),a.count=w,F=0):E=!0),B.start=a.count;B.count=Math.min(p+
F,d.maxRowsPerPage);E&&(z&&z.offsetWidth)&&(E=z.offsetTop);f(a);g=e(z,"-div.dgrid-loading[style\x3dheight:"+p*d.rowHeight+"px]");e(g,"div.dgrid-"+(D?"below":"above")).innerHTML=d.loadingMessage;g.count=p;g.blockRowIndex=!0;B.query=a.query;var H=a.query(B);if(void 0===d._trackError(function(){return H})){e(g,"!");return}(function(a,b,c,h,g){x=n.when(d.renderArray(g,a,B),function(b){t=g;z=a.nextSibling;e(a,"!");if(h&&z&&z.offsetWidth){var k=d.getScrollPosition();d.scrollTo({x:k.x,y:k.y+z.offsetTop-
h,preserveMomentum:!0})}c&&n.when(g.total||g.length,function(a){c.count=a-c.node.rowIndex;f(c)});d._processScroll();return b},function(b){e(a,"!");throw b;})}).call(this,g,k,D,E,H);a=a.previous}}if(x&&(s=this._refreshDeferred))delete this._refreshDeferred,n.when(x,function(){s.resolve(t)})}})})},"dgrid/_StoreMixin":function(){define("dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on dojo/aspect put-selector/put".split(" "),function(x,m,c,l,n,r,u){function e(b){return b}
function v(b){"object"!==typeof b&&(b=Error(b));b.grid=this;n.emit(this.domNode,"dgrid-error",{grid:this,error:b,cancelable:!0,bubbles:!0})&&console.error(b)}return m(null,{store:null,query:null,queryOptions:null,getBeforePut:!0,noDataMessage:"",loadingMessage:"",constructor:function(){this.query={};this.queryOptions={};this.dirty={};this._updating={};this._columnsWithSet={};r.before(this,"configStructure",c.hitch(this,function(){this._columnsWithSet={}}))},_configColumn:function(b){b.set&&(this._columnsWithSet[b.field]=
b)},_setStore:function(b,c,d){this.store=b;this.dirty={};this.set("query",c,d)},_setQuery:function(b,c){var d=c&&c.sort;this.query=void 0!==b?b:this.query;this.queryOptions=c||this.queryOptions;d?this.set("sort",d):this.refresh()},setStore:function(b,c,d){x.deprecated("setStore(...)",'use set("store", ...) instead',"dgrid 1.0");this.set("store",b,c,d)},setQuery:function(b,c){x.deprecated("setQuery(...)",'use set("query", ...) instead',"dgrid 1.0");this.set("query",b,c)},_getQueryOptions:function(){var b=
c.delegate(this.queryOptions,{});this._sort.length&&(b.sort=this._sort);return b},_getQuery:function(){var b=this.query;return"object"==typeof b&&null!=b?c.delegate(b,{}):b},_setSort:function(b,c){this.store&&(this._lastCollection=null);this.inherited(arguments)},insertRow:function(b,e,d,k,l){var m=this.store,g=this.dirty,m=m&&m.getIdentity(b),a;m in g&&!(m in this._updating)&&(a=g[m]);a&&(b=c.delegate(b,a));return this.inherited(arguments)},updateDirty:function(b,c,d){var e=this.dirty,l=e[b];l||
(l=e[b]={});l[c]=d},setDirty:function(b,c,d){x.deprecated("setDirty(...)","use updateDirty() instead","dgrid 1.0");this.updateDirty(b,c,d)},save:function(){function b(a,b){return function(g){var m=c._columnsWithSet,n=c._updating,p,q;for(p in b)g[p]=b[p];for(p in m)q=m[p].set(g),void 0!==q&&(g[p]=q);n[a]=!0;return l.when(d.put(g),function(){delete e[a];delete n[a]})}}var c=this,d=this.store,e=this.dirty,m=new l,n=m.promise,g=function(a){var b;return c.getBeforePut||!(b=c.row(a).data)?function(){return d.get(a)}:
function(){return b}},a;for(a in e)var r=b(a,e[a]),n=n.then(g(a)).then(r);m.resolve();return n},revert:function(){this.dirty={};this.refresh()},_trackError:function(b){var f;"string"==typeof b&&(b=c.hitch(this,b));try{f=b()}catch(d){v.call(this,d)}return l.when(f,e,c.hitch(this,v))},newRow:function(){this.noDataNode&&(u(this.noDataNode,"!"),delete this.noDataNode);return this.inherited(arguments)},removeRow:function(b,c){var d={element:b};!c&&(this.noDataMessage&&this.up(d).element===b&&this.down(d).element===
b)&&(this.noDataNode=u(this.contentNode,"div.dgrid-no-data"),this.noDataNode.innerHTML=this.noDataMessage);return this.inherited(arguments)}})})}}});define("dojorama/layers/dgrid-common",[],1);
//@ sourceMappingURL=dgrid-common.js.map