//>>built
require({cache:{"put-selector/put":function(){(function(r){var s,k=/[-+,> ]/;r("put-selector/put",[],s=function(n,f){function t(c){function q(){j&&p&&j!=p&&(p==c&&(f||(f=k.test(b)&&n.createDocumentFragment()))||p).insertBefore(j,o||null)}for(var f,e,o,p,j,m=arguments,g=m[0],a=0;a<m.length;a++){var b=m[a];if("object"==typeof b){e=!1;if(b instanceof Array){j=n.createDocumentFragment();for(var l=0;l<b.length;l++)j.appendChild(t(b[l]));b=j}if(b.nodeType)j=b,q(),p=b,o=0;else for(l in b)j[l]=b[l]}else if(e)e=
!1,j.appendChild(n.createTextNode(b));else{1>a&&(c=null);e=!0;if(g=b.replace(r,function(i,h,l,e,g,f){if(h){q();if("-"==h||"+"==h){if(p=(o=j||p).parentNode,j=null,"+"==h)o=o.nextSibling}else"<"==h?p=j=(j||p).parentNode:(","==h?p=c:j&&(p=j),j=null),o=0;j&&(p=j)}if((i=!l&&e)||!j&&(l||g))"$"==i?(i=m[++a],p.appendChild(n.createTextNode(i))):(i=i||t.defaultTag,(h=d&&m[a+1]&&m[a+1].name)&&(i="<"+i+' name="'+h+'">'),j=n.createElement(i));if(l)if("$"==e&&(e=m[++a]),"#"==l)j.id=e;else if(h=(i=j.className)&&
(" "+i+" ").replace(" "+e+" "," "),"."==l)j.className=i?(h+e).substring(1):e;else if("!"==b)t("div",j,"<").innerHTML="";else if(h=h.substring(1,h.length-1),h!=i)j.className=h;if(g)if("$"==f&&(f=m[++a]),"style"==g)j.style.cssText=f;else j["!"==g.charAt(0)?(g=g.substring(1))&&"removeAttribute":"setAttribute"](g,""===f?g:f);return""}))throw new SyntaxError("Unexpected char "+g+" in "+b);q();p=g=j||p}}c&&f&&c.appendChild(f);return g}k=f||k;var r=/(?:\s*([-+ ,<>]))?\s*(\.|!\.?|#)?([-\w%$]+)?(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,
n=n||document,d="object"==typeof n.createElement;t.defaultTag="div";t.forDocument=s;return t})})("undefined"==typeof define?function(r,s){"undefined"==typeof window?require("./node-html")(module,s):put=s()}:define)},"xstyle/has-class":function(){define("xstyle/has-class",["dojo/has"],function(r){var s={};return function(){for(var k,n=arguments,f=0;f<n.length;f++)if(k=n[f],!s[k]){s[k]=!0;var t=k.match(/^(no-)?(.+?)((-[\d\.]+)(-[\d\.]+)?)?$/),u=r(t[2]),d=-t[4];if((0<d?d<=u&&(-t[5]||d)>=u:!!u)==!t[1])document.documentElement.className+=
" has-"+k}}})},"xstyle/css":function(){define("xstyle/css",["require"],function(r){var s=window.cssCache||(window.cssCache={});return{load:function(k,n,f){var t=n.toUrl(k);if(s[t])return createStyleSheet(s[t]);var u=document.documentElement,d=u.insertBefore(document.createElement("div"),u.firstChild);d.id=n.toAbsMid(k).replace(/\//g,"-").replace(/\..*/,"")+"-loaded";k=(d.currentStyle||getComputedStyle(d,null)).display;u.removeChild(d);if("none"==k)return f();r(["./load-css"],function(c){c(t,f)})},
pluginBuilder:"xstyle/css-builder"}})},"dgrid/List":function(){define("dgrid/List","dojo/_base/array,dojo/_base/kernel,dojo/_base/declare,dojo/on,dojo/has,./util/misc,dojo/has!touch?./TouchScroll,xstyle/has-class,put-selector/put,dojo/_base/sniff,xstyle/css!./css/dgrid.css".split(","),function(r,s,k,n,f,t,u,d,c){function q(a){var b=a?"."+a.replace(m,"."):"";this._class&&(b="!"+this._class.replace(m,"!")+b);c(this.domNode,b);this._class=a}function x(){return this._class}d("mozilla","opera","webkit",
"ie","ie-6","ie-6-7","quirks","no-quirks","touch");var e,o=c(document.getElementsByTagName("head")[0],"style"),p=[],o=o.sheet||o.styleSheet,j=0,m=/ +/g,g=7>f("ie")&&!f("quirks")?function(){var a,b,l;if(this._started&&(a=document.documentElement,b=a.clientWidth,a=a.clientHeight,l=this._prevWinDims||[],l[0]!==b||l[1]!==a))this.resize(),this._prevWinDims=[b,a]}:function(){this._started&&this.resize()};return k(u?u:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,postscript:function(a,
b){var l=this;(this._Row=function(a,b,l){this.id=a;this.data=b;this.element=l}).prototype.remove=function(){l.removeRow(this.element)};if(b)this.srcNodeRef=b=b.nodeType?b:document.getElementById(b);this.create(a,b)},listType:"list",create:function(a,b){var l=this.domNode=b||c("div"),i;a?(this.params=a,k.safeMixin(this,a),i=a["class"]||a.className||l.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&
this.postMixInProperties();this.id=l.id=l.id||this.id||"dgrid_"+j++;this.buildRendering();i&&q.call(this,i);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,l,i,h,e;e=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";c(a,"[role=grid].ui-widget.dgrid.dgrid-"+this.listType);l=this.headerNode=c(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+
(this.showHeader?"":".dgrid-header-hidden"));(f("quirks")||8>f("ie"))&&c(a,"div.dgrid-spacer");i=this.bodyNode=c(a,"div.dgrid-scroller");i.tabIndex=-1;this.headerScrollNode=c(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");h=this.footerNode=c("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));c(a,h);e&&(a.className+=" dgrid-rtl"+(f("webkit")?"":" dgrid-rtl-nonwebkit"));n(i,"scroll",function(h){if(b.showHeader)l.scrollLeft=h.scrollLeft||i.scrollLeft;h.stopPropagation();
n.emit(a,"scroll",{scrollTarget:i})});this.configStructure();this.renderHeader();this.contentNode=this.touchNode=c(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=n(window,"resize",t.throttleDelayed(g,this)))},startup:function(){this.inherited(arguments);if(!this._started)this._started=!0,this.resize(),this.set("sort",this._sort)},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,l=this.footerNode,i=b.offsetHeight,h=this.showFooter?
l.offsetHeight:0,d=f("quirks")||7>f("ie");this.headerScrollNode.style.height=a.style.marginTop=i+"px";a.style.marginBottom=h+"px";if(d&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-i-h,0)+"px",h))l.style.bottom="1px",setTimeout(function(){l.style.bottom=""},0);e||(i=c(document.body,"div.dgrid-scrollbar-measure"),e=i.offsetWidth-i.clientWidth,c(i,"!"),7===f("ie")&&e++,this.addCssRule(".dgrid-scrollbar-width","width: "+e+"px"),this.addCssRule(".dgrid-scrollbar-height","height: "+
e+"px"),17!=e&&!d&&(this.addCssRule(".dgrid-header","right: "+e+"px"),this.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header","left: "+e+"px")));if(d)b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0)},addCssRule:function(a,b){var l=p.length;p[l]=(o.cssRules||o.rules).length;o.addRule?o.addRule(a,b):o.insertRule(a+"{"+b+"}",p[l]);return{remove:function(){var a=p[l],b,e=p.length;if(void 0!==a){o.deleteRule?o.deleteRule(a):o.removeRule(a);p[l]=void 0;for(b=l;b<e;b++)p[b]>
a&&p[b]--}}}},on:function(a,b){var l=n(this.domNode,a,b);f("dom-addeventlistener")||this._listeners.push(l);return l},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var l=document.getElementById(b);l&&this.removeRow(l,!0)}for(b=0;b<a.length;b++)(l=a[b])&&l.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();
c(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},newRow:function(a,b,l,e){if(!b||b.parentNode){var h=this.insertRow(a,b?b.parentNode:this.contentNode,b,e.start+l,e);c(h,".ui-state-highlight");setTimeout(function(){c(h,"!ui-state-highlight")},250);return h}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;if(-1<b){do if(-1<a.rowIndex)-1<(a.className+" ").indexOf("dgrid-row ")&&
c(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++;while((a=a.nextSibling)&&a.rowIndex!=b&&!a.blockRowIndex)}}},renderArray:function(a,b,e){function c(a){k=d.insertRow(a,o,null,g++,e);k.observerIndex=m;return k}function h(a){if(j=b?b.parentNode:d.contentNode)j.insertBefore(o,b||null),(k=a[a.length-1])&&d.adjustRowIndices(k);return q=a}var e=e||{},d=this,g=e.start||0,f,q,j;if(!b)this._lastCollection=a;if(a.observe)var m=this.observers.push(a.observe(function(a,
b,c){var h,g;if(-1<b&&q[b]){f=q.splice(b,1)[0];if(f.parentNode==j)(h=f.nextSibling)&&b!=c&&h.rowIndex--,d.removeRow(f);d._processScroll&&d._processScroll()}if(-1<c){g=q[c];if(!g&&(g=q[c-1]))g=(g.connected||g).nextSibling;if(f=d.newRow(a,g,c,e))if(f.observerIndex=m,q.splice(c,0,f),!h||c<b)a=f.previousSibling,h=!a||a.rowIndex+1==f.rowIndex||0==f.rowIndex?f:a;e.count++}b!=c&&h&&d.adjustRowIndices(h)},!0))-1;var o=document.createDocumentFragment();if(a.map){if(q=a.map(c,console.error),q.then)return q.then(h)}else{q=
[];for(var n=0,p=a.length;n<p;n++)q[n]=c(a[n])}var k;return h(q)},renderHeader:function(){},_autoId:0,insertRow:function(a,b,e,c,h){var d=h.parentId,d=this.id+"-row-"+(d?d+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),g=document.getElementById(d),f=g&&g.previousSibling;if(!g||e&&g.parentNode!=e.parentNode)g&&this.removeRow(g),g=this.renderRow(a,h),g.className=(g.className||"")+" ui-state-default dgrid-row "+(1==c%2?"dgrid-row-odd":"dgrid-row-even"),this._rowIdToObject[g.id=
d]=a;b.insertBefore(g,e||null);f&&this.adjustRowIndices(f);g.rowIndex=c;return g},renderRow:function(a){return c("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||c(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;if(a.target&&a.target.nodeType)a=a.target;if(a.nodeType){do{var e=a.id;if(b=this._rowIdToObject[e])return new this._Row(e.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):
(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,e,g){var c,d;d=c=a.element;b=b||1;do if(a=c[0>b?"previousSibling":"nextSibling"]){do if((c=a)&&-1<(c.className+" ").indexOf(e+" ")){d=c;b+=0>b?1:-1;break}while(a=(!g||!c.hidden)&&c[0>b?"lastChild":"firstChild"])}else if(c=c.parentNode,c===this.bodyNode||c===this.headerNode)break;while(b);return d},up:function(a,b,c){a.element||(a=
this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:f("touch")?function(){return this.inherited(arguments)}:function(a){if("undefined"!==typeof a.x)this.bodyNode.scrollLeft=a.x;if("undefined"!==typeof a.y)this.bodyNode.scrollTop=a.y},getScrollPosition:f("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},
get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:x,_setClass:q,_getClassName:x,_setClassName:q,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,
descending:b}];this.refresh();if(this._lastCollection){if(a.length){if("string"!=typeof a)b=a[0].descending,a=a[0].attribute;this._lastCollection.sort(function(c,e){var g=c[a],d=e[a];void 0===g&&(g="");void 0===d&&(d="");return g==d?0:g>d==!b?1:-1})}this.renderArray(this._lastCollection)}},sort:function(a,b){s.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=
a;c(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();if(a)b.scrollLeft=this.getScrollPosition().x},setShowHeader:function(a){s.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;c(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})})},"dgrid/util/misc":function(){define("dgrid/util/misc",[],function(){var r={defaultDelay:15,throttle:function(s,k,n){var f=!1,n=
n||r.defaultDelay;return function(){f||(f=!0,s.apply(k,arguments),setTimeout(function(){f=!1},n))}},throttleDelayed:function(s,k,n){var f=!1,n=n||r.defaultDelay;return function(){if(!f){f=!0;var t=arguments;setTimeout(function(){f=!1;s.apply(k,t)},n)}}},debounce:function(s,k,n){var f,n=n||r.defaultDelay;return function(){f&&(clearTimeout(f),f=null);var t=arguments;f=setTimeout(function(){s.apply(k,t)},n)}}};return r})},"dgrid/OnDemandList":function(){define("dgrid/OnDemandList","./List,./_StoreMixin,dojo/_base/declare,dojo/_base/lang,dojo/_base/Deferred,dojo/on,./util/misc,put-selector/put".split(","),
function(r,s,k,n,f,t,u,d){return k([r,s],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;t(this.bodyNode,"scroll",u[this.pagingMethod](function(d){c._processScroll(d)},null,this.pagingDelay))},renderQuery:function(c,q,k){var e={query:c,count:0,node:q,options:k};if(!q){var o={node:d(this.contentNode,
"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:e,options:k};e.node=q=d(this.contentNode,"div.dgrid-preload");e.previous=o}q.rowIndex=this.minRowsPerPage;(o=this.preload)?((e.next=o.next)&&this.bodyNode.scrollTop>=o.node.offsetTop?e.previous=o:(e.next=o,e.previous=o.previous),e.previous.next=e,e.next.previous=e):this.preload=e;var p=d(q,"-div.dgrid-loading");d(p,"div.dgrid-below").innerHTML=this.loadingMessage;var k=n.mixin(this.get("queryOptions"),k,{start:0,count:this.minRowsPerPage,query:c}),
j=c(k),m=this;f.when(this.renderArray(j,q,k),function(c){return f.when(j.total||j.length,function(a){d(p,"!");var b=c.length,a=a||b;if(!a)m.noDataNode=d(m.contentNode,"div.dgrid-no-data"),m.noDataNode.innerHTML=m.noDataMessage;for(var f=0,i=0;i<b;i++)f+=m._calcRowHeight(c[i]);if(b&&f)m.rowHeight=f/b;a-=b;e.count=a;q.rowIndex=b;a?q.style.height=Math.min(a*m.rowHeight,m.maxEmptySpace)+"px":q.style.display="none";m._previousScrollPosition&&(m.scrollTo(m._previousScrollPosition),delete m._previousScrollPosition);
m._processScroll();return c})});return j},refresh:function(c){var d=c&&c.keepScrollPosition;if("undefined"===typeof d)d=this.keepScrollPosition;if(d)this._previousScrollPosition=this.getScrollPosition();this.inherited(arguments);if(this.store){var f=this;this._trackError(function(){return f.renderQuery(function(c){return f.store.query(f.query,c)})})}},_calcRowHeight:function(c){var d=c.previousSibling;return d&&d.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,_processScroll:function(c){function q(a,
b,c,g){var f=e.farOffRemoval,h=a.node;if(b>2*f){for(var i,l=h[c],q=0,j=0,m=[];i=l;){var o=e._calcRowHeight(i);if(q+o+f>b||0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;var l=i[c],n,p=i.observerIndex;if(p!=n&&-1<n){var r=e.observers,s=r[n];s&&s.cancel();r[n]=0}q+=o;j+=i.count||1;n=p;e.removeRow(i,!0);m.push(i)}a.count+=j;g?(h.rowIndex-=j,k(a)):h.style.height=h.offsetHeight+q+"px";for(var t=d("div"),a=0;a<m.length;a++)d(t,m[a]);setTimeout(function(){d(t,"!")},1)}}
function k(a,b){a.node.style.height=Math.min(a.count*e.rowHeight,b?Infinity:e.maxEmptySpace)+"px"}var e=this,o=e.bodyNode,c=c&&c.scrollTop||o.scrollTop,p=o.offsetHeight+c,j,m,g=e.preload,a=e.lastScrollTop,b=e.bufferRows*e.rowHeight,l=b-e.rowHeight;for(e.lastScrollTop=c;g&&!g.node.offsetWidth;)g=g.previous;for(;g&&g!=j;){j=e.preload;e.preload=g;m=g.node;var i=m.offsetTop;if(p+1+l<i){do g=g.previous;while(g&&!g.node.offsetWidth)}else if(c-1-l>i+m.offsetHeight){do g=g.next;while(g&&!g.node.offsetWidth)
}else{var h=((m.rowIndex?c-b:p)-i)/e.rowHeight,i=(p-c+2*b)/e.rowHeight,t=Math.max(Math.min((c-a)*e.rowHeight,e.maxRowsPerPage/2),e.maxRowsPerPage/-2),i=i+Math.min(Math.abs(t),10);0==m.rowIndex&&(h-=i);h=Math.max(h,0);10>h&&0<h&&i+h<e.maxRowsPerPage&&(i+=Math.max(0,h),h=0);i=Math.min(Math.max(i,e.minRowsPerPage),e.maxRowsPerPage,g.count);if(0==i)break;var i=Math.ceil(i),h=Math.min(Math.floor(h),g.count-i),s=n.mixin(e.get("queryOptions"),g.options);g.count-=i;var r=m,u,w=e.queryRowsOverlap;if(t=0<m.rowIndex&&
g){var v=g.previous;v&&(q(v,c-(v.node.offsetTop+v.node.offsetHeight),"nextSibling"),0<h&&v.node==m.previousSibling?(h=Math.min(g.count,h),g.previous.count+=h,k(g.previous,!0),m.rowIndex+=h,w=0):i+=h,g.count-=h);s.start=m.rowIndex-w;m.rowIndex+=i}else{if(g.next)q(g.next,g.next.node.offsetTop-p,"previousSibling",!0),r=m.nextSibling,r==g.next.node?(g.next.count+=g.count-h,g.next.node.rowIndex=h+i,k(g.next),g.count=h,w=0):u=!0;s.start=g.count}s.count=Math.min(i+w,e.maxRowsPerPage);if(u&&r&&r.offsetWidth)u=
r.offsetTop;k(g);m=d(r,"-div.dgrid-loading[style=height:"+i*e.rowHeight+"px]");d(m,"div.dgrid-"+(t?"below":"above")).innerHTML=e.loadingMessage;m.count=i;m.blockRowIndex=!0;s.query=g.query;var y=g.query(s);if(void 0===e._trackError(function(){return y}))break;(function(a,b,c,g,h){f.when(e.renderArray(h,a,s),function(){r=a.nextSibling;d(a,"!");if(g&&r&&r.offsetWidth){var b=e.getScrollPosition();e.scrollTo({x:b.x,y:b.y+r.offsetTop-g,preserveMomentum:!0})}c&&f.when(h.total||h.length,function(a){c.count=
a-c.node.rowIndex;k(c)});e._processScroll()})}).call(this,m,o,t,u,y);g=g.previous}}}})})},"dgrid/_StoreMixin":function(){define("dgrid/_StoreMixin","dojo/_base/kernel,dojo/_base/declare,dojo/_base/lang,dojo/_base/Deferred,dojo/on,put-selector/put".split(","),function(r,s,k,n,f,t){function u(d){"object"!==typeof d&&(d=Error(d));d.grid=this;f.emit(this.domNode,"dgrid-error",{grid:this,error:d,cancelable:!0,bubbles:!0})&&console.error(d)}return s(null,{store:null,query:null,queryOptions:null,getBeforePut:!0,
noDataMessage:"",loadingMessage:"",constructor:function(){this.query={};this.queryOptions={};this.dirty={};this._updating={}},_configColumn:function(d){if(d.set){if(!this._columnsWithSet)this._columnsWithSet={};this._columnsWithSet[d.field]=d}},_configColumns:function(){this._columnsWithSet=null;return this.inherited(arguments)},_setStore:function(d,c,f){this.store=d;this.dirty={};this.set("query",c,f)},_setQuery:function(d,c){var f=c&&c.sort;this.query=void 0!==d?d:this.query;this.queryOptions=c||
this.queryOptions;f?this.set("sort",f):this.refresh()},setStore:function(d,c,f){r.deprecated("setStore(...)",'use set("store", ...) instead',"dgrid 1.0");this.set("store",d,c,f)},setQuery:function(d,c){r.deprecated("setQuery(...)",'use set("query", ...) instead',"dgrid 1.0");this.set("query",d,c)},_getQueryOptions:function(){var d=k.delegate(this.queryOptions,{});if(this._sort.length)d.sort=this._sort;return d},_getQuery:function(){var d=this.query;return"object"==typeof d&&null!=d?k.delegate(d,{}):
d},_setSort:function(d,c){if(this.store)this._lastCollection=null;this.inherited(arguments)},insertRow:function(d,c,f,n,e){var o=this.store,p=this.dirty,o=o&&o.getIdentity(d),j;o in p&&!(o in this._updating)&&(j=p[o]);j&&(d=k.delegate(d,j));return this.inherited(arguments)},updateDirty:function(d,c,f){var k=this.dirty,e=k[d];e||(e=k[d]={});e[c]=f},setDirty:function(d,c,f){r.deprecated("setDirty(...)","use updateDirty() instead","dgrid 1.0");this.updateDirty(d,c,f)},save:function(){function d(d,a){return function(b){var e=
c._columnsWithSet,i=c._updating,h,j;for(h in a)b[h]=a[h];if(e)for(h in e)j=e[h].set(b),void 0!==j&&(b[h]=j);i[d]=!0;return n.when(f.put(b),function(){delete k[d];delete i[d]})}}var c=this,f=this.store,k=this.dirty,e=new n,o=e.promise,p=function(d){var a;return c.getBeforePut||!(a=c.row(d).data)?function(){return f.get(d)}:function(){return a}},j;for(j in k)var m=d(j,k[j]),o=o.then(p(j)).then(m);e.resolve();return o},revert:function(){this.dirty={};this.refresh()},_trackError:function(d){var c;"string"==
typeof d&&(d=k.hitch(this,d));try{c=d()}catch(f){u.call(this,f)}return n.when(c,null,k.hitch(this,u))},newRow:function(){this.noDataNode&&(t(this.noDataNode,"!"),delete this.noDataNode);return this.inherited(arguments)},removeRow:function(d,c){var f={element:d};if(!c&&this.noDataMessage&&this.up(f).element===d&&this.down(f).element===d)this.noDataNode=t(this.contentNode,"div.dgrid-no-data"),this.noDataNode.innerHTML=this.noDataMessage;return this.inherited(arguments)}})})}}});
define("dojorama/layers/dgrid-common",[],1);