//>>built
require({cache:{"mijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(w,n,h,d,k,p,a,t){var r=n("dijit._TemplatedMixin",t,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(B){var m=this.declaredClass,A=this;return a.substitute(B,this,function(e,a){"!"==a.charAt(0)&&(e=d.getObject(a.substr(1),!1,A));if("undefined"==typeof e)throw Error(m+
" template:"+a);return null==e?"":"!"==a.charAt(0)?e:this._escapeValue(""+e)},this)},_escapeValue:function(a){return a.replace(/["'<>&]/g,function(a){return{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[a]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=w(this.templatePath,{sanitize:!0}));var a=r.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),m;if(d.isString(a)){if(m=h.toDom(this._stringRepl(a),
this.ownerDocument),1!=m.nodeType)throw Error("Invalid template: "+a);}else m=a.cloneNode(!0);this.domNode=m}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(a){var m=this.containerNode;if(a&&m)for(;a.hasChildNodes();)m.appendChild(a.firstChild)}});r._templateCache={};r.getCachedTemplate=function(d,m,A){var e=r._templateCache,k=d,t=e[k];if(t){try{if(!t.ownerDocument||t.ownerDocument==(A||document))return t}catch(n){}h.destroy(t)}d=
a.trim(d);if(m||d.match(/\$\{([^\}]+)\}/g))return e[k]=d;m=h.toDom(d,A);if(1!=m.nodeType)throw Error("Invalid template: "+d);return e[k]=m};p("ie")&&k(window,"unload",function(){var a=r._templateCache,d;for(d in a){var t=a[d];"object"==typeof t&&h.destroy(t);delete a[d]}});return r})},"mijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(w,n,h,d,k,p,a,t,r){var B=k.delegate(t,
{mouseenter:p.enter,mouseleave:p.leave,keypress:h._keypress}),m;h=d("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(a){for(var e=a;;)if(1==e.nodeType&&(this._processTemplateNode(e,function(a,e){return a.getAttribute(e)},this._attach)||this.searchContainerNode)&&e.firstChild)e=
e.firstChild;else{if(e==a)break;for(;!e.nextSibling;)if(e=e.parentNode,e==a)return;e=e.nextSibling}},_processTemplateNode:function(a,e,d){var t=!0,h=this.attachScope||this,m=e(a,"dojoAttachPoint")||e(a,"data-dojo-attach-point");if(m)for(var n=m.split(/\s*,\s*/);m=n.shift();)k.isArray(h[m])?h[m].push(a):h[m]=a,t="containerNode"!=m,this._attachPoints.push(m);if(e=e(a,"dojoAttachEvent")||e(a,"data-dojo-attach-event")){m=e.split(/\s*,\s*/);for(n=k.trim;e=m.shift();)if(e){var r=null;-1!=e.indexOf(":")?
(r=e.split(":"),e=n(r[0]),r=n(r[1])):e=n(e);r||(r=e);this._attachEvents.push(d(a,e,k.hitch(h,r)))}}return t},_attach:function(d,e,t){e=e.replace(/^on/,"").toLowerCase();e="dijitclick"==e?m||(m=w("./a11yclick")):B[e]||e;return a(d,e,t)},_detachTemplateNodes:function(){var a=this.attachScope||this;n.forEach(this._attachPoints,function(e){delete a[e]});this._attachPoints=[];n.forEach(this._attachEvents,function(a){a.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();
this.inherited(arguments)}});k.extend(r,{dojoAttachEvent:"",dojoAttachPoint:""});return h})},"mijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(w,n,
h,d,k,p,a,t,r,B,m,A,e,L,x,M,I,P,J,G,E,K,D){function g(b){return function(c){t[c?"set":"remove"](this.domNode,b,c);this._set(b,c)}}e.add("dijit-legacy-requires",!L.isAsync);e.add("dojo-bidi",!1);e("dijit-legacy-requires")&&I(0,function(){w(["dijit/_base/manager"])});var S={};d=p("dijit._WidgetBase",[P,E],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:g("lang"),dir:"",_setDirAttr:g("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",
srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(b){this._set("ownerDocument",b)},attributeMap:{},_blankGif:d.blankGif||w.toUrl("dojo/resources/blank.gif"),_introspect:function(){var b=this.constructor;if(!b._setterAttrs){var c=b.prototype,f=b._setterAttrs=[],b=b._onMap={},a;for(a in c.attributeMap)f.push(a);for(a in c)/^on/.test(a)&&(b[a.substring(2).toLowerCase()]=a),/^_set[A-Z](.*)Attr$/.test(a)&&(a=a.charAt(4).toLowerCase()+a.substr(5,a.length-
9),(!c.attributeMap||!(a in c.attributeMap))&&f.push(a))}},postscript:function(b,c){this.create(b,c)},create:function(b,c){this._introspect();this.srcNodeRef=a.byId(c);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);b&&(this.params=b,x.mixin(this,b));this.postMixInProperties();this.id||(this.id=D.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=G.body(this.ownerDocument);D.add(this);this.buildRendering();var f;if(this.domNode){this._applyAttributes();var g=this.srcNodeRef;g&&(g.parentNode&&this.domNode!==g)&&(g.parentNode.replaceChild(this.domNode,g),f=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();f&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var b={},c;for(c in this.params||{})b[c]=this._get(c);n.forEach(this.constructor._setterAttrs,
function(c){if(!(c in b)){var a=this._get(c);a&&this.set(c,a)}},this);for(c in b)this.set(c,b[c])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var b=this.baseClass.split(" ");this.isLeftToRight()||(b=b.concat(n.map(b,function(b){return b+"Rtl"})));r.add(this.domNode,b)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,n.forEach(this.getChildren(),function(b){!b._started&&
(!b._destroyed&&x.isFunction(b.startup))&&(b.startup(),b._started=!0)}))},destroyRecursive:function(b){this._beingDestroyed=!0;this.destroyDescendants(b);this.destroy(b)},destroy:function(b){function c(c){c.destroyRecursive?c.destroyRecursive(b):c.destroy&&c.destroy(b)}this._beingDestroyed=!0;this.uninitialize();n.forEach(this._connects,x.hitch(this,"disconnect"));n.forEach(this._supportingWidgets,c);this.domNode&&n.forEach(D.findWidgets(this.domNode,this.containerNode),c);this.destroyRendering(b);
D.remove(this.id);this._destroyed=!0},destroyRendering:function(b){this.bgIframe&&(this.bgIframe.destroy(b),delete this.bgIframe);this.domNode&&(b?t.remove(this.domNode,"widgetId"):B.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(b||B.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(b){n.forEach(this.getChildren(),function(c){c.destroyRecursive&&c.destroyRecursive(b)})},uninitialize:function(){return!1},_setStyleAttr:function(b){var c=this.domNode;x.isObject(b)?
A.set(c,b):c.style.cssText=c.style.cssText?c.style.cssText+("; "+b):b;this._set("style",b)},_attrToDom:function(b,c,a){a=3<=arguments.length?a:this.attributeMap[b];n.forEach(x.isArray(a)?a:[a],function(a){var f=this[a.node||a||"domNode"];switch(a.type||"attribute"){case "attribute":x.isFunction(c)&&(c=x.hitch(this,c));a=a.attribute?a.attribute:/^on[A-Z][a-zA-Z]*$/.test(b)?b.toLowerCase():b;f.tagName?t.set(f,a,c):f.set(a,c);break;case "innerText":f.innerHTML="";f.appendChild(this.ownerDocument.createTextNode(c));
break;case "innerHTML":f.innerHTML=c;break;case "class":r.replace(f,c,this[b])}},this)},get:function(b){var c=this._getAttrNames(b);return this[c.g]?this[c.g]():this._get(b)},set:function(b,c){if("object"===typeof b){for(var a in b)this.set(a,b[a]);return this}a=this._getAttrNames(b);var g=this[a.s];if(x.isFunction(g))var D=g.apply(this,Array.prototype.slice.call(arguments,1));else{var g=this.focusNode&&!x.isFunction(this.focusNode)?"focusNode":"domNode",e=this[g]&&this[g].tagName,d;if(d=e)if(!(d=
S[e])){d=this[g];var m={},l;for(l in d)m[l.toLowerCase()]=!0;d=S[e]=m}l=d;a=b in this.attributeMap?this.attributeMap[b]:a.s in this?this[a.s]:l&&a.l in l&&"function"!=typeof c||/^aria-|^data-|^role$/.test(b)?g:null;null!=a&&this._attrToDom(b,c,a);this._set(b,c)}return D||this},_attrPairNames:{},_getAttrNames:function(b){var c=this._attrPairNames;if(c[b])return c[b];var a=b.replace(/^[a-z]|-[a-zA-Z]/g,function(b){return b.charAt(b.length-1).toUpperCase()});return c[b]={n:b+"Node",s:"_set"+a+"Attr",
g:"_get"+a+"Attr",l:a.toLowerCase()}},_set:function(b,a){var f=this[b];this[b]=a;this._created&&a!==f&&(this._watchCallbacks&&this._watchCallbacks(b,f,a),this.emit("attrmodified-"+b,{detail:{prevValue:f,newValue:a}}))},_get:function(b){return this[b]},emit:function(b,a,f){a=a||{};void 0===a.bubbles&&(a.bubbles=!0);void 0===a.cancelable&&(a.cancelable=!0);a.detail||(a.detail={});a.detail.widget=this;var g,e=this["on"+b];e&&(g=e.apply(this,f?f:[a]));this._started&&!this._beingDestroyed&&M.emit(this.domNode,
b.toLowerCase(),a);return g},on:function(a,c){var f=this._onMap(a);return f?h.after(this,f,c,!0):this.own(M(this.domNode,a,c))[0]},_onMap:function(a){var c=this.constructor,f=c._onMap;if(!f){var f=c._onMap={},g;for(g in c.prototype)/^on/.test(g)&&(f[g.replace(/^on/,"").toLowerCase()]=g)}return f["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?D.findWidgets(this.containerNode):
[]},getParent:function(){return D.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,c,f){return this.own(k.connect(a,c,this,f))[0]},disconnect:function(a){a.remove()},subscribe:function(a,c){return this.own(J.subscribe(a,x.hitch(this,c)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:m.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=A.get(this.domNode,"display")},placeAt:function(b,c){var f=!b.tagName&&
D.byId(b);f&&f.addChild&&(!c||"number"===typeof c)?f.addChild(this,c):(f=f?f.containerNode&&!/after|before|replace/.test(c||"")?f.containerNode:f.domNode:a.byId(b,this.ownerDocument),B.place(this.domNode,f,c),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,c){var f=setTimeout(x.hitch(this,function(){f&&(f=null,this._destroyed||x.hitch(this,a)())}),c||0);return{remove:function(){f&&(clearTimeout(f),f=null);return null}}}});e("dojo-bidi")&&d.extend(K);
return d})},"mijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(w,n,h){return h("dijit.Destroyable",null,{destroy:function(d){this._destroyed=!0},own:function(){w.forEach(arguments,function(d){var h="destroyRecursive"in d?"destroyRecursive":"destroy"in d?"destroy":"remove",p=n.before(this,"destroy",function(a){d[h](a)}),a=n.after(d,h,function(){p.remove();a.remove()},!0)},this);return arguments}})})},"mijit/registry":function(){define(["dojo/_base/array",
"dojo/_base/window","./main"],function(w,n,h){var d={},k={},p={length:0,add:function(a){if(k[a.id])throw Error("Tried to register widget with id\x3d\x3d"+a.id+" but that id is already registered");k[a.id]=a;this.length++},remove:function(a){k[a]&&(delete k[a],this.length--)},byId:function(a){return"string"==typeof a?k[a]:a},byNode:function(a){return k[a.getAttribute("widgetId")]},toArray:function(){var a=[],d;for(d in k)a.push(k[d]);return a},getUniqueId:function(a){var t;do t=a+"_"+(a in d?++d[a]:
d[a]=0);while(k[t]);return"dijit"==h._scopeName?t:h._scopeName+"_"+t},findWidgets:function(a,d){function h(a){for(a=a.firstChild;a;a=a.nextSibling)if(1==a.nodeType){var p=a.getAttribute("widgetId");p?(p=k[p])&&n.push(p):a!==d&&h(a)}}var n=[];h(a);return n},_destroyAll:function(){h._curFocus=null;h._prevFocus=null;h._activeStack=[];w.forEach(p.findWidgets(n.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var d=
1==a.nodeType&&a.getAttribute("widgetId");if(d)return k[d];a=a.parentNode}return null},_hash:k};return h.registry=p})},"mijit/main":function(){define(["dojo/_base/kernel"],function(w){return w.dijit})},"mijit/_WidgetsInTemplateMixin":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare","dojo/_base/lang","dojo/parser"],function(w,n,h,d,k){return h("dijit._WidgetsInTemplateMixin",null,{_earlyTemplatedStartup:!1,widgetsInTemplate:!0,contextRequire:null,_beforeFillContent:function(){if(this.widgetsInTemplate){var h=
this.domNode;this.containerNode&&!this.searchContainerNode&&(this.containerNode.stopParser=!0);k.parse(h,{noStart:!this._earlyTemplatedStartup,template:!0,inherited:{dir:this.dir,lang:this.lang,textDir:this.textDir},propsThis:this,contextRequire:this.contextRequire,scope:"dojo"}).then(d.hitch(this,function(a){this._startupWidgets=a;for(var d=0;d<a.length;d++)this._processTemplateNode(a[d],function(a,d){return a[d]},function(a,d,h){return d in a?a.connect(a,d,h):a.on(d,h,!0)});this.containerNode&&
this.containerNode.stopParser&&delete this.containerNode.stopParser}));if(!this._startupWidgets)throw Error(this.declaredClass+": parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation.");}},_processTemplateNode:function(d,a,h){return a(d,"dojoType")||a(d,"data-dojo-type")?!0:this.inherited(arguments)},startup:function(){w.forEach(this._startupWidgets,function(d){d&&(!d._started&&
d.startup)&&d.startup()});this._startupWidgets=null;this.inherited(arguments)}})})},"dojo/parser":function(){define("require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),function(w,n,h,d,k,p,a,t,r,B,m,A,e,L,x,M){function I(a){return eval("("+a+")")}function P(a){var g=a._nameCaseMap,d=a.prototype;if(!g||g._extendCnt<G){var g=a._nameCaseMap={},b;for(b in d)"_"!==b.charAt(0)&&
(g[b.toLowerCase()]=b);g._extendCnt=G}return g}function J(a,g){var d=a.join();if(!E[d]){for(var b=[],c=0,f=a.length;c<f;c++){var e=a[c];b[b.length]=E[e]=E[e]||h.getObject(e)||~e.indexOf("/")&&(g?g(e):w(e))}c=b.shift();E[d]=b.length?c.createSubclass?c.createSubclass(b):c.extend.apply(c,b):c}return E[d]}new Date("X");var G=0;r.after(h,"extend",function(){G++},!0);var E={},K={_clearCache:function(){G++;E={}},_functionFromScript:function(a,g){var e="",b="",c=a.getAttribute(g+"args")||a.getAttribute("args"),
f=a.getAttribute("with"),c=(c||"").split(/\s*,\s*/);f&&f.length&&d.forEach(f.split(/\s*,\s*/),function(a){e+="with("+a+"){";b+="}"});return new Function(c,e+a.innerHTML+b)},instantiate:function(a,g,e){g=g||{};e=e||{};var b=(e.scope||n._scopeName)+"Type",c="data-"+(e.scope||n._scopeName)+"-",f=c+"type",h=c+"mixins",m=[];d.forEach(a,function(a){var c=b in g?g[b]:a.getAttribute(f)||a.getAttribute(b);if(c){var d=a.getAttribute(h),c=d?[c].concat(d.split(/\s*,\s*/)):[c];m.push({node:a,types:c})}});return this._instantiate(m,
g,e)},_instantiate:function(a,g,e,b){function c(a){!g._started&&!e.noStart&&d.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a}a=d.map(a,function(a){var b=a.ctor||J(a.types,e.contextRequire);if(!b)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(b,a.node,g,e,a.scripts,a.inherited)},this);return b?B(a).then(c):c(a)},construct:function(a,g,k,b,c,f){function w(a){Q&&h.setObject(Q,a);for(u=0;u<C.length;u++)r[C[u].advice||
"after"](a,C[u].method,h.hitch(a,C[u].func),!0);for(u=0;u<R.length;u++)R[u].call(a);for(u=0;u<N.length;u++)a.watch(N[u].prop,N[u].func);for(u=0;u<O.length;u++)x(a,O[u].event,O[u].func);return a}var H=a&&a.prototype;b=b||{};var z={};b.defaults&&h.mixin(z,b.defaults);f&&h.mixin(z,f);var p;e("dom-attributes-explicit")?p=g.attributes:e("dom-attributes-specified-flag")?p=d.filter(g.attributes,function(a){return a.specified}):(f=(/^input$|^img$/i.test(g.nodeName)?g:g.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,
"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),p=d.map(f.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:"LI"==g.nodeName&&"value"==a||"enctype"==b?g.getAttribute(b):g.getAttributeNode(b).value}}));var s=b.scope||n._scopeName;f="data-"+s+"-";var l={};"dojo"!==s&&(l[f+"props"]="data-dojo-props",l[f+"type"]="data-dojo-type",l[f+"mixins"]="data-dojo-mixins",l[s+"type"]="dojoType",l[f+"id"]="data-dojo-id");for(var u=0,q,s=[],Q,y;q=p[u++];){var v=q.name,F=v.toLowerCase();
q=q.value;switch(l[F]||F){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":y=q;break;case "data-dojo-id":case "jsid":Q=q;break;case "data-dojo-attach-point":case "dojoattachpoint":z.dojoAttachPoint=q;break;case "data-dojo-attach-event":case "dojoattachevent":z.dojoAttachEvent=q;break;case "class":z["class"]=g.className;break;case "style":z.style=g.style&&g.style.cssText;break;default:if(v in H||(v=P(a)[F]||v),v in H)switch(typeof H[v]){case "string":z[v]=
q;break;case "number":z[v]=q.length?Number(q):NaN;break;case "boolean":z[v]="false"!=q.toLowerCase();break;case "function":""===q||-1!=q.search(/[^\w\.]+/i)?z[v]=new Function(q):z[v]=h.getObject(q,!1)||new Function(q);s.push(v);break;default:F=H[v],z[v]=F&&"length"in F?q?q.split(/\s*,\s*/):[]:F instanceof Date?""==q?new Date(""):"now"==q?new Date:m.fromISOString(q):F instanceof t?n.baseUrl+q:I(q)}else z[v]=q}}for(p=0;p<s.length;p++)l=s[p].toLowerCase(),g.removeAttribute(l),g[l]=null;if(y)try{y=I.call(b.propsThis,
"{"+y+"}"),h.mixin(z,y)}catch(A){throw Error(A.toString()+" in data-dojo-props\x3d'"+y+"'");}h.mixin(z,k);c||(c=a&&(a._noScript||H._noScript)?[]:L("\x3e script[type^\x3d'dojo/']",g));var C=[],R=[],N=[],O=[];if(c)for(u=0;u<c.length;u++)l=c[u],g.removeChild(l),k=l.getAttribute(f+"event")||l.getAttribute("event"),b=l.getAttribute(f+"prop"),y=l.getAttribute(f+"method"),s=l.getAttribute(f+"advice"),p=l.getAttribute("type"),l=this._functionFromScript(l,f),k?"dojo/connect"==p?C.push({method:k,func:l}):"dojo/on"==
p?O.push({event:k,func:l}):z[k]=l:"dojo/aspect"==p?C.push({method:y,advice:s,func:l}):"dojo/watch"==p?N.push({prop:b,func:l}):R.push(l);a=(c=a.markupFactory||H.markupFactory)?c(z,g,a):new a(z,g);return a.then?a.then(w):w(a)},scan:function(a,g){function h(a){if(!a.inherited){a.inherited={};var b=a.node,c=h(a.parent),b={dir:b.getAttribute("dir")||c.dir,lang:b.getAttribute("lang")||c.lang,textDir:b.getAttribute(t)||c.textDir},d;for(d in b)b[d]&&(a.inherited[d]=b[d])}return a.inherited}var b=[],c=[],
f={},m=(g.scope||n._scopeName)+"Type",k="data-"+(g.scope||n._scopeName)+"-",p=k+"type",t=k+"textdir",k=k+"mixins",s=a.firstChild,l=g.inherited;if(!l){var u=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&u(a.parentNode,b)},l={dir:u(a,"dir"),lang:u(a,"lang"),textDir:u(a,t)},q;for(q in l)l[q]||delete l[q]}for(var l={inherited:l},r,y;;)if(s)if(1!=s.nodeType)s=s.nextSibling;else if(r&&"script"==s.nodeName.toLowerCase())(v=s.getAttribute("type"))&&/^dojo\/\w/i.test(v)&&r.push(s),
s=s.nextSibling;else if(y)s=s.nextSibling;else{var v=s.getAttribute(p)||s.getAttribute(m);q=s.firstChild;if(!v&&(!q||3==q.nodeType&&!q.nextSibling))s=s.nextSibling;else{y=null;if(v){var x=s.getAttribute(k);r=x?[v].concat(x.split(/\s*,\s*/)):[v];try{y=J(r,g.contextRequire)}catch(B){}y||d.forEach(r,function(a){~a.indexOf("/")&&!f[a]&&(f[a]=!0,c[c.length]=a)});x=y&&!y.prototype._noScript?[]:null;l={types:r,ctor:y,parent:l,node:s,scripts:x};l.inherited=h(l);b.push(l)}else l={node:s,scripts:r,parent:l};
r=x;y=s.stopParser||y&&y.prototype.stopParser&&!g.template;s=q}}else{if(!l||!l.node)break;s=l.node.nextSibling;y=!1;l=l.parent;r=l.scripts}var C=new A;c.length?(e("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+c.join(", ")),(g.contextRequire||w)(c,function(){C.resolve(d.filter(b,function(a){if(!a.ctor)try{a.ctor=J(a.types,g.contextRequire)}catch(b){}for(var c=a.parent;c&&!c.types;)c=c.parent;var d=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(d&&d.stopParser&&!g.template);
a.instantiate=!c||c.instantiate&&c.instantiateChildren;return a.instantiate}))})):C.resolve(b);return C.promise},_require:function(a,d){var e=I("{"+a.innerHTML+"}"),b=[],c=[],f=new A,k=d&&d.contextRequire||w,m;for(m in e)b.push(m),c.push(e[m]);k(c,function(){for(var a=0;a<b.length;a++)h.setObject(b[a],arguments[a]);f.resolve(arguments)});return f.promise},_scanAmd:function(a,d){var e=new A,b=e.promise;e.resolve(!0);var c=this;L("script[type\x3d'dojo/require']",a).forEach(function(a){b=b.then(function(){return c._require(a,
d)});a.parentNode.removeChild(a)});return b},parse:function(d,e){var k;!e&&d&&d.rootNode?(e=d,k=e.rootNode):d&&h.isObject(d)&&!("nodeType"in d)?e=d:k=d;k=k?p.byId(k):a.body();e=e||{};var b=e.template?{template:!0}:{},c=[],f=this,m=this._scanAmd(k,e).then(function(){return f.scan(k,e)}).then(function(a){return f._instantiate(a,b,e,!0)}).then(function(a){return c=c.concat(a)}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});h.mixin(c,m);return c}};n.parser=K;k.parseOnLoad&&
M(100,K,"parse");return K})}}});define("dojorama/layers/mijit",[],1);
//@ sourceMappingURL=mijit.js.map