//>>built
require({cache:{"mijit/_TemplatedMixin":function(){define("mijit/_TemplatedMixin","dojo/_base/lang,dojo/touch,./_WidgetBase,dojo/string,dojo/cache,dojo/_base/array,dojo/_base/declare,dojo/dom-construct,dojo/sniff,dojo/_base/unload".split(","),function(n,j,d,t,m,A,i,u,a,w){var C=i("dijit._TemplatedMixin",null,{templateString:null,templatePath:null,_skipNodeCache:!1,_earlyTemplatedStartup:!1,constructor:function(){this._attachPoints=[];this._attachEvents=[]},_stringRepl:function(a){var l=this.declaredClass,
j=this;return t.substitute(a,this,function(a,B){"!"==B.charAt(0)&&(a=n.getObject(B.substr(1),!1,j));if("undefined"==typeof a)throw Error(l+" template:"+B);return null==a?"":"!"==B.charAt(0)?a:a.toString().replace(/"/g,"&quot;")},this)},buildRendering:function(){if(!this.templateString)this.templateString=m(this.templatePath,{sanitize:!0});var a=C.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),l;if(n.isString(a)){if(l=u.toDom(this._stringRepl(a),this.ownerDocument),1!=
l.nodeType)throw Error("Invalid template: "+a);}else l=a.cloneNode(!0);this.domNode=l;this.inherited(arguments);this._attachTemplateNodes(l,function(a,l){return a.getAttribute(l)});this._beforeFillContent();this._fillContent(this.srcNodeRef)},_beforeFillContent:function(){},_fillContent:function(a){var l=this.containerNode;if(a&&l)for(;a.hasChildNodes();)l.appendChild(a.firstChild)},_attachTemplateNodes:function(a,l){for(var t=n.isArray(a)?a:a.all||a.getElementsByTagName("*"),s=n.isArray(a)?0:-1;0>
s||t[s];s++){var d=-1==s?a:t[s];if(!this.widgetsInTemplate||!l(d,"dojoType")&&!l(d,"data-dojo-type")){var o=l(d,"dojoAttachPoint")||l(d,"data-dojo-attach-point");if(o)for(var i=o.split(/\s*,\s*/);o=i.shift();)n.isArray(this[o])?this[o].push(d):this[o]=d,this._attachPoints.push(o);if(o=l(d,"dojoAttachEvent")||l(d,"data-dojo-attach-event"))for(var i=o.split(/\s*,\s*/),w=n.trim;o=i.shift();)if(o){var m=null;-1!=o.indexOf(":")?(m=o.split(":"),o=w(m[0]),m=w(m[1])):o=w(o);m||(m=o);this._attachEvents.push(this.connect(d,
j[o]||o,m))}}}},destroyRendering:function(){A.forEach(this._attachPoints,function(a){delete this[a]},this);this._attachPoints=[];A.forEach(this._attachEvents,this.disconnect,this);this._attachEvents=[];this.inherited(arguments)}});C._templateCache={};C.getCachedTemplate=function(a,l,d){var j=C._templateCache,m=a,o=j[m];if(o){try{if(!o.ownerDocument||o.ownerDocument==(d||document))return o}catch(i){}u.destroy(o)}a=t.trim(a);if(l||a.match(/\$\{([^\}]+)\}/g))return j[m]=a;l=u.toDom(a,d);if(1!=l.nodeType)throw Error("Invalid template: "+
a);return j[m]=l};a("ie")&&w.addOnWindowUnload(function(){var a=C._templateCache,l;for(l in a){var d=a[l];"object"==typeof d&&u.destroy(d);delete a[l]}});n.extend(d,{dojoAttachEvent:"",dojoAttachPoint:""});return C})},"mijit/_WidgetBase":function(){define("mijit/_WidgetBase","require,dojo/_base/array,dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-class,dojo/dom-construct,dojo/dom-geometry,dojo/dom-style,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/on,dojo/ready,dojo/Stateful,dojo/topic,dojo/_base/window,./Destroyable,./registry".split(","),
function(n,j,d,t,m,A,i,u,a,w,C,B,l,H,s,I,o,F,E,D,G,g){function f(b){return function(c){u[c?"set":"remove"](this.domNode,b,c);this._set(b,c)}}l.add("dijit-legacy-requires",!H.isAsync);l("dijit-legacy-requires")&&o(0,function(){n(["dijit/_base/manager"])});var x={};return A("dijit._WidgetBase",[F,G],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:f("lang"),dir:"",_setDirAttr:f("dir"),textDir:"","class":"",_setClassAttr:{node:"domNode",type:"class"},style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,
domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(b){this._set("ownerDocument",b)},attributeMap:{},_blankGif:t.blankGif||n.toUrl("dojo/resources/blank.gif"),postscript:function(b,c){this.create(b,c)},create:function(b,c){this.srcNodeRef=i.byId(c);this._connects=[];this._supportingWidgets=[];if(this.srcNodeRef&&"string"==typeof this.srcNodeRef.id)this.id=this.srcNodeRef.id;if(b)this.params=b,s.mixin(this,b);this.postMixInProperties();if(!this.id)this.id=g.getUniqueId(this.declaredClass.replace(/\./g,
"_")),this.params&&delete this.params.id;this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:D.doc);this.ownerDocumentBody=D.body(this.ownerDocument);g.add(this);this.buildRendering();var e;if(this.domNode){this._applyAttributes();var a=this.srcNodeRef;a&&a.parentNode&&this.domNode!==a&&(a.parentNode.replaceChild(this.domNode,a),e=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();e&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var b=
this.constructor,c=b._setterAttrs;if(!c){var c=b._setterAttrs=[],e;for(e in this.attributeMap)c.push(e);var b=b.prototype,a;for(a in b)a in this.attributeMap||"_set"+a.replace(/^[a-z]|-[a-zA-Z]/g,function(b){return b.charAt(b.length-1).toUpperCase()})+"Attr"in b&&c.push(a)}var g={},f;for(f in this.params||{})g[f]=this[f];j.forEach(c,function(b){b in g||this[b]&&this.set(b,this[b])},this);for(f in g)this.set(f,g[f])},postMixInProperties:function(){},buildRendering:function(){if(!this.domNode)this.domNode=
this.srcNodeRef||this.ownerDocument.createElement("div");if(this.baseClass){var b=this.baseClass.split(" ");this.isLeftToRight()||(b=b.concat(j.map(b,function(b){return b+"Rtl"})));a.add(this.domNode,b)}},postCreate:function(){},startup:function(){if(!this._started)this._started=!0,j.forEach(this.getChildren(),function(b){if(!b._started&&!b._destroyed&&s.isFunction(b.startup))b.startup(),b._started=!0})},destroyRecursive:function(b){this._beingDestroyed=!0;this.destroyDescendants(b);this.destroy(b)},
destroy:function(b){function c(c){c.destroyRecursive?c.destroyRecursive(b):c.destroy&&c.destroy(b)}this._beingDestroyed=!0;this.uninitialize();j.forEach(this._connects,s.hitch(this,"disconnect"));j.forEach(this._supportingWidgets,c);this.domNode&&j.forEach(g.findWidgets(this.domNode,this.containerNode),c);this.destroyRendering(b);g.remove(this.id);this._destroyed=!0},destroyRendering:function(b){this.bgIframe&&(this.bgIframe.destroy(b),delete this.bgIframe);this.domNode&&(b?u.remove(this.domNode,
"widgetId"):w.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(b||w.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(b){j.forEach(this.getChildren(),function(c){c.destroyRecursive&&c.destroyRecursive(b)})},uninitialize:function(){return!1},_setStyleAttr:function(b){var c=this.domNode;s.isObject(b)?B.set(c,b):c.style.cssText=c.style.cssText?c.style.cssText+("; "+b):b;this._set("style",b)},_attrToDom:function(b,c,e){e=3<=arguments.length?e:this.attributeMap[b];
j.forEach(s.isArray(e)?e:[e],function(e){var g=this[e.node||e||"domNode"];switch(e.type||"attribute"){case "attribute":s.isFunction(c)&&(c=s.hitch(this,c));e=e.attribute?e.attribute:/^on[A-Z][a-zA-Z]*$/.test(b)?b.toLowerCase():b;g.tagName?u.set(g,e,c):g.set(e,c);break;case "innerText":g.innerHTML="";g.appendChild(this.ownerDocument.createTextNode(c));break;case "innerHTML":g.innerHTML=c;break;case "class":a.replace(g,c,this[b])}},this)},get:function(b){var c=this._getAttrNames(b);return this[c.g]?
this[c.g]():this[b]},set:function(b,c){if("object"===typeof b){for(var e in b)this.set(e,b[e]);return this}e=this._getAttrNames(b);var a=this[e.s];if(s.isFunction(a))var g=a.apply(this,Array.prototype.slice.call(arguments,1));else{var a=this.focusNode&&!s.isFunction(this.focusNode)?"focusNode":"domNode",f=this[a]&&this[a].tagName,k;if(k=f)if(!(k=x[f])){k=this[a];var l={},h;for(h in k)l[h.toLowerCase()]=!0;k=x[f]=l}h=k;e=b in this.attributeMap?this.attributeMap[b]:e.s in this?this[e.s]:h&&e.l in h&&
"function"!=typeof c||/^aria-|^data-|^role$/.test(b)?a:null;null!=e&&this._attrToDom(b,c,e);this._set(b,c)}return g||this},_attrPairNames:{},_getAttrNames:function(b){var c=this._attrPairNames;if(c[b])return c[b];var e=b.replace(/^[a-z]|-[a-zA-Z]/g,function(b){return b.charAt(b.length-1).toUpperCase()});return c[b]={n:b+"Node",s:"_set"+e+"Attr",g:"_get"+e+"Attr",l:e.toLowerCase()}},_set:function(b,c){var e=this[b];this[b]=c;this._created&&c!==e&&(this._watchCallbacks&&this._watchCallbacks(b,e,c),
this.emit("attrmodified-"+b,{detail:{prevValue:e,newValue:c}}))},emit:function(b,c,e){c=c||{};if(void 0===c.bubbles)c.bubbles=!0;if(void 0===c.cancelable)c.cancelable=!0;if(!c.detail)c.detail={};c.detail.widget=this;var a,g=this["on"+b];g&&(a=g.apply(this,e?e:[c]));this._started&&!this._beingDestroyed&&I.emit(this.domNode,b.toLowerCase(),c);return a},on:function(b,c){var a=this._onMap(b);return a?d.after(this,a,c,!0):this.own(I(this.domNode,b,c))[0]},_onMap:function(b){var c=this.constructor,a=c._onMap;
if(!a){var a=c._onMap={},g;for(g in c.prototype)/^on/.test(g)&&(a[g.replace(/^on/,"").toLowerCase()]=g)}return a["string"==typeof b&&b.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?g.findWidgets(this.containerNode):[]},getParent:function(){return g.getEnclosingWidget(this.domNode.parentNode)},connect:function(b,c,a){return this.own(m.connect(b,c,this,a))[0]},disconnect:function(b){b.remove()},subscribe:function(b,
c){return this.own(E.subscribe(b,s.hitch(this,c)))[0]},unsubscribe:function(b){b.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:C.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=B.get(this.domNode,"display")},placeAt:function(b,c){var a=!b.tagName&&g.byId(b);a&&a.addChild&&(!c||"number"===typeof c)?a.addChild(this,c):(a=a?a.containerNode&&!/after|before|replace/.test(c||"")?a.containerNode:a.domNode:i.byId(b,this.ownerDocument),w.place(this.domNode,
a,c),!this._started&&(this.getParent()||{})._started&&this.startup());return this},getTextDir:function(b,a){return a},applyTextDir:function(){},defer:function(b,a){var g=setTimeout(s.hitch(this,function(){g=null;this._destroyed||s.hitch(this,b)()}),a||0);return{remove:function(){g&&(clearTimeout(g),g=null);return null}}}})})},"mijit/Destroyable":function(){define("mijit/Destroyable",["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(n,j,d){return d("dijit.Destroyable",null,{destroy:function(){this._destroyed=
!0},own:function(){n.forEach(arguments,function(d){var m="destroyRecursive"in d?"destroyRecursive":"destroy"in d?"destroy":"remove",n=j.before(this,"destroy",function(j){d[m](j)}),i=j.after(d,m,function(){n.remove();i.remove()},!0)},this);return arguments}})})},"mijit/registry":function(){define("mijit/registry",["dojo/_base/array","dojo/sniff","dojo/_base/unload","dojo/_base/window","./main"],function(n,j,d,t,m){var A={},i={},u={length:0,add:function(a){if(i[a.id])throw Error("Tried to register widget with id=="+
a.id+" but that id is already registered");i[a.id]=a;this.length++},remove:function(a){i[a]&&(delete i[a],this.length--)},byId:function(a){return"string"==typeof a?i[a]:a},byNode:function(a){return i[a.getAttribute("widgetId")]},toArray:function(){var a=[],d;for(d in i)a.push(i[d]);return a},getUniqueId:function(a){var d;do d=a+"_"+(a in A?++A[a]:A[a]=0);while(i[d]);return"dijit"==m._scopeName?d:m._scopeName+"_"+d},findWidgets:function(a,d){function j(a){for(a=a.firstChild;a;a=a.nextSibling)if(1==
a.nodeType){var t=a.getAttribute("widgetId");t?(t=i[t])&&m.push(t):a!==d&&j(a)}}var m=[];j(a);return m},_destroyAll:function(){m._curFocus=null;m._prevFocus=null;m._activeStack=[];n.forEach(u.findWidgets(t.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var d=a.getAttribute&&a.getAttribute("widgetId");if(d)return i[d];a=a.parentNode}return null},_hash:i};return m.registry=u})},"mijit/main":function(){define("mijit/main",
["dojo/_base/kernel"],function(n){return n.dijit})},"mijit/_WidgetsInTemplateMixin":function(){define("mijit/_WidgetsInTemplateMixin",["dojo/_base/array","dojo/_base/declare","dojo/parser"],function(n,j,d){return j("dijit._WidgetsInTemplateMixin",null,{_earlyTemplatedStartup:!1,widgetsInTemplate:!0,_beforeFillContent:function(){if(this.widgetsInTemplate){var j=this._startupWidgets=d.parse(this.domNode,{noStart:!this._earlyTemplatedStartup,template:!0,inherited:{dir:this.dir,lang:this.lang,textDir:this.textDir},
propsThis:this,scope:"dojo"});if(!j.isFulfilled())throw Error(this.declaredClass+": parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation.");this._attachTemplateNodes(j,function(d,j){return d[j]})}},startup:function(){n.forEach(this._startupWidgets,function(d){d&&!d._started&&d.startup&&d.startup()});this.inherited(arguments)}})})},"dojo/parser":function(){define("dojo/parser","require,./_base/kernel,./_base/lang,./_base/array,./_base/config,./_base/html,./_base/window,./_base/url,./_base/json,./aspect,./date/stamp,./Deferred,./has,./query,./on,./ready".split(","),
function(n,j,d,t,m,A,i,u,a,w,C,B,l,H,s,I){function o(a){var f=a._nameCaseMap,d=a.prototype;if(!f||f._extendCnt<E){var f=a._nameCaseMap={},b;for(b in d)"_"!==b.charAt(0)&&(f[b.toLowerCase()]=b);f._extendCnt=E}return f}function F(a){var f=a.join();if(!D[f]){for(var x=[],b=0,c=a.length;b<c;b++){var e=a[b];x[x.length]=D[e]=D[e]||d.getObject(e)||~e.indexOf("/")&&n(e)}a=x.shift();D[f]=x.length?a.createSubclass?a.createSubclass(x):a.extend.apply(a,x):a}return D[f]}var E=0;w.after(d,"extend",function(){E++},
!0);var D={},G={_clearCache:function(){E++;D={}},_functionFromScript:function(a,f){var d="",b="",c=a.getAttribute(f+"args")||a.getAttribute("args"),e=a.getAttribute("with"),c=(c||"").split(/\s*,\s*/);e&&e.length&&t.forEach(e.split(/\s*,\s*/),function(a){d+="with("+a+"){";b+="}"});return new Function(c,d+a.innerHTML+b)},instantiate:function(a,f,d){var f=f||{},d=d||{},b=(d.scope||j._scopeName)+"Type",c="data-"+(d.scope||j._scopeName)+"-",e=c+"type",l=c+"mixins",r=[];t.forEach(a,function(a){var c=b in
f?f[b]:a.getAttribute(e)||a.getAttribute(b);if(c){var g=a.getAttribute(l),c=g?[c].concat(g.split(/\s*,\s*/)):[c];r.push({node:a,types:c})}});return this._instantiate(r,f,d)},_instantiate:function(a,f,d){a=t.map(a,function(a){var c=a.ctor||F(a.types);if(!c)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(c,a.node,f,d,a.scripts,a.inherited)},this);!f._started&&!d.noStart&&t.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a},
construct:function(g,f,x,b,c,e){var K;var m=g&&g.prototype,b=b||{},r={};b.defaults&&d.mixin(r,b.defaults);e&&d.mixin(r,e);var i;l("dom-attributes-explicit")?i=f.attributes:l("dom-attributes-specified-flag")?i=t.filter(f.attributes,function(a){return a.specified}):(e=(/^input$|^img$/i.test(f.nodeName)?f:f.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),i=t.map(e.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,
value:"LI"==f.nodeName&&"value"==a||"enctype"==b?f.getAttribute(b):f.getAttributeNode(b).value}}));var k=b.scope||j._scopeName,e="data-"+k+"-",p={};"dojo"!==k&&(p[e+"props"]="data-dojo-props",p[e+"type"]="data-dojo-type",p[e+"mixins"]="data-dojo-mixins",p[k+"type"]="dojoType",p[e+"id"]="data-dojo-id");for(var k=0,h,n=[],J,v;h=i[k++];){var q=h.name,y=q.toLowerCase();h=h.value;switch(p[y]||y){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":v=h;break;case "data-dojo-id":case "jsid":J=
h;break;case "data-dojo-attach-point":case "dojoattachpoint":r.dojoAttachPoint=h;break;case "data-dojo-attach-event":case "dojoattachevent":r.dojoAttachEvent=h;break;case "class":r["class"]=f.className;break;case "style":r.style=f.style&&f.style.cssText;break;default:if(q in m||(q=o(g)[y]||q),q in m)switch(typeof m[q]){case "string":r[q]=h;break;case "number":r[q]=h.length?Number(h):NaN;break;case "boolean":r[q]="false"!=h.toLowerCase();break;case "function":r[q]=""===h||-1!=h.search(/[^\w\.]+/i)?
new Function(h):d.getObject(h,!1)||new Function(h);n.push(q);break;default:y=m[q],r[q]=y&&"length"in y?h?h.split(/\s*,\s*/):[]:y instanceof Date?""==h?new Date(""):"now"==h?new Date:C.fromISOString(h):y instanceof u?j.baseUrl+h:a.fromJson(h)}else r[q]=h}}for(k=0;k<n.length;k++)i=n[k].toLowerCase(),f.removeAttribute(i),f[i]=null;if(v)try{v=a.fromJson.call(b.propsThis,"{"+v+"}"),d.mixin(r,v)}catch(B){throw Error(B.toString()+" in data-dojo-props='"+v+"'");}d.mixin(r,x);c||(c=g&&(g._noScript||m._noScript)?
[]:H("> script[type^='dojo/']",f));x=[];b=[];v=[];n=[];if(c)for(k=0;k<c.length;k++){var z=c[k];f.removeChild(z);i=z.getAttribute(e+"event")||z.getAttribute("event");p=z.getAttribute(e+"prop");q=z.getAttribute(e+"method");y=z.getAttribute(e+"advice");h=z.getAttribute("type");z=this._functionFromScript(z,e);i?"dojo/connect"==h?x.push({method:i,func:z}):"dojo/on"==h?n.push({event:i,func:z}):r[i]=z:"dojo/aspect"==h?x.push({method:q,advice:y,func:z}):"dojo/watch"==h?v.push({prop:p,func:z}):b.push(z)}K=
(c=g.markupFactory||m.markupFactory)?c(r,f,g):new g(r,f),g=K;J&&d.setObject(J,g);for(k=0;k<x.length;k++)w[x[k].advice||"after"](g,x[k].method,d.hitch(g,x[k].func),!0);for(k=0;k<b.length;k++)b[k].call(g);for(k=0;k<v.length;k++)g.watch(v[k].prop,v[k].func);for(k=0;k<n.length;k++)s(g,n[k].event,n[k].func);return g},scan:function(a,d){function i(a){if(!a.inherited){a.inherited={};var b=a.node,c=i(a.parent),b={dir:b.getAttribute("dir")||c.dir,lang:b.getAttribute("lang")||c.lang,textDir:b.getAttribute(k)||
c.textDir},d;for(d in b)b[d]&&(a.inherited[d]=b[d])}return a.inherited}var b=[],c=[],e={},m=(d.scope||j._scopeName)+"Type",r="data-"+(d.scope||j._scopeName)+"-",o=r+"type",k=r+"textdir",r=r+"mixins",p=a.firstChild,h=d.inherited;if(!h){var s=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&s(a.parentNode,b)},h={dir:s(a,"dir"),lang:s(a,"lang"),textDir:s(a,k)},u;for(u in h)h[u]||delete h[u]}for(var h={inherited:h},v,q;;)if(p)if(1!=p.nodeType)p=p.nextSibling;else if(v&&"script"==
p.nodeName.toLowerCase())(y=p.getAttribute("type"))&&/^dojo\/\w/i.test(y)&&v.push(p),p=p.nextSibling;else if(q)p=p.nextSibling;else{var y=p.getAttribute(o)||p.getAttribute(m);u=p.firstChild;if(!y&&(!u||3==u.nodeType&&!u.nextSibling))p=p.nextSibling;else{q=null;if(y){var w=p.getAttribute(r);v=w?[y].concat(w.split(/\s*,\s*/)):[y];try{q=F(v)}catch(z){}q||t.forEach(v,function(a){~a.indexOf("/")&&!e[a]&&(e[a]=!0,c[c.length]=a)});w=q&&!q.prototype._noScript?[]:null;h={types:v,ctor:q,parent:h,node:p,scripts:w};
h.inherited=i(h);b.push(h)}else h={node:p,scripts:v,parent:h};p=u;v=w;q=q&&q.prototype.stopParser&&!d.template}}else{if(!h||!h.node)break;p=h.node.nextSibling;q=!1;h=h.parent;v=h.scripts}var A=new B;c.length?(l("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+c.join(", ")),n(c,function(){A.resolve(t.filter(b,function(a){if(!a.ctor)try{a.ctor=F(a.types)}catch(b){}for(var c=a.parent;c&&!c.types;)c=c.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&
!d.template);a.instantiate=!c||c.instantiate&&c.instantiateChildren;return a.instantiate}))})):A.resolve(b);return A.promise},_require:function(g){var g=a.fromJson("{"+g.innerHTML+"}"),f=[],i=[],b=new B,c;for(c in g)f.push(c),i.push(g[c]);n(i,function(){for(var a=0;a<f.length;a++)d.setObject(f[a],arguments[a]);b.resolve(arguments)});return b.promise},_scanAmd:function(a){var d=new B,i=d.promise;d.resolve(!0);var b=this;H("script[type='dojo/require']",a).forEach(function(a){i=i.then(function(){return b._require(a)});
a.parentNode.removeChild(a)});return i},parse:function(a,f){var j;!f&&a&&a.rootNode?(f=a,j=f.rootNode):a&&d.isObject(a)&&!("nodeType"in a)?f=a:j=a;j=j?A.byId(j):i.body();var f=f||{},b=f.template?{template:!0}:{},c=[],e=this,l=this._scanAmd(j,f).then(function(){return e.scan(j,f)}).then(function(a){return c=c.concat(e._instantiate(a,b,f))}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});d.mixin(c,l);return c}};j.parser=G;m.parseOnLoad&&I(100,G,"parse");return G})}}});
define("dojorama/layers/mijit",[],1);