//>>built
define("dgrid/editor","dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has dojo/query ./Grid put-selector/put dojo/_base/sniff".split(" "),function(C,w,D,x,l,q,s,E,y,r){function u(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=a.defaultChecked=!!b}function z(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date){var c=new Date(a);a=isNaN(c.getTime())?
a:c}return a}function F(a,b,c,d,g){var e,f,h;if((c&&c.valueOf())!=(d&&d.valueOf())&&(e=a.cell(b),f=e.row,h=e.column,h.field&&f))if(e={grid:a,cell:e,rowId:f.id,oldValue:c,value:d,bubbles:!0,cancelable:!0},g&&g.type&&(e.parentType=g.type),l.emit(b,"dgrid-datachange",e))a.updateDirty?(a.updateDirty(f.id,h.field,d),h.autoSave&&setTimeout(function(){a._trackError("save")},0)):f.data[h.field]=d;else{var k;(k=b.widget)?(k._dgridIgnoreChange=!0,k.set("value",c),setTimeout(function(){k._dgridIgnoreChange=
!1},0)):(k=b.input)&&u(k,c);return c}return d}function v(a,b,c,d){var g;if(!c.isValid||c.isValid())if(d=F(a,(c.domNode||c).parentNode,m?p:c._dgridLastValue,"function"==typeof c.get?z(c.get("value")):z(c["checkbox"==c.type||"radio"==c.type?"checked":"value"]),d),m?p=d:c._dgridLastValue=d,"radio"===c.type&&c.name&&!b.editOn&&b.field)for(g in d=a.row(c),E("input[type\x3dradio][name\x3d"+c.name+"]",a.contentNode).forEach(function(d){var f=a.row(d);d!==c&&d._dgridLastValue&&(d._dgridLastValue=!1,a.updateDirty?
a.updateDirty(f.id,b.field,!1):f.data[b.field]=!1)}),a.dirty)d.id!==g&&a.dirty[g][b.field]&&a.updateDirty(g,b.field,!1)}function A(a){var b=a.editor,c=a.editOn,d=a.grid,g="string"!=typeof b,e,f,h;e=a.editorArgs||{};"function"==typeof e&&(e=e.call(d,a));if(g)f=new b(e),g=f.focusNode||f.domNode,g.className+=" dgrid-input",f.connect(f,c?"onBlur":"onChange",function(){f._dgridIgnoreChange||v(d,a,this,{type:"widget"})});else if(h=function(c){var b=c.target;"_dgridLastValue"in b&&-1<b.className.indexOf("dgrid-input")&&
v(d,a,b,c)},a.grid._hasInputListener||(d._hasInputListener=!0,d.on("change",function(a){h(a)})),f=g=r(("textarea"==b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",w.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},e)),9>s("ie")||s("ie")&&s("quirks"))"radio"==b||"checkbox"==b?l(f,"click",function(a){h(a)}):l(f,"change",function(a){h(a)});l(g,"mousedown",function(a){a.stopPropagation()});return f}function G(a,b){function c(){var a=m;h.blur();"function"===typeof g.focus&&setTimeout(function(){g.focus(a)},
e&&9>s("ie")?15:0)}var d=A(a),g=a.grid,e=d.domNode,f=d.domNode||d,h=d.focusNode||f,k=e?function(){d.set("value",d._dgridLastValue)}:function(){u(d,d._dgridLastValue);v(a.grid,a,d)};l(h,"keydown",function(b){b=b.keyCode||b.which;27==b?(k(),p=d._dgridLastValue,c()):13==b&&!1!==a.dismissOnEnter&&c()});(a._editorBlurHandle=l.pausable(d,"blur",function(){var b=f.parentNode,c=b.children.length-1,e={alreadyHooked:!0},k=g.cell(f);l.emit(k.element,"dgrid-editor-hide",{grid:g,cell:k,column:a,editor:d,bubbles:!0,
cancelable:!1});a._editorBlurHandle.pause();b.removeChild(f);for(r(k.element,"!dgrid-cell-editing");c--;)r(b.firstChild,"!");y.appendIfNode(b,a.renderCell(a.grid.row(b).data,p,b,t?w.delegate(e,t):e));m=p=t=null})).pause();return d}function B(a,b,c,d){var g=a.domNode,e=b.grid;g||u(a,d);c.innerHTML="";r(c,".dgrid-cell-editing");r(c,a.domNode||a);g&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",d),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=d;m&&(p=d,l.emit(c,
"dgrid-editor-show",{grid:e,cell:e.cell(c),column:b,editor:a,bubbles:!0,cancelable:!1}))}function H(a){var b,c,d,g,e,f;a.column||(a=this.cell(a));if(!a||!a.element)return null;b=a.column;g=b.field;c=a.element.contents||a.element;if(e=b.editorInstance){if(m!=c&&(!b.canEdit||b.canEdit(a.row.data,d)))return m=c,a=a.row,d=(d=this.dirty&&this.dirty[a.id])&&g in d?d[g]:b.get?b.get(a.data):a.data[g],B(b.editorInstance,b,c,d),f=new x,setTimeout(function(){e.focus&&e.focus();b._editorBlurHandle&&b._editorBlurHandle.resume();
f.resolve(e)},0),f.promise}else if(b.editor&&(e=c.widget||c.input))return f=new x,e.focus&&e.focus(),f.resolve(e),f.promise;return null}var m,p,t,n;return function(a,b,c){function d(a){var b=a.grid,c;b.edit||(b.edit=H,e.push(l(b.domNode,".dgrid-input:focusin",function(){n=b.cell(this)})),c=b._editorFocusoutHandle=l.pausable(b.domNode,".dgrid-input:focusout",function(){n=null}),e.push(c),e.push(q.before(b,"removeRow",function(a){a=b.row(a);n&&n.row.id===a.id&&(c.pause(),setTimeout(function(){c.resume()},
0))})),e.push(q.after(b,"insertRow",function(a){var c=b.row(a);n&&n.row.id===c.id&&b.edit(b.cell(c,n.column.id));return a})))}var g=a.renderCell||y.defaultRenderCell,e=[],f;a||(a={});a.editor=b=b||a.editor||"text";a.editOn=c=c||a.editOn;f="string"!=typeof b;a.widgetArgs&&(C.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 0.4"),a.editorArgs=a.widgetArgs);q.after(a,"init",c?function(){d(a);a.editorInstance=G(a,g)}:function(){var b=a.grid;d(a);f&&e.push(q.before(b,"removeRow",function(c){if(c=
(c=b.cell(c,a.id).element)&&(c.contents||c).widget)b._editorFocusoutHandle.pause(),c.destroyRecursive()}))});q.after(a,"destroy",function(){D.forEach(e,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();c&&f&&a.editorInstance.destroyRecursive();a.grid.edit=null});a.renderCell=c?function(b,d,e,f){if(!f||!f.alreadyHooked)l("TD"==e.tagName?e:e.parentNode,c,function(){t=f;a.grid.edit(this)});return g.call(a,b,d,e,f)}:function(b,c,d,e){if(!a.canEdit||a.canEdit(b,c))b=A(a),B(b,a,
d,c),d[f?"widget":"input"]=b;else return g.call(a,b,c,d,e)};return a}});
//@ sourceMappingURL=editor.js.map