//>>built
require({cache:{"url:dojorama/ui/release/widget/template/ReleaseGridWidget.html":'\x3cdiv\x3e\n    \x3cdiv class\x3d"clearfix"\x3e\n        \x3cform class\x3d"form-inline pull-right" data-dojo-attach-point\x3d"filterFormNode"\x3e\n            \x3cdiv class\x3d"form-group"\x3e\n                \x3cinput data-dojo-attach-point\x3d"filterInputNode" class\x3d"form-control"\x3e\n            \x3c/div\x3e\n            \x3cbutton data-dojo-attach-point\x3d"filterSubmitNode" class\x3d"btn"\x3e\x3c/button\x3e\n        \x3c/form\x3e\n    \x3c/div\x3e\n\n    \x3cbr\x3e\n    \n    \x3cdiv data-dojo-attach-point\x3d"mainNode" style\x3d"display:none"\x3e\n        \x3cdiv data-dojo-attach-point\x3d"gridNode"\x3e\x3c/div\x3e\n    \n        \x3cdiv class\x3d"btn-toolbar"\x3e\n            \x3cbutton data-dojo-attach-point\x3d"gridSaveButtonNode" class\x3d"btn"\x3e\x3c/button\x3e\n            \x3cbutton data-dojo-attach-point\x3d"gridDeleteButtonNode" class\x3d"btn btn-danger"\x3e\x3c/button\x3e\n        \x3c/div\x3e\n    \x3c/div\x3e\n\x3c/div\x3e'}});
define("dojorama/ui/release/widget/ReleaseGridWidget","dojo/_base/declare dojo/_base/lang mijit/_WidgetBase mijit/_TemplatedMixin dojomat/_StateAware dgrid/OnDemandGrid dgrid/Selection dgrid/editor dojo-form-controls/Checkbox dojo-form-controls/Button dojo-form-controls/Textbox dobolo/DatepickerInput dojo-data-model/Observable dojo/dom-construct dojo/dom-style dojo/dom-attr dojo/aspect dojo/topic dojo/on dojo/when dojo/promise/all dojo/text!./template/ReleaseGridWidget.html dojo/i18n!./nls/ReleaseGridWidget".split(" "),
function(p,a,s,t,u,v,w,q,x,k,y,z,A,r,g,h,B,e,l,m,C,D,b){return p([s,t,u],{router:null,store:null,templateString:D,filterInputWidget:null,filterSubmitWidget:null,gridWidget:null,gridSaveButtonWidget:null,gridDeleteButtonWidget:null,constructor:function(a){this.request=a.request;this.router=a.router;this.store=a.store},postCreate:function(){this.inherited(arguments);this.store=A(this.store);this.buildFilterForm();this.gridSaveButtonWidget=this.buildSaveButton();this.gridDeleteButtonWidget=this.buildDeleteButton();
this.gridWidget=this.buildGrid();this.gridWidget.setStore(this.store)},startup:function(){this.filterInputWidget.startup();this.filterSubmitWidget.startup();this.gridSaveButtonWidget.startup();this.gridDeleteButtonWidget.startup()},buildFilterForm:function(){this.filterInputWidget=new y({"class":h.get(this.filterInputNode,"class"),value:this.request.getQueryParam("find")},this.filterInputNode);this.filterSubmitWidget=new k({type:"submit","class":h.get(this.filterSubmitNode,"class"),label:b.filterSubmitLabel},
this.filterSubmitNode);this.own(l(this.filterFormNode,"submit",a.hitch(this,function(a){a.preventDefault();this.push(this.router.getRoute("releaseIndex").assemble(null,{find:this.filterInputWidget.value}))})))},buildGrid:function(){var f={selector:{label:" ",sortable:!1,renderCell:a.hitch(this,function(d,c,b,n){c=r.create("input",{type:"checkbox"},b,"last");this.own(l(c,"change",a.hitch(this,function(a){a=this.gridWidget.row(d);this.gridWidget.isSelected(d.get("id"))?this.gridWidget.deselect(a):this.gridWidget.select(a)})))})},
title:{label:b.gridColumnLabelTitle,field:"title",sortable:!0,renderCell:a.hitch(this,function(d,c,b,n){d=r.create("a",{href:this.router.getRoute("releaseUpdate").assemble({id:d.get("id")}),innerHTML:d.get("title")},b,"last");this.own(l(d,"click",a.hitch(this,function(a){a.preventDefault();this.push(a.target.href)})))})},releaseDate:q({label:b.gridColumnLabelReleaseDate,field:"releaseDate",sortable:!0,autoSave:!1,editorArgs:{required:!0,"class":"form-control",format:"medium"}},z),publish:q({label:b.gridColumnLabelPublish,
field:"publish",sortable:!0,autoSave:!1,editorArgs:{value:"on"}},x)},c=new (p([v,w]))({getBeforePut:!0,columns:f,selectionMode:"none",queryOptions:{sort:[{attribute:"title",descending:!1}]},loadingMessage:b.gridLoadingState,noDataMessage:b.gridNoDataAvailable},this.gridNode),n=function(){var a=0,b;for(b in c.selection)c.selection.hasOwnProperty(b)&&(a+=1);return a};this.request.getQueryParam("find")&&c.set("query",{title:this.request.getQueryParam("find")});c.on("dgrid-error",function(a){e.publish("ui/release/widget/ReleaseGridWidget/unknown-error",
{notification:{message:b.notificationUnknownError,type:"error"}})});c.on(".dgrid-header .dgrid-column-title:click",a.hitch(this,function(a){}));c.on(".dgrid-row .dgrid-column-title:click",a.hitch(this,function(a){}));c.on("dgrid-select",a.hitch(this,function(a){g.set(this.gridDeleteButtonWidget.domNode,"display","inline")}));c.on("dgrid-deselect",a.hitch(this,function(a){g.set(this.gridDeleteButtonWidget.domNode,"display",n()?"inline":"none")}));c.on("dgrid-datachange",a.hitch(this,function(a){g.set(this.gridSaveButtonWidget.domNode,
"display","inline")}));var E=B.after(this.store,"query",a.hitch(this,function(b){m(b,a.hitch(this,function(a){a.length&&(g.set(this.mainNode,"display","block"),E.remove())}));return b}));return c},buildSaveButton:function(){var f=function(){e.publish("ui/release/widget/ReleaseGridWidget/update-ok",{notification:{message:b.notificationUpdateOk,type:"ok"}})},c=function(a){e.publish("ui/release/widget/ReleaseGridWidget/update-error",{notification:{message:b.notificationUpdateError,type:"error"}})};return new k({style:"display: none",
"class":h.get(this.gridSaveButtonNode,"class"),label:b.gridSaveButtonLabel,onClick:a.hitch(this,function(){m(this.gridWidget.save(),f,c)})},this.gridSaveButtonNode)},buildDeleteButton:function(){var f=function(a){e.publish("ui/release/widget/ReleaseGridWidget/delete-ok",{notification:{message:b.notificationDeleteOk,type:"ok"}})},c=function(a){e.publish("ui/release/widget/ReleaseGridWidget/delete-error",{notification:{message:b.notificationDeleteError,type:"error"}})};return new k({style:"display: none",
"class":h.get(this.gridDeleteButtonNode,"class"),label:b.gridDeleteButtonLabel,onClick:a.hitch(this,function(){var a=[],b;for(b in this.gridWidget.selection)this.gridWidget.selection.hasOwnProperty(b)&&a.push(this.store.remove(b));m(C(a),f,c)})},this.gridDeleteButtonNode)}})});
//@ sourceMappingURL=ReleaseGridWidget.js.map