//>>built
define("dgrid/Selection","dojo/_base/kernel dojo/_base/declare dojo/_base/Deferred dojo/on dojo/has dojo/aspect ./List dojo/has!touch?./util/touch put-selector/put dojo/query dojo/_base/sniff".split(" "),function(u,v,w,h,g,k,x,m,n){function p(a,b){for(var c=a.unselectable=b?"on":"",d=a.getElementsByTagName("*"),e=d.length;--e;)"INPUT"===d[e].tagName||"TEXTAREA"===d[e].tagName||(d[e].unselectable=c)}function q(a,b){var c=a.bodyNode,d=b?"text":21>g("ff")?"-moz-none":"none";r?c.style[r]=d:g("dom-selectstart")?
!b&&!a._selectstartHandle?a._selectstartHandle=h(c,"selectstart",function(a){var b=a.target&&a.target.tagName;"INPUT"!==b&&"TEXTAREA"!==b&&a.preventDefault()}):b&&a._selectstartHandle&&(a._selectstartHandle.remove(),delete a._selectstartHandle):(p(c,!b),!b&&!a._unselectableHandle?a._unselectableHandle=k.after(a,"renderRow",function(a){p(a,!0);return a}):b&&a._unselectableHandle&&(a._unselectableHandle.remove(),delete a._unselectableHandle))}g.add("mspointer",function(a,b,c){return"onmspointerdown"in
c});g.add("css-user-select",function(a,b,c){a=c.style;b=["Khtml","O","ms","Moz","Webkit"];c=b.length;var d="userSelect";do if("undefined"!==typeof a[d])return d;while(c--&&(d=b[c]+"UserSelect"));return!1});g.add("dom-selectstart","undefined"!==typeof document.onselectstart);var l=g("mac")?"metaKey":"ctrlKey",r=g("css-user-select"),s=g("mspointer")?"MSPointerDown":"mousedown",t=g("mspointer")?"MSPointerUp":"mouseup";return v(null,{selectionDelegate:".dgrid-row",selectionEvents:s+","+t+",dgrid-cellfocusin",
deselectOnRefresh:!0,allowSelectAll:!1,selection:{},selectionMode:"extended",allowTextSelection:void 0,create:function(){this.selection={};return this.inherited(arguments)},postCreate:function(){this.inherited(arguments);var a=this.selectionMode;this.selectionMode="";this._setSelectionMode(a);this._initSelectionEvents()},destroy:function(){this.inherited(arguments);this._selectstartHandle&&this._selectstartHandle.remove();this._unselectableHandle&&this._unselectableHandle.remove();this._removeDeselectSignals&&
this._removeDeselectSignals()},_setSelectionMode:function(a){a!=this.selectionMode&&(this.clearSelection(),this.selectionMode=a,this._selectionHandlerName="_"+a+"SelectionHandler",this._setAllowTextSelection(this.allowTextSelection))},setSelectionMode:function(a){u.deprecated("setSelectionMode(...)",'use set("selectionMode", ...) instead',"dgrid 0.4");this.set("selectionMode",a)},_setAllowTextSelection:function(a){"undefined"!==typeof a?q(this,a):q(this,"none"===this.selectionMode);this.allowTextSelection=
a},_handleSelect:function(a,b){if(this[this._selectionHandlerName]&&!("dgrid-cellfocusin"===a.type&&"mousedown"===a.parentType||a.type===t&&b!=this._waitForMouseUp)){this._waitForMouseUp=null;this._selectionTriggerEvent=a;if(!a.keyCode||!a.ctrlKey||32==a.keyCode)if(!a.shiftKey&&a.type===s&&this.isSelected(b))this._waitForMouseUp=b;else this[this._selectionHandlerName](a,b);this._selectionTriggerEvent=null}},_singleSelectionHandler:function(a,b){var c=a.keyCode?a.ctrlKey:a[l];this._lastSelected===
b?this.select(b,null,!c||!this.isSelected(b)):(this.clearSelection(),this.select(b),this._lastSelected=b)},_multipleSelectionHandler:function(a,b){var c=this._lastSelected,d=a.keyCode?a.ctrlKey:a[l],e;a.shiftKey||(e=d?null:!0,c=null);this.select(b,c,e);c||(this._lastSelected=b)},_extendedSelectionHandler:function(a,b){(2===a.button?!this.isSelected(b):!(a.keyCode?a.ctrlKey:a[l]))&&this.clearSelection(null,!0);this._multipleSelectionHandler(a,b)},_toggleSelectionHandler:function(a,b){this.select(b,
null,null)},_initSelectionEvents:function(){var a=this,b=this.selectionDelegate;g("touch")&&!g("mspointer")?h(this.contentNode,m.selector(b,m.tap),function(b){a._handleSelect(b,this)}):h(this.contentNode,h.selector(b,this.selectionEvents),function(b){a._handleSelect(b,this)});this.addKeyHandler&&this.addKeyHandler(32,function(b){a._handleSelect(b,b.target)});if(this.allowSelectAll)this.on("keydown",function(b){b[l]&&(65==b.keyCode&&!/\bdgrid-input\b/.test(b.target.className))&&(b.preventDefault(),
a[a.allSelected?"clearSelection":"selectAll"]())});this._setStore&&k.after(this,"_setStore",function(){a._updateDeselectionAspect()});this._updateDeselectionAspect()},_updateDeselectionAspect:function(){function a(a,c,d){a=c||a&&a[b.idProperty||"id"];if(null!=a&&(c=(a=b.row(a))&&b.selection[a.id]))b[d](a,null,c)}var b=this,c=this.store,d,e;this._removeDeselectSignals&&this._removeDeselectSignals();c&&c.notify?(d=k.before(c,"notify",function(b,c){b||a(b,c,"deselect")}),e=k.after(c,"notify",function(b,
c){a(b,c,"select")},!0),this._removeDeselectSignals=function(){d.remove();e.remove()}):(d=k.before(this,"removeRow",function(a,b){var c;b||(c=this.row(a))&&c.id in this.selection&&this.deselect(c)}),this._removeDeselectSignals=function(){d.remove()})},allowSelect:function(a){return!0},_selectionEventQueue:function(a,b){var c=this,d="dgrid-"+(a?"select":"deselect"),e=this[d],f=this._selectionTriggerEvent;f&&(f=f.type);if(e)return e;setTimeout(this._fireSelectionEvent=function(){if(e){var a={bubbles:!0,
grid:c};f&&(a.parentType=f);a[b]=e;h.emit(c.contentNode,d,a);e=null;delete c[d]}},0);return e=this[d]=[]},select:function(a,b,c){void 0===c&&(c=!0);a.element||(a=this.row(a));if(!1===c||this.allowSelect(a)){var d=this.selection,e=d[a.id];null===c&&(c=!e);var f=a.element;!c&&!this.allSelected?delete this.selection[a.id]:d[a.id]=c;f&&(c?n(f,".dgrid-selected.ui-state-active"):n(f,"!dgrid-selected!ui-state-active"));c!=e&&f&&this._selectionEventQueue(c,"rows").push(a);if(b){b.element||(b=this.row(b));
b=b.element;d=a.element;for(d=b&&(b.compareDocumentPosition?2==b.compareDocumentPosition(d):b.sourceIndex>d.sourceIndex)?"down":"up";a.element!=b&&(a=this[d](a));)this.select(a,null,c)}}},deselect:function(a,b){this.select(a,b,!1)},clearSelection:function(a,b){this.allSelected=!1;for(var c in this.selection)a!==c&&this.deselect(c);b||(this._lastSelected=null)},selectAll:function(){this.allSelected=!0;this.selection={};for(var a in this._rowIdToObject){var b=this.row(this._rowIdToObject[a]);this.select(b.id)}},
isSelected:function(a){if("undefined"===typeof a||null===a)return!1;a.element||(a=this.row(a));return a.id in this.selection?!!this.selection[a.id]:this.allSelected&&(!a.data||this.allowSelect(a))},refresh:function(){this.deselectOnRefresh&&(this.clearSelection(),this._fireSelectionEvent&&this._fireSelectionEvent());this._lastSelected=null;return this.inherited(arguments)},renderArray:function(){var a=this,b=this.inherited(arguments);w.when(b,function(b){var d=a.selection,e,f,g;for(e=0;e<b.length;e++)f=
a.row(b[e]),(g=f.id in d?d[f.id]:a.allSelected)&&a.select(f,null,g)});return b}})});
//@ sourceMappingURL=Selection.js.map