//>>built
define("dojo/touch","./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(C,r,s,D,E,g,n,p,t,c){function f(a,d,b){return u&&b?function(a,d){return g(a,b,d)}:q?function(b,c){var e=g(b,d,c),F=g(b,a,function(a){(!k||(new Date).getTime()>k+1E3)&&c.call(this,a)});return{remove:function(){e.remove();F.remove()}}}:function(b,d){return g(b,a,d)}}function G(a){do if(a.dojoClick)return a;while(a=a.parentNode)}function v(a,d,b){var h=G(a.target);
if(e=!a.target.disabled&&h&&h.dojoClick){var f="useTarget"==e;l=f?h:a.target;f&&a.preventDefault();w=a.touches?a.touches[0].pageX:a.clientX;x=a.touches?a.touches[0].pageY:a.clientY;y=("object"==typeof e?e.x:"number"==typeof e?e:0)||4;z=("object"==typeof e?e.y:"number"==typeof e?e:0)||4;if(!A){A=!0;var k=function(a){e=f?s.isDescendant(c.doc.elementFromPoint(a.changedTouches?a.changedTouches[0].pageX:a.clientX,a.changedTouches?a.changedTouches[0].pageY:a.clientY),l):e&&a.target==l&&Math.abs((a.changedTouches?
a.changedTouches[0].pageX:a.clientX)-w)<=y&&Math.abs((a.changedTouches?a.changedTouches[0].pageY:a.clientY)-x)<=z};c.doc.addEventListener(d,function(a){k(a);f&&a.preventDefault()},!0);c.doc.addEventListener(b,function(a){k(a);if(e){B=(new Date).getTime();var b=f?l:a.target;"LABEL"===b.tagName&&(b=s.byId(b.getAttribute("for"))||b);setTimeout(function(){g.emit(b,"click",{bubbles:!0,cancelable:!0,_dojo_click:!0})},0)}},!0);a=function(a){c.doc.addEventListener(a,function(b){!b._dojo_click&&((new Date).getTime()<=
B+1E3&&!("INPUT"==b.target.tagName&&D.contains(b.target,"dijitOffScreen")))&&(b.stopPropagation(),b.stopImmediatePropagation&&b.stopImmediatePropagation(),"click"==a&&(("INPUT"!=b.target.tagName||"radio"==b.target.type||"checkbox"==b.target.type)&&"TEXTAREA"!=b.target.tagName&&"AUDIO"!=b.target.tagName&&"VIDEO"!=b.target.tagName)&&b.preventDefault())},!0)};a("click");a("mousedown");a("mouseup")}}}var q=n("touch"),m=5>n("ios"),u=navigator.msPointerEnabled,A,e,l,w,x,y,z,B,k,h;q&&(u?t(function(){c.doc.addEventListener("MSPointerDown",
function(a){v(a,"MSPointerMove","MSPointerUp")},!0)}):t(function(){function a(a){var b=E.delegate(a,{bubbles:!0});6<=n("ios")&&(b.touches=a.touches,b.altKey=a.altKey,b.changedTouches=a.changedTouches,b.ctrlKey=a.ctrlKey,b.metaKey=a.metaKey,b.shiftKey=a.shiftKey,b.targetTouches=a.targetTouches);return b}h=c.body();c.doc.addEventListener("touchstart",function(a){k=(new Date).getTime();var b=h;h=a.target;g.emit(b,"dojotouchout",{relatedTarget:h,bubbles:!0});g.emit(h,"dojotouchover",{relatedTarget:b,
bubbles:!0});v(a,"touchmove","touchend")},!0);g(c.doc,"touchmove",function(d){k=(new Date).getTime();var b=c.doc.elementFromPoint(d.pageX-(m?0:c.global.pageXOffset),d.pageY-(m?0:c.global.pageYOffset));b&&(h!==b&&(g.emit(h,"dojotouchout",{relatedTarget:b,bubbles:!0}),g.emit(b,"dojotouchover",{relatedTarget:h,bubbles:!0}),h=b),g.emit(b,"dojotouchmove",a(d))||d.preventDefault())});g(c.doc,"touchend",function(d){k=(new Date).getTime();var b=c.doc.elementFromPoint(d.pageX-(m?0:c.global.pageXOffset),d.pageY-
(m?0:c.global.pageYOffset))||c.body();g.emit(b,"dojotouchend",a(d))})}));r={press:f("mousedown","touchstart","MSPointerDown"),move:f("mousemove","dojotouchmove","MSPointerMove"),release:f("mouseup","dojotouchend","MSPointerUp"),cancel:f(p.leave,"touchcancel",q?"MSPointerCancel":null),over:f("mouseover","dojotouchover","MSPointerOver"),out:f("mouseout","dojotouchout","MSPointerOut"),enter:p._eventHandler(f("mouseover","dojotouchover","MSPointerOver")),leave:p._eventHandler(f("mouseout","dojotouchout",
"MSPointerOut"))};return C.touch=r});
//@ sourceMappingURL=touch.js.map