//>>built
define("dojorama/layers/nls/d08_pt-pt",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"Do,Sg,Te,Qu,Qi,Sx,Sb".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dia da semana","dateFormatItem-yQQQ":"QQQ 'de' y","dateFormatItem-yMEd":"E, dd/MM/yyyy","dateFormatItem-MMMEd":"E, d/MM",eraNarrow:["a.C.","d.C."],"days-format-short":"Do,Sg,Te,Qu,Qi,Sx,Sb".split(","),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d 'de' MMMM 'de' y","months-format-wide":"Janeiro,Fevereiro,Mar\u00e7o,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro".split(","),"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"a.m.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"dd/MM/yyyy","field-era":"Era","dateFormatItem-yM":"MM/yyyy","months-standAlone-wide":"Janeiro,Fevereiro,Mar\u00e7o,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro".split(","),
"timeFormat-short":"HH:mm","quarters-format-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"timeFormat-long":"HH:mm:ss z","field-year":"Ano","dateFormatItem-yMMM":"MM/y","dateFormatItem-yQ":"QQQ 'de' yyyy","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Hora","months-format-abbr":"Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez".split(","),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Hoje",
"field-day-relative+1":"Amanh\u00e3","dateFormatItem-H":"HH","months-standAlone-abbr":"Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez".split(","),"quarters-format-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-standAlone-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"dateFormatItem-M":"L","days-standAlone-wide":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),
"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],eraAbbr:["a.C.","d.C."],"field-minute":"Minuto","field-dayperiod":"Per\u00edodo do dia","days-standAlone-abbr":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Ontem",
"dateFormatItem-h":"h a","dateTimeFormat-long":"{1} \u00e0s {0}","dayPeriods-format-narrow-am":"a.m.","dateFormatItem-MMMd":"d/MM","dateFormatItem-MEd":"E, dd/MM","dateTimeFormat-full":"{1} \u00e0s {0}","field-day":"Dia","days-format-wide":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),"field-zone":"Fuso hor\u00e1rio","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),
"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"p.m.","days-format-abbr":"Domingo,Segunda-feira,Ter\u00e7a-feira,Quarta-feira,Quinta-feira,Sexta-feira,S\u00e1bado".split(","),"dateFormatItem-yMMMd":"d/MM/y",eraNames:["Antes de Cristo","Ano do Senhor"],"days-format-narrow":"D,S,T,Q,Q,S,S".split(","),"days-standAlone-narrow":"D,S,T,Q,Q,S,S".split(","),"dateFormatItem-MMM":"LLL","field-month":"M\u00eas",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy","field-second":"Segundo","dateFormatItem-yMMMEd":"E, d/MM/y","dateFormatItem-Ed":"E, d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Semana","dateFormat-medium":"dd/MM/yyyy","dayPeriods-format-narrow-pm":"p.m.","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss",
"dateFormatItem-hms":"h:mm:ss a","dateFormatItem-yyMMMEd":"E, d/MM/yy","dayPeriods-format-wide-morning":"manh\u00e3","dayPeriods-format-wide-noon":"meio-dia","dateFormatItem-MMdd":"dd/MM","dateFormatItem-yyQ":"QQQ 'de' yy","field-day-relative+2":"Depois de amanh\u00e3","dateFormatItem-HHmmss":"HH:mm:ss","dateFormatItem-yyyyMMM":"MMM 'de' y","dateFormatItem-yyMMM":"MM/yy","dayPeriods-format-wide-night":"noite","dateFormatItem-yyMMMd":"d/MM/yy","field-day-relative+-2":"Anteontem","dateFormatItem-yyyyMM":"MM/yyyy",
"field-year-relative+-1":"Ano passado","field-month-relative+-1":"M\u00eas passado","dateFormatItem-yyMM":"MM/yy","dateFormatItem-HHmm":"HH:mm","dayPeriods-format-wide-afternoon":"tarde","field-month-relative+0":"Este m\u00eas","field-month-relative+1":"Pr\u00f3ximo m\u00eas","field-year-relative+0":"Este ano","field-week-relative+-1":"Semana passada","field-year-relative+1":"Pr\u00f3ximo ano","field-week-relative+0":"Esta semana","field-week-relative+1":"Pr\u00f3xima semana","dayPeriods-standAlone-abbr-pm":"p.m.",
"dayPeriods-standAlone-abbr-am":"a.m.","dayPeriods-standAlone-wide-pm":"p.m.","dateFormatItem-yMMMMEd":"E, d 'de' MMMM 'de' y","dayPeriods-standAlone-wide-am":"a.m.","dateFormatItem-yMMMM":"MMMM 'de' y","dateFormatItem-yMMMMd":"d 'de' MMMM 'de' y","dateFormatItem-MMMMEd":"E, d 'de' MMMM","dateFormatItem-MMMMd":"d 'de' MMMM"}});