//>>built
define("dojorama/layers/nls/d08_nb",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"months-format-narrow":"JFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"ukedag","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E d.MM.y","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"E d. MMM",eraNarrow:["f.Kr.","e.Kr."],"days-format-short":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d. MMMM y","months-format-wide":"januar februar mars april mai juni juli august september oktober november desember".split(" "),"dateTimeFormat-medium":"{0} {1}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d. MMMM y","dateFormatItem-Md":"d.M.","dayPeriods-format-abbr-am":"a.m.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"d.M.y","field-era":"tidsalder","dateFormatItem-yM":"M y","months-standAlone-wide":"januar februar mars april mai juni juli august september oktober november desember".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"HH:mm:ss z","field-year":"\u00e5r","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"time","months-format-abbr":"jan. feb. mars apr. mai juni juli aug. sep. okt. nov. des.".split(" "),"timeFormat-full":"'kl'. HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"i dag","field-day-relative+1":"i morgen",
"dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"jan feb mar apr mai jun jul aug sep okt nov des".split(" "),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["K1",
"K2","K3","K4"],eraAbbr:["f.Kr.","e.Kr."],"field-minute":"minutt","field-dayperiod":"AM/PM","days-standAlone-abbr":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"i g\u00e5r","dateFormatItem-h":"h a","dateTimeFormat-long":"{0} {1}","dayPeriods-format-narrow-am":"a","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E d.M","dateTimeFormat-full":"{0} {1}","field-day":"dag","days-format-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),
"field-zone":"sone","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"JFMAMJJASOND".split(""),"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"p.m.","days-format-abbr":"s\u00f8n. man. tir. ons. tor. fre. l\u00f8r.".split(" "),eraNames:["f.Kr.","e.Kr."],"dateFormatItem-yMMMd":"d. MMM y","days-format-narrow":"SMTOTFL".split(""),"days-standAlone-narrow":"SMTOTFL".split(""),
"dateFormatItem-MMM":"LLL","field-month":"m\u00e5ned","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd.MM.yy","field-second":"sekund","dateFormatItem-yMMMEd":"E d. MMM y","dateFormatItem-Ed":"E d.","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"uke","dateFormat-medium":"d. MMM y","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{0} {1}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-yMM":"MM.y","dateFormatItem-MMdd":"d.M.","field-day-relative+2":"i overmorgen","field-day-relative+-2":"i forg\u00e5rs","dateFormatItem-yMMMM":"MMMM y","field-year-relative+-1":"I fjor","field-month-relative+-1":"Sist m\u00e5ned","field-month-relative+0":"Denne m\u00e5neden","field-month-relative+1":"Neste m\u00e5ned","field-year-relative+0":"Dette \u00e5ret","field-week-relative+-1":"Sist uke",
"field-year-relative+1":"Neste \u00e5r","field-week-relative+0":"Denne uken","field-week-relative+1":"Neste uke"}});
//@ sourceMappingURL=d08_nb.js.map