//>>built
define("dojorama/layers/nls/d08_es-es",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"DLMXJVS".split(""),"months-format-narrow":"EFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1T","2T","3T","4T"],"field-weekday":"d\u00eda de la semana","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"EEE, d/M/y","dateFormatItem-GyMMMEd":"E, d 'de' MMMM 'de' y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["a.C.","d.C."],"days-format-short":"DLMXJVS".split(""),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d 'de' MMMM 'de' y","months-format-wide":"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"d/M/y","field-era":"era","dateFormatItem-yM":"M/y","months-standAlone-wide":"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1er trimestre","2\u00ba trimestre","3er trimestre","4\u00ba trimestre"],"dateFormatItem-yQQQQ":"QQQQ 'de' y","timeFormat-long":"HH:mm:ss z","field-year":"a\u00f1o","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"hora","months-format-abbr":"ene feb mar abr may jun jul ago sep oct nov dic".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"hoy",
"field-day-relative+1":"ma\u00f1ana","dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"ene feb mar abr mayo jun jul ago sep oct nov dic".split(" "),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1.er trimestre","2.\u00ba trimestre","3.er trimestre","4.\u00ba trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),"timeFormat-medium":"HH:mm:ss",
"dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["a.C.","d.C."],"field-minute":"minuto","field-dayperiod":"periodo del d\u00eda","days-standAlone-abbr":"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1T","2T","3T","4T"],"field-day-relative+-1":"ayer","dateFormatItem-h":"hh a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, d/M",
"dateTimeFormat-full":"{1} {0}","field-day":"d\u00eda","days-format-wide":"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),"field-zone":"zona","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"EFMAMJJASOND".split(""),"dateFormatItem-hm":"hh:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),
eraNames:["antes de Cristo","anno D\u00f3mini"],"dateFormatItem-yMMMd":"d MMM y","days-format-narrow":"DLMXJVS".split(""),"days-standAlone-narrow":"DLMXJVS".split(""),"dateFormatItem-MMM":"LLL","field-month":"mes","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy","field-second":"segundo","dateFormatItem-yMMMEd":"EEE, d 'de' MMMM 'de' y",
"dateFormatItem-Ed":"E d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"semana","dateFormat-medium":"dd/MM/y","dayPeriods-format-narrow-pm":"PM","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-yMM":"MM/y","dateFormatItem-MMMdd":"dd-MMM","dateFormatItem-MMdd":"dd/MM","field-day-relative+2":"pasado ma\u00f1ana","dateFormatItem-MMMMd":"d 'de' MMMM","field-day-relative+-2":"antes de ayer",
"dateFormatItem-yMMMM":"MMMM 'de' y","field-year-relative+-1":"el a\u00f1o pasado","field-month-relative+-1":"el mes pasado","dateFormatItem-MMd":"d/MM","field-month-relative+0":"este mes","field-month-relative+1":"el pr\u00f3ximo mes","field-year-relative+0":"este a\u00f1o","field-week-relative+-1":"la semana pasada","field-year-relative+1":"el pr\u00f3ximo a\u00f1o","field-week-relative+0":"esta semana","field-week-relative+1":"la pr\u00f3xima semana"}});
//@ sourceMappingURL=d08_es-es.js.map