//>>built
define("dojorama/layers/nls/d08_hu",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"V H K Sze Cs P Szo".split(" "),"months-format-narrow":"J F M \u00c1 M J J \u00c1 Sz O N D".split(" "),"quarters-standAlone-narrow":["1.","2.","3.","4."],"field-weekday":"h\u00e9t napja","dateFormatItem-yQQQ":"y. QQQ","dateFormatItem-yMEd":"y.MM.dd., E","dateFormatItem-GyMMMEd":"G y. MMM d., E","dateFormatItem-MMMEd":"MMM d., E",eraNarrow:["ie.","isz."],"days-format-short":"V H K Sze Cs P Szo".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"y. MMMM d.","months-format-wide":"janu\u00e1r febru\u00e1r m\u00e1rcius \u00e1prilis m\u00e1jus j\u00fanius j\u00falius augusztus szeptember okt\u00f3ber november december".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"du.","dateFormat-full":"y. MMMM d., EEEE","dateFormatItem-Md":"M. d.","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"y.MM.dd.","field-era":"\u00e9ra","dateFormatItem-yM":"y.M.",
"months-standAlone-wide":"janu\u00e1r febru\u00e1r m\u00e1rcius \u00e1prilis m\u00e1jus j\u00fanius j\u00falius augusztus szeptember okt\u00f3ber november december".split(" "),"timeFormat-short":"H:mm","quarters-format-wide":["I. negyed\u00e9v","II. negyed\u00e9v","III. negyed\u00e9v","IV. negyed\u00e9v"],"dateFormatItem-yQQQQ":"y. QQQQ","timeFormat-long":"H:mm:ss z","field-year":"\u00e9v","dateFormatItem-yMMM":"y. MMM","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"\u00f3ra","months-format-abbr":"jan. febr. m\u00e1rc. \u00e1pr. m\u00e1j. j\u00fan. j\u00fal. aug. szept. okt. nov. dec.".split(" "),
"timeFormat-full":"H:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"ma","field-day-relative+1":"holnap","dateFormatItem-GyMMMd":"G y. MMM d.","dateFormatItem-H":"H","months-standAlone-abbr":"jan. febr. m\u00e1rc. \u00e1pr. m\u00e1j. j\u00fan. j\u00fal. aug. szept. okt. nov. dec.".split(" "),"quarters-format-abbr":["N1","N2","N3","N4"],"quarters-standAlone-wide":["1. negyed\u00e9v","2. negyed\u00e9v","3. negyed\u00e9v","4. negyed\u00e9v"],"dateFormatItem-Gy":"G y",
"dateFormatItem-M":"L","days-standAlone-wide":"vas\u00e1rnap h\u00e9tf\u0151 kedd szerda cs\u00fct\u00f6rt\u00f6k p\u00e9ntek szombat".split(" "),"timeFormat-medium":"H:mm:ss","dateFormatItem-Hm":"H:mm","quarters-standAlone-abbr":["N1","N2","N3","N4"],eraAbbr:["i. e.","i. sz."],"field-minute":"perc","field-dayperiod":"napszak","days-standAlone-abbr":"V H K Sze Cs P Szo".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"tegnap",
"dateFormatItem-h":"a h","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"de.","dateFormatItem-MMMd":"MMM d.","dateFormatItem-MEd":"M. d., E","dateTimeFormat-full":"{1} {0}","field-day":"nap","days-format-wide":"vas\u00e1rnap h\u00e9tf\u0151 kedd szerda cs\u00fct\u00f6rt\u00f6k p\u00e9ntek szombat".split(" "),"field-zone":"id\u0151z\u00f3na","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"J F M \u00c1 M J J A Sz O N D".split(" "),
"dateFormatItem-hm":"a h:mm","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"V H K Sze Cs P Szo".split(" "),eraNames:["id\u0151sz\u00e1m\u00edt\u00e1sunk el\u0151tt","id\u0151sz\u00e1m\u00edt\u00e1sunk szerint"],"dateFormatItem-yMMMd":"y. MMM d.","days-format-narrow":"V H K Sz Cs P Sz".split(" "),"days-standAlone-narrow":"V H K Sz Cs P Sz".split(" "),"dateFormatItem-MMM":"LLL","field-month":"h\u00f3nap",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"de.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"y.MM.dd.","field-second":"m\u00e1sodperc","dateFormatItem-yMMMEd":"y. MMM d., E","dateFormatItem-Ed":"d., E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"h\u00e9t","dateFormat-medium":"y.MM.dd.","dayPeriods-format-narrow-pm":"du.","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"H:mm:ss",
"dateFormatItem-hms":"a h:mm:ss","dateFormatItem-GyMMM":"G y. MMM","field-day-relative+2":"holnaput\u00e1n","dateFormatItem-MMMMd":"MMMM d.","field-day-relative+-2":"tegnapel\u0151tt","dateFormatItem-yMMMM":"y. MMMM","field-year-relative+-1":"El\u0151z\u0151 \u00e9v","field-month-relative+-1":"El\u0151z\u0151 h\u00f3nap","field-month-relative+0":"Ez a h\u00f3nap","field-month-relative+1":"K\u00f6vetkez\u0151 h\u00f3nap","field-year-relative+0":"Ez az \u00e9v","field-week-relative+-1":"El\u0151z\u0151 h\u00e9t",
"field-year-relative+1":"K\u00f6vetkez\u0151 \u00e9v","dateFormatItem-mmss":"mm:ss","field-week-relative+0":"Ez a h\u00e9t","field-week-relative+1":"K\u00f6vetkez\u0151 h\u00e9t"}});
//@ sourceMappingURL=d08_hu.js.map