//>>built
define("dojo/nls/dojo_pt-pt",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"Do Sg Te Qu Qi Sx Sb".split(" "),"months-format-narrow":"JFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dia da semana","dateFormatItem-yQQQ":"QQQQ 'de' y","dateFormatItem-yMEd":"E, dd/MM/y","dateFormatItem-GyMMMEd":"E, d 'de' MMM 'de' y G","dateFormatItem-MMMEd":"E, d/MM",eraNarrow:["a.C.","d.C."],"days-format-short":"Do Sg Te Qu Qi Sx Sb".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d 'de' MMMM 'de' y","months-format-wide":"Janeiro Fevereiro Mar\u00e7o Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro".split(" "),"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"a.m.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"dd/MM/y","field-era":"Era","dateFormatItem-yM":"MM/y","months-standAlone-wide":"Janeiro Fevereiro Mar\u00e7o Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"dateFormatItem-yQQQQ":"QQQQ 'de' y","timeFormat-long":"HH:mm:ss z","field-year":"Ano","dateFormatItem-yMMM":"MM/y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hora","months-format-abbr":"Jan Fev Mar Abr Mai Jun Jul Ago Set Out Nov Dez".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Hoje",
"field-day-relative+1":"Amanh\u00e3","dateFormatItem-GyMMMd":"d 'de' MMM 'de' y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Jan Fev Mar Abr Mai Jun Jul Ago Set Out Nov Dez".split(" "),"quarters-format-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-standAlone-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"Domingo Segunda-feira Ter\u00e7a-feira Quarta-feira Quinta-feira Sexta-feira S\u00e1bado".split(" "),
"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],eraAbbr:["a.C.","d.C."],"field-minute":"Minuto","field-dayperiod":"Per\u00edodo do dia","days-standAlone-abbr":"Domingo Segunda-feira Ter\u00e7a-feira Quarta-feira Quinta-feira Sexta-feira S\u00e1bado".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Ontem",
"dateFormatItem-h":"h a","dateTimeFormat-long":"{1} '\u00e0s' {0}","dayPeriods-format-narrow-am":"a.m.","dateFormatItem-MMMd":"d/MM","dateFormatItem-MEd":"E, dd/MM","dateTimeFormat-full":"{1} '\u00e0s' {0}","field-day":"Dia","days-format-wide":"Domingo Segunda-feira Ter\u00e7a-feira Quarta-feira Quinta-feira Sexta-feira S\u00e1bado".split(" "),"field-zone":"Fuso hor\u00e1rio","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"JFMAMJJASOND".split(""),
"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"p.m.","days-format-abbr":"Domingo Segunda-feira Ter\u00e7a-feira Quarta-feira Quinta-feira Sexta-feira S\u00e1bado".split(" "),eraNames:["Antes de Cristo","Ano do Senhor"],"dateFormatItem-yMMMd":"d/MM/y","days-format-narrow":"DSTQQSS".split(""),"days-standAlone-narrow":"DSTQQSS".split(""),"dateFormatItem-MMM":"LLL","field-month":"M\u00eas","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})",
"dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy","field-second":"Segundo","dateFormatItem-yMMMEd":"E, d/MM/y","dateFormatItem-Ed":"E, d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Semana","dateFormat-medium":"dd/MM/y","dayPeriods-format-narrow-pm":"p.m.","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM 'de' y G",
"dateFormatItem-yMM":"MM/y","dayPeriods-format-wide-morning":"manh\u00e3","dayPeriods-format-wide-noon":"meio-dia","dateFormatItem-MMdd":"dd/MM","field-day-relative+2":"Depois de amanh\u00e3","dateFormatItem-HHmmss":"HH:mm:ss","dayPeriods-format-wide-night":"noite","field-day-relative+-2":"Anteontem","field-year-relative+-1":"Ano passado","field-month-relative+-1":"M\u00eas passado","dateFormatItem-HHmm":"HH:mm","dayPeriods-format-wide-afternoon":"tarde","field-month-relative+0":"Este m\u00eas","field-month-relative+1":"Pr\u00f3ximo m\u00eas",
"field-year-relative+0":"Este ano","field-week-relative+-1":"Semana passada","field-year-relative+1":"Pr\u00f3ximo ano","field-week-relative+0":"Esta semana","field-week-relative+1":"Pr\u00f3xima semana","dayPeriods-standAlone-abbr-pm":"p.m.","dayPeriods-standAlone-abbr-am":"a.m.","dayPeriods-standAlone-wide-pm":"p.m.","dateFormatItem-yMMMMEd":"E, d 'de' MMMM 'de' y","dayPeriods-standAlone-wide-am":"a.m.","dateFormatItem-yMMMEEEEd":"EEEE, d/MM/y","dateFormatItem-yMMMM":"MMMM 'de' y","dateFormatItem-yMMMMd":"d 'de' MMMM 'de' y",
"dateFormatItem-MMMMEd":"E, d 'de' MMMM","dateFormatItem-MMMMd":"d 'de' MMMM"},"dojorama/model/nls/ReleaseModel":{titleMissing:"Title required",titleInvalid:"Invalid title"},"dojorama/ui/_global/widget/nls/FooterWidget":{},"dojorama/ui/_global/widget/nls/NavigationWidget":{labelHome:"Dojorama",labelStorage:"Storage",labelReleaseIndex:"Releases"}});
//@ sourceMappingURL=dojo_pt-pt.js.map