//>>built
require({cache:{"dojomat/_AppAware":function(){define(["dojo/_base/declare","dojo/topic"],function(f,c){return f([],{setCss:function(b,a){c.publish("dojomat/_AppAware/css",{css:b,media:a})},setTitle:function(b){c.publish("dojomat/_AppAware/title",{title:b})},setNotification:function(b,a){c.publish("dojomat/_AppAware/notification",{message:b,type:a})},handleNotFound:function(){c.publish("dojomat/_AppAware/not-found",{})},handleError:function(b){c.publish("dojomat/_AppAware/error",b)}})})},"dojomat/_StateAware":function(){define(["dojo/_base/declare",
"dojo/topic"],function(f,c){return f([],{pushState:function(b){c.publish("dojomat/_StateAware/push-state",{url:b});document.body.scrollTop&&(document.body.scrollTop=0);document.documentElement.scrollTop&&(document.documentElement.scrollTop=0)}})})},"dojomat/Application":function(){define("routed/Request routed/Router dojo/has!dijit?dijit/registry:mijit/registry dojo/_base/declare dojo/_base/lang dojo/has dojo/on dojo/dom dojo/query dojo/topic dojo/dom-construct ./Notification ./Session dojo/domReady!".split(" "),
function(f,c,b,a,d,e,g,h,k,l,m,n,p){var q=function(){e.add("native-history-state",function(a){return void 0!==a.history&&void 0!==a.history.pushState})},r=function(){e.add("native-localstorage",function(a){var b=!1;try{b=void 0!==a.localStorage&&void 0!==a.localStorage.setItem}catch(d){}return b})};return a([],{lastRequest:null,router:new c,session:new p,notification:new n,cssNodes:{},domNode:null,constructor:function(a,b){d.mixin(this,a);this.domNode=h.byId(b)},run:function(){q();r();this.setSubscriptions();
this.registerPopState();this.handleState()},clearCss:function(){for(var a in this.cssNodes)this.cssNodes.hasOwnProperty(a)&&m.destroy(this.cssNodes[a]);this.cssNodes={}},setCss:function(a,b){a=a||"";b=b||"all";this.cssNodes[b]||(this.cssNodes[b]=m.create("style",{media:b},k("head")[0],"last"));this.cssNodes[b].styleSheet?this.cssNodes[b].styleSheet.cssText=a:this.cssNodes[b].innerHTML=a},prepareDomNode:function(){var a,d=this.domNode.id;b.byId(d)&&(a=m.create("div",{id:"new-dojomat-"+d+"-node"},b.byId(d).domNode,
"after"),b.byId(d).destroyRecursive(),this.domNode=a,this.domNode.id=d)},handleState:function(a,b,d){var c;return function(){var e=this,k=arguments,g=d&&!c;clearTimeout(c);c=setTimeout(function(){c=null;d||a.apply(e,k)},b);g&&a.apply(e,k)}}(function(){var a=null,b=new f(window.location.href);if(!this.lastRequest||!this.lastRequest.isSame(window.location.href))this.lastRequest=b,this.router.route(b),(a=this.router.getCurrentRoute())?a.run(b):this.makeNotFoundPage()},500,!0),registerPopState:function(){g(window,
"popstate",d.hitch(this,function(a){this.handleState()}))},makePage:function(a,b,c){var e=function(b){this.clearCss();this.prepareDomNode();b=new b({request:a,router:this.router,session:this.session,notification:this.notification.get()},this.domNode);this.notification.clear();b.startup()};c.length?require(c,d.hitch(this,function(){require([b],d.hitch(this,e))})):require([b],d.hitch(this,e))},makeNotFoundPage:function(){alert("Page not found")},makeErrorPage:function(a){alert("An error has occured")},
setSubscriptions:function(){l.subscribe("dojomat/_AppAware/css",d.hitch(this,function(a){this.setCss(a.css,a.media)}));l.subscribe("dojomat/_AppAware/title",d.hitch(this,function(a){window.document.title=a.title}));l.subscribe("dojomat/_AppAware/notification",d.hitch(this,function(a){this.notification.set(a)}));l.subscribe("dojomat/_AppAware/error",d.hitch(this,function(a){this.makeErrorPage(a)}));l.subscribe("dojomat/_AppAware/not-found",d.hitch(this,function(){this.makeNotFoundPage()}));l.subscribe("dojomat/_StateAware/push-state",
d.hitch(this,function(a){this.pushState(a)}))},pushState:function(a){e("native-history-state")?(history.pushState({},"",a.url),this.handleState()):window.location=a.url}})})},"routed/Request":function(){define([],function(){var f=function(a){return a.replace(/^\s+|\s+$/g,"")},c=function(a){a=a.split("?")[0].split("#")[0].replace(/\w+:\/\/[\w\d\._\-]*:?\d*/,"");return a.match(/^\//)?a:""},b=function(a){var b={};a=(a.split("?")[1]||"").split("#")[0];var c=null,g=null,h=null;if(a){c=a.split("\x26");
for(g=0;g<c.length;g+=1)h=c[g].split("\x3d"),b[f(decodeURIComponent(h[0]))]=f(decodeURIComponent(h[1]))}return b};return function(a){var d=c(f(decodeURIComponent(a))),e=(a.split("?")[1]||"").split("#")[0],g=b(a),h={};return{getPathname:function(){return d},getQueryString:function(){return e},getQueryParams:function(){return g},getPathParams:function(){return h},setPathParam:function(a,b){h[a]=b},getPathParam:function(a){return h[a]||null},getQueryParam:function(a){return g[a]||null},isSame:function(a){var e;
if(d!==c(a))return!1;a=b(a);for(e in g)if(g.hasOwnProperty(e)&&(void 0===a[e]||a[e]!==g[e]))return!1;for(e in a)if(a.hasOwnProperty(e)&&(void 0===g[e]||a[e]!==g[e]))return!1;return!0},debug:function(){console.log("getPathname(): ",this.getPathname());console.log("getQueryParams(): ",this.getQueryParams());console.log("getPathParams(): ",this.getPathParams())}}}})},"routed/Router":function(){define(["./Route"],function(f){return function(c){var b=null,a=[],d=null;for(d in c)c.hasOwnProperty(d)&&(a[d]=
c[d]);return{addRoute:function(b,d){a[b]=d},route:function(d){var c,f,k=[];for(c in a)if(a.hasOwnProperty(c)&&(k=a[c].match(d.getPathname()))){b=c;for(f in k)k.hasOwnProperty(f)&&d.setPathParam(f,k[f]);return d}return null},getCurrentRoute:function(){return a[b]||null},getCurrentRouteName:function(){return b},getRoute:function(b){return a[b]||void 0}}}})},"routed/Route":function(){define([],function(){return function(f,c){return{run:c,match:function(b){b=b.replace(/^\/|\/$/g,"").split("/");var a=
f.replace(/^\/|\/$/g,"").split("/"),d={},c=0,g=null;if(b.length!==a.length)return!1;for(c=0;c<b.length;c+=1)if(a[c].match(/^\:(\w*)$/))g=a[c].replace(/^\:(\w*)$/,"$1"),d[g]=decodeURIComponent(b[c]);else if(a[c]!==decodeURIComponent(b[c]))return!1;return d},assemble:function(b,a){for(var c="",e=null,e=null,g=0,h=f.replace(/^\/|\/$/g,"").split("/"),k=null,l=[],g=0;g<h.length;g+=1){if(h[g].match(/^\:(\w*)$/)){e=h[g].replace(/^\:(\w*)$/,"$1");if(void 0===b[e])throw Error('Missing param "'+e+'" for schema: "'+
f+'"');e=b[e]}else e=h[g];c+="/"+e}f.match(/\/$/)&&(c+="/");if(a){for(k in a)a.hasOwnProperty(k)&&l.push(k+"\x3d"+encodeURIComponent(a[k]));l.length&&(c+="?"+l.join("\x26"))}return c}}}})},"dojomat/Notification":function(){define(["dojo/_base/declare","dojo/_base/json","dojo/has","dojo/cookie"],function(f,c,b,a){return f([],{id:"dojomat-notification",get:function(){return b("native-localstorage")&&b("native-history-state")?c.fromJson(localStorage.getItem(this.id)):c.fromJson(a(this.id))},clear:function(){b("native-localstorage")&&
b("native-history-state")?localStorage.removeItem(this.id):a(this.id,null,{expires:-1,path:"/"})},set:function(d){b("native-localstorage")&&b("native-history-state")?localStorage.setItem(this.id,c.toJson(d)):a(this.id,c.toJson(d),{expires:1,path:"/"})}})})},"dojomat/Session":function(){define(["dojo/_base/declare"],function(f){return f([],{props:{},get:function(c){return this.props[c]},set:function(c,b){this.props[c]=b},destroy:function(c){this.props[c]&&this.props[c].remove&&(this.props[c].remove(),
delete this.props[c]);this.props[c]&&this.props[c].destroy&&(this.props[c].destroy(),delete this.props[c])}})})},"dojomat/populateRouter":function(){define(["routed/Route","dojo/_base/lang"],function(f,c){return function(b,a){var d=null,e=function(a,c){return function(d){b.makePage(d,a,c)}};for(d in a)a.hasOwnProperty(d)&&b.router.addRoute(d,new f(a[d].schema,c.hitch(b,e(a[d].widget,a[d].layers||[]))))}})},"dojorama/routing-map":function(){define(["dojo/_base/config","require"],function(f,c){var b=
f["routing-map"].pathPrefix,a=f["routing-map"].layers||{},d=c.toAbsMid;return{home:{schema:b+"",widget:d("./ui/home/HomePage"),layers:a.home||[]},storage:{schema:b+"/storage",widget:d("./ui/storage/StoragePage"),layers:a.storage||[]},releaseIndex:{schema:b+"/releases",widget:d("./ui/release/ReleaseIndexPage"),layers:a.release||[]},releaseUpdate:{schema:b+"/release/:id",widget:d("./ui/release/ReleaseUpdatePage"),layers:a.release||[]},releaseCreate:{schema:b+"/new-release/",widget:d("./ui/release/ReleaseCreatePage"),
layers:a.release||[]}}})},"dojorama/App":function(){define("dojo/_base/declare dojo/_base/lang routed/Request dojomat/Application dojomat/populateRouter ./routing-map require dojo/domReady!".split(" "),function(f,c,b,a,d,e,g){var h=function(a){var b=a.getQueryString();a=a.getPathname()+(""!==b?"?":"")+b;window._gaq&&window._gaq.push(["_trackPageview",a])};return f([a],{constructor:function(){d(this,e);this.run()},makeNotFoundPage:function(){var a=new b(window.location.href);g(["./ui/error/NotFoundPage"],
c.hitch(this,function(b){this.clearCss();this.prepareDomNode();(new b({request:a,router:this.router},this.domNode)).startup();this.notification.clear()}));h(a)},makeErrorPage:function(a){var d=new b(window.location.href);g(["./ui/error/ErrorPage"],c.hitch(this,function(b){this.clearCss();this.prepareDomNode();(new b({request:d,router:this.router,error:a},this.domNode)).startup();this.notification.clear()}));h(d)},makePage:function(a,b,c,d){this.inherited(arguments);h(a)}})})}}});
define("dojorama/layers/app",[],1);
//@ sourceMappingURL=app.js.map