//>>built
require({cache:{"dgrid/OnDemandGrid":function(){define(["dojo/_base/declare","./Grid","./OnDemandList"],function(A,v,y){return A([v,y],{})})},"dgrid/Grid":function(){define("dojo/_base/kernel dojo/_base/declare dojo/on dojo/has put-selector/put ./List ./util/misc dojo/_base/sniff".split(" "),function(A,v,y,p,c,w,B){function C(b,d){d&&d.nodeType&&b.appendChild(d)}function D(b,d,c,e){if(this.formatter){e=this.formatter;var a=this.grid.formatterScope;c.innerHTML="string"===typeof e&&a?a[e](d,b):e(d,
b)}else null!=d&&c.appendChild(document.createTextNode(d))}var z=8>p("ie")&&!p("quirks"),E=/[^\._a-zA-Z0-9-]/g;v=v(w,{columns:null,cellNavigation:!0,tabableHeader:!0,showHeader:!0,column:function(b){return"object"!=typeof b?this.columns[b]:this.cell(b).column},listType:"grid",cell:function(b,d){if(b.column&&b.element)return b;b.target&&b.target.nodeType&&(b=b.target);var c;if(b.nodeType){do{if(this._rowIdToObject[b.id])break;var e=b.columnId;if(e){d=e;c=b;break}b=b.parentNode}while(b&&b!=this.domNode)
}if(!c&&"undefined"!=typeof d){var a=this.row(b);if(e=a&&a.element)for(var e=e.getElementsByTagName("td"),f=0;f<e.length;f++)if(e[f].columnId==d){c=e[f];break}}if(null!=b)return{row:a||this.row(b),column:d&&this.column(d),element:c}},createRowCells:function(b,d,k){var e=c("table.dgrid-row-table[role\x3dpresentation]"),a=9>p("ie")||p("quirks")?c(e,"tbody"):e,f,g,m,n,r,x,h,u,t,H;k=k||this.subRows;g=0;for(m=k.length;g<m;g++){x=k[g];f=c(a,"tr");x.className&&c(f,"."+x.className);n=0;for(r=x.length;n<r;n++){h=
x[n];u=h.id;t=h.className||h.field&&"field-"+h.field;t=c(b+(".dgrid-cell.dgrid-cell-padding"+(u?".dgrid-column-"+u:"")+(t?"."+t:"")).replace(E,"-")+"[role\x3d"+("th"===b?"columnheader":"gridcell")+"]");t.columnId=u;z?(u=c(t,"!dgrid-cell-padding div.dgrid-cell-padding"),t.contents=u):u=t;if(H=h.colSpan)t.colSpan=H;if(H=h.rowSpan)t.rowSpan=H;d(u,h);f.appendChild(t)}}return e},left:function(b,d){b.element||(b=this.cell(b));return this.cell(this._move(b,-(d||1),"dgrid-cell"))},right:function(b,d){b.element||
(b=this.cell(b));return this.cell(this._move(b,d||1,"dgrid-cell"))},renderRow:function(b,d){var k=this.createRowCells("td",function(e,a){var f=b;a.get?f=a.get(b):"field"in a&&"_item"!=a.field&&(f=f[a.field]);a.renderCell?C(e,a.renderCell(b,f,e,d)):D.call(a,b,f,e,d)},d&&d.subRows);return c("div[role\x3drow]\x3e",k)},renderHeader:function(){var b=this,d=this.headerNode,k=d.childNodes.length;for(d.setAttribute("role","row");k--;)c(d.childNodes[k],"!");k=this.createRowCells("th",function(b,a){var f=a.headerNode=
b;z&&(b=b.parentNode);var g=a.field;g&&(b.field=g);if(a.renderHeaderCell)C(f,a.renderHeaderCell(f));else if("label"in a||a.field)f.appendChild(document.createTextNode("label"in a?a.label:a.field));!1!==a.sortable&&(g&&"_item"!=g)&&(b.sortable=!0,b.className+=" dgrid-sortable")},this.subRows&&this.subRows.headerRows);this._rowIdToObject[k.id=this.id+"-header"]=this.columns;d.appendChild(k);this._sortListener&&this._sortListener.remove();this._sortListener=y(k,"click,keydown",function(c){if("click"==
c.type||32==c.keyCode||!p("opera")&&13==c.keyCode){var a=c.target,f,g,m;do if(a.sortable){m=[{attribute:f=a.field||a.columnId,descending:(g=b._sort[0])&&g.attribute==f&&!g.descending}];f={bubbles:!0,cancelable:!0,grid:b,parentType:c.type,sort:m};y.emit(c.target,"dgrid-sort",f)&&(b._sortNode=a,b.set("sort",m));break}while((a=a.parentNode)&&a!=d)}})},resize:function(){var b=this.headerNode.firstChild,d=this.contentNode,c;this.inherited(arguments);if(!p("ie")||7<p("ie")&&!p("quirks"))if(d.style.width=
"",d&&b&&(c=b.offsetWidth)!=d.offsetWidth)d.style.width=c+"px"},destroy:function(){this._destroyColumns();this._sortListener&&this._sortListener.remove();this.inherited(arguments)},_setSort:function(b,d){this.inherited(arguments);this.updateSortArrow(this._sort)},updateSortArrow:function(b,d){this._lastSortedArrow&&(c(this._lastSortedArrow,"\x3c!dgrid-sort-up!dgrid-sort-down"),c(this._lastSortedArrow,"!"),delete this._lastSortedArrow);d&&(this._sort=b);if(b[0]){var k=b[0].attribute,e=b[0].descending,
a=this._sortNode,f,g,m;delete this._sortNode;if(!a)for(m in f=this.columns,f)if(g=f[m],g.field==k){a=g.headerNode;break}a&&(a=a.contents||a,this._lastSortedArrow=c(a.firstChild,"-div.dgrid-sort-arrow.ui-icon[role\x3dpresentation]"),this._lastSortedArrow.innerHTML="\x26nbsp;",c(a,e?".dgrid-sort-down":".dgrid-sort-up"),this.resize())}},styleColumn:function(b,d){return this.addCssRule("#"+B.escapeCssIdentifier(this.domNode.id)+" .dgrid-column-"+b,d)},_configColumns:function(b,d){var c=[],e=d instanceof
Array;B.each(d,function(a,f){"string"==typeof a&&(d[f]=a={label:a});!e&&!a.field&&(a.field=f);f=a.id=a.id||(isNaN(f)?f:b+f);e&&(this.columns[f]=a);this._configColumn&&this._configColumn(a,f,d,b);a.grid=this;"function"===typeof a.init&&a.init();c.push(a)},this);return e?d:c},_destroyColumns:function(){var b=this.subRows,d=b&&b.length,c,e,a,f;this.cleanup();for(c=0;c<d;c++){e=0;for(f=b[c].length;e<f;e++)a=b[c][e],"function"===typeof a.destroy&&a.destroy()}},configStructure:function(){var b=this.subRows,
c=this._columns=this.columns;this.columns=!c||c instanceof Array?{}:c;if(b)for(c=0;c<b.length;c++)b[c]=this._configColumns(c+"-",b[c]);else this.subRows=[this._configColumns("",c)]},_getColumns:function(){return this._columns||this.columns},_setColumns:function(b){this._destroyColumns();this.subRows=null;this.columns=b;this._updateColumns()},_setSubRows:function(b){this._destroyColumns();this.subRows=b;this._updateColumns()},setColumns:function(b){A.deprecated("setColumns(...)",'use set("columns", ...) instead',
"dgrid 0.4");this.set("columns",b)},setSubRows:function(b){A.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 0.4");this.set("subRows",b)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);this._started&&(this._sort&&this._sort.length?this.updateSortArrow(this._sort):this.resize())}});v.appendIfNode=C;v.defaultRenderCell=D;return v})},"dgrid/Selection":function(){define("dojo/_base/kernel dojo/_base/declare dojo/_base/Deferred dojo/on dojo/has dojo/aspect ./List dojo/has!touch?./util/touch put-selector/put dojo/query dojo/_base/sniff".split(" "),
function(A,v,y,p,c,w,B,C,D){function z(a,b){for(var c=a.unselectable=b?"on":"",d=a.getElementsByTagName("*"),n=d.length;--n;)"INPUT"===d[n].tagName||"TEXTAREA"===d[n].tagName||(d[n].unselectable=c)}function E(a,b){var g=a.bodyNode,m=b?"text":21>c("ff")?"-moz-none":"none";d?g.style[d]=m:c("dom-selectstart")?!b&&!a._selectstartHandle?a._selectstartHandle=p(g,"selectstart",function(a){var b=a.target&&a.target.tagName;"INPUT"!==b&&"TEXTAREA"!==b&&a.preventDefault()}):b&&a._selectstartHandle&&(a._selectstartHandle.remove(),
delete a._selectstartHandle):(z(g,!b),!b&&!a._unselectableHandle?a._unselectableHandle=w.after(a,"renderRow",function(a){z(a,!0);return a}):b&&a._unselectableHandle&&(a._unselectableHandle.remove(),delete a._unselectableHandle))}c.add("mspointer",function(a,b,c){return"onmspointerdown"in c});c.add("css-user-select",function(a,b,c){a=c.style;b=["Khtml","O","ms","Moz","Webkit"];c=b.length;var d="userSelect";do if("undefined"!==typeof a[d])return d;while(c--&&(d=b[c]+"UserSelect"));return!1});c.add("dom-selectstart",
"undefined"!==typeof document.onselectstart);var b=c("mac")?"metaKey":"ctrlKey",d=c("css-user-select"),k=c("mspointer")?"MSPointerDown":"mousedown",e=c("mspointer")?"MSPointerUp":"mouseup";return v(null,{selectionDelegate:".dgrid-row",selectionEvents:k+","+e+",dgrid-cellfocusin",deselectOnRefresh:!0,allowSelectAll:!1,selection:{},selectionMode:"extended",allowTextSelection:void 0,create:function(){this.selection={};return this.inherited(arguments)},postCreate:function(){this.inherited(arguments);
var a=this.selectionMode;this.selectionMode="";this._setSelectionMode(a);this._initSelectionEvents()},destroy:function(){this.inherited(arguments);this._selectstartHandle&&this._selectstartHandle.remove();this._unselectableHandle&&this._unselectableHandle.remove();this._removeDeselectSignals&&this._removeDeselectSignals()},_setSelectionMode:function(a){a!=this.selectionMode&&(this.clearSelection(),this.selectionMode=a,this._selectionHandlerName="_"+a+"SelectionHandler",this._setAllowTextSelection(this.allowTextSelection))},
setSelectionMode:function(a){A.deprecated("setSelectionMode(...)",'use set("selectionMode", ...) instead',"dgrid 0.4");this.set("selectionMode",a)},_setAllowTextSelection:function(a){"undefined"!==typeof a?E(this,a):E(this,"none"===this.selectionMode);this.allowTextSelection=a},_handleSelect:function(a,b){if(this[this._selectionHandlerName]&&!("dgrid-cellfocusin"===a.type&&"mousedown"===a.parentType||a.type===e&&b!=this._waitForMouseUp)){this._waitForMouseUp=null;this._selectionTriggerEvent=a;if(!a.keyCode||
!a.ctrlKey||32==a.keyCode)if(!a.shiftKey&&a.type===k&&this.isSelected(b))this._waitForMouseUp=b;else this[this._selectionHandlerName](a,b);this._selectionTriggerEvent=null}},_singleSelectionHandler:function(a,c){var g=a.keyCode?a.ctrlKey:a[b];this._lastSelected===c?this.select(c,null,!g||!this.isSelected(c)):(this.clearSelection(),this.select(c),this._lastSelected=c)},_multipleSelectionHandler:function(a,c){var g=this._lastSelected,d=a.keyCode?a.ctrlKey:a[b],e;a.shiftKey||(e=d?null:!0,g=null);this.select(c,
g,e);g||(this._lastSelected=c)},_extendedSelectionHandler:function(a,c){(2===a.button?!this.isSelected(c):!(a.keyCode?a.ctrlKey:a[b]))&&this.clearSelection(null,!0);this._multipleSelectionHandler(a,c)},_toggleSelectionHandler:function(a,b){this.select(b,null,null)},_initSelectionEvents:function(){var a=this,f=this.selectionDelegate;c("touch")&&!c("mspointer")?p(this.contentNode,C.selector(f,C.tap),function(b){a._handleSelect(b,this)}):p(this.contentNode,p.selector(f,this.selectionEvents),function(b){a._handleSelect(b,
this)});this.addKeyHandler&&this.addKeyHandler(32,function(b){a._handleSelect(b,b.target)});if(this.allowSelectAll)this.on("keydown",function(c){c[b]&&(65==c.keyCode&&!/\bdgrid-input\b/.test(c.target.className))&&(c.preventDefault(),a[a.allSelected?"clearSelection":"selectAll"]())});this._setStore&&w.after(this,"_setStore",function(){a._updateDeselectionAspect()});this._updateDeselectionAspect()},_updateDeselectionAspect:function(){function a(a,c,h){a=c||a&&a[b.idProperty||"id"];if(null!=a&&(c=(a=
b.row(a))&&b.selection[a.id]))b[h](a,null,c)}var b=this,c=this.store,d,e;this._removeDeselectSignals&&this._removeDeselectSignals();c&&c.notify?(d=w.before(c,"notify",function(b,c){b||a(b,c,"deselect")}),e=w.after(c,"notify",function(b,c){a(b,c,"select")},!0),this._removeDeselectSignals=function(){d.remove();e.remove()}):(d=w.before(this,"removeRow",function(a,b){var h;b||(h=this.row(a))&&h.id in this.selection&&this.deselect(h)}),this._removeDeselectSignals=function(){d.remove()})},allowSelect:function(a){return!0},
_selectionEventQueue:function(a,b){var c=this,d="dgrid-"+(a?"select":"deselect"),e=this[d],r=this._selectionTriggerEvent;r&&(r=r.type);if(e)return e;setTimeout(this._fireSelectionEvent=function(){if(e){var a={bubbles:!0,grid:c};r&&(a.parentType=r);a[b]=e;p.emit(c.contentNode,d,a);e=null;delete c[d]}},0);return e=this[d]=[]},select:function(a,b,c){void 0===c&&(c=!0);a.element||(a=this.row(a));if(!1===c||this.allowSelect(a)){var d=this.selection,e=d[a.id];null===c&&(c=!e);var r=a.element;!c&&!this.allSelected?
delete this.selection[a.id]:d[a.id]=c;r&&(c?D(r,".dgrid-selected.ui-state-active"):D(r,"!dgrid-selected!ui-state-active"));c!=e&&r&&this._selectionEventQueue(c,"rows").push(a);if(b){b.element||(b=this.row(b));b=b.element;d=a.element;for(d=b&&(b.compareDocumentPosition?2==b.compareDocumentPosition(d):b.sourceIndex>d.sourceIndex)?"down":"up";a.element!=b&&(a=this[d](a));)this.select(a,null,c)}}},deselect:function(a,b){this.select(a,b,!1)},clearSelection:function(a,b){this.allSelected=!1;for(var c in this.selection)a!==
c&&this.deselect(c);b||(this._lastSelected=null)},selectAll:function(){this.allSelected=!0;this.selection={};for(var a in this._rowIdToObject){var b=this.row(this._rowIdToObject[a]);this.select(b.id)}},isSelected:function(a){if("undefined"===typeof a||null===a)return!1;a.element||(a=this.row(a));return a.id in this.selection?!!this.selection[a.id]:this.allSelected&&(!a.data||this.allowSelect(a))},refresh:function(){this.deselectOnRefresh&&(this.clearSelection(),this._fireSelectionEvent&&this._fireSelectionEvent());
this._lastSelected=null;return this.inherited(arguments)},renderArray:function(){var a=this,b=this.inherited(arguments);y.when(b,function(b){var c=a.selection,d,e,f;for(d=0;d<b.length;d++)e=a.row(b[d]),(f=e.id in c?c[e.id]:a.allSelected)&&a.select(e,null,f)});return b}})})},"dgrid/Keyboard":function(){define("dojo/_base/declare dojo/aspect dojo/on dojo/_base/lang dojo/has put-selector/put dojo/_base/Deferred dojo/_base/sniff".split(" "),function(A,v,y,p,c,w,B){function C(a){a.preventDefault()}var D=
{checkbox:1,radio:1,button:1},z=/\bdgrid-cell\b/,E=/\bdgrid-row\b/;c.add("dom-contains",function(a,b,c){return!!c.contains});var b=A(null,{pageSkip:10,tabIndex:0,keyMap:null,headerKeyMap:null,postMixInProperties:function(){this.inherited(arguments);this.keyMap||(this.keyMap=p.mixin({},b.defaultKeyMap));this.headerKeyMap||(this.headerKeyMap=p.mixin({},b.defaultHeaderKeyMap))},postCreate:function(){function a(b){var h=b.target;return h.type&&(!D[h.type]||32==b.keyCode)}function b(t){function d(){if(h._focusedHeaderNode=
G=e?h.headerNode.getElementsByTagName("th")[0]:h.headerNode)G.tabIndex=h.tabIndex}var e=h.cellNavigation,f=e?z:E,l=t===h.headerNode,G=t;l?(d(),v.after(h,"renderHeader",d,!0)):v.after(h,"renderArray",function(a){return B.when(a,function(a){var b=h._focusedNode||G,u;if(u=f.test(b.className))u=b,u=c("dom-contains")?t.contains(u):t.compareDocumentPosition(u)&8;if(u)return a;u=0;for(var d=t.getElementsByTagName("*"),l;l=d[u];++u)if(f.test(l.className)){b=h._focusedNode=l;break}b.tabIndex=h.tabIndex;return a})});
h._listeners.push(y(t,"mousedown",function(b){a(b)||h._focusOnNode(b.target,l,b)}));h._listeners.push(y(t,"keydown",function(b){if(!b.metaKey&&!b.altKey){var c=h[l?"headerKeyMap":"keyMap"][b.keyCode];c&&!a(b)&&c.call(h,b)}}))}this.inherited(arguments);var h=this;this.tabableHeader&&(b(this.headerNode),y(this.headerNode,"dgrid-cellfocusin",function(){h.scrollTo({x:this.scrollLeft})}));b(this.contentNode)},removeRow:function(a){if(!this._focusedNode)return this.inherited(arguments);var b=this,h=document.activeElement===
this._focusedNode,c=this[this.cellNavigation?"cell":"row"](this._focusedNode),d=c.row||c,e;a=a.element||a;if(a===d.element){e=this.down(d,!0);if(!e||e.element===a)e=this.up(d,!0);this._removedFocus={active:h,rowId:d.id,columnId:c.column&&c.column.id,siblingId:!e||e.element===a?void 0:e.id};setTimeout(function(){b._removedFocus&&b._restoreFocus(d.id)},0);this._focusedNode=null}this.inherited(arguments)},insertRow:function(a){var b=this.inherited(arguments);this._removedFocus&&!this._removedFocus.wait&&
this._restoreFocus(b);return b},_restoreFocus:function(a){var b=this._removedFocus;if((a=(a=a&&this.row(a))&&a.element&&a.id===b.rowId?a:"undefined"!==typeof b.siblingId&&this.row(b.siblingId))&&a.element){if(!a.element.parentNode.parentNode){b.wait=!0;return}a="undefined"!==typeof b.columnId?this.cell(a,b.columnId):a;b.active?this.focus(a):(w(a.element,".dgrid-focus"),a.element.tabIndex=this.tabIndex)}delete this._removedFocus},addKeyHandler:function(a,b,h){return v.after(this[h?"headerKeyMap":"keyMap"],
a,b,!0)},_focusOnNode:function(a,b,h){b="_focused"+(b?"Header":"")+"Node";var d=this[b],e=this.cellNavigation?"cell":"row",f=this[e](a),q,l,G,g,k;if(a=f&&f.element){if(this.cellNavigation){q=a.getElementsByTagName("input");k=0;for(G=q.length;k<G;k++)if(l=q[k],(-1!=l.tabIndex||"lastValue"in l)&&!l.disabled){8>c("ie")&&(l.style.position="relative");l.focus();8>c("ie")&&(l.style.position="");g=!0;break}}h=p.mixin({grid:this},h);h.type&&(h.parentType=h.type);h.bubbles||(h.bubbles=!0);d&&(w(d,"!dgrid-focus[!tabIndex]"),
8>c("ie")&&(d.style.position=""),h[e]=this[e](d),y.emit(a,"dgrid-cellfocusout",h));d=this[b]=a;h[e]=f;g||(8>c("ie")&&(a.style.position="relative"),a.tabIndex=this.tabIndex,a.focus());w(a,".dgrid-focus");y.emit(d,"dgrid-cellfocusin",h)}},focusHeader:function(a){this._focusOnNode(a||this._focusedHeaderNode,!0)},focus:function(a){this._focusOnNode(a||this._focusedNode,!1)}}),d=b.moveFocusVertical=function(a,b){var h=this.cellNavigation,c=this[h?"cell":"row"](a),c=h&&c.column.id,d=this.down(this._focusedNode,
b,!0);h&&(d=this.cell(d,c));this._focusOnNode(d,!1,a);a.preventDefault()};A=b.moveFocusUp=function(a){d.call(this,a,-1)};var k=b.moveFocusDown=function(a){d.call(this,a,1)},e=b.moveFocusPageUp=function(a){d.call(this,a,-this.pageSkip)},a=b.moveFocusPageDown=function(a){d.call(this,a,this.pageSkip)},f=b.moveFocusHorizontal=function(a,b){if(this.cellNavigation){var h=!this.row(a);this._focusOnNode(this.right(this["_focused"+(h?"Header":"")+"Node"],b),h,a);a.preventDefault()}},g=b.moveFocusLeft=function(a){f.call(this,
a,-1)},m=b.moveFocusRight=function(a){f.call(this,a,1)},n=b.moveHeaderFocusEnd=function(a,b){var h;this.cellNavigation&&(h=this.headerNode.getElementsByTagName("th"),this._focusOnNode(h[b?0:h.length-1],!0,a));a.preventDefault()},r=b.moveHeaderFocusHome=function(a){n.call(this,a,!0)},x=b.moveFocusEnd=function(a,b){var h=this,d=this.cellNavigation,e=this.contentNode,f=e.scrollTop+(b?0:e.scrollHeight),e=e[b?"firstChild":"lastChild"],q=-1<e.className.indexOf("dgrid-preload"),l=q?e[(b?"next":"previous")+
"Sibling"]:e,G=l.offsetTop+(b?0:l.offsetHeight),g;if(q){for(;l&&0>l.className.indexOf("dgrid-row");)l=l[(b?"next":"previous")+"Sibling"];if(!l)return}!q||1>e.offsetHeight?(d&&(l=this.cell(l,this.cell(a).column.id)),this._focusOnNode(l,!1,a)):(c("dom-addeventlistener")||(a=p.mixin({},a)),g=v.after(this,"renderArray",function(c){g.remove();return B.when(c,function(c){c=c[b?0:c.length-1];d&&(c=h.cell(c,h.cell(a).column.id));h._focusOnNode(c,!1,a)})}));f===G&&a.preventDefault()},h=b.moveFocusHome=function(a){x.call(this,
a,!0)};b.defaultKeyMap={32:C,33:e,34:a,35:x,36:h,37:g,38:A,39:m,40:k};b.defaultHeaderKeyMap={32:C,35:n,36:r,37:g,39:m};return b})},"dgrid/editor":function(){define("dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has dojo/query ./Grid put-selector/put dojo/_base/sniff".split(" "),function(A,v,y,p,c,w,B,C,D,z){function E(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=a.defaultChecked=!!b}function b(a,b){if("number"==typeof b)a=isNaN(a)?
a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date){var c=new Date(a);a=isNaN(c.getTime())?a:c}return a}function d(a,b,d,e,f){var F,g,q;if((d&&d.valueOf())!=(e&&e.valueOf())&&(F=a.cell(b),g=F.row,q=F.column,q.field&&g))if(F={grid:a,cell:F,rowId:g.id,oldValue:d,value:e,bubbles:!0,cancelable:!0},f&&f.type&&(F.parentType=f.type),c.emit(b,"dgrid-datachange",F))a.updateDirty?(a.updateDirty(g.id,q.field,e),q.autoSave&&setTimeout(function(){a._trackError("save")},
0)):g.data[q.field]=e;else{var l;(l=b.widget)?(l._dgridIgnoreChange=!0,l.set("value",d),setTimeout(function(){l._dgridIgnoreChange=!1},0)):(l=b.input)&&E(l,d);return d}return e}function k(a,c,e,f){var g;if(!e.isValid||e.isValid())if(f=d(a,(e.domNode||e).parentNode,m?n:e._dgridLastValue,"function"==typeof e.get?b(e.get("value")):b(e["checkbox"==e.type||"radio"==e.type?"checked":"value"]),f),m?n=f:e._dgridLastValue=f,"radio"===e.type&&e.name&&!c.editOn&&c.field)for(g in f=a.row(e),C("input[type\x3dradio][name\x3d"+
e.name+"]",a.contentNode).forEach(function(b){var d=a.row(b);b!==e&&b._dgridLastValue&&(b._dgridLastValue=!1,a.updateDirty?a.updateDirty(d.id,c.field,!1):d.data[c.field]=!1)}),a.dirty)f.id!==g&&a.dirty[g][c.field]&&a.updateDirty(g,c.field,!1)}function e(a){var b=a.editor,d=a.editOn,e=a.grid,f="string"!=typeof b,g,s,q;g=a.editorArgs||{};"function"==typeof g&&(g=g.call(e,a));if(f)s=new b(g),f=s.focusNode||s.domNode,f.className+=" dgrid-input",s.connect(s,d?"onBlur":"onChange",function(){s._dgridIgnoreChange||
k(e,a,this,{type:"widget"})});else if(q=function(b){var c=b.target;"_dgridLastValue"in c&&-1<c.className.indexOf("dgrid-input")&&k(e,a,c,b)},a.grid._hasInputListener||(e._hasInputListener=!0,e.on("change",function(a){q(a)})),s=f=z(("textarea"==b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",v.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},g)),9>B("ie")||B("ie")&&B("quirks"))"radio"==b||"checkbox"==b?c(s,"click",function(a){q(a)}):c(s,"change",function(a){q(a)});c(f,"mousedown",
function(a){a.stopPropagation()});return s}function a(a,b){function d(){var a=m;q.blur();"function"===typeof g.focus&&setTimeout(function(){g.focus(a)},F&&9>B("ie")?15:0)}var f=e(a),g=a.grid,F=f.domNode,s=f.domNode||f,q=f.focusNode||s,l=F?function(){f.set("value",f._dgridLastValue)}:function(){E(f,f._dgridLastValue);k(a.grid,a,f)};c(q,"keydown",function(b){b=b.keyCode||b.which;27==b?(l(),n=f._dgridLastValue,d()):13==b&&!1!==a.dismissOnEnter&&d()});(a._editorBlurHandle=c.pausable(f,"blur",function(){var b=
s.parentNode,d=b.children.length-1,e={alreadyHooked:!0},l=g.cell(s);c.emit(l.element,"dgrid-editor-hide",{grid:g,cell:l,column:a,editor:f,bubbles:!0,cancelable:!1});a._editorBlurHandle.pause();b.removeChild(s);for(z(l.element,"!dgrid-cell-editing");d--;)z(b.firstChild,"!");D.appendIfNode(b,a.renderCell(a.grid.row(b).data,n,b,r?v.delegate(e,r):e));m=n=r=null})).pause();return f}function f(a,b,d,e){var f=a.domNode,g=b.grid;f||E(a,e);d.innerHTML="";z(d,".dgrid-cell-editing");z(d,a.domNode||a);f&&(a._started||
a.startup(),a._dgridIgnoreChange=!0,a.set("value",e),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=e;m&&(n=e,c.emit(d,"dgrid-editor-show",{grid:g,cell:g.cell(d),column:b,editor:a,bubbles:!0,cancelable:!1}))}function g(a){var b,c,d,e,g,k;a.column||(a=this.cell(a));if(!a||!a.element)return null;b=a.column;e=b.field;c=a.element.contents||a.element;if(g=b.editorInstance){if(m!=c&&(!b.canEdit||b.canEdit(a.row.data,d)))return m=c,a=a.row,d=(d=this.dirty&&this.dirty[a.id])&&e in d?
d[e]:b.get?b.get(a.data):a.data[e],f(b.editorInstance,b,c,d),k=new p,setTimeout(function(){g.focus&&g.focus();b._editorBlurHandle&&b._editorBlurHandle.resume();k.resolve(g)},0),k.promise}else if(b.editor&&(g=c.widget||c.input))return k=new p,g.focus&&g.focus(),k.resolve(g),k.promise;return null}var m,n,r,x;return function(b,d,k){function p(a){var b=a.grid,d;b.edit||(b.edit=g,n.push(c(b.domNode,".dgrid-input:focusin",function(){x=b.cell(this)})),d=b._editorFocusoutHandle=c.pausable(b.domNode,".dgrid-input:focusout",
function(){x=null}),n.push(d),n.push(w.before(b,"removeRow",function(a){a=b.row(a);x&&x.row.id===a.id&&(d.pause(),setTimeout(function(){d.resume()},0))})),n.push(w.after(b,"insertRow",function(a){var c=b.row(a);x&&x.row.id===c.id&&b.edit(b.cell(c,x.column.id));return a})))}var m=b.renderCell||D.defaultRenderCell,n=[],s;b||(b={});b.editor=d=d||b.editor||"text";b.editOn=k=k||b.editOn;s="string"!=typeof d;b.widgetArgs&&(A.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 0.4"),b.editorArgs=
b.widgetArgs);w.after(b,"init",k?function(){p(b);b.editorInstance=a(b,m)}:function(){var a=b.grid;p(b);s&&n.push(w.before(a,"removeRow",function(c){if(c=(c=a.cell(c,b.id).element)&&(c.contents||c).widget)a._editorFocusoutHandle.pause(),c.destroyRecursive()}))});w.after(b,"destroy",function(){y.forEach(n,function(a){a.remove()});b._editorBlurHandle&&b._editorBlurHandle.remove();k&&s&&b.editorInstance.destroyRecursive();b.grid.edit=null});b.renderCell=k?function(a,d,e,f){if(!f||!f.alreadyHooked)c("TD"==
e.tagName?e:e.parentNode,k,function(){r=f;b.grid.edit(this)});return m.call(b,a,d,e,f)}:function(a,c,d,g){if(!b.canEdit||b.canEdit(a,c))a=e(b),f(a,b,d,c),d[s?"widget":"input"]=a;else return m.call(b,a,c,d,g)};return b}})}}});define("dojorama/layers/dgrid-extra",[],1);
//@ sourceMappingURL=dgrid-extra.js.map