//>>built
define("dgrid/editor","dojo/_base/kernel,dojo/_base/lang,dojo/_base/array,dojo/_base/Deferred,dojo/on,dojo/aspect,dojo/has,./Grid,put-selector/put,dojo/_base/sniff".split(","),function(z,s,A,t,j,n,o,u,p){function q(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=!!b}function v(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date)var c=new Date(a),a=isNaN(c.getTime())?a:c;return a}function B(a,b,c,
d,f){var e,g,i;if(!(c>=d&&c<=d)&&(e=a.cell(b),g=e.row,i=e.column,i.field&&g)){e={grid:a,cell:e,rowId:g.id,oldValue:c,value:d,bubbles:!0,cancelable:!0};if(f&&f.type)e.parentType=f.type;if(j.emit(b,"dgrid-datachange",e))a.updateDirty&&(a.updateDirty(g.id,i.field,d),i.autoSave&&setTimeout(function(){a._trackError("save")},0));else{var k;(k=b.widget)?(k._dgridIgnoreChange=!0,k.set("value",c),setTimeout(function(){k._dgridIgnoreChange=!1},0)):(k=b.input)&&q(k,c);return c}}return d}function r(a,b,c,d){if(!c.isValid||
c.isValid())a=B(a,(c.domNode||c).parentNode,h?l:c._dgridLastValue,"function"==typeof c.get?v(c.get("value")):v(c["checkbox"==c.type||"radio"==c.type?"checked":"value"]),d),h?l=a:c._dgridLastValue=a}function w(a){var b=a.editor,c=a.editOn,d=a.grid,f="string"!=typeof b,e,g,i;e=a.editorArgs||{};"function"==typeof e&&(e=e.call(d,a));if(f)g=new b(e),f=g.focusNode||g.domNode,f.className+=" dgrid-input",g.connect(g,c?"onBlur":"onChange",function(){g._dgridIgnoreChange||r(d,a,this,{type:"widget"})});else{i=
function(b){var c=b.target;"_dgridLastValue"in c&&-1<c.className.indexOf("dgrid-input")&&r(d,a,c,b)};if(!a.grid._hasInputListener)d._hasInputListener=!0,d.on("change",function(a){i(a)});g=f=p(("textarea"==b?"textarea":"input[type="+b+"]")+".dgrid-input",s.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},e));if(9>o("ie")||o("ie")&&o("quirks"))"radio"==b||"checkbox"==b?j(g,"click",function(a){i(a)}):j(g,"change",function(a){i(a)})}j(f,"mousedown",function(a){a.stopPropagation()});return g}
function C(a){var b=w(a),c=b.domNode||b,d=b.focusNode||c,f=b.domNode?function(){b.set("value",b._dgridLastValue)}:function(){q(b,b._dgridLastValue);r(a.grid,a,b)};j(d,"keydown",function(c){c=c.keyCode||c.which;27==c?(f(),l=b._dgridLastValue,d.blur()):13==c&&!1!==a.dismissOnEnter&&d.blur()});(a._editorBlurHandle=j.pausable(b,"blur",function(){var b=c.parentNode;a.grid.cell(c);var g=b.children.length-1,d={alreadyHooked:!0};for(b.removeChild(c);g--;)p(b.firstChild,"!");u.appendIfNode(b,a.renderCell(a.grid.row(b).data,
l,b,m?s.delegate(d,m):d));h=l=m=null;a._editorBlurHandle.pause()})).pause();return b}function x(a,b,c,d){(b=a.domNode)||q(a,d);c.innerHTML="";p(c,a.domNode||a);if(b)a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",d),setTimeout(function(){a._dgridIgnoreChange=!1},0);a._dgridLastValue=d;h&&(l=d)}function y(a){var b,c,d,f,e,g;a.column||(a=this.cell(a));b=a.column;f=b.field;c=a.element.contents||a.element;if(e=b.editorInstance){if(h!=c&&(!b.canEdit||b.canEdit(a.row.data,d)))return h=c,a=
a.row,d=(d=this.dirty&&this.dirty[a.id])&&f in d?d[f]:b.get?b.get(a.data):a.data[f],x(b.editorInstance,b,c,d),g=new t,setTimeout(function(){e.focus&&e.focus();b._editorBlurHandle&&b._editorBlurHandle.resume();g.resolve(e)},0),g.promise}else if(b.editor&&(e=c.widget||c.input))return g=new t,e.focus&&e.focus(),g.resolve(e),g.promise;return null}var h,l,m;return function(a,b,c){var d=a.renderCell||u.defaultRenderCell,f=[],e;a||(a={});a.editor=b=b||a.editor||"text";a.editOn=c=c||a.editOn;e="string"!=
typeof b;if(a.widgetArgs)z.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 1.0"),a.editorArgs=a.widgetArgs;n.after(a,"init",c?function(){var b=a.grid;if(!b.edit)b.edit=y;a.editorInstance=C(a,d)}:function(){var b=a.grid;if(!b.edit)b.edit=y;e&&f.push(n.before(b,"removeRow",function(c){c=b.cell(c,a.id).element;(c=(c.contents||c).widget)&&c.destroyRecursive()}))});n.after(a,"destroy",function(){A.forEach(f,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();
c&&e&&a.editorInstance.destroyRecursive()});a.renderCell=c?function(b,e,f,h){if(!h||!h.alreadyHooked)j("TD"==f.tagName?f:f.parentNode,c,function(){m=h;a.grid.edit(this)});return d.call(a,b,e,f,h)}:function(b,c,f,h){if(!a.canEdit||a.canEdit(b,c))b=w(a),x(b,a,f,c),f[e?"widget":"input"]=b;else return d.call(a,b,c,f,h)};return a}});