//>>built
define("dgrid/Grid","dojo/_base/kernel dojo/_base/declare dojo/on dojo/has put-selector/put ./List ./util/misc dojo/_base/sniff".split(" "),function(v,h,w,m,g,y,z){function u(a,b){b&&b.nodeType&&a.appendChild(b)}var x=8>m("ie")&&!m("quirks"),A=/[^\._a-zA-Z0-9-]/g;h=h(y,{columns:null,cellNavigation:!0,tabableHeader:!0,showHeader:!0,column:function(a){return"string"==typeof a?this.columns[a]:this.cell(a).column},listType:"grid",cell:function(a,b){if(a.column&&a.element)return a;a.target&&a.target.nodeType&&
(a=a.target);var d;if(a.nodeType){do{if(this._rowIdToObject[a.id])break;var e=a.columnId;if(e){b=e;d=a;break}a=a.parentNode}while(a&&a!=this.domNode)}if(!d&&"undefined"!=typeof b){var f=this.row(a);if(e=f.element)for(var e=e.getElementsByTagName("td"),c=0;c<e.length;c++)if(e[c].columnId==b){d=e[c];break}}if(null!=a)return{row:f||this.row(a),column:b&&this.column(b),element:d}},createRowCells:function(a,b,d){var e=g("table.dgrid-row-table[role\x3dpresentation]"),f=9>m("ie")||m("quirks")?g(e,"tbody"):
e,c,r,l,s,h,q,n,p,k,t;d=d||this.subRows;r=0;for(l=d.length;r<l;r++){q=d[r];c=g(f,"tr");q.className&&g(c,"."+q.className);s=0;for(h=q.length;s<h;s++){n=q[s];p=n.id;k=n.className||n.field&&"field-"+n.field;k=g(a+(".dgrid-cell.dgrid-cell-padding"+(p?".dgrid-column-"+p:"")+(k?"."+k:"")).replace(A,"-")+"[role\x3d"+("th"===a?"columnheader":"gridcell")+"]");k.columnId=p;x?(p=g(k,"!dgrid-cell-padding div.dgrid-cell-padding"),k.contents=p):p=k;if(t=n.colSpan)k.colSpan=t;if(t=n.rowSpan)k.rowSpan=t;b(p,n);c.appendChild(k)}}return e},
left:function(a,b){a.element||(a=this.cell(a));return this.cell(this._move(a,-(b||1),"dgrid-cell"))},right:function(a,b){a.element||(a=this.cell(a));return this.cell(this._move(a,b||1,"dgrid-cell"))},renderRow:function(a,b){var d=this,e=this.createRowCells("td",function(f,c){var e=a;c.get?e=c.get(a):"field"in c&&"_item"!=c.field&&(e=e[c.field]);var l=c.formatter,g=d.formatterScope;l?f.innerHTML="string"===typeof l&&g?g[l](e,a):l(e,a):c.renderCell?u(f,c.renderCell(a,e,f,b)):null!=e&&f.appendChild(document.createTextNode(e))},
b&&b.subRows);return g("div[role\x3drow]\x3e",e)},renderHeader:function(){var a=this,b=this.headerNode,d=b.childNodes.length;for(b.setAttribute("role","row");d--;)g(b.childNodes[d],"!");d=this.createRowCells("th",function(a,b){var c=b.headerNode=a;x&&(a=a.parentNode);var d=b.field;d&&(a.field=d);if(b.renderHeaderCell)u(c,b.renderHeaderCell(c));else if(b.label||b.field)c.appendChild(document.createTextNode(b.label||b.field));!1!==b.sortable&&(d&&"_item"!=d)&&(a.sortable=!0,a.className+=" dgrid-sortable")},
this.subRows&&this.subRows.headerRows);this._rowIdToObject[d.id=this.id+"-header"]=this.columns;b.appendChild(d);this._sortListener&&this._sortListener.remove();this._sortListener=w(d,"click,keydown",function(e){if("click"==e.type||32==e.keyCode||!m("opera")&&13==e.keyCode){var f=e.target,c,d,g;do if(f.sortable){g=[{attribute:c=f.field||f.columnId,descending:(d=a._sort[0])&&d.attribute==c&&!d.descending}];e={bubbles:!0,cancelable:!0,grid:a,parentType:e.type,sort:g};w.emit(f,"dgrid-sort",e)&&(a._sortNode=
f,a.set("sort",g));break}while((f=f.parentNode)&&f!=b)}})},resize:function(){var a=this.headerNode.firstChild,b=this.contentNode,d;this.inherited(arguments);if(!m("ie")||7<m("ie")&&!m("quirks"))if(b.style.width="",b&&a&&(d=a.offsetWidth)!=b.offsetWidth)b.style.width=d+"px"},destroy:function(){this._destroyColumns();this._sortListener&&this._sortListener.remove();this.inherited(arguments)},_setSort:function(a,b){this.inherited(arguments);this.updateSortArrow(this._sort)},updateSortArrow:function(a,
b){this._lastSortedArrow&&(g(this._lastSortedArrow,"\x3c!dgrid-sort-up!dgrid-sort-down"),g(this._lastSortedArrow,"!"),delete this._lastSortedArrow);b&&(this._sort=a);if(a[0]){var d=a[0].attribute,e=a[0].descending,f=this._sortNode,c,h,l;delete this._sortNode;if(!f)for(l in c=this.columns,c)if(h=c[l],h.field==d){f=h.headerNode;break}f&&(f=f.contents||f,this._lastSortedArrow=g(f.firstChild,"-div.dgrid-sort-arrow.ui-icon[role\x3dpresentation]"),this._lastSortedArrow.innerHTML="\x26nbsp;",g(f,e?".dgrid-sort-down":
".dgrid-sort-up"),this.resize())}},styleColumn:function(a,b){return this.addCssRule("#"+z.escapeCssIdentifier(this.domNode.id)+" .dgrid-column-"+a,b)},_configColumns:function(a,b){var d=[],e=b instanceof Array,f,c;for(f in b)c=b[f],"string"==typeof c&&(b[f]=c={label:c}),!e&&!c.field&&(c.field=f),f=c.id=c.id||(isNaN(f)?f:a+f),e&&(this.columns[f]=c),this._configColumn&&this._configColumn(c,f,b,a),c.grid=this,"function"===typeof c.init&&c.init(),d.push(c);return e?b:d},_destroyColumns:function(){var a=
this.subRows,b=a&&a.length,d,e,f,c;this.cleanup();for(d=0;d<b;d++){e=0;for(c=a[d].length;e<c;e++)f=a[d][e],"function"===typeof f.destroy&&f.destroy()}},configStructure:function(){var a=this.subRows,b=this._columns=this.columns;this.columns=!b||b instanceof Array?{}:b;if(a)for(b=0;b<a.length;b++)a[b]=this._configColumns(b+"-",a[b]);else this.subRows=[this._configColumns("",b)]},_getColumns:function(){return this._columns||this.columns},_setColumns:function(a){this._destroyColumns();this.subRows=null;
this.columns=a;this._updateColumns()},_setSubRows:function(a){this._destroyColumns();this.subRows=a;this._updateColumns()},setColumns:function(a){v.deprecated("setColumns(...)",'use set("columns", ...) instead',"dgrid 1.0");this.set("columns",a)},setSubRows:function(a){v.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 1.0");this.set("subRows",a)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);
this._started&&(this._sort&&this._sort.length?this.updateSortArrow(this._sort):this.resize())}});h.appendIfNode=u;h.defaultRenderCell=function(a,b,d,e){null!=b&&d.appendChild(document.createTextNode(b))};return h});