//>>built
define("dgrid/List","dojo/_base/array,dojo/_base/kernel,dojo/_base/declare,dojo/on,dojo/has,./util/misc,dojo/has!touch?./TouchScroll,xstyle/has-class,put-selector/put,dojo/_base/sniff,xstyle/css!./css/dgrid.css".split(","),function(z,q,r,n,h,v,s,w,d){function p(a){var b=a?"."+a.replace(t,"."):"";this._class&&(b="!"+this._class.replace(t,"!")+b);d(this.domNode,b);this._class=a}function u(){return this._class}w("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var l,i=d(document.getElementsByTagName("head")[0],
"style"),j=[],i=i.sheet||i.styleSheet,x=0,t=/ +/g,y=7>h("ie")&&!h("quirks")?function(){var a,b,c;if(this._started&&(a=document.documentElement,b=a.clientWidth,a=a.clientHeight,c=this._prevWinDims||[],c[0]!==b||c[1]!==a))this.resize(),this._prevWinDims=[b,a]}:function(){this._started&&this.resize()};return r(s?s:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=
function(){c.removeRow(this.element)};if(b)this.srcNodeRef=b=b.nodeType?b:document.getElementById(b);this.create(a,b)},listType:"list",create:function(a,b){var c=this.domNode=b||d("div"),f;a?(this.params=a,r.safeMixin(this,a),f=a["class"]||a.className||c.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||"dgrid_"+x++;this.buildRendering();f&&p.call(this,
f);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,c,f,e,g;g=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";d(a,"[role=grid].ui-widget.dgrid.dgrid-"+this.listType);c=this.headerNode=d(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+(this.showHeader?"":".dgrid-header-hidden"));(h("quirks")||8>h("ie"))&&d(a,"div.dgrid-spacer");
f=this.bodyNode=d(a,"div.dgrid-scroller");f.tabIndex=-1;this.headerScrollNode=d(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");e=this.footerNode=d("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));d(a,e);g&&(a.className+=" dgrid-rtl"+(h("webkit")?"":" dgrid-rtl-nonwebkit"));n(f,"scroll",function(e){if(b.showHeader)c.scrollLeft=e.scrollLeft||f.scrollLeft;e.stopPropagation();n.emit(a,"scroll",{scrollTarget:f})});this.configStructure();this.renderHeader();this.contentNode=
this.touchNode=d(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=n(window,"resize",v.throttleDelayed(y,this)))},startup:function(){this.inherited(arguments);if(!this._started)this._started=!0,this.resize(),this.set("sort",this._sort)},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,f=b.offsetHeight,e=this.showFooter?c.offsetHeight:0,g=h("quirks")||7>h("ie");this.headerScrollNode.style.height=a.style.marginTop=
f+"px";a.style.marginBottom=e+"px";if(g&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-f-e,0)+"px",e))c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0);l||(f=d(document.body,"div.dgrid-scrollbar-measure"),l=f.offsetWidth-f.clientWidth,d(f,"!"),7===h("ie")&&l++,this.addCssRule(".dgrid-scrollbar-width","width: "+l+"px"),this.addCssRule(".dgrid-scrollbar-height","height: "+l+"px"),17!=l&&!g&&(this.addCssRule(".dgrid-header","right: "+l+"px"),this.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header",
"left: "+l+"px")));if(g)b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0)},addCssRule:function(a,b){var c=j.length;j[c]=(i.cssRules||i.rules).length;i.addRule?i.addRule(a,b):i.insertRule(a+"{"+b+"}",j[c]);return{remove:function(){var a=j[c],b,g=j.length;if(void 0!==a){i.deleteRule?i.deleteRule(a):i.removeRule(a);j[c]=void 0;for(b=c;b<g;b++)j[b]>a&&j[b]--}}}},on:function(a,b){var c=n(this.domNode,a,b);h("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){var a=
this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();d(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,
y:0})},newRow:function(a,b,c,f){if(!b||b.parentNode){var e=this.insertRow(a,b?b.parentNode:this.contentNode,b,f.start+c,f);d(e,".ui-state-highlight");setTimeout(function(){d(e,"!ui-state-highlight")},250);return e}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;if(-1<b){do if(-1<a.rowIndex)-1<(a.className+" ").indexOf("dgrid-row ")&&d(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++;while((a=a.nextSibling)&&a.rowIndex!=
b&&!a.blockRowIndex)}}},renderArray:function(a,b,c){function f(a){o=g.insertRow(a,l,null,d++,c);o.observerIndex=i;return o}function e(a){if(h=b?b.parentNode:g.contentNode)h.insertBefore(l,b||null),(o=a[a.length-1])&&g.adjustRowIndices(o);return k=a}var c=c||{},g=this,d=c.start||0,m,k,h;if(!b)this._lastCollection=a;if(a.observe)var i=this.observers.push(a.observe(function(a,b,e){var f,d;if(-1<b&&k[b]){m=k.splice(b,1)[0];if(m.parentNode==h)(f=m.nextSibling)&&b!=e&&f.rowIndex--,g.removeRow(m);g._processScroll&&
g._processScroll()}if(-1<e){d=k[e];if(!d&&(d=k[e-1]))d=(d.connected||d).nextSibling;if(m=g.newRow(a,d,e,c))if(m.observerIndex=i,k.splice(e,0,m),!f||e<b)a=m.previousSibling,f=!a||a.rowIndex+1==m.rowIndex||0==m.rowIndex?m:a;c.count++}b!=e&&f&&g.adjustRowIndices(f)},!0))-1;var l=document.createDocumentFragment();if(a.map){if(k=a.map(f,console.error),k.then)return k.then(e)}else{k=[];for(var j=0,n=a.length;j<n;j++)k[j]=f(a[j])}var o;return e(k)},renderHeader:function(){},_autoId:0,insertRow:function(a,
b,c,f,e){var g=e.parentId,g=this.id+"-row-"+(g?g+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),d=document.getElementById(g),h=d&&d.previousSibling;if(!d||c&&d.parentNode!=c.parentNode)d&&this.removeRow(d),d=this.renderRow(a,e),d.className=(d.className||"")+" ui-state-default dgrid-row "+(1==f%2?"dgrid-row-odd":"dgrid-row-even"),this._rowIdToObject[d.id=g]=a;b.insertBefore(d,c||null);h&&this.adjustRowIndices(h);d.rowIndex=f;return d},renderRow:function(a){return d("div",
""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||d(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;if(a.target&&a.target.nodeType)a=a.target;if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+
b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,d){var e,g;g=e=a.element;b=b||1;do if(a=e[0>b?"previousSibling":"nextSibling"]){do if((e=a)&&-1<(e.className+" ").indexOf(c+" ")){g=e;b+=0>b?1:-1;break}while(a=(!d||!e.hidden)&&e[0>b?"lastChild":"firstChild"])}else if(e=e.parentNode,e===this.bodyNode||e===this.headerNode)break;while(b);return g},up:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));
return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:h("touch")?function(){return this.inherited(arguments)}:function(a){if("undefined"!==typeof a.x)this.bodyNode.scrollLeft=a.x;if("undefined"!==typeof a.y)this.bodyNode.scrollTop=a.y},getScrollPosition:h("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,
[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:u,_setClass:p,_getClassName:u,_setClassName:p,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,descending:b}];this.refresh();if(this._lastCollection){if(a.length){if("string"!=typeof a)b=a[0].descending,a=a[0].attribute;
this._lastCollection.sort(function(c,d){var e=c[a],g=d[a];void 0===e&&(e="");void 0===g&&(g="");return e==g?0:e>g==!b?1:-1})}this.renderArray(this._lastCollection)}},sort:function(a,b){q.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;d(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();if(a)b.scrollLeft=this.getScrollPosition().x},
setShowHeader:function(a){q.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;d(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})});