//>>built
define("xstyle/core/parser",["xstyle/core/utils"],function(Q){function K(){this.push.apply(this,arguments)}function L(f){this.value=f}function M(f,s,D){function E(t,q){function s(a){y=!1;var k=n.lastIndex;a.then(function(){y=!0;d&&(n.lastIndex=k,x())});var d=!0}function x(){function u(a){a&&("string"==typeof a&&x)&&(a=x+a);b?b.push?"string"==typeof b[b.length-1]&&"string"==typeof a?b[b.length-1]+=a:a&&b.push(a):"string"==typeof b&&"string"==typeof a?b+=a:b=new K(b,a):b=a}for(y=!0;y;){var f=n.exec(t),
d=f[5],x=f[1],c=f[2],l=f[3],g=f[4],h,m,b,F,g=g&&G(g),c=c&&G(c);v?(l?(m=c,h=l.charAt(0),F="?"==l.charAt(1),-1<l.indexOf("\n")&&(g=l.slice(1))):g=c,b=g,v=!1):(g=l?c+l:c,u(g));"{"!=d&&(k+=f[0]);switch(d){case "'":case '"':var z="'"==d?R:S;z.lastIndex=n.lastIndex;(d=z.exec(t))||r("unterminated string");c=d[1];n.lastIndex=z.lastIndex;u(new L(c));k+=d[0];continue;case "\\":d=z.lastIndex++;u(t.charAt(d));continue;case "(":case "{":case "[":var e,N=!1;if("{"==d){v=!0;":"==h&&(c+=l);k=G((k+c).replace(/\s+/g,
" ").replace(/([\.#:])\S+|\w+/g,function(a,b){return b?a:a.toLowerCase()}));u(e=a.newRule(k));"\x3d"==h&&(A=!1,b.creating=!0,g&&(N=!0));":"==h&&!a.root&&(b.creating=!0);var l=null,D=B;if(f[6]){var H=q.cssRules||q.rules;if(e.cssRule=l=H[f[6].slice(1)])k=l.selectorText}if(a.root&&A)for(H=q.cssRules||q.rules;l=H[B++];)if(l.selectorText==k){e.cssRule=l;break}l||(e.ruleIndex=B=D,e.styleSheet=q);b.creating?(e.selector="."+("\x3d"==h?c.match(/[\w-]*$/g,"")[0]:"")+"-x-"+T++,e.creating=!0):e.selector=a.root?
k:a.selector+" "+k;k=""}else c=g.match(/(.*?)([\w-]*)$/),u(e=a.newCall(c[2],b,a)),e.ref=a.getDefinition(c[2]),(b.calls||(b.calls=[])).push(e);e.parent=a;N&&g.replace(/\s*([\w-]+)\s*$/g,function(a,b){var c=Q.extend(e,b,r);c&&c.then&&s(c)});a.currentName=m;a.currentSequence=b;a.assignmentOperator=h;var C;if("{"==d&&(C=e.selector.match(/[@:]\w+/)))C=C[0],(m=a.getDefinition(C))&&m.selector&&m.selector(e);p.push(a=e);a.operator=d;a.start=n.lastIndex;b=m=null;continue}if(b)if(c="string"==typeof b?b:b[0],
c.charAt&&"@"==c.charAt(0))if(g=c.match(/\w+/)[0],"import"==g)c=M.getStyleSheet((q.cssRules||q.imports)[B++],b,q),g=n.lastIndex,E(c.localSource,c),n.lastIndex=g;else{if("xstyle"==g){if("start"==c.slice(8,13))e=a?a.newRule(""):O,e.root=a.root,e.parent=a,p.push(a=e);else{var O=a||O;p.pop();a=p[p.length-1]}n=a?P:/(@[\w\s])/g}}else if(h)try{var w=a[":"==h?"setValue":"declareProperty"](m,b,F);w&&w.then&&s(w)}catch(J){r(J)}switch(d){case ":":"\x3d"==h?(v=!0,h=":"):u(":");break;case "}":case ")":case "]":U[a.operator]!=
d&&r("Incorrect opening operator "+a.operator+" with closing operator "+d);m=null;m=t.slice(a.start,n.lastIndex-1);a.cssText=a.cssText?a.cssText+";"+m:m;if("}"==d){"}"==I&&(I=a.parent.selector)&&"@"==!I.charAt(0)&&r("A nested rule must end with a semicolon");if(a.root)r("Unmatched "+d);else{try{a.onRule(a.selector,a)}catch(V){r(V)}A=!0}k=""}")"==d&&!h&&(a.args=b.isSequence?b:[b],(w=p[p.length-2].onCall(a))&&w.then&&s(w));p.pop();a=p[p.length-1];b=a.currentSequence;m=a.currentName;h=a.assignmentOperator;
if(a.root&&"}"==d){if(h)try{a[":"==h?"setValue":"declareProperty"](m,b[1]||b,F)}catch(W){r(W)}v=!0;h=!1}break;case "":case void 0:return;case ";":b=null,v=!0,h=A=!1,k=""}var I=d}}function r(a){console.error(a.message||a,(q.href||"in-page stylesheet")+":"+t.slice(0,n.lastIndex).split("\n").length);a.stack&&console.error(a.stack)}t=t.replace(J,function(a){return a.replace(/[^\n]/g,"")});var a=f;n.lastIndex=0;var y,B=0,A=!0,k="",v=!0;x()}var P,n=P=/(\s*)((?:[^{\}\[\]\(\)\\'":=;]|\[(?:[^\]'"]|'(?:\\.|[^'])*'|"(?:\\.|[^"])*")\])*)([=:]\??\s*([^{\}\[\]\(\)\\'":;]*))?(?:([{\}\[\]\(\)\\'":;])(\/\d+)?|$)/g,
p=[f];f.parse=E;E(s,D)}var R=/((?:\\.|[^'])*)'/g,S=/((?:\\.|[^"])*)"/g,J=/\/\*[\w\W]*?\*\//g,U={"{":"}","[":"]","(":")"},T=0,G="".trim?function(f){return f.trim()}:function(f){return f.replace(/^\s+|\s+$/g,"")},s=K.prototype=[];s.toString=function(){return this.join("")};s.isSequence=!0;L.prototype.toString=function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};return M});
//@ sourceMappingURL=parser.js.map