//>>built
require({cache:{"url:dojorama/ui/release/widget/template/ReleaseGridWidget.html":'<div>\n    <div class="clearfix">\n        <form class="form-search pull-right" data-dojo-attach-point="filterFormNode">\n            <div class="input-append">\n                <input data-dojo-attach-point="filterInputNode" class="search-query" />\n                <button data-dojo-attach-point="filterSubmitNode" class="btn"></button>\n            </div>\n        </form>\n    </div>\n    \n    <div data-dojo-attach-point="mainNode" style="display:none">\n        <div data-dojo-attach-point="gridNode"></div>\n    \n        <div class="btn-toolbar">\n            <button data-dojo-attach-point="gridSaveButtonNode" class="btn"></button>\n            <button data-dojo-attach-point="gridDeleteButtonNode" class="btn btn-danger"></button>\n        </div>\n    </div>\n</div>'}});
define("dojorama/ui/release/widget/ReleaseGridWidget","dojo/_base/declare,dojo/_base/lang,mijit/_WidgetBase,mijit/_TemplatedMixin,dojomat/_StateAware,dgrid/OnDemandGrid,dgrid/Selection,dgrid/editor,dojo-form-controls/Checkbox,dojo-form-controls/Button,dojo-form-controls/Textbox,dobolo/DatepickerInput,dojo-data-model/Observable,dojo/dom-construct,dojo/dom-style,dojo/dom-attr,dojo/aspect,dojo/topic,dojo/on,dojo/when,dojo/promise/all,dojo/text!./template/ReleaseGridWidget.html,dojo/i18n!./nls/ReleaseGridWidget".split(","),
function(k,a,n,o,p,q,r,l,s,h,t,u,v,m,g,d,w,e,i,j,x,y,c){return k([n,o,p],{router:null,store:null,templateString:y,filterInputWidget:null,filterSubmitWidget:null,gridWidget:null,gridSaveButtonWidget:null,gridDeleteButtonWidget:null,constructor:function(a){this.request=a.request;this.router=a.router;this.store=a.store},postCreate:function(){this.inherited(arguments);this.store=v(this.store);this.buildFilterForm();this.gridSaveButtonWidget=this.buildSaveButton();this.gridDeleteButtonWidget=this.buildDeleteButton();
this.gridWidget=this.buildGrid();this.gridWidget.setStore(this.store)},startup:function(){this.filterInputWidget.startup();this.filterSubmitWidget.startup();this.gridSaveButtonWidget.startup();this.gridDeleteButtonWidget.startup()},buildFilterForm:function(){this.filterInputWidget=new t({"class":d.get(this.filterInputNode,"class"),value:this.request.getQueryParam("find")},this.filterInputNode);this.filterSubmitWidget=new h({type:"submit","class":d.get(this.filterSubmitNode,"class"),label:c.filterSubmitLabel},
this.filterSubmitNode);this.own(i(this.filterFormNode,"submit",a.hitch(this,function(a){a.preventDefault();this.push(this.router.getRoute("releaseIndex").assemble(null,{find:this.filterInputWidget.value}))})))},buildGrid:function(){var f={selector:{label:" ",sortable:!1,renderCell:a.hitch(this,function(b,c,d){c=m.create("input",{type:"checkbox"},d,"last");this.own(i(c,"change",a.hitch(this,function(){var a=this.gridWidget.row(b);this.gridWidget.isSelected(b.get("id"))?this.gridWidget.deselect(a):
this.gridWidget.select(a)})))})},title:{label:c.gridColumnLabelTitle,field:"title",sortable:!0,renderCell:a.hitch(this,function(b,c,d){b=m.create("a",{href:this.router.getRoute("releaseUpdate").assemble({id:b.get("id")}),innerHTML:b.get("title")},d,"last");this.own(i(b,"click",a.hitch(this,function(a){a.preventDefault();this.push(a.target.href)})))})},releaseDate:l({label:c.gridColumnLabelReleaseDate,field:"releaseDate",sortable:!0,autoSave:!1,editorArgs:{required:!0,"class":"span3",format:"medium"}},
u),publish:l({label:c.gridColumnLabelPublish,field:"publish",sortable:!0,autoSave:!1,editorArgs:{value:"on"}},s)},b=new (k([q,r]))({getBeforePut:!0,columns:f,selectionMode:"none",queryOptions:{sort:[{attribute:"title",descending:!1}]},loadingMessage:c.gridLoadingState,noDataMessage:c.gridNoDataAvailable},this.gridNode),d=function(){var a=0,c;for(c in b.selection)b.selection.hasOwnProperty(c)&&(a+=1);return a};this.request.getQueryParam("find")&&b.set("query",{title:this.request.getQueryParam("find")});
b.on("dgrid-error",function(){e.publish("ui/release/widget/ReleaseGridWidget/unknown-error",{notification:{message:c.notificationUnknownError,type:"error"}})});b.on(".dgrid-header .dgrid-column-title:click",a.hitch(this,function(){}));b.on(".dgrid-row .dgrid-column-title:click",a.hitch(this,function(){}));b.on("dgrid-select",a.hitch(this,function(){g.set(this.gridDeleteButtonWidget.domNode,"display","inline")}));b.on("dgrid-deselect",a.hitch(this,function(){g.set(this.gridDeleteButtonWidget.domNode,
"display",d()?"inline":"none")}));b.on("dgrid-datachange",a.hitch(this,function(){g.set(this.gridSaveButtonWidget.domNode,"display","inline")}));var z=w.after(this.store,"query",a.hitch(this,function(b){j(b,a.hitch(this,function(a){a.length&&(g.set(this.mainNode,"display","block"),z.remove())}));return b}));return b},buildSaveButton:function(){var f=function(){e.publish("ui/release/widget/ReleaseGridWidget/update-ok",{notification:{message:c.notificationUpdateOk,type:"ok"}})},b=function(){e.publish("ui/release/widget/ReleaseGridWidget/update-error",
{notification:{message:c.notificationUpdateError,type:"error"}})};return new h({style:"display: none","class":d.get(this.gridSaveButtonNode,"class"),label:c.gridSaveButtonLabel,onClick:a.hitch(this,function(){j(this.gridWidget.save(),f,b)})},this.gridSaveButtonNode)},buildDeleteButton:function(){var f=function(){e.publish("ui/release/widget/ReleaseGridWidget/delete-ok",{notification:{message:c.notificationDeleteOk,type:"ok"}})},b=function(){e.publish("ui/release/widget/ReleaseGridWidget/delete-error",
{notification:{message:c.notificationDeleteError,type:"error"}})};return new h({style:"display: none","class":d.get(this.gridDeleteButtonNode,"class"),label:c.gridDeleteButtonLabel,onClick:a.hitch(this,function(){var a=[],c;for(c in this.gridWidget.selection)this.gridWidget.selection.hasOwnProperty(c)&&a.push(this.store.remove(c));j(x(a),f,b)})},this.gridDeleteButtonNode)}})});