//>>built
define("dojo/nls/dojo_ca",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"dg. dl. dm. dc. dj. dv. ds.".split(" "),"months-format-narrow":"GFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, d.M.y","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["aC","dC"],"days-format-short":"dg. dl. dt. dc. dj. dv. ds.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM 'de' y",
"months-format-wide":"de gener;de febrer;de mar\u00e7;d\u2019abril;de maig;de juny;de juliol;d\u2019agost;de setembre;d\u2019octubre;de novembre;de desembre".split(";"),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE d MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"d/M/y","dateFormatItem-yM":"M/y","months-standAlone-wide":"gener febrer mar\u00e7 abril maig juny juliol agost setembre octubre novembre desembre".split(" "),
"timeFormat-short":"H.mm","quarters-format-wide":["1r trimestre","2n trimestre","3r trimestre","4t trimestre"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"H.mm.ss z","dateFormatItem-yMMM":"LLL y","dateTimeFormats-appendItem-Era":"{1} {0}","months-format-abbr":"de gen.;de febr.;de mar\u00e7;d\u2019abr.;de maig;de juny;de jul.;d\u2019ag.;de set.;d\u2019oct.;de nov.;de des.".split(";"),"timeFormat-full":"H.mm.ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateFormatItem-GyMMMd":"G y MMM d",
"dateFormatItem-H":"H","months-standAlone-abbr":"gen. febr. mar\u00e7 abr. maig juny jul. ag. set. oct. nov. des.".split(" "),"quarters-format-abbr":["1T","2T","3T","4T"],"quarters-standAlone-wide":["1r trimestre","2n trimestre","3r trimestre","4t trimestre"],"dateFormatItem-Gy":"G y","dateFormatItem-M":"L","days-standAlone-wide":"Diumenge Dilluns Dimarts Dimecres Dijous Divendres Dissabte".split(" "),"timeFormat-medium":"H.mm.ss","dateFormatItem-Hm":"H.mm","quarters-standAlone-abbr":["1T","2T","3T",
"4T"],eraAbbr:["aC","dC"],"days-standAlone-abbr":"dg dl dt dc dj dv ds".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a.m.","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E d/M","dateTimeFormat-full":"{1} {0}","days-format-wide":"diumenge dilluns dimarts dimecres dijous divendres dissabte".split(" "),"dateTimeFormats-appendItem-Day":"{0} ({2}: {1})",
"dateFormatItem-y":"y","months-standAlone-narrow":"gfmamjjasond".split(""),"dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dg. dl. dt. dc. dj. dv. ds.".split(" "),"dateFormatItem-yMMMd":"d MMM y",eraNames:["abans de Crist","despr\u00e9s de Crist"],"days-format-narrow":"dg dl dt dc dj dv ds".split(" "),"days-standAlone-narrow":"dg dl dt dc dj dv ds".split(" "),"dateFormatItem-MMM":"LLL",
"dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy","dateFormatItem-yMMMEd":"E, d MMM, y","dateFormatItem-Ed":"E d","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormat-medium":"dd/MM/y","dayPeriods-format-narrow-pm":"p.m.","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"H.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"G y MMM",
"dateFormatItem-yMM":"MM/y","dateFormatItem-yMMMM":"LLLL 'de' y","dateFormatItem-MMMMEd":"E d MMMM","dateFormatItem-MMMMd":"d MMMM","dateFormatItem-mmss":"mm:ss"},"dojorama/model/nls/ReleaseModel":{titleMissing:"Title required",titleInvalid:"Invalid title"},"dojorama/ui/_global/widget/nls/FooterWidget":{},"dojorama/ui/_global/widget/nls/NavigationWidget":{labelHome:"Dojorama",labelStorage:"Storage",labelReleaseIndex:"Releases"}});
//@ sourceMappingURL=dojo_ca.js.map