//>>built
define("dojo/nls/dojo_sv",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"s\u00f6,m\u00e5,ti,on,to,fr,l\u00f6".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"veckodag","dateFormatItem-yQQQ":"y QQQ","dateFormatItem-yMEd":"E, yyyy-MM-dd","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["f.Kr.","e.Kr."],"days-format-short":"s\u00f6,m\u00e5,ti,on,to,fr,l\u00f6".split(","),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d MMMM y","months-format-wide":"januari,februari,mars,april,maj,juni,juli,augusti,september,oktober,november,december".split(","),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"em","dateFormat-full":"EEEE'en' 'den' d:'e' MMMM y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"FM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"yyyy-MM-dd","field-era":"era","dateFormatItem-yM":"yyyy-MM","months-standAlone-wide":"januari,februari,mars,april,maj,juni,juli,augusti,september,oktober,november,december".split(","),
"timeFormat-short":"HH:mm","quarters-format-wide":["1:a kvartalet","2:a kvartalet","3:e kvartalet","4:e kvartalet"],"timeFormat-long":"HH:mm:ss z","field-year":"\u00e5r","dateFormatItem-yMMM":"MMM y","dateFormatItem-yQ":"yyyy Q","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"timme","months-format-abbr":"jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec".split(","),"timeFormat-full":"'kl'. HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"i dag","field-day-relative+1":"i morgon",
"dateFormatItem-H":"HH","months-standAlone-abbr":"jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec".split(","),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1:a kvartalet","2:a kvartalet","3:e kvartalet","4:e kvartalet"],"dateFormatItem-M":"L","days-standAlone-wide":"s\u00f6ndag,m\u00e5ndag,tisdag,onsdag,torsdag,fredag,l\u00f6rdag".split(","),"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["K1","K2","K3","K4"],eraAbbr:["f.Kr.","e.Kr."],
"field-minute":"minut","field-dayperiod":"fm/em","days-standAlone-abbr":"s\u00f6n,m\u00e5n,tis,ons,tor,fre,l\u00f6r".split(","),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"i g\u00e5r","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"f","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E d/M","dateTimeFormat-full":"{1} {0}","field-day":"dag","days-format-wide":"s\u00f6ndag,m\u00e5ndag,tisdag,onsdag,torsdag,fredag,l\u00f6rdag".split(","),
"field-zone":"tidszon","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"EM","days-format-abbr":"s\u00f6n,m\u00e5n,tis,ons,tors,fre,l\u00f6r".split(","),"dateFormatItem-yMMMd":"d MMM y",eraNames:["f\u00f6re Kristus","efter Kristus"],"days-format-narrow":"S,M,T,O,T,F,L".split(","),
"days-standAlone-narrow":"S,M,T,O,T,F,L".split(","),"dateFormatItem-MMM":"LLL","field-month":"m\u00e5nad","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"fm","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"yyyy-MM-dd","field-second":"sekund","dateFormatItem-yMMMEd":"E d MMM y","dateFormatItem-Ed":"E d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"vecka","dateFormat-medium":"d MMM y",
"dayPeriods-format-narrow-pm":"e","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-MMdd":"dd/MM","dateFormatItem-yyQ":"Q yy","field-day-relative+2":"i \u00f6vermorgon","dateFormatItem-yyyyMMM":"MMM y","dateFormatItem-MMMMd":"d:'e' MMMM","dateFormatItem-yyMMM":"MMM -yy","field-day-relative+-2":"i f\u00f6rrg\u00e5r","dateFormatItem-yyyyMM":"yyyy-MM","field-year-relative+-1":"i fjol","field-month-relative+-1":"f\u00f6rra m\u00e5naden",
"dateFormatItem-yyMM":"yy-MM","dateFormatItem-MMMMEd":"E d:'e' MMMM","dateFormatItem-MMd":"d/M","field-month-relative+0":"denna m\u00e5nad","field-month-relative+1":"n\u00e4sta m\u00e5nad","field-year-relative+0":"i \u00e5r","field-week-relative+-1":"f\u00f6rra veckan","field-year-relative+1":"n\u00e4sta \u00e5r","dateFormatItem-yyyyQQQQ":"QQQQ y","field-week-relative+0":"denna vecka","field-week-relative+1":"n\u00e4sta vecka"},"dojorama/model/nls/ReleaseModel":{titleMissing:"Title required",titleInvalid:"Invalid title"},
"dojorama/ui/_global/widget/nls/FooterWidget":{},"dojorama/ui/_global/widget/nls/NavigationWidget":{labelHome:"Dojorama",labelStorage:"Storage",labelReleaseIndex:"Releases"}});