//>>built
define("dgrid/List","dojo/_base/kernel dojo/_base/declare dojo/on dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(u,v,m,h,n,w,A,d){function x(a,b){var c=document.body,g;d(c,a,".dgrid-scrollbar-measure");g=a["offset"+b]-a["client"+b];d(a,"!dgrid-scrollbar-measure");c.removeChild(a);return g}function q(a){var b=a?"."+a.replace(y,"."):"";this._class&&(b="!"+this._class.replace(y,"!")+b);d(this.domNode,
b);this._class=a}function z(){return this._class}A("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var l,t;h.add("dom-scrollbar-width",function(a,b,c){return x(c,"Width")});h.add("dom-scrollbar-height",function(a,b,c){return x(c,"Height")});var B=0,y=/ +/g,C=7>h("ie")&&!h("quirks")?function(){var a,b,c;if(this._started&&(a=document.documentElement,b=a.clientWidth,a=a.clientHeight,c=this._prevWinDims||[],c[0]!==b||c[1]!==a))this.resize(),this._prevWinDims=[b,a]}:function(){this._started&&
this.resize()};return v(w?w:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=function(){c.removeRow(this.element)};b&&(this.srcNodeRef=b=b.nodeType?b:document.getElementById(b));this.create(a,b)},listType:"list",create:function(a,b){var c=this.domNode=b||d("div"),g;a?(this.params=a,v.safeMixin(this,a),g=a["class"]||a.className||c.className,
this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||"dgrid_"+B++;this.buildRendering();g&&q.call(this,g);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,c,g,e,f;f=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();
a.className="";d(a,"[role\x3dgrid].ui-widget.dgrid.dgrid-"+this.listType);c=this.headerNode=d(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+(this.showHeader?"":".dgrid-header-hidden"));(h("quirks")||8>h("ie"))&&d(a,"div.dgrid-spacer");g=this.bodyNode=d(a,"div.dgrid-scroller");g.tabIndex=-1;this.headerScrollNode=d(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");e=this.footerNode=d("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));d(a,e);f&&(a.className+=" dgrid-rtl"+
(h("webkit")?"":" dgrid-rtl-nonwebkit"));m(g,"scroll",function(f){b.showHeader&&(c.scrollLeft=f.scrollLeft||g.scrollLeft);f.stopPropagation();m.emit(a,"scroll",{scrollTarget:g})});this.configStructure();this.renderHeader();this.contentNode=this.touchNode=d(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=m(window,"resize",n.throttleDelayed(C,this)))},startup:function(){this._started||(this.inherited(arguments),this._started=!0,this.resize(),this.set("sort",
this._sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,g=b.offsetHeight,e=this.showFooter?c.offsetHeight:0,f=h("quirks")||7>h("ie");this.headerScrollNode.style.height=a.style.marginTop=g+"px";a.style.marginBottom=e+"px";f&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-g-e,0)+"px",e&&(c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0)));l||(l=h("dom-scrollbar-width"),t=h("dom-scrollbar-height"),h("ie")&&
(l++,t++),n.addCssRule(".dgrid-scrollbar-width","width: "+l+"px"),n.addCssRule(".dgrid-scrollbar-height","height: "+t+"px"),17!=l&&!f&&(n.addCssRule(".dgrid-header","right: "+l+"px"),n.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header","left: "+l+"px")));f&&(b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0))},addCssRule:function(a,b){var c=n.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(c);return c},on:function(a,b){var c=m(this.domNode,a,b);h("dom-addeventlistener")||
this._listeners.push(c);return c},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();d(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject=
{};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},newRow:function(a,b,c,g,e){if(b){var f=this.insertRow(a,b,c,g,e);d(f,".ui-state-highlight");setTimeout(function(){d(f,"!ui-state-highlight")},250);return f}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(-1<(a.className+" ").indexOf("dgrid-row ")&&d(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++);while((a=a.nextSibling)&&
a.rowIndex!=b&&!a.blockRowIndex)}}},renderArray:function(a,b,c){function g(a){r=f.insertRow(a,m,null,d++,c);r.observerIndex=n;return r}function e(a){if(l=b?b.parentNode:f.contentNode)l.insertBefore(m,b||null),(r=a[a.length-1])&&f.adjustRowIndices(r);return k=a}c=c||{};var f=this,d=c.start||0,h,k,l;b||(this._lastCollection=a);if(a.observe)var n=this.observers.push(a.observe(function(a,e,g){var d,p,m;-1<e&&k[e]&&(h=k.splice(e,1)[0],h.parentNode==l&&((d=h.nextSibling)&&e!=g&&d.rowIndex--,f.removeRow(h)),
f._processScroll&&f._processScroll());if(-1<g){p=k[g];if(!p&&(p=k[g-1]))p=(p.connected||p).nextSibling;m=b&&b.parentNode||p&&p.parentNode||f.contentNode;if(h=f.newRow(a,m,p,c.start+g,c))if(h.observerIndex=n,k.splice(g,0,h),!d||g<e)d=h.previousSibling,d=!d||d.rowIndex+1==h.rowIndex||0==h.rowIndex?h:d;c.count++}e!=g&&d&&f.adjustRowIndices(d);f._onNotification(k,a,e,g)},!0))-1;var m=document.createDocumentFragment();if(a.map){if(k=a.map(g,console.error),k.then)return k.then(e)}else{k=[];for(var s=0,
q=a.length;s<q;s++)k[s]=g(a[s])}var r;return e(k)},_onNotification:function(a,b,c,g){},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,g,e){var f=e.parentId,f=this.id+"-row-"+(f?f+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),d=document.getElementById(f),h=d&&d.previousSibling;d&&this.removeRow(d);d=this.renderRow(a,e);d.className=(d.className||"")+" ui-state-default dgrid-row "+(1==g%2?"dgrid-row-odd":"dgrid-row-even");this._rowIdToObject[d.id=
f]=a;b.insertBefore(d,c||null);h&&this.adjustRowIndices(h);d.rowIndex=g;return d},renderRow:function(a,b){return d("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||d(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):
(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,d){var e,f;f=e=a.element;b=b||1;do if(a=e[0>b?"previousSibling":"nextSibling"]){do if((e=a)&&-1<(e.className+" ").indexOf(c+" ")){f=e;b+=0>b?1:-1;break}while(a=(!d||!e.hidden)&&e[0>b?"lastChild":"firstChild"])}else if(e=e.parentNode,e===this.bodyNode||e===this.headerNode)break;while(b);return f},up:function(a,b,c){a.element||(a=
this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:h("touch")?function(){return this.inherited(arguments)}:function(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:h("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},
get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:z,_setClass:q,_getClassName:z,_setClassName:q,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,
descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(c,d){var e=c[a],f=d[a];void 0===e&&(e="");void 0===f&&(f="");return e==f?0:e>f==!b?1:-1})),this.renderArray(this._lastCollection))},sort:function(a,b){u.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=
a;d(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},setShowHeader:function(a){u.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;d(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})});
//@ sourceMappingURL=List.js.map