//>>built
define("dgrid/OnDemandList","./List,./_StoreMixin,dojo/_base/declare,dojo/_base/lang,dojo/_base/Deferred,dojo/on,./util/misc,put-selector/put".split(","),function(z,A,B,w,p,C,q,k){return B([z,A],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:q.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;C(this.bodyNode,"scroll",q[this.pagingMethod](function(g){c._processScroll(g)},
null,this.pagingDelay))},renderQuery:function(c,g,i){var b={query:c,count:0,node:g,options:i};if(!g){var h={node:k(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:b,options:i};b.node=g=k(this.contentNode,"div.dgrid-preload");b.previous=h}g.rowIndex=this.minRowsPerPage;(h=this.preload)?((b.next=h.next)&&this.bodyNode.scrollTop>=h.node.offsetTop?b.previous=h:(b.next=h,b.previous=h.previous),b.previous.next=b,b.next.previous=b):this.preload=b;var l=k(g,"-div.dgrid-loading");k(l,
"div.dgrid-below").innerHTML=this.loadingMessage;var i=w.mixin(this.get("queryOptions"),i,{start:0,count:this.minRowsPerPage,query:c}),m=c(i),d=this;p.when(this.renderArray(m,g,i),function(a){return p.when(m.total||m.length,function(c){k(l,"!");var i=a.length,c=c||i;if(!c)d.noDataNode=k(d.contentNode,"div.dgrid-no-data"),d.noDataNode.innerHTML=d.noDataMessage;for(var h=0,e=0;e<i;e++)h+=d._calcRowHeight(a[e]);if(i&&h)d.rowHeight=h/i;c-=i;b.count=c;g.rowIndex=i;c?g.style.height=Math.min(c*d.rowHeight,
d.maxEmptySpace)+"px":g.style.display="none";d._previousScrollPosition&&(d.scrollTo(d._previousScrollPosition),delete d._previousScrollPosition);d._processScroll();return a})});return m},refresh:function(c){var g=c&&c.keepScrollPosition;if("undefined"===typeof g)g=this.keepScrollPosition;if(g)this._previousScrollPosition=this.getScrollPosition();this.inherited(arguments);if(this.store){var i=this;this._trackError(function(){return i.renderQuery(function(b){return i.store.query(i.query,b)})})}},_calcRowHeight:function(c){var g=
c.previousSibling;return g&&g.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,_processScroll:function(c){function g(a,c,d,e){var g=b.farOffRemoval,f=a.node;if(c>2*g){for(var h,j=f[d],l=0,m=0,n=[];h=j;){var o=b._calcRowHeight(h);if(l+o+g>c||0>j.className.indexOf("dgrid-row")&&0>j.className.indexOf("dgrid-loading"))break;var j=h[d],t,p=h.observerIndex;if(p!=t&&-1<t){var q=b.observers,r=q[t];r&&r.cancel();q[t]=0}l+=o;m+=h.count||1;t=p;b.removeRow(h,!0);n.push(h)}a.count+=m;e?(f.rowIndex-=m,
i(a)):f.style.height=f.offsetHeight+l+"px";for(var s=k("div"),a=0;a<n.length;a++)k(s,n[a]);setTimeout(function(){k(s,"!")},1)}}function i(a,c){a.node.style.height=Math.min(a.count*b.rowHeight,c?Infinity:b.maxEmptySpace)+"px"}var b=this,h=b.bodyNode,c=c&&c.scrollTop||h.scrollTop,l=h.offsetHeight+c,m,d,a=b.preload,q=b.lastScrollTop,v=b.bufferRows*b.rowHeight,x=v-b.rowHeight;for(b.lastScrollTop=c;a&&!a.node.offsetWidth;)a=a.previous;for(;a&&a!=m;){m=b.preload;b.preload=a;d=a.node;var e=d.offsetTop;if(l+
1+x<e){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(c-1-x>e+d.offsetHeight){do a=a.next;while(a&&!a.node.offsetWidth)}else{var f=((d.rowIndex?c-v:l)-e)/b.rowHeight,e=(l-c+2*v)/b.rowHeight,r=Math.max(Math.min((c-q)*b.rowHeight,b.maxRowsPerPage/2),b.maxRowsPerPage/-2),e=e+Math.min(Math.abs(r),10);0==d.rowIndex&&(f-=e);f=Math.max(f,0);10>f&&0<f&&e+f<b.maxRowsPerPage&&(e+=Math.max(0,f),f=0);e=Math.min(Math.max(e,b.minRowsPerPage),b.maxRowsPerPage,a.count);if(0==e)break;var e=Math.ceil(e),f=Math.min(Math.floor(f),
a.count-e),n=w.mixin(b.get("queryOptions"),a.options);a.count-=e;var j=d,s,u=b.queryRowsOverlap;if(r=0<d.rowIndex&&a){var o=a.previous;o&&(g(o,c-(o.node.offsetTop+o.node.offsetHeight),"nextSibling"),0<f&&o.node==d.previousSibling?(f=Math.min(a.count,f),a.previous.count+=f,i(a.previous,!0),d.rowIndex+=f,u=0):e+=f,a.count-=f);n.start=d.rowIndex-u;d.rowIndex+=e}else{if(a.next)g(a.next,a.next.node.offsetTop-l,"previousSibling",!0),j=d.nextSibling,j==a.next.node?(a.next.count+=a.count-f,a.next.node.rowIndex=
f+e,i(a.next),a.count=f,u=0):s=!0;n.start=a.count}n.count=Math.min(e+u,b.maxRowsPerPage);if(s&&j&&j.offsetWidth)s=j.offsetTop;i(a);d=k(j,"-div.dgrid-loading[style=height:"+e*b.rowHeight+"px]");k(d,"div.dgrid-"+(r?"below":"above")).innerHTML=b.loadingMessage;d.count=e;d.blockRowIndex=!0;n.query=a.query;var y=a.query(n);if(void 0===b._trackError(function(){return y}))break;(function(a,c,d,e,f){p.when(b.renderArray(f,a,n),function(){j=a.nextSibling;k(a,"!");if(e&&j&&j.offsetWidth){var c=b.getScrollPosition();
b.scrollTo({x:c.x,y:c.y+j.offsetTop-e,preserveMomentum:!0})}d&&p.when(f.total||f.length,function(a){d.count=a-d.node.rowIndex;i(d)});b._processScroll()})}).call(this,d,h,r,s,y);a=a.previous}}}})});