//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(E,F,G,B,r,q,t,p){return G([E,F],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:t.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;q(this.bodyNode,"scroll",t[this.pagingMethod](function(g){c._processScroll(g)},
null,this.pagingDelay))},renderQuery:function(c,g,k){function b(a){p(u,"!");if(a)throw f._refreshDeferred&&(f._refreshDeferred.reject(a),delete f._refreshDeferred),a;}var f=this,l={query:c,count:0,node:g,options:k},m=this.preload,d;if(!g){var a={node:p(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:l,options:k};a.node.style.height="0";l.node=g=p(this.contentNode,"div.dgrid-preload");l.previous=a}g.rowIndex=this.minRowsPerPage;m?((l.next=m.next)&&this.bodyNode.scrollTop>=m.node.offsetTop?
l.previous=m:(l.next=m,l.previous=m.previous),l.previous.next=l,l.next.previous=l):this.preload=l;var u=p(g,"-div.dgrid-loading");p(u,"div.dgrid-below").innerHTML=this.loadingMessage;k=B.mixin(this.get("queryOptions"),k,{start:0,count:this.minRowsPerPage,query:c});this._trackError(function(){return d=c(k)});if("undefined"===typeof d)b();else return r.when(f.renderArray(d,g,k),function(a){return r.when(d.total||d.length,function(b){p(u,"!");var c=a.length;0===b&&(f.noDataNode=p(f.contentNode,"div.dgrid-no-data"),
f.noDataNode.innerHTML=f.noDataMessage);for(var k=0,m=0;m<c;m++)k+=f._calcRowHeight(a[m]);c&&k&&(f.rowHeight=k/c);b-=c;l.count=b;g.rowIndex=c;b?g.style.height=Math.min(b*f.rowHeight,f.maxEmptySpace)+"px":g.style.display="none";f._previousScrollPosition&&(f.scrollTo(f._previousScrollPosition),delete f._previousScrollPosition);f._processScroll();f._refreshDeferred&&(f._refreshDeferred.resolve(d),delete f._refreshDeferred);return a},b)},b),d},refresh:function(c){var g=this,k=c&&c.keepScrollPosition,
b;"undefined"===typeof k&&(k=this.keepScrollPosition);k&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return k=this._refreshDeferred=new r,b=g.renderQuery(function(b){return g.store.query(g.query,b)}),"undefined"===typeof b&&k.reject(),k.then(function(b){setTimeout(function(){q.emit(g.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:g,results:b})},0);delete g._refreshDeferred;return b},function(b){delete g._refreshDeferred;throw b;
})},resize:function(){this.inherited(arguments);this._processScroll()},_calcRowHeight:function(c){var g=c.previousSibling;return g&&g.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,_processScroll:function(c){function g(a,c,d,g){var h=b.farOffRemoval,f=a.node;if(c>2*h){for(var e,l=f[d],m=0,n=0,r=[];e=l;){var s=b._calcRowHeight(e);if(m+s+h>c||0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;var l=e[d],q,t=e.observerIndex;if(t!=q&&-1<q){var u=b.observers,v=u[q];
v&&v.cancel();u[q]=0}m+=s;n+=e.count||1;q=t;b.removeRow(e,!0);r.push(e)}a.count+=n;g?(f.rowIndex-=n,k(a)):f.style.height=f.offsetHeight+m+"px";var w=p("div",r);setTimeout(function(){p(w,"!")},1)}}function k(a,c){a.node.style.height=Math.min(a.count*b.rowHeight,c?Infinity:b.maxEmptySpace)+"px"}var b=this,f=b.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;var l=f.offsetHeight+c,m,d,a=b.preload,u=b.lastScrollTop,z=b.bufferRows*b.rowHeight,q=z-b.rowHeight,t,C,A;for(b.lastScrollTop=c;a&&!a.node.offsetWidth;)a=
a.previous;for(;a&&a!=m;){m=b.preload;b.preload=a;d=a.node;var h=d.offsetTop;if(l+1+q<h){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(c-1-q>h+d.offsetHeight){do a=a.next;while(a&&!a.node.offsetWidth)}else{var e=((d.rowIndex?c-z:l)-h)/b.rowHeight,h=(l-c+2*z)/b.rowHeight,w=Math.max(Math.min((c-u)*b.rowHeight,b.maxRowsPerPage/2),b.maxRowsPerPage/-2),h=h+Math.min(Math.abs(w),10);0==d.rowIndex&&(e-=h);e=Math.max(e,0);10>e&&(0<e&&h+e<b.maxRowsPerPage)&&(h+=Math.max(0,e),e=0);h=Math.min(Math.max(h,
b.minRowsPerPage),b.maxRowsPerPage,a.count);if(0==h)return;var h=Math.ceil(h),e=Math.min(Math.floor(e),a.count-h),s=B.mixin(b.get("queryOptions"),a.options);a.count-=h;var n=d,x,y=b.queryRowsOverlap;if(w=0<d.rowIndex&&a){var v=a.previous;v&&(g(v,c-(v.node.offsetTop+v.node.offsetHeight),"nextSibling"),0<e&&v.node==d.previousSibling?(e=Math.min(a.count,e),a.previous.count+=e,k(a.previous,!0),d.rowIndex+=e,y=0):h+=e,a.count-=e);s.start=d.rowIndex-y;d.rowIndex+=h}else a.next&&(g(a.next,a.next.node.offsetTop-
l,"previousSibling",!0),n=d.nextSibling,n==a.next.node?(a.next.count+=a.count-e,a.next.node.rowIndex=e+h,k(a.next),a.count=e,y=0):x=!0),s.start=a.count;s.count=Math.min(h+y,b.maxRowsPerPage);x&&(n&&n.offsetWidth)&&(x=n.offsetTop);k(a);d=p(n,"-div.dgrid-loading[style\x3dheight:"+h*b.rowHeight+"px]");p(d,"div.dgrid-"+(w?"below":"above")).innerHTML=b.loadingMessage;d.count=h;d.blockRowIndex=!0;s.query=a.query;var D=a.query(s);if(void 0===b._trackError(function(){return D})){p(d,"!");return}(function(a,
c,d,f,e){A=r.when(b.renderArray(e,a,s),function(c){C=e;n=a.nextSibling;p(a,"!");if(f&&n&&n.offsetWidth){var g=b.getScrollPosition();b.scrollTo({x:g.x,y:g.y+n.offsetTop-f,preserveMomentum:!0})}d&&r.when(e.total||e.length,function(a){d.count=a-d.node.rowIndex;k(d)});b._processScroll();return c},function(b){p(a,"!");throw b;})}).call(this,d,f,w,x,D);a=a.previous}}if(A&&(t=this._refreshDeferred))delete this._refreshDeferred,r.when(A,function(){t.resolve(C)})}})});
//@ sourceMappingURL=OnDemandList.js.map