//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(G,H,I,D,t,x,u,p){return I([G,H],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:1,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;x(this.bodyNode,"scroll",u[this.pagingMethod](function(d){c._processScroll(d)},
null,this.pagingDelay))},renderQuery:function(c,d,h){function f(c){p(b,"!");if(c)throw a._refreshDeferred&&(a._refreshDeferred.reject(c),delete a._refreshDeferred),c;}var a=this,m={query:c,count:0,node:d,options:h},l=this.preload,r;if(!d){var e={node:p(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:m,options:h};e.node.style.height="0";m.node=d=p(this.contentNode,"div.dgrid-preload");m.previous=e}d.rowIndex=this.minRowsPerPage;l?((m.next=l.next)&&this.bodyNode.scrollTop>=l.node.offsetTop?
m.previous=l:(m.next=l,m.previous=l.previous),m.previous.next=m,m.next.previous=m):this.preload=m;var b=p(d,"-div.dgrid-loading");p(b,"div.dgrid-below").innerHTML=this.loadingMessage;h=D.mixin(this.get("queryOptions"),h,{start:0,count:this.minRowsPerPage},"level"in c?{queryLevel:c.level}:null);this._trackError(function(){return r=c(h)});if("undefined"===typeof r)f();else return t.when(a.renderArray(r,d,h),function(c){return t.when("undefined"===typeof r.total?r.length:r.total,function(f){var e=c.length,
l=d.parentNode,q=a.noDataNode;p(b,"!");"queryLevel"in h||(a._total=f);0===f&&(q&&(p(q,"!"),delete a.noDataNode),a.noDataNode=q=p("div.dgrid-no-data"),l.insertBefore(q,a._getFirstRowSibling(l)),q.innerHTML=a.noDataMessage);for(q=l=0;q<e;q++)l+=a._calcRowHeight(c[q]);e&&l&&(a.rowHeight=l/e);f-=e;m.count=f;d.rowIndex=e;f?d.style.height=Math.min(f*a.rowHeight,a.maxEmptySpace)+"px":d.style.display="none";a._previousScrollPosition&&(a.scrollTo(a._previousScrollPosition),delete a._previousScrollPosition);
a._processScroll();a._refreshDeferred&&(a._refreshDeferred.resolve(r),delete a._refreshDeferred);return c},f)},f),r},refresh:function(c){var d=this,h=c&&c.keepScrollPosition,f;"undefined"===typeof h&&(h=this.keepScrollPosition);h&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return h=this._refreshDeferred=new t,f=d.renderQuery(function(a){return d.store.query(d.query,a)}),"undefined"===typeof f&&h.reject(),h.then(function(a){setTimeout(function(){x.emit(d.domNode,
"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:d,results:a})},0);delete d._refreshDeferred;return a},function(a){delete d._refreshDeferred;throw a;})},resize:function(){this.inherited(arguments);this._processScroll()},_getFirstRowSibling:function(c){return c.lastChild},_calcRowHeight:function(c){var d=c.previousSibling;return(d=d&&!/\bdgrid-preload\b/.test(d.className)&&d)?c.offsetTop-d.offsetTop:c.offsetHeight},lastScrollTop:0,_processScroll:function(c){function d(b,c,d,f){var e=a.farOffRemoval,
g=b.node;if(c>2*e){for(var k,l=g[d],m=0,n=0,q=[];k=l;){var r=a._calcRowHeight(k);if(m+r+e>c||0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;l=k[d];m+=r;n+=k.count||1;a.removeRow(k,!0);q.push(k)}b.count+=n;f?(g.rowIndex-=n,h(b)):g.style.height=g.offsetHeight+m+"px";var s=p("div",q);setTimeout(function(){p(s,"!")},1)}}function h(b,c){b.node.style.height=Math.min(b.count*a.rowHeight,c?Infinity:a.maxEmptySpace)+"px"}function f(a,b){do a=b?a.next:a.previous;while(a&&!a.node.offsetWidth);
return a}var a=this,m=a.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;var l=m.offsetHeight+c,r,e,b=a.preload,x=a.lastScrollTop,A=a.bufferRows*a.rowHeight,u=A-a.rowHeight,E,q,B,C=!0;for(a.lastScrollTop=c;b&&!b.node.offsetWidth;)b=b.previous;for(;b&&b!=r;){r=a.preload;a.preload=b;e=b.node;var g=e.offsetTop;if(l+1+u<g)b=f(b,C=!1);else if(c-1-u>g+e.offsetHeight)b=f(b,C=!0);else{var k=((e.rowIndex?c-A:l)-g)/a.rowHeight,g=(l-c+2*A)/a.rowHeight,y=Math.max(Math.min((c-x)*a.rowHeight,a.maxRowsPerPage/
2),a.maxRowsPerPage/-2),g=g+Math.min(Math.abs(y),10);0==e.rowIndex&&(k-=g);k=Math.max(k,0);10>k&&(0<k&&g+k<a.maxRowsPerPage)&&(g+=Math.max(0,k),k=0);g=Math.min(Math.max(g,a.minRowsPerPage),a.maxRowsPerPage,b.count);if(0==g)b=f(b,C);else{var g=Math.ceil(g),k=Math.min(Math.floor(k),b.count-g),n=D.mixin(a.get("queryOptions"),b.options);b.count-=g;var s=e,z,v=a.queryRowsOverlap;if(y=0<e.rowIndex&&b){var w=b.previous;w&&(d(w,c-(w.node.offsetTop+w.node.offsetHeight),"nextSibling"),0<k&&w.node==e.previousSibling?
(k=Math.min(b.count,k),b.previous.count+=k,h(b.previous,!0),e.rowIndex+=k,v=0):g+=k,b.count-=k);n.start=e.rowIndex-v;n.count=Math.min(g+v,a.maxRowsPerPage);e.rowIndex=n.start+n.count}else b.next&&(d(b.next,b.next.node.offsetTop-l,"previousSibling",!0),s=e.nextSibling,s==b.next.node?(b.next.count+=b.count-k,b.next.node.rowIndex=k+g,h(b.next),b.count=k,v=0):z=!0),n.start=b.count,n.count=Math.min(g+v,a.maxRowsPerPage);z&&(s&&s.offsetWidth)&&(z=s.offsetTop);h(b);e=p(s,"-div.dgrid-loading[style\x3dheight:"+
g*a.rowHeight+"px]");p(e,"div.dgrid-"+(y?"below":"above")).innerHTML=a.loadingMessage;e.count=g;"level"in b.query&&(n.queryLevel=b.query.level);if("queryLevel"in n||!(n.start>a._total||0>n.count)){var F=b.query(n);if(void 0===a._trackError(function(){return F})){p(e,"!");return}(function(b,c,d,f,e){B=t.when(a.renderArray(e,b,n),function(c){q=e;s=b.nextSibling;p(b,"!");if(f&&s&&s.offsetWidth){var g=a.getScrollPosition();a.scrollTo({x:g.x,y:g.y+s.offsetTop-f,preserveMomentum:!0})}t.when(e.total||e.length,
function(b){"queryLevel"in n||(a._total=b);d&&(d.count=b-d.node.rowIndex,h(d))});a._processScroll();return c},function(a){p(b,"!");throw a;})}).call(this,e,m,y,z,F);b=b.previous}}}}if(B&&(E=this._refreshDeferred))delete this._refreshDeferred,t.when(B,function(){E.resolve(q)})},removeRow:function(c,d){if(c){var h=c.previousSibling,f=c.nextSibling,h=h&&(null!=h.observerIndex?h.observerIndex:h.previousObserverIndex),a=f&&(null!=f.observerIndex?f.observerIndex:f.nextObserverIndex),f=c.observerIndex;c.observerIndex=
void 0;d&&(c.nextObserverIndex=a,c.previousObserverIndex=h);if(this.cleanEmptyObservers&&(-1<f&&f!==h&&f!==a)&&(h=this.observers,a=h[f]))a.cancel(),this._numObservers--,h[f]=0}this.inherited(arguments)}})});
//@ sourceMappingURL=OnDemandList.js.map