//>>built
define("dgrid/TouchScroll","dojo/_base/declare,dojo/on,./util/touch,./util/has-css3,put-selector/put,xstyle/css!./css/TouchScroll.css".split(","),function(E,p,s,n,h){function t(c,a,d){var f=c.touchNode,b=l[c.id],k,e,i;if("object"!==typeof a)i=a,a=d,d=e=!0;else{d="x"in a;e="y"in a;if(!d||!e)k=c.getScrollPosition();i=d?a.x:k.x;a=e?a.y:k.y}f.style[g]=j+-i+"px,"+-a+"px"+m;b&&d&&c._scrollbarXNode&&(c._scrollbarXNode.style[g]=j+i*b.parentWidth/b.scrollWidth+"px,0"+m);b&&e&&c._scrollbarYNode&&(c._scrollbarYNode.style[g]=
j+"0,"+a*b.parentHeight/b.scrollHeight+"px"+m);p.emit(c.touchNode.parentNode,"scroll",{scrollLeft:i,scrollTop:a})}function w(c){return l[c.id]?F.exec(window.getComputedStyle(c.touchNode)[g]):u.exec(c.touchNode.style[g])}function G(c){var a=this.widget,a=[this.node,a._scrollbarXNode,a._scrollbarYNode],d=a.length;if(this.timer)clearTimeout(this.timer),this.timer=null;for(this.transitionHandler&&this.transitionHandler.remove();d--;)a[d]&&(a[d].style[o+"Duration"]="0");(!c||!c.preserveScrollbars)&&h(this.node.parentNode,
".touchscroll-fadeout");delete this.resetEffects}function H(c){var a=c.widget,d=a.touchNode,f=a.id,b=0,k=0,e;if(s.countCurrentTouches(c,d)===a.touchesToScroll){if(e=w(a))b=+e[1],k=+e[2];if(e=l[f])e.resetEffects&&e.resetEffects({preserveScrollbars:!0}),d.style[g]=j+b+"px,"+k+"px"+m,q[f]=e;c=c.targetTouches[0];e=l[f]={widget:a,node:d,startX:b-c.pageX,startY:k-c.pageY,lastX:b,lastY:k,pageX:c.pageX,pageY:c.pageY,tickFunc:function(){var a=l[f],c,b;if(a)(c=u.exec(a.node.style[g]))?(b=+c[1],c=+c[2],a.velX=
b-a.lastX,a.velY=c-a.lastY,a.lastX=b,a.lastY=c):a.lastX=a.lastY=0,a.timer=setTimeout(a.tickFunc,x)}};e.timer=setTimeout(e.tickFunc,x)}}function I(c){var a=c.widget,d=a.id,f=a.touchesToScroll,b=l[d],k,e;if(!b||(k=s.countCurrentTouches(c,a.touchNode))!==f)k>f&&a.cancelTouchScroll();else{k=c.targetTouches;f=k[0];if(!b.scrollbarsShown&&(q[d]||Math.abs(f.pageX-b.pageX)>a.scrollThreshold||Math.abs(f.pageY-b.pageY)>a.scrollThreshold)){var d=a.touchNode,i=d.parentNode,g=i.offsetWidth-y,j=i.offsetHeight-y,
m=b.scrollWidth=d.scrollWidth,z=b.scrollHeight=d.scrollHeight,n=b.parentWidth=i.offsetWidth,o=b.parentHeight=i.offsetHeight;m>n?(a._scrollbarXNode||(e=h(i,"div.touchscroll-x")),e=a._scrollbarXNode=a._scrollbarXNode||h(e,"div.touchscroll-bar"),e.style.width=g*g/m+"px",e.style.left=d.offsetLeft+"px",h(i,".touchscroll-scrollable-x"),b.scrollableX=!0):h(i,"!touchscroll-scrollable-x");z>o?(a._scrollbarYNode||(e=h(i,"div.touchscroll-y")),e=a._scrollbarYNode=a._scrollbarYNode||h(e,"div.touchscroll-bar"),
e.style.height=j*j/z+"px",e.style.top=d.offsetTop+"px",h(i,".touchscroll-scrollable-y"),b.scrollableY=!0):h(i,"!touchscroll-scrollable-y");h(i,"!touchscroll-fadeout");b.scrollbarsShown=!0;for(e=k.length;e--;)k[e].touchScrolled=!0}c.preventDefault();if(b.scrollbarsShown&&(b.scrollableX||b.scrollableY))c=b.scrollableX?b.startX+f.pageX:0,f=b.scrollableY?b.startY+f.pageY:0,e=b.scrollableX?-(b.scrollWidth-b.parentWidth):0,b=b.scrollableY?-(b.scrollHeight-b.parentHeight):0,0<c?c/=2:c<e&&(c=e-(e-c)/2),0<
f?f/=2:f<b&&(f=b-(b-f)/2),t(a,-c,-f)}}function J(c){var a=c.widget,d=a.id;l[d]&&s.countCurrentTouches(c,a.touchNode)==a.touchesToScroll-1&&K(d)}function A(c,a,d){function f(){delete b.transitionHandler;b.resetEffects();delete l[c]}var b=l[c],k=b.widget,e=b.node,i=b.scrollableX?Math.max(Math.min(0,a),-(b.scrollWidth-b.parentWidth)):a,h=b.scrollableY?Math.max(Math.min(0,d),-(b.scrollHeight-b.parentHeight)):d;delete b.timer;if(i!=a||h!=d){b.transitionHandler=p.once(e,L,f);e.style[o+"Duration"]=k.bounceDuration+
"ms";e.style[g]=j+i+"px,"+h+"px"+m;if(i!=a&&b.scrollableX)e=b.widget._scrollbarXNode,e.style[o+"Duration"]=k.bounceDuration+"ms",e.style[g]=a>i?j+"0,0"+m:j+(e.parentNode.offsetWidth-e.offsetWidth)+"px,0"+m;if(h!=d&&b.scrollableY)e=b.widget._scrollbarYNode,e.style[o+"Duration"]=k.bounceDuration+"ms",e.style[g]=d>h?j+"0,0"+m:j+"0,"+(e.parentNode.offsetHeight-e.offsetHeight)+"px"+m}else f()}function K(c){var a=l[c],d=q[c],f,b;delete q[c];a.timer&&clearTimeout(a.timer);a.resetEffects=G;(f=u.exec(a.node.style[g]))?
(b=+f[1],f=+f[2]):b=f=0;if(!a.velX&&!a.velY||(0<=b||b<=-(a.scrollWidth-a.parentWidth))&&(0<=f||f<=-(a.scrollHeight-a.parentHeight)))A(c,b,f);else{if(d&&(d.velX||d.velY)&&(0>=a.velX&&0>=d.velX||0<=a.velX&&0<=d.velX)&&(0>=a.velY&&0>=d.velY||0<=a.velY&&0<=d.velY))a.velX=1.15*(a.velX+d.velX),a.velY=1.15*(a.velY+d.velY);a.lastX=b;a.lastY=f;a.calcFunc=function(){var a=l[c],b,d,f,g,h,j;if(a)if(b=a.widget,h=b.glideDecel(a.velX),j=b.glideDecel(a.velY),Math.abs(h)>=B||Math.abs(j)>=B){f=a.lastX+h;g=a.lastY+
j;if(0<f||f<-(a.scrollWidth-a.parentWidth))for(d=6;d--;)h=b.glideDecel(h);if(0<g||g<-(a.scrollHeight-a.parentHeight))for(d=6;d--;)j=b.glideDecel(j);t(b,-f,-g);a.lastX=f;a.lastY=g;a.velX=h;a.velY=j;a.timer=setTimeout(a.calcFunc,C)}else A(c,a.lastX,a.lastY)};a.timer=setTimeout(a.calcFunc,C)}}var x=50,C=30,l={},q={},B=1,y=8,u=/^translate(?:3d)?\((-?\d+)(?:\.\d*)?(?:px)?, (-?\d+)/,F=/^matrix\(1, 0, 0, 1, (-?\d+)(?:\.\d*)?(?:px)?, (-?\d+)/,v=n("css-transitions"),L=n("transitionend"),r=n("css-transforms"),
n=n("css-transforms3d"),D,o,g,j,m;n?(j="translate3d(",m=",0)"):r&&(j="translate(",m=")");if(!v||!j)return console.warn("CSS3 features unavailable for touch scroll effects."),function(){};g=n||r;g=!0===g?"transform":g+"Transform";o=!0===v?"transition":v+"Transition";D=!0===r?"":"-"+r.toLowerCase()+"-";return E(null,{touchesToScroll:1,touchNode:null,scrollThreshold:10,bounceDuration:300,postCreate:function(){this._initTouch();this.inherited(arguments)},_initTouch:function(){function c(){f.cancelTouchScroll()}
function a(a){return function(b){b.widget=f;b.cancelTouchScroll=c;a.call(this,b)}}var d=this.touchNode=this.touchNode||this.containerNode,f=this,b;!d||!d.parentNode?console.warn("TouchScroll requires a nested node upon which to operate."):(b=d.parentNode,b.style.overflow="hidden",d.style[o+"Property"]=D+"transform",d.style[o+"TimingFunction"]="cubic-bezier(0.33, 0.66, 0.66, 1)",this._touchScrollListeners=[p(b,"touchstart",a(H)),p(b,"touchmove",a(I)),p(b,"touchend,touchcancel",a(J))])},destroy:function(){for(var c=
this._touchScrollListeners.length;c--;)this._touchScrollListeners[c].remove();delete l[this.id];this.inherited(arguments)},scrollTo:function(c){var a=l[this.id],d=this.touchNode,f=d.parentNode;!c.preserveMomentum&&a&&a.resetEffects&&a.resetEffects();if(c.x)c.x=Math.max(0,Math.min(c.x,d.scrollWidth-f.offsetWidth));if(c.y)c.y=Math.max(0,Math.min(c.y,d.scrollHeight-f.offsetHeight));t(this,c)},getScrollPosition:function(){var c=w(this);return c?{x:-c[1],y:-c[2]}:{x:0,y:0}},cancelTouchScroll:function(){var c=
l[this.id];c&&(c.resetEffects?c.resetEffects():(c.timer&&clearTimeout(c.timer),h(c.node.parentNode,".touchscroll-fadeout")),delete l[this.id])},glideDecel:function(c){return 0.9*c}})});