//>>built
define("xstyle/core/ruleModel",["xstyle/core/elemental","put-selector/put"],function(v,n){function w(a,b){return a&&a.then?a.then(b):b(a)}function q(a,b,c){return w(a,function(a){var d=b[0];if(!a)return c(d||a);if(d&&a.get)return q(a.get(d),b.slice(1),c);if(a.receive)return a.receive(d?function(a){q(a,b,c)}:c);if(d)return q(a[d],b.slice(1),c);c(a)})}function G(a,b,c){q(a,b.slice(0,b.length-1),function(a){var d=b[b.length-1];a.set?a.set(d,c):a[d]=c})}function x(){}function A(a){this.caller=a;this.args=
[]}function B(a,b){C++;a=a.sort?a:[a];return function(c,e){for(var d=c,h=0,m=a.length;h<m;h++){var f=g,g=a[h];try{if(g.eachProperty)if(g.args)if("("==g.operator){var k=a[h+1];k&&k.eachProperty&&n(d,k.selector);var r=g.args.toString(),u=t(g.parent,0,r);(function(a){w(u,function(c){c.forElement&&(c=c.forElement(a));var d=a.appendChild(y.createTextNode("Loading"));c.receive(function(b){if(b&&b.sort){d&&(d.parentNode.removeChild(d),d=null);var l=k&&k.eachProperty&&k.get("each");l&&(l=B(l,k));b.forEach(l?
function(b){l(a,b)}:function(b){n(a,H[a.tagName]||"div",b)})}else"value"in a?(a.value=b,a["-x-variable"]=c):d.nodeValue=b},b,r)})})(d)}else n(d,g.toString());else n(d,g.selector),v.update(d,g.selector);else if("string"==typeof g){"\x3d"==g.charAt(0)&&(g=g.slice(1));var l=d,k=a[h+1];g.replace(/(,\s*)?(\.|#)?([-\w%$|\.\#]+)(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,function(a,h,g,r,u,m){h&&(l=c);l=g?n(l,(f&&f.args?"":"span")+g+r):(a=b.getDefinition(r))?a.appendTo(l):n(l,r);u&&l.setAttribute(u,""===
m?u:m);e&&(l.item=e);l!=d&&(l!=c&&(!k||!k.eachProperty))&&v.update(l);d=l})}else d.appendChild(y.createTextNode(g.value))}catch(z){console.error(z,z.stack),d.appendChild(y.createTextNode(z))}}return d}}function t(a,b,c){function e(){var a=h.length+1,b=[],c=[],d,e,g=function(h){return function(g){b[h]=g;a--;if(0>=a){e=!0;d=k?k.apply(this,b):b[0];for(g=0;g<c.length;g++)c[g](d)}}};if(k)for(var m=0;m<h.length;m++){var f=h[m];q(f[0],f.slice(1),g(m))}else{var f=h[0],p={then:function(a){c?c.push(a):a(p)}};
w(f[0],function(a){p=a;for(var b=1;b<f.length;b++)if(p&&p.get)p=p.get(f[b]);else{p={receive:function(b){q(a,f.slice(1),b)},put:function(b){G(a,f.slice(1),b)}};break}for(b=0;b<c.length;b++)c[b](p);c=null});return p}g(-1)();return d&&d.then?d:{receive:function(a){c&&c.push(a);e&&a(d)}}}var d=a["var-expr-"+b];if(h)return d;var h=[],m;h.id=C++;var f=[],g;c=c.join?c.join(""):c.toString();d=c.match(/^[\w_$\/\.-]*$/);c=c.replace(/("[^\"]*")|([\w_$\.\/-]+)/g,function(b,c,d){if(d){if(D.hasOwnProperty(d))return D[d];
g=d.split("/");b=g.join("_");f.push(b);h.push(g);c=g[0];d=a.getDefinition(c);if("string"==typeof d||d instanceof Array)d=t(a,c,d);else if(!d)throw Error('Could not find reference "'+c+'"');d.forElement&&(m=!0);g[0]=d}return b});if(!d)var k=Function.apply(this,f.concat(["return ("+c+")"]));h.func=k;a["var-expr-"+b]=h;return a["var-expr-"+b]=m?{forElement:function(b){for(var c,d=b;!I.call(b,a.selector);)b=b.parentNode;for(b=0;b<h.length;b++){var g=h[b],f=g[0];f.forElement&&(f=g[0]=f.forElement(d));
g=f.element;if(d!=c){for(;d!=g;){if(d==c)return;d=d.parentNode}c=d}}d=c["expr-result-"+h.id];d||(c["expr-result-"+h.id]=d=e(),d.element=c);return d}}:e()}var C=0,H={TABLE:"tr",TBODY:"tr",TR:"td",UL:"li",OL:"li",SELECT:"option"},J={"{":"}","[":"]","(":")"},K={display:["none",""],visibility:["hidden","visible"],"float":["none","left"]},L={"":0,"false":0,"true":1},y=document,s=y.createElement("div"),E=Object.create||function(a){function b(){}b.prototype=a;return new b},f=navigator.userAgent,F=-1<f.indexOf("WebKit")?
"-webkit-":-1<f.indexOf("Firefox")?"-moz-":-1<f.indexOf("MSIE")?"-ms-":-1<f.indexOf("Opera")?"-o-":"";x.prototype={eachProperty:function(a){for(var b=this.values||0,c=0;c<b.length;c++){var e=b[c];a.call(this,e||"unnamed",b[e])}},fullSelector:function(){return(this.parent?this.parent.fullSelector():"")+(this.selector||"")+" "},newRule:function(a){return(this.rules||(this.rules={}))[a]=new x},newCall:function(a,b,c){return new A(a)},addSheetRule:function(a,b){if(b&&"@"!=a.charAt(0))try{var c=this.styleSheet,
e=c.cssRules||c.rules,d=-1<this.ruleIndex?this.ruleIndex:e.length;c.addRule(a,b,d);return e[d]}catch(h){console.warn("Unable to add rule",h.message)}},onRule:function(){var a=this.getCssRule();if(this.installStyles)for(var b=0;b<this.installStyles.length;b++){var c=this.installStyles[b];a.style[c[0]]=c[1]}},setStyle:function(a,b){this.cssRule?this.cssRule.style[a]=b:(this.installStyles||(this.installStyles=[])).push([a,b])},getCssRule:function(){this.cssRule||(this.cssRule=this.addSheetRule(this.selector,
this.cssText));return this.cssRule},get:function(a){return this.values[a]},declareProperty:function(a,b,c){if(b.length)if("\x3e"==b[0].toString().charAt(0))a||(this.generator=b,b=B(b,this),v.addRenderer(this,b));else{var e=a in s.style||this.getDefinition(a,!0);if(!c||!e){c=this.definitions||(this.definitions={});var d=b[0];if(d.indexOf&&-1<d.indexOf(","))for(var d=b.join("").split(/\s*,\s*/),h=[],f=0;f<d.length;f++)h[f]=t(this,a,d[f]);c[a]=h||t(this,a,b);e&&console.warn('Overriding existing property "'+
a+'"')}}else c=this.definitions||(this.definitions={}),c[a]=b},setValue:function(a,b,c){var e=this.values||(this.values=[]);e.push(a);e[a]=b;var d=b.calls;if(d)for(e=0;e<d.length;e++){var h=d[e],f=h.ref;f&&"function"==typeof f.call&&f.call(h,this,a,b)}if(a){var n=a;do{if(d=(c||this).getDefinition(a,!0)){for(var g=this,d=d.splice?d:[d],e=0;e<d.length;e++){var k;w(d[e],function(a){k=a.put&&a.put(b,g,n)});if(k){k.then&&k.then(function(){});break}}break}a=a.substring(0,a.lastIndexOf("-"))}while(a)}},
put:function(a,b){this.extend(b);if("default"!=a&&a&&"string"==typeof a&&this.values)for(var c=a.toString().split(" "),e=0;e<c.length;e++){var d=this.values[e];d&&b.setValue(d,c[e],this)}},extend:function(a,b){console.log("extending ",a);var c=this;a.cssText+=c.cssText;"values,variables,calls".replace(/\w+/g,function(b){var e=c[b];e&&(a[b]=E(e))});if(b){var e=c.definitions;e&&(a.definitions=E(e));a.tagName=c.tagName||a.tagName}c.eachProperty(function(b,c){a.setValue(b,c)});c.generator&&a.declareProperty(null,
c.generator)},getDefinition:function(a){var b=this;do var c=b.definitions&&b.definitions[a],b=b.parent;while(!c&&b);return c},appendTo:function(a){return n(a,(this.tagName||"")+this.selector)},cssText:""};f=A.prototype=new x;f.declareProperty=f.setValue=function(a,b){this.args.push(b)};f.toString=function(){var a=this.operator;return a+this.args+J[a]};var D={"true":!0,"false":!1,"null":"null","typeof":"typeof",or:"||",and:"\x26\x26"},I=s.matches||s.webkitMatchesSelector||s.msMatchesSelector||s.mozMatchesSelector,
f=new x;f.root=!0;f.definitions={Math:Math,module:function(a){return{then:function(b){require([a],b)}}},item:{forElement:function(a){for(;!a.item;)a=a.parentNode;return{element:a,receive:function(b){b(a.item)}}}},prefix:{put:function(a,b,c){if("string"==typeof s.style[F+c])return b.setStyle(F+c,a),!0}},"var":{put:function(a,b,c){(b.variables||(b.variables={}))[c]=a;b=(b=b.variableListeners)&&b[c]||0;for(c=0;c<b.length;c++)b[c](a)},call:function(a,b,c,e){this.receive(function(a){a=e.toString().replace(/var\([^)]+\)/g,
a);var f=L[a];if(-1<f){var m=K[c];m&&(a=m[f])}b.setStyle(c,a)},b,a.args[0])},receive:function(a,b,c){var e=b;do{var d=e.variables&&e.variables[c]||e.definitions&&e.definitions[c];if(d){if(d.receive)return d.receive(a,b,c);b=e.variableListeners||(e.variableListeners={});(b[c]||(b[c]=[])).push(a);return a(d)}e=e.parent}while(e);a()}},on:{put:function(a,b,c){q(t(b,c,a),0,function(a){v.on(document,c.slice(3),b.selector,a)})}}};return f});
//@ sourceMappingURL=ruleModel.js.map