//>>built
define("dojo/on",["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(v,w,h){function x(a,b,c,d,e){if(d=b.match(/(.*):(.*)/))return b=d[2],d=d[1],k.selector(d,b).call(e,a,c);h("touch")&&(y.test(b)&&(c=n(c)),!h("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,c=n(c)));p&&(c=p(c));if(a.addEventListener){var g=b in m,f=g?m[b]:b;a.addEventListener(f,c,g);return{remove:function(){a.removeEventListener(f,c,g)}}}if(q&&a.attachEvent)return q(a,"on"+b,c);throw Error("Target must be an event emitter");
}function z(){this.cancelable=!1;this.defaultPrevented=!0}function A(){this.bubbles=!1}var r=window.ScriptEngineMajorVersion;h.add("jscript",r&&r()+ScriptEngineMinorVersion()/10);h.add("event-orientationchange",h("touch")&&!h("android"));h.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);var k=function(a,b,c,d){return"function"==typeof a.on&&"function"!=typeof b&&!a.nodeType?a.on(b,c):k.parse(a,b,c,x,d,this)};k.pausable=
function(a,b,c,d){var e;a=k(a,b,function(){if(!e)return c.apply(this,arguments)},d);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};k.once=function(a,b,c,d){var e=k(a,b,function(){e.remove();return c.apply(this,arguments)});return e};k.parse=function(a,b,c,d,e,g){if(b.call)return b.call(g,a,c);if(-1<b.indexOf(",")){b=b.split(/\s*,\s*/);for(var f=[],k=0,h;h=b[k++];)f.push(d(a,h,c,e,g));f.remove=function(){for(var a=0;a<f.length;a++)f[a].remove()};return f}return d(a,b,c,e,g)};var y=/^touch/;
k.selector=function(a,b,c){return function(d,e){function g(b){for(f=f&&f.matches?f:w.query;!f.matches(b,a,d);)if(b==d||!1===c||!(b=b.parentNode)||1!=b.nodeType)return;return b}var f="function"==typeof a?{matches:a}:this,h=b.bubble;return h?k(d,h(g),e):k(d,b,function(a){var b=g(a.target);return b&&e.call(b,a)})}};var B=[].slice,C=k.emit=function(a,b,c){var d=B.call(arguments,2),e="on"+b;if("parentNode"in a){var g=d[0]={},f;for(f in c)g[f]=c[f];g.preventDefault=z;g.stopPropagation=A;g.target=a;g.type=
b;c=g}do a[e]&&a[e].apply(a,d);while(c&&c.bubbles&&(a=a.parentNode));return c&&c.cancelable&&c},m={};if(!h("event-stopimmediatepropagation"))var D=function(){this.modified=this.immediatelyStopped=!0},p=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=D,a.apply(this,arguments)}};if(h("dom-addeventlistener"))m={focusin:"focus",focusout:"blur"},k.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=a.ownerDocument.createEvent("HTMLEvents");d.initEvent(b,
!!c.bubbles,!!c.cancelable);for(var e in c)e in d||(d[e]=c[e]);return a.dispatchEvent(d)&&d}return C.apply(k,arguments)};else{k._fixEvent=function(a,b){a||(a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{l&&(a.type==l.type&&a.srcElement==l.target)&&(a=l)}catch(c){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=b||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=
E,a.preventDefault=F),a.type){case "keypress":var d="charCode"in a?a.charCode:a.keyCode;10==d?(d=0,a.keyCode=13):13==d||27==d?d=0:3==d&&(d=99);a.charCode=d;d=a;d.keyChar=d.charCode?String.fromCharCode(d.charCode):"";d.charOrCode=d.keyChar||d.keyCode}return a};var l,s=function(a){this.handle=a};s.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var G=function(a){return function(b){b=k._fixEvent(b,this);var c=a.call(this,b);b.modified&&(l||setTimeout(function(){l=null}),l=b);return c}},
q=function(a,b,c){c=G(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>h("jscript"))&&!h("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var d=a[b];if(!d||!d.listeners){var e=d,d=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");d.listeners=[];a[b]=d;d.global=
this;e&&d.listeners.push(_dojoIEListeners_.push(e)-1)}d.listeners.push(a=d.global._dojoIEListeners_.push(c)-1);return new s(a)}return v.after(a,b,c,!0)},E=function(){this.cancelBubble=!0},F=k._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(h("touch"))var t=function(){},u=window.orientation,n=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(e){}if(b.type){if(h("mozilla")){var c=
{},g;for(g in b)c[g]=b[g]}else t.prototype=b,c=new t;c.preventDefault=function(){b.preventDefault()};c.stopPropagation=function(){b.stopPropagation()}}else c=b,c.type=d;b.corrected=c;if("resize"==d){if(u==window.orientation)return null;u=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var d=c.changedTouches[0],f;for(f in d)delete c[f],c[f]=d[f]}return a.call(this,c)}};return k});
//@ sourceMappingURL=on.js.map