//>>built
define("dojo/on",["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(s,t,g){function u(a,b,c,d,h){if(d=b.match(/(.*):(.*)/))return b=d[2],d=d[1],e.selector(d,b).call(h,a,c);g("touch")&&(v.test(b)&&(c=l(c)),!g("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,c=l(c)));m&&(c=m(c));if(a.addEventListener){var f=b in k,i=f?k[b]:b;a.addEventListener(i,c,f);return{remove:function(){a.removeEventListener(i,c,f)}}}if(n&&a.attachEvent)return n(a,"on"+b,c);throw Error("Target must be an event emitter");
}function w(){this.cancelable=!1;this.defaultPrevented=!0}function x(){this.bubbles=!1}var o=window.ScriptEngineMajorVersion;g.add("jscript",o&&o()+ScriptEngineMinorVersion()/10);g.add("event-orientationchange",g("touch")&&!g("android"));g.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);var e=function(a,b,c,d){return"function"==typeof a.on&&"function"!=typeof b?a.on(b,c):e.parse(a,b,c,u,d,this)};e.pausable=function(a,
b,c,d){var h,a=e(a,b,function(){if(!h)return c.apply(this,arguments)},d);a.pause=function(){h=!0};a.resume=function(){h=!1};return a};e.once=function(a,b,c){var d=e(a,b,function(){d.remove();return c.apply(this,arguments)});return d};e.parse=function(a,b,c,d,h,f){if(b.call)return b.call(f,a,c);if(-1<b.indexOf(",")){for(var b=b.split(/\s*,\s*/),i=[],e=0,g;g=b[e++];)i.push(d(a,g,c,h,f));i.remove=function(){for(var a=0;a<i.length;a++)i[a].remove()};return i}return d(a,b,c,h,f)};var v=/^touch/;e.selector=
function(a,b,c){return function(d,h){function f(b){for(i=i&&i.matches?i:t.query;!i.matches(b,a,d);)if(b==d||!1===c||!(b=b.parentNode)||1!=b.nodeType)return;return b}var i="function"==typeof a?{matches:a}:this,g=b.bubble;return g?e(d,g(f),h):e(d,b,function(a){var b=f(a.target);return b&&h.call(b,a)})}};var y=[].slice,z=e.emit=function(a,b,c){var d=y.call(arguments,2),h="on"+b;if("parentNode"in a){var f=d[0]={},e;for(e in c)f[e]=c[e];f.preventDefault=w;f.stopPropagation=x;f.target=a;f.type=b;c=f}do a[h]&&
a[h].apply(a,d);while(c&&c.bubbles&&(a=a.parentNode));return c&&c.cancelable&&c},k={};if(!g("event-stopimmediatepropagation"))var A=function(){this.modified=this.immediatelyStopped=!0},m=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=A,a.apply(this,arguments)}};if(g("dom-addeventlistener"))k={focusin:"focus",focusout:"blur"},e.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=a.ownerDocument.createEvent("HTMLEvents");d.initEvent(b,!!c.bubbles,
!!c.cancelable);for(var h in c)h in d||(d[h]=c[h]);return a.dispatchEvent(d)&&d}return z.apply(e,arguments)};else{e._fixEvent=function(a,b){if(!a)a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event;if(!a)return a;try{j&&a.type==j.type&&a.target==j.target&&(a=j)}catch(c){}if(!a.target){a.target=a.srcElement;a.currentTarget=b||a.srcElement;if("mouseover"==a.type)a.relatedTarget=a.fromElement;if("mouseout"==a.type)a.relatedTarget=a.toElement;if(!a.stopPropagation)a.stopPropagation=B,a.preventDefault=
C;switch(a.type){case "keypress":var d="charCode"in a?a.charCode:a.keyCode;10==d?(d=0,a.keyCode=13):13==d||27==d?d=0:3==d&&(d=99);a.charCode=d;d=a;d.keyChar=d.charCode?String.fromCharCode(d.charCode):"";d.charOrCode=d.keyChar||d.keyCode}}return a};var j,p=function(a){this.handle=a};p.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var D=function(a){return function(b){var b=e._fixEvent(b,this),c=a.call(this,b);b.modified&&(j||setTimeout(function(){j=null}),j=b);return c}},n=function(a,
b,c){c=D(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>g("jscript"))&&!g("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var d=a[b];if(!d||!d.listeners){var e=d,d=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");d.listeners=[];a[b]=d;d.global=this;e&&d.listeners.push(_dojoIEListeners_.push(e)-
1)}d.listeners.push(a=d.global._dojoIEListeners_.push(c)-1);return new p(a)}return s.after(a,b,c,!0)},B=function(){this.cancelBubble=!0},C=e._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(g("touch"))var q=function(){},r=window.orientation,l=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(e){}b.type?(q.prototype=b,c=new q,c.preventDefault=
function(){b.preventDefault()},c.stopPropagation=function(){b.stopPropagation()}):(c=b,c.type=d);b.corrected=c;if("resize"==d){if(r==window.orientation)return null;r=window.orientation;c.type="orientationchange";return a.call(this,c)}if(!("rotation"in c))c.rotation=0,c.scale=1;var d=c.changedTouches[0],f;for(f in d)delete c[f],c[f]=d[f]}return a.call(this,c)}};return e});