//>>built
"undefined"==typeof define&&addXstyleDefine();
define("xstyle/xstyle",["require"],function(J,u){function K(a,b){return a&&a.then?a.then(b):b(a)}function s(a,b,d){return K(a,function(a){var c=b[0];if(!a)return d(c||a);if(c&&a.get)return s(a.get(c),b.slice(1),d);if(a.receive)return a.receive(c?function(a){s(a,b,d)}:d);if(c)return s(a[c],b.slice(1),d);d(a)})}function aa(a,b,d){s(a,b.slice(0,b.length-1),function(a){var c=b[b.length-1];a.set?a.set(c,d):a[c]=d})}function S(a){a=p.getElementsByTagName(a);for(var b=0;b<a.length;b++)L(a[b])}function ba(){return this.join("")}
function T(a){this.value=a}function L(a,b,d){function f(){J(["xstyle/load-imports"],function(c){c(a,function(){L(a,b,!0)})})}var c=a.sheet||a.styleSheet||a,e=c.needsParsing,g=c.rules||c.cssRules;if(c.imports&&!d&&c.imports.length)return f();if(!e)for(var h=0;h<g.length;h++){var l=g[h];if(l.href&&!d)return f();l.selectorText&&"x-"==l.selectorText.substring(0,2)&&(e=!0,/^'/.test(l.style.content))}e&&B(c.localSource||c.ownerElement.innerHTML,c,b)}function B(a,b,d){function f(a,b,c){(r[a]||(r[a]={}))[b]=
c}function c(a){r[a]||(r[a]={});f("selector","x-"+a,{onRule:function(b){b.eachProperty(function(b,c){var e=c.toString();do{e=e.match(/([^, \(]+)(?:[, ]+(.+))?/);if(!e)break;var d=e[1];if("require"==d)return f(a,b,c[1].args[0]);if("default"==d){if("property"==a&&"string"==typeof k.style[b])break;if("pseudo"==a)try{p.querySelectorAll("x:"+b);break}catch(ia){}}else if("prefix"==d){if("string"==typeof k.style[D+b])return f(a,b,"xstyle/xstyle")}else return f(a,b,function(){return c})}while(e=e[2])})}})}
function e(){}function g(a){this.caller=a;this.args=[]}function h(a,b){if(a){var c=a;do{var e=r.property[a];if(e)return E(e,"onProperty",c,b);a=a.substring(0,a.lastIndexOf("-"))}while(a)}}function l(a,b){var c=r["function"][a];c&&E(c,"onCall",a,b,b.args)}function M(a,b){b.onRule();var c=r.selector[a];c&&E(c,"onRule",b)}function E(a,c,e,h){if(a){var f=m,r=function(a){a&&b.addRule(f.fullSelector(),a);0==--y&&d&&d(b)};y++;var l=function(a){function d(a){console.error("Error occurred processing "+c.slice(2)+
" "+e+' in rule "'+f.selector+'" {'+f.cssText);a&&console.error(a)}try{var C=a[c](e,h,f,b);C&&C.then?C.then(r,d):r(C)}catch(m){d(m)}};"string"==typeof a?J([a],l):l(a)}}function v(a,b){function c(a){n?n.push?"string"==typeof n[n.length-1]&&"string"==typeof a?n[n.length-1]+=a:a&&n.push(a):"string"==typeof n&&"string"==typeof a?n+=a:(a=[n,a],a.toString=ba,n=a):n=a}m=z;for(var e=w.lastIndex=0,f=!0;;){var g=w.exec(a),q=g[4],t=g[1],p=g[2],g=g[3],k,x,n,u,g=g&&U(g),t=U(t);if(u){if(p?(x=t,k=p.charAt(0)):g=
t,n=g,x||"/"!=q)u=!1}else g=g?t+p:t,c(g);switch(q){case "'":case '"':var s="'"==q?ca:da;s.lastIndex=w.lastIndex;(q=s.exec(a))||error("unterminated string");q=q[1];w.lastIndex=s.lastIndex;c(new T(q));continue;case "/":"*"==a[w.lastIndex]?(N.lastIndex=w.lastIndex+1,N.exec(a),w.lastIndex=N.lastIndex):c("/");continue;case "\\":q=s.lastIndex++;c(a.charAt(q));continue;case "(":case "{":"{"==q?(u=!0,c(t=m.newRule(g)),m.root&&f&&(t.cssRule=b.cssRules[e++]),k&&(n.creating=!0)):c(t=m.newCall(g));t.parent=m;
t.selector=n.creating?".x-generated-"+O++:m.root?g:m.selector+" "+g;m.currentName=x;m.currentSequence=n;m.assignmentOperator=k;F.push(m=t);m.operator=q;m.start=w.lastIndex;m.selector&&m.selector.replace(/:([-\w]+)/,function(a,b){var c=r.pseudo[b];c&&E(c,"onPseudo",b,m)});n=x=null;continue}if(n)if(t=n[0],t.charAt&&"@"==t.charAt(0))"import"==n[0].slice(1,7)&&(x=B.getStyleSheet(b.cssRules[e++],n,b),y++,t=w.lastIndex,v(x.localSource,x),w.lastIndex=t);else m[":"==k?"addProperty":"addVariable"](x,n);x=
null;switch(q){case "}":case ")":m.cssText=a.slice(m.start,w.lastIndex-1);"}"==q?(M(m.selector,m),"x-"!=m.selector.slice(0,2)&&m.eachProperty(h),f=!0):l(m.caller,m);F.pop();m=F[F.length-1];n=m.currentSequence;x=m.currentName;k=m.assignmentOperator;m.root&&"}"==q&&(u=!0,k=!1);break;case "":d&&d();return;case ";":n=null,u=!0,k=f=!1}}}b.addRule||(b.addRule=function(a,b,c){return this.insertRule(a+"{"+b+"}",0<=c?c:this.cssRules.length)});b.deleteRule||(b.deleteRule=b.removeRule);var r={property:{}};c("property");
c("function");c("pseudo");var y=1;(b.href||location.href).replace(/[^\/]+$/,"");e.prototype={eachProperty:function(a){for(var b=this.properties||0,c=0;c<b.length;c++){var e=b[c];a(e||"unnamed",b[e])}},fullSelector:function(){return(this.parent?this.parent.fullSelector():"")+(this.selector||"")+" "},newRule:function(a){return(this.rules||(this.rules={}))[a]=new e},newCall:function(a){return new g(a)},addSheetRule:function(a,c){if(c&&"@"!=a.charAt(0))return b.addRule(a,c)},onRule:function(){this.cssRule||
this.addSheetRule(this.selector,this.cssText)},recomputeAttribute:function(a,b){this.attributeFunctions[b](a)},get:function(a){return this.properties[a]},addVariable:function(a,b){"\x3e"==b[0].toString().charAt(0)?(b=V(b,this),a||G.addRenderer("",b,this,b)):(this.variables||(this.variables={}))[a]=b},addProperty:function(a,b){var c=this.properties||(this.properties=[]);c.push(a);c[a]=b},cssText:""};var q=g.prototype=new e;q.addVariable=q.addProperty=function(a,b){this.args.push(b)};q.toString=function(){return"("+
this.args+")"};var m,z=new e;z.root=!0;z.variables={Math:Math,require:function(a){return{then:function(b){J([a],b)}}},item:{forElement:function(a){for(;!a.item;)a=a.parentNode;return{element:a,receive:function(b){b(a.item)}}}}};z.css=a;z.parse=v;var F=[z];v(a,b);0==--y&&d&&d(b);return z}function W(){S("link");S("style");if(!P)if(P=!0,ea["dom-qsa2.1"]){for(var a=0,b=A.length;a<b;a++)X(A[a]);Y()}else for(var d=p.all,a=0,b=d.length;a<b;a++)Z(d[a])}function X(a){for(var b=p.querySelectorAll(a.selector),
d=a.name,f=0,c=b.length;f<c;f++){var e=b[f],g=e.elementalStyle;g||(g=e.elementalStyle={},e.elementalSpecificities={});var h=e.renderings;h||(h=e.renderings=[],H.push(e));h.push({name:d,rendered:g[d]==a.propertyValue,renderer:a});g[d]=a.propertyValue}}function Y(){for(var a=0;a<H.length;a++){var b=H[a],d=b.renderings,f=b.elementalStyle;delete b.renderings;for(var c=0;c<d.length;c++){var e=d[c],g=e.renderer,h=g.rendered;Q=f[e.name]==g.propertyValue;if(!h&&Q)try{g.render(b)}catch(l){console.error(l,
l.stack),u(b,"div.error",l.toString())}h&&(!Q&&g.unrender)&&(g.unrender(b),d.splice(c--,1))}}H=[]}function Z(a){for(var b=0,d=A.length;b<d;b++){var f=A[b];(R?R.call(a,f.selector):a.currentStyle[f.name]==f.propertyValue)&&f.render(a)}}function V(a,b){O++;a=a.sort?a:[a];return function(b,f){for(var c=b,e=0,g=a.length;e<g;e++){var h=a[e];try{if(h.eachProperty)if(h.args){var l=a[e+1];l&&l.eachProperty&&u(c,l.selector);var M=$(h,0,h.args.toString());(function(a,b){K(M,function(c){c.forElement&&(c=c.forElement(b));
var e=a.appendChild(p.createTextNode("Loading"));c.receive(function(b){if(b&&b.sort){e&&(e.parentNode.removeChild(e),e=null);var d=l&&l.eachProperty&&l.get("each");d&&(d=V(d,l));b.forEach(d?function(b){d(a,b)}:function(b){u(a,fa[a.tagName]||"div",b)})}else"value"in a?(a.value=b,a["-x-variable"]=c):e.nodeValue=b})})})(c,b)}else u(c,h.selector),G.update(c);else if("string"==typeof h){"\x3d"==h.charAt(0)&&(h=h.slice(1));for(var k=h.split(","),h=0,v=k.length;h<v;h++){var r=k[h].trim();if(r){var r=r.replace(/\([^)]*\)/,
function(a){}),y=u(0==h?c:b,r);f&&(y.item=f);y!=c&&G.update(y);c=y}}}else c.appendChild(p.createTextNode(h.value))}catch(q){console.error(q,q.stack),c.appendChild(p.createTextNode(q))}}return c}}function $(a,b,d){function f(){var a=e.length+1,b=[],c=[],d,h,g=function(e){return function(f){b[e]=f;a--;if(0>=a){h=!0;d=p?p.apply(this,b):b[0];for(f=0;f<c.length;f++)c[f](d)}}};if(p)for(var f=0;f<e.length;f++){var l=e[f];s(l[0],l.slice(1),g(f))}else{var l=e[0],k={then:function(a){c.push(a)}};K(l[0],function(a){k=
a;for(var b=1;b<l.length;b++)if(k&&k.get)k=k.get(l[b]);else{k={receive:function(b){s(a,l.slice(1),b)},put:function(a){aa(resolve,l.slice(1),a)}};break}for(b=0;b<c.length;b++)c[b](k)});return k}g(-1)();return d&&d.then?d:{receive:function(a){c&&c.push(a);h&&a(d)}}}var c=a["var-expr-"+b];if(e)return c;var e=[],g;e.id=O++;var h,l=[],k;d=d.join?d.join(""):d.toString();c=d.match(/^[\w_$\/\.]*$/);d=d.replace(/("[^\"]*")|([\w_$\.\/]+)/g,function(b,c,d){if(d){k=d.split("/");b=k.join("_");l.push(b);e.push(k);
c=a;for(d=k[0];!(h=c.variables&&c.variables[d]);)if(c=c.parent,!c)throw Error('Could not find reference "'+d+'"');if("string"==typeof h||h instanceof Array)h=$(c,d,h);h.forElement&&(g=!0);k[0]=h}return b});if(!c)var p=Function.apply(this,l.concat(["return "+d]));e.func=p;a["var-expr-"+b]=e;return a["var-expr-"+b]=g?{forElement:function(b){for(var c,d=b;!R.call(b,a.selector);)b=b.parentNode;for(b=0;b<e.length;b++){var h=e[b],g=h[0];g.forElement&&(g=h[0]=g.forElement(d));h=g.element;if(d!=c){for(;d!=
h;){if(d==c)return;d=d.parentNode}c=d}}d=c["expr-result-"+e.id];d||(c["expr-result-"+e.id]=d=f(),d.element=c);return d}}:f()}function u(a,b,d){function f(){e&&(a&&e!=a)&&a.insertBefore(e,c||null)}var c,e=a,g=arguments;b.replace(ga,function(b,d,k,s,v,r){d&&(f(),"-"==d||"+"==d?(a=(c=e||a).parentNode,e=null,"+"==d&&(c=c.nextSibling)):("\x3c"==d?a=e=(e||a).parentNode:(","==d?a=topReferenceElement:e&&(a=e),e=null),c=0),e&&(a=e));if((b=!k&&s)||!e&&(k||v))b=b||u.defaultTag,(d=ha&&g[i+1]&&g[i+1].name)&&(b=
"\x3c"+b+' name\x3d"'+d+'"\x3e'),e=p.createElement(b);k&&("#"==k?e.id=s:(d=(b=e.className)&&(" "+b+" ").replace(" "+s+" "," "),"."==k&&(e.className=b?(d+s).substring(1):s)));v&&(k="!"==v.charAt(0)?(v=v.substring(1))&&"removeAttribute":"setAttribute",e[k](v,""===r?v:r));return""});f();d&&e.appendChild(p.createTextNode(d));return e}var w=/\s*([^{\}\(\)\/\\'":=;]*)([=:]\s*([^{\}\(\)\/\\'";]*))?([{\}\(\)\/\\'";]|$)/g,ca=/((?:\\.|[^'])*)'/g,da=/((?:\\.|[^"])*)"/g,N=/\*\//g,O=0,fa={TABLE:"tr",TBODY:"tr",
TR:"td",UL:"li",OL:"li",SELECT:"option"},p=document,U="".trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")},k=p.createElement("div");T.prototype.toString=function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};var I=navigator.userAgent,D=-1<I.indexOf("WebKit")?"-webkit-":-1<I.indexOf("Firefox")?"-moz-":-1<I.indexOf("MSIE")?"-ms-":-1<I.indexOf("Opera")?"-o-":"";B.getStyleSheet=function(a,b){return a.styleSheet};p.addEventListener("change",function(a){a=a.target;
var b=a["-x-variable"];b.put&&b.put(a.value)});var k=p.createElement("div"),ea={"dom-qsa2.1":!!k.querySelectorAll},R=k.matches||k.matchesSelector||k.webkitMatchesSelector||k.mozMatchesSelector||k.msMatchesSelector||k.oMatchesSelector,A=[],H=[],P;/e/.test(p.readyState||"")?setTimeout(W,200):p.addEventListener("DOMContentLoaded",W);var Q,ga=/(?:\s*([-+ ,<>]))?\s*(\.|!\.?|#)?([-\w%$|]+)?(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,ha="object"==typeof p.createElement,G={process:L,vendorPrefix:D,onProperty:function(a,
b){return"opacity"==a&&"-ms-"==D?"filter: alpha(opacity\x3d"+100*b+"); zoom: 1;":D+a+":"+b+";"},onFunction:function(a,b,d){},onCall:function(a,b){var d=b.args,f=b.parent,c=f,e="extends"==a?"rules":"variables";do{if(!c)throw Error('Could not find "'+a+'" in the defined '+e);var g=c[e]&&c[e][d[0]],c=c.parent}while(!g);"extends"==a?(f.cssText+=g.cssText,f.properties=Object.create(g.properties),g.eachProperty(function(a,b){if(a){var c=f.cssRule.style;c[a]||(c[a]=b)}})):"var"==a&&(c=b.parent,c.addSheetRule(c.selector,
c.currentName+": "+c.currentSequence.toString().replace(/var\([^)]+\)/g,g)))},parse:B,addRenderer:function(a,b,d,f){a={selector:d.selector,propertyValue:b,name:a,render:f};A.push(a);P&&X(a);Y()},update:Z,clearRenderers:function(){A=[]},load:function(a,b,d,f){b(["xstyle/css"],function(c){c.load(a,b,d,f)})}};return G});addXstyleDefine=function(){};