//>>built
"undefined"==typeof define&&function(){var u={};define=function(p,s,n){for(var k=0;k<s.length;k++)s[k]=u[s[k]];u[p]=n.apply(this,s)};require=function(p){define("",p,factory)}}();
define("xstyle/xstyle",["require"],function(u){function p(d){for(var d=document.getElementsByTagName(d),c=0;c<d.length;c++)n(d[c])}function s(){return this.join("")}function n(d,c,o){function h(){u(["./load-imports"],function(g){g(d,function(){n(d,c,!0)})})}var g=d.sheet||d.styleSheet,j=g.needsParsing,m=g.rules||g.cssRules;if(g.imports&&!o&&g.imports.length)return h();if(!j)for(var v=0;v<m.length;v++){var t=m[v];if(t.href&&!o)return h();t.selectorText&&"x-"==t.selectorText.substring(0,2)&&(j=!0,/^'/.test(t.style.content))}j&&
k(g.localSource||g.ownerElement.innerHTML,g,c)}function k(d,c,o){function h(a,b,e){(q[a]||(q[a]={}))[b]=e}function g(a){q[a]||(q[a]={});h("selector","x-"+a,{onRule:function(b){b.eachProperty(function(e,b){var f=b.toString();do{f=f.match(/([^, \(]+)(?:[, ]+(.+))?/);if(!f)break;var c=f[1];if("require"==c)return h(a,e,b[1].args[0]);if("default"==c){if("property"==a&&"string"==typeof A.style[e])break;if("pseudo"==a)try{document.querySelectorAll("x:"+e);break}catch(E){}}else if("prefix"==c){if("string"==
typeof A.style[w+e])return h(a,e,"xstyle/xstyle")}else return h(a,e,function(){return b})}while(f=f[2])})}})}function k(a){this.caller=a;this.args=[]}function m(){}function v(a,b){console.log("onProperty",a,b);if(a){var e=a;do{var c=q.property[a];if(c)return n(c,"onProperty",e,b);a=a.substring(0,a.lastIndexOf("-"))}while(a)}}function t(a,b){var e=q["function"][a];e&&n(e,"onCall",a,b,b.args)}function p(a,b){b.onRule();var e=q.selector[a];e&&n(e,"onRule",b)}function n(a,g,e,d){if(a){var f=b,j=function(b){console.log("loaded ",
a,b);b&&c.addRule(f.fullSelector(),b);0==--x&&o&&o(c)};x++;console.log("loading ",a,e,d);var l=function(a){(a=a[g](e,d,f,c))&&a.then?a.then(j):j(a)};"string"==typeof a?u([a],l):l(a)}}function r(a,c){function e(a){i?i.push?a&&i.push(a):"string"==typeof i&&"string"==typeof a?i+=a:(a=[i,a],a.toString=s,i=a):i=a}for(var g=j.lastIndex=0;;){var f=j.exec(a),d=f[3],l=f[1].trim(),f=f[2],h,i,k,f=f&&f.trim();if(k){if(h="string"==typeof f&&l,i=f=f||l,h||"/"!=d)k=!1}else f=f?l+":"+f:l,e(f);switch(d){case "'":case '"':var m=
"'"==d?B:C;m.lastIndex=j.lastIndex;d=m.exec(a)[1];j.lastIndex=m.lastIndex;e(new String(d));continue;case "/":"*"==a[j.lastIndex]?(z.lastIndex=j.lastIndex+1,z.exec(a),j.lastIndex=z.lastIndex):e("/");continue;case "\\":d=m.lastIndex++;e(a.charAt(d));continue;case "(":case "{":"{"==d?(k=!0,e(l=b.newRule(f))):e(l=b.newCall(f));l.parent=b;if(b.root)l.cssRule=c.cssRules[g++];if("="==i[0].charAt(0))i.creating=!0;l.selector=i.creating?".x-generated-"+D++:b.root?f:b.selector+" "+f;b.currentName=h;b.currentSequence=
i;y.push(b=l);b.operator=d;b.start=j.lastIndex;b.selector&&b.selector.replace(/:([-\w]+)/,function(a,c){var e=q.pseudo[c];e&&n(e,"onPseudo",c,b)});i=h=null;continue}if(i)if("@"==i[0].charAt(0)){if("import"==i[0].slice(1,7))console.log("found import",i),h=c.cssRules[g++].styleSheet,x++,l=j.lastIndex,r(h.localSource,h),j.lastIndex=l}else b.addProperty(h,i);h=null;switch(d){case "}":case ")":h=a.slice(b.start,j.lastIndex-1);b.cssText=h;"}"==d?(p(b.selector,b),"x-"!=b.selector.slice(0,2)&&b.eachProperty(v)):
t(b.caller,b);y.pop();b=y[y.length-1];i=b.currentSequence;h=b.currentName;break;case "":o&&o();return;case ";":i=null,k=!0}}}if(!c.addRule)c.addRule=function(a,b,c){return this.insertRule(a+"{"+b+"}",0<=c?c:this.cssRules.length)};if(!c.deleteRule)c.deleteRule=sheet.removeRule;var q={property:{}};g("property");g("function");g("pseudo");var x=1;(c.href||location.href).replace(/[^\/]+$/,"");k.prototype={addProperty:function(a,b){this.args.push(b)},toString:function(){return"("+this.args+")"}};m.prototype=
{eachProperty:function(a){for(var b=this.properties||0,c=0;c<b.length;c++){var d=b[c];a(d||"unnamed",b[d])}},fullSelector:function(){return(this.parent?this.parent.fullSelector():"")+(this.selector||"")+" "},newRule:function(a){return(this.rules||(this.rules={}))[a]=new m},newCall:function(a){return new k(a)},add:function(a){console.log("add",this.selector,a);a&&(c.addRule?c.addRule(this.selector,a):c.insertRule(this.selector+"{"+a+"}",c.cssRules.length))},onRule:function(){this.parent.root||this.add(this.cssText)},
addProperty:function(a,b){!a&&"="==b[0].charAt(0)&&(a="-x-content",b[0]=b[0].slice(1));var c=this.properties||(this.properties=[]);c.push(a);c[a]=b},cssText:""};var b=new m;b.root=!0;b.css=d;var y=[b];r(d,c);0==--x&&o&&o(c)}var j=/\s*([^{\}\(\)\/\\'":;]*)(?::\s*([^{\}\(\)\/\\'";]*))?([{\}\(\)\/\\'";]|$)/g,B=/((?:\\.|[^'])*)'/g,C=/((?:\\.|[^"])*)"/g,z=/\*\//g,D=0,A=document.createElement("div"),r=navigator.userAgent,w=-1<r.indexOf("WebKit")?"-webkit-":-1<r.indexOf("Firefox")?"-moz-":-1<r.indexOf("MSIE")?
"-ms-":-1<r.indexOf("Opera")?"-o-":"";p("link");p("style");return{process:n,vendorPrefix:w,onProperty:function(d,c){return"opacity"==d&&"-ms-"==w?"filter: alpha(opacity="+100*c+"); zoom: 1;":w+d+":"+c+";"},onCall:function(d,c){var j=c.args;console.log("extends",j);var h=c.parent,g=h;do var k=g.rules&&g.rules[j[0]],g=g.parent;while(!k);h.cssText+=k.cssText;h.properties=Object.create(k.properties);k.eachProperty(function(c,d){if(c){var g=h.cssRule.style;g[c]||(g[c]=d)}})},parse:k}});