//>>built
define("dgrid/extensions/ColumnResizer","dojo/_base/declare,dojo/on,dojo/query,dojo/_base/lang,dojo/dom,dojo/dom-geometry,dojo/has,../util/misc,put-selector/put,dojo/_base/html,xstyle/css!../css/extensions/ColumnResizer.css".split(","),function(w,m,i,x,s,t,n,y,j){function u(a){for(var b=a.length,c=b,d=a[0].length,e=Array(b);b--;)e[b]=Array(d);for(var g={},b=0;b<c;b++)for(var k=e[b],f=a[b],o=0,j=0;o<d;o++){var h=f[j],i;if("undefined"==typeof k[o]){k[o]=h.id;if(h.rowSpan&&1<h.rowSpan){i=e;for(var l=
h.rowSpan,m=b,n=o,p=h.id,q=1;q<l;q++)i[m+q][n]=p}if(0<b&&h.colSpan&&1<h.colSpan)for(i=1;i<h.colSpan;i++)if(k[++o]=h.id,h.rowSpan&&1<h.rowSpan)for(var l=e,m=h.rowSpan,n=b,p=o,q=h.id,r=1;r<m;r++)l[n+r][p]=q;g[h.id]=a[0][o].id;j++}}return g}function p(a,b,c,d){if(!(0>=c)){var e={grid:a,columnId:b,width:c,bubbles:!0,cancelable:!0};if(d)e.parentType=d;if(m.emit(a.headerNode,"dgrid-columnresize",e))return d=a._columnStyles[b],c=a.styleColumn(b,"width: "+(("auto"!==c?c+"px":c)+";")),d&&d.remove(),a._columnStyles[b]=
c,!0}}n("touch");var f,v=0,l={create:function(){f=j("div.dgrid-column-resizer")},destroy:function(){j(f,"!");f=null},show:function(a){a=t.position(a.domNode,!0);f.style.top=a.y+"px";f.style.height=a.h+"px";j(document.body,f)},move:function(a){f.style.left=a+"px"},hide:function(){f.parentNode.removeChild(f)}};return w(null,{resizeNode:null,minWidth:40,gridWidth:null,_resizedColumns:!1,buildRendering:function(){this.inherited(arguments);v++||l.create()},destroy:function(){this.inherited(arguments);
--v||l.destroy()},resizeColumnWidth:function(a,b){return p(this,a,b)},configStructure:function(){this._resizedColumns=!1;for(var a in this._columnStyles)this._columnStyles[a].remove();this._columnStyles={};this.inherited(arguments)},_configColumn:function(a,b){this.inherited(arguments);"width"in a&&this.resizeColumnWidth(b,a.width)},renderHeader:function(){this.inherited(arguments);var a=this;a.gridWidth=a.headerNode.clientWidth-1;var b;if(this.columnSets&&this.columnSets.length)for(var c=this.columnSets.length;c--;)b=
x.mixin(b||{},u(this.columnSets[c]));else this.subRows&&1<this.subRows.length&&(b=u(this.subRows));for(var c=i(".dgrid-cell",a.headerNode),d=c.length;d--;){var e=c[d],g=e.columnId,k=a.columns[g],f=e.childNodes;if(k&&!1!==k.resizable){k=j("div.dgrid-resize-header-container");for(e.contents=k;0<f.length;)j(k,f[0]);j(e,k,"div.dgrid-resize-handle.resizeNode-"+g).columnId=b?b[g]:g}}if(!a.mouseMoveListen)m(a.headerNode,".dgrid-resize-handle:mousedown"+(n("touch")?",.dgrid-resize-handle:touchstart":""),
function(b){a._resizeMouseDown(b,this);a.mouseMoveListen.resume();a.mouseUpListen.resume()}),a.mouseMoveListen=m.pausable(document,"mousemove"+(n("touch")?",touchmove":""),y.throttleDelayed(function(b){a._updateResizerPosition(b)})),a.mouseUpListen=m.pausable(document,"mouseup"+(n("touch")?",touchend":""),function(b){a._resizeMouseUp(b);a.mouseMoveListen.pause();a.mouseUpListen.pause()}),a.mouseMoveListen.pause(),a.mouseUpListen.pause()},_resizeMouseDown:function(a,b){a.preventDefault();s.setSelectable(this.domNode,
!1);this._startX=this._getResizeMouseLocation(a);t.position(this.bodyNode);this._targetCell=i(".dgrid-column-"+b.columnId,this.headerNode)[0];this._updateResizerPosition(a);l.show(this)},_resizeMouseUp:function(a){if(!this._resizedColumns){var b=i(".dgrid-cell",this.headerNode);this.columnSets&&this.columnSets.length?b=b.filter(function(a){return"0"==a.columnId.split("-")[0]}):this.subRows&&1<this.subRows.length&&(b=b.filter(function(a){return"0"==a.columnId.charAt(0)}));var c=b.map(function(a){return a.offsetWidth});
b.forEach(function(a,b){this.resizeColumnWidth(a.columnId,c[b])},this);this._resizedColumns=!0}s.setSelectable(this.domNode,!0);var b=this._targetCell,d=this._getResizeMouseLocation(a)-this._startX,e=b.offsetWidth+d,g=this._getResizedColumnWidths(),f=g.totalWidth,g=g.lastColId,j=i(".dgrid-column-"+g,this.headerNode)[0].offsetWidth;if(e<this.minWidth)e=this.minWidth;p(this,b.columnId,e,a.type)&&b.columnId!=g&&(f+d<this.gridWidth?p(this,g,"auto",a.type):j-d<=this.minWidth&&p(this,g,this.minWidth,a.type),
this.resize());l.hide();delete this._startX;delete this._targetCell},_updateResizerPosition:function(a){if(this._targetCell){var a=this._getResizeMouseLocation(a),b=this._targetCell.offsetWidth,c=a;b+(a-this._startX)<this.minWidth&&(c=this._startX-(b-this.minWidth));l.move(c)}},_getResizeMouseLocation:function(a){var b=0;a.pageX?b=a.pageX:a.clientX&&(b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft);return b},_getResizedColumnWidths:function(){var a=0,b=i(".dgrid-cell",this.headerNode);
this.columnSets&&this.columnSets.length?b=b.filter(function(a){return"0"==a.columnId.split("-")[1]}):this.subRows&&1<this.subRows.length&&(b=b.filter(function(a){return"0"==a.columnId.charAt(0)}));var c=b.length;if(!c)return{};for(var d=b[c-1].columnId;c--;)a+=b[c].offsetWidth;return{totalWidth:a,lastColId:d}}})});