//>>built
define("dgrid/extensions/Pagination","../_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on dojo/query dojo/string dojo/has put-selector/put dojo/i18n!./nls/pagination dojo/_base/sniff xstyle/css!../css/extensions/Pagination.css".split(" "),function(v,w,x,q,m,s,t,r,d,y){function z(a){a.noDataNode?(d(a.noDataNode,"!"),delete a.noDataNode):a.cleanup();a.contentNode.innerHTML=""}function u(a){if(a.loadingNode)d(a.loadingNode,"!"),delete a.loadingNode;else if(a._oldPageNodes){for(var c in a._oldPageNodes)a.removeRow(a._oldPageNodes[c]);
delete a._oldPageNodes;a._oldPageObserver&&(a._oldPageObserver.cancel(),delete a._oldPageObserver)}delete a._isLoading}return w(v,{rowsPerPage:10,pagingTextBox:!1,previousNextArrows:!0,firstLastArrows:!1,pagingLinks:2,pageSizeOptions:[],showLoadingMessage:!0,i18nPagination:y,showFooter:!0,_currentPage:1,_total:0,buildRendering:function(){this.inherited(arguments);var a=this,c=this.paginationNode=d(this.footerNode,"div.dgrid-pagination"),b=this.paginationStatusNode=d(c,"div.dgrid-status"),f=this.pageSizeOptions,
h=this.i18nPagination;b.tabIndex=0;if(f.length){var g=d(c,"select.dgrid-page-size"),e;for(e=0;e<f.length;e++)d(g,"option",f[e],{value:f[e]});this._listeners.push(m(g,"change",function(){a.rowsPerPage=+g.value;a.gotoPage(1)}))}b.innerHTML=t.substitute(h.status,{start:1,end:1,total:0});c=this.paginationNavigationNode=d(c,"div.dgrid-navigation");this.firstLastArrows&&(b=this.paginationFirstNode=d(c,"span.dgrid-first.dgrid-page-link","\u00ab"),b.setAttribute("aria-label",h.gotoFirst),b.tabIndex=0);this.previousNextArrows&&
(b=this.paginationPreviousNode=d(c,"span.dgrid-previous.dgrid-page-link","\u2039"),b.setAttribute("aria-label",h.gotoPrev),b.tabIndex=0);this.paginationLinksNode=d(c,"span.dgrid-pagination-links");this.previousNextArrows&&(b=this.paginationNextNode=d(c,"span.dgrid-next.dgrid-page-link","\u203a"),b.setAttribute("aria-label",h.gotoNext),b.tabIndex=0);this.firstLastArrows&&(b=this.paginationLastNode=d(c,"span.dgrid-last.dgrid-page-link","\u00bb"),b.setAttribute("aria-label",h.gotoLast),b.tabIndex=0);
this._listeners.push(m(c,".dgrid-page-link:click,.dgrid-page-link:keydown",function(b){if(!("keydown"===b.type&&13!==b.keyCode)){b=this.className;var c,d;a._isLoading||-1<b.indexOf("dgrid-page-disabled")||(c=a._currentPage,d=Math.ceil(a._total/a.rowsPerPage),this===a.paginationPreviousNode?a.gotoPage(c-1):this===a.paginationNextNode?a.gotoPage(c+1):this===a.paginationFirstNode?a.gotoPage(1):this===a.paginationLastNode?a.gotoPage(d):"dgrid-page-link"===b&&a.gotoPage(+this.innerHTML,!0))}}))},destroy:function(){this.inherited(arguments);
this._pagingTextBoxHandle&&this._pagingTextBoxHandle.remove()},_updateNavigation:function(a){function c(c){var e;b.pagingTextBox&&c==g?(e=d(h,"input.dgrid-page-input[type\x3dtext][value\x3d$]",g),e.setAttribute("aria-label",f.jumpPage),b._pagingTextBoxHandle=m(e,"change",function(){var a=+this.value;!isNaN(a)&&(0<a&&a<=l)&&b.gotoPage(+this.value,!0)})):(e=d(h,"span"+(c==g?".dgrid-page-disabled":"")+".dgrid-page-link",c),e.setAttribute("aria-label",f.gotoPage),e.tabIndex=0);c==g&&a&&e.focus()}var b=
this,f=this.i18nPagination,h=this.paginationLinksNode,g=this._currentPage,e=this.pagingLinks,k=this.paginationNavigationNode,l=Math.ceil(this._total/this.rowsPerPage),n=this._pagingTextBoxHandle;n&&n.remove();h.innerHTML="";s(".dgrid-first, .dgrid-previous",k).forEach(function(a){d(a,(1==g?".":"!")+"dgrid-page-disabled")});s(".dgrid-last, .dgrid-next",k).forEach(function(a){d(a,(g>=l?".":"!")+"dgrid-page-disabled")});if(e&&0<l){c(1);k=g-e;for(2<k?d(h,"span.dgrid-page-skip","..."):k=2;k<Math.min(g+
e+1,l);k++)c(k);g+e+1<l&&d(h,"span.dgrid-page-skip","...");c(l)}else b.pagingTextBox&&c(g)},refresh:function(){var a=this;this.inherited(arguments);if(this.store)return this.gotoPage(1).then(function(c){setTimeout(function(){m.emit(a.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:a,results:c})},0);return c});console.warn("Pagination requires a store to operate.")},_onNotification:function(a){a.length!==this._rowsOnPage&&this.gotoPage(this._currentPage)},renderArray:function(){var a=
this.inherited(arguments);this._lastCollection=null;return a},insertRow:function(){var a=this._oldPageNodes,c=this.inherited(arguments);a&&c===a[c.id]&&delete a[c.id];return c},gotoPage:function(a,c){var b=this,f=new q;this._trackError(function(){var h=b.rowsPerPage,g=(a-1)*h,e=x.mixin(b.get("queryOptions"),{start:g,count:h}),k,l=b.contentNode,n,p,m;if(b.showLoadingMessage)z(b),n=b.loadingNode=d(l,"div.dgrid-loading"),n.innerHTML=b.loadingMessage;else{b._oldPageNodes=n={};l=l.children;p=0;for(m=l.length;p<
m;p++)n[l[p].id]=l[p];b._oldPageObserver=b.observers.pop()}b._isLoading=!0;k=b.store.query(b.query,e);q.when(b.renderArray(k,null,e),function(e){u(b);b.scrollTo({y:0});q.when(k.total,function(f){f||(b.noDataNode=d(b.contentNode,"div.dgrid-no-data"),b.noDataNode.innerHTML=b.noDataMessage);b.paginationStatusNode.innerHTML=t.substitute(b.i18nPagination.status,{start:Math.min(g+1,f),end:Math.min(f,g+h),total:f});b._total=f;b._currentPage=a;b._rowsOnPage=e.length;b._updateNavigation(c)});(7>r("ie")||r("ie")&&
r("quirks"))&&b.resize();f.resolve(k)},function(a){u(b);f.reject(a)});return f.promise})||f.reject();return f.promise}})});