//>>built
define("xstyle/core/parser",["xstyle/core/utils"],function(J){function K(){return this.join("")}function G(p){this.value=p}function H(p,v,w){function C(k,q){function s(b){a?a.push?"string"==typeof a[a.length-1]&&"string"==typeof b?a[a.length-1]+=b:b&&a.push(b):"string"==typeof a&&"string"==typeof b?a+=b:(b=[a,b],b.toString=K,a=b):a=b}k=k.replace(L,"");target=p;for(var x=l.lastIndex=0,t=!0,f="",u=!0;;){var m=l.exec(k),b=m[4],g=m[1],h=m[2],c=m[3],d,n,a,D,c=c&&E(c),g=E(g);u?(h?(n=g,d=h.charAt(0),D="?"==
h.charAt(1)):c=g,a=c,u=!1):(c=h?g+h:g,s(c));"{"!=b&&(f+=m[0]);switch(b){case "'":case '"':var y="'"==b?M:N;y.lastIndex=l.lastIndex;(b=y.exec(k))||r("unterminated string");c=b[1];l.lastIndex=y.lastIndex;s(new G(c));f+=b[0];continue;case "\\":b=y.lastIndex++;s(k.charAt(b));continue;case "(":case "{":case "[":var e,z=!1;if("{"==b){u=!0;":"==d&&(g+=h);f=E((f+g).replace(/\s+/g," ").replace(/([\.#:])\S+|\w+/g,function(a,b){return b?a:a.toLowerCase()}));s(e=target.newRule(f));"\x3d"==d&&(t=!1,a.creating=
!0,c&&(z=!0));":"==d&&!target.root&&(a.creating=!0);var h=null,v=x;if(m[5]){var F=q.cssRules||q.rules;if(e.cssRule=h=F[m[5].slice(1)])f=h.selectorText}if(target.root&&t)for(F=q.cssRules||q.rules;h=F[x++];)if(h.selectorText==f){e.cssRule=h;break}h||(e.ruleIndex=x=v,e.styleSheet=q);a.creating?(e.selector="."+("\x3d"==d?g.match(/[\w-]*$/g,"")[0]:"")+"-x-"+O++,e.creating=!0):e.selector=target.root?f:target.selector+" "+f;f=""}else m=c.match(/(.*?)([\w-]*)$/),s(e=target.newCall(m[2],a,target)),e.ref=target.getDefinition(m[2]),
(a.calls||(a.calls=[])).push(e);e.parent=target;z&&c.replace(/([\w-]+)$/g,function(a,b){var c=target.getDefinition(b,!0);c?c.extend(e,!0):(e.tagName=b,J.isTagSupported(b)||r("Extending undefined definition "+b))});target.currentName=n;target.currentSequence=a;target.assignmentOperator=d;var A;if("{"==b&&(A=e.selector.match(/[@:]\w+/)))A=A[0],(n=target.getDefinition(A))&&n.selector&&n.selector(e);B.push(target=e);target.operator=b;target.start=l.lastIndex;a=n=null;continue}if(a)if(g=a[0]||a,g.charAt&&
"@"==g.charAt(0))c=a[0].match(/\w+/)[0],"import"==c?(c=H.getStyleSheet((q.cssRules||q.imports)[x++],a,q),z=l.lastIndex,C(c.localSource,c),l.lastIndex=z):"xstyle"==c&&(l="on"==a[0].slice(8,10)?I:/(@[\w\s])/g);else if(d)try{target[":"==d?"setValue":"declareProperty"](n,a,D)}catch(w){r(w)}switch(b){case ":":"\x3d"==d?(u=!0,d=":"):s(":");break;case "}":case ")":case "]":P[target.operator]!=b&&r("Incorrect opening operator "+target.operator+" with closing operator "+b);n=null;d=k.slice(target.start,l.lastIndex-
1);target.cssText=target.cssText?target.cssText+";"+d:d;"}"==b&&("}"==Q&&(t=target.parent.selector)&&"@"==!t.charAt(0)&&r("A nested rule must end with a semicolon"),target.root&&r("Unmatched "+b),target.onRule(target.selector,target),t=!0,f="");B.pop();target=B[B.length-1];a=target.currentSequence;n=target.currentName;d=target.assignmentOperator;if(target.root&&"}"==b){if(d)try{target[":"==d?"setValue":"declareProperty"](n,a[1]||a,D)}catch(R){r(R)}u=!0;d=!1}break;case "":case void 0:return;case ";":a=
null,u=!0,d=t=!1,f=""}var Q=b}}function r(k){console.error(k.message||k,"line "+v.slice(0,l.lastIndex).split("\n").length+" in "+(w.href||"in-page stylesheet"));k.stack&&console.error(k.stack)}var I,l=I=/\s*((?:[^{\}\[\]\(\)\\'":=;]|\[(?:[^\]'"]|'(?:\\.|[^'])*'|"(?:\\.|[^"])*")\])*)([=:]\??\s*([^{\}\[\]\(\)\\'":;]*))?(?:([{\}\[\]\(\)\\'":;])(\/\d+)?|$)/g,B=[p];p.parse=C;C(v,w)}var M=/((?:\\.|[^'])*)'/g,N=/((?:\\.|[^"])*)"/g,L=/\/\*[\w\W]*?\*\//g,P={"{":"}","[":"]","(":")"},O=0,E="".trim?function(p){return p.trim()}:
function(p){return p.replace(/^\s+|\s+$/g,"")};G.prototype.toString=function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};return H});
//@ sourceMappingURL=parser.js.map